//
// Generated by Bluespec Compiler, version 2024.07 (build b4f31db)
//
//
//
// Ports:
// Name                         I/O  size props
// RDY_rxSample                   O     1 const
// getTx                          O     1
// RDY_getTx                      O     1 const
// getLeds                        O     4
// RDY_getLeds                    O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// rxSample_x_0                   I     1 reg
// EN_rxSample                    I     1
// EN_getTx                       I     1 unused
// EN_getLeds                     I     1 unused
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkThieleSystem(CLK,
		      RST_N,

		      rxSample_x_0,
		      EN_rxSample,
		      RDY_rxSample,

		      EN_getTx,
		      getTx,
		      RDY_getTx,

		      EN_getLeds,
		      getLeds,
		      RDY_getLeds);
  input  CLK;
  input  RST_N;

  // action method rxSample
  input  rxSample_x_0;
  input  EN_rxSample;
  output RDY_rxSample;

  // actionvalue method getTx
  input  EN_getTx;
  output getTx;
  output RDY_getTx;

  // actionvalue method getLeds
  input  EN_getLeds;
  output [3 : 0] getLeds;
  output RDY_getLeds;

  // signals for module outputs
  wire [3 : 0] getLeds;
  wire RDY_getLeds, RDY_getTx, RDY_rxSample, getTx;

  // register m2_ld_accum
  reg [127 : 0] m2_ld_accum;
  wire [127 : 0] m2_ld_accum$D_IN;
  wire m2_ld_accum$EN;

  // register m2_ld_byte
  reg [3 : 0] m2_ld_byte;
  wire [3 : 0] m2_ld_byte$D_IN;
  wire m2_ld_byte$EN;

  // register m2_ld_count_hi
  reg [7 : 0] m2_ld_count_hi;
  wire [7 : 0] m2_ld_count_hi$D_IN;
  wire m2_ld_count_hi$EN;

  // register m2_ld_count_lo
  reg [7 : 0] m2_ld_count_lo;
  wire [7 : 0] m2_ld_count_lo$D_IN;
  wire m2_ld_count_lo$EN;

  // register m2_ld_index
  reg [7 : 0] m2_ld_index;
  wire [7 : 0] m2_ld_index$D_IN;
  wire m2_ld_index$EN;

  // register m2_ld_phase
  reg [1 : 0] m2_ld_phase;
  wire [1 : 0] m2_ld_phase$D_IN;
  wire m2_ld_phase$EN;

  // register m2_load_ack
  reg m2_load_ack;
  wire m2_load_ack$D_IN, m2_load_ack$EN;

  // register m2_load_addr
  reg [6 : 0] m2_load_addr;
  wire [6 : 0] m2_load_addr$D_IN;
  wire m2_load_addr$EN;

  // register m2_load_data
  reg [127 : 0] m2_load_data;
  wire [127 : 0] m2_load_data$D_IN;
  wire m2_load_data$EN;

  // register m2_load_req
  reg m2_load_req;
  wire m2_load_req$D_IN, m2_load_req$EN;

  // register m2_rx_bit
  reg [2 : 0] m2_rx_bit;
  wire [2 : 0] m2_rx_bit$D_IN;
  wire m2_rx_bit$EN;

  // register m2_rx_clk
  reg [7 : 0] m2_rx_clk;
  wire [7 : 0] m2_rx_clk$D_IN;
  wire m2_rx_clk$EN;

  // register m2_rx_shift
  reg [7 : 0] m2_rx_shift;
  wire [7 : 0] m2_rx_shift$D_IN;
  wire m2_rx_shift$EN;

  // register m2_rx_state
  reg [1 : 0] m2_rx_state;
  reg [1 : 0] m2_rx_state$D_IN;
  wire m2_rx_state$EN;

  // register m2_rx_sync1
  reg m2_rx_sync1;
  wire m2_rx_sync1$D_IN, m2_rx_sync1$EN;

  // register m2_rx_sync2
  reg m2_rx_sync2;
  wire m2_rx_sync2$D_IN, m2_rx_sync2$EN;

  // register m2_seen_bianchi
  reg m2_seen_bianchi;
  wire m2_seen_bianchi$D_IN, m2_seen_bianchi$EN;

  // register m2_seen_err
  reg m2_seen_err;
  wire m2_seen_err$D_IN, m2_seen_err$EN;

  // register m2_seen_halted
  reg m2_seen_halted;
  wire m2_seen_halted$D_IN, m2_seen_halted$EN;

  // register m2_start_ack
  reg m2_start_ack;
  wire m2_start_ack$D_IN, m2_start_ack$EN;

  // register m2_start_req
  reg m2_start_req;
  wire m2_start_req$D_IN, m2_start_req$EN;

  // register m2_started
  reg m2_started;
  wire m2_started$D_IN, m2_started$EN;

  // register m2_tx_active
  reg m2_tx_active;
  wire m2_tx_active$D_IN, m2_tx_active$EN;

  // register m2_tx_bit
  reg [3 : 0] m2_tx_bit;
  wire [3 : 0] m2_tx_bit$D_IN;
  wire m2_tx_bit$EN;

  // register m2_tx_bytes
  reg [119 : 0] m2_tx_bytes;
  wire [119 : 0] m2_tx_bytes$D_IN;
  wire m2_tx_bytes$EN;

  // register m2_tx_clk
  reg [7 : 0] m2_tx_clk;
  wire [7 : 0] m2_tx_clk$D_IN;
  wire m2_tx_clk$EN;

  // register m2_tx_done
  reg m2_tx_done;
  wire m2_tx_done$D_IN, m2_tx_done$EN;

  // register m2_tx_index
  reg [3 : 0] m2_tx_index;
  wire [3 : 0] m2_tx_index$D_IN;
  wire m2_tx_index$EN;

  // register m2_tx_shift
  reg [7 : 0] m2_tx_shift;
  wire [7 : 0] m2_tx_shift$D_IN;
  wire m2_tx_shift$EN;

  // ports of submodule m1
  wire [159 : 0] m1$apbWrite_x_0;
  wire [134 : 0] m1$loadInstr_x_0;
  wire [31 : 0] m1$apbReadData_x_0,
		m1$apbReadErr_x_0,
		m1$getErrorCode,
		m1$getMu,
		m1$getPC,
		m1$setTrapVector_x_0;
  wire [5 : 0] m1$getLassertCbufWord_x_0,
	       m1$getLassertFbufWord_x_0,
	       m1$getPtSize_x_0,
	       m1$setActiveModule_x_0;
  wire [3 : 0] m1$getCertDescBase_x_0,
	       m1$getCertDescCount_x_0,
	       m1$getCertDescValid_x_0,
	       m1$getCouplingDescBase_x_0,
	       m1$getCouplingDescCount_x_0,
	       m1$getCouplingDescValid_x_0,
	       m1$getCouplingPairDst_x_0,
	       m1$getCouplingPairSrc_x_0,
	       m1$getCouplingPairValid_x_0,
	       m1$getDescMetaAux_x_0,
	       m1$getDescMetaInlineLen_x_0,
	       m1$getDescMetaKind_x_0,
	       m1$getDescMetaSubtype_x_0,
	       m1$getDescMetaValid_x_0,
	       m1$getFormulaDescBase_x_0,
	       m1$getFormulaDescCount_x_0,
	       m1$getFormulaDescValid_x_0,
	       m1$getMorphCouplingDesc_x_0,
	       m1$getMorphDst_x_0,
	       m1$getMorphIdentity_x_0,
	       m1$getMorphSrc_x_0,
	       m1$getMorphValid_x_0;
  wire m1$EN_apbReadData,
       m1$EN_apbReadErr,
       m1$EN_apbWrite,
       m1$EN_getBianchiAlarm,
       m1$EN_getCertAddr,
       m1$EN_getCertDescBase,
       m1$EN_getCertDescCount,
       m1$EN_getCertDescNextId,
       m1$EN_getCertDescValid,
       m1$EN_getCertified,
       m1$EN_getCouplingDescBase,
       m1$EN_getCouplingDescCount,
       m1$EN_getCouplingDescNextId,
       m1$EN_getCouplingDescValid,
       m1$EN_getCouplingPairDst,
       m1$EN_getCouplingPairNextId,
       m1$EN_getCouplingPairSrc,
       m1$EN_getCouplingPairValid,
       m1$EN_getDescMetaAux,
       m1$EN_getDescMetaInlineLen,
       m1$EN_getDescMetaKind,
       m1$EN_getDescMetaNextId,
       m1$EN_getDescMetaSubtype,
       m1$EN_getDescMetaValid,
       m1$EN_getErr,
       m1$EN_getErrorCode,
       m1$EN_getFormulaDescBase,
       m1$EN_getFormulaDescCount,
       m1$EN_getFormulaDescNextId,
       m1$EN_getFormulaDescValid,
       m1$EN_getHalted,
       m1$EN_getInfoGain,
       m1$EN_getLassertCBase,
       m1$EN_getLassertCLen,
       m1$EN_getLassertCPtr,
       m1$EN_getLassertCbufWord,
       m1$EN_getLassertClauseSat,
       m1$EN_getLassertFBase,
       m1$EN_getLassertFLen,
       m1$EN_getLassertFPtr,
       m1$EN_getLassertFbufWord,
       m1$EN_getLassertKind,
       m1$EN_getLassertPhase,
       m1$EN_getLogicAcc,
       m1$EN_getMcycleHi,
       m1$EN_getMcycleLo,
       m1$EN_getMdlOps,
       m1$EN_getMinstretHi,
       m1$EN_getMinstretLo,
       m1$EN_getMorphCouplingDesc,
       m1$EN_getMorphDst,
       m1$EN_getMorphIdentity,
       m1$EN_getMorphNextId,
       m1$EN_getMorphSrc,
       m1$EN_getMorphValid,
       m1$EN_getMstatus,
       m1$EN_getMu,
       m1$EN_getMuTensor0,
       m1$EN_getMuTensor1,
       m1$EN_getMuTensor2,
       m1$EN_getMuTensor3,
       m1$EN_getPC,
       m1$EN_getPartitionOps,
       m1$EN_getPtNextId,
       m1$EN_getPtSize,
       m1$EN_getWcDiff00,
       m1$EN_getWcDiff01,
       m1$EN_getWcDiff10,
       m1$EN_getWcDiff11,
       m1$EN_getWcSame00,
       m1$EN_getWcSame01,
       m1$EN_getWcSame10,
       m1$EN_getWcSame11,
       m1$EN_loadInstr,
       m1$EN_setActiveModule,
       m1$EN_setTrapVector,
       m1$EN_start,
       m1$RDY_loadInstr,
       m1$getCertified,
       m1$getErr,
       m1$getHalted;

  // remaining internal signals
  reg [1 : 0] CASE_m2_ld_phase_0x0_0x1_0x1_IF_m2_rx_shift_CO_ETC__q1;
  wire [127 : 0] x_19__h3043;
  wire [119 : 0] IF_m2_tx_active_5_AND_m2_tx_clk_6_EQ_0xAD_7_0__ETC___d57,
		 x_16__h2290;
  wire [15 : 0] x_18__h3042;
  wire [7 : 0] x_10__h2836, x_15__h2289, x_21__h3045;
  wire [3 : 0] IF_m2_tx_active_5_AND_m2_tx_clk_6_EQ_0xAD_7_0__ETC___d60,
	       IF_m2_tx_active_5_AND_m2_tx_clk_6_EQ_0xAD_7_0__ETC___d64;
  wire [1 : 0] IF_m2_rx_clk_4_EQ_0xAD_9_THEN_0x0_ELSE_0x3___d94;
  wire NOT_m2_tx_active_5_6_AND_NOT_m2_tx_done_7_8_9__ETC___d25,
       _0_CONCAT_m2_ld_index_28_PLUS_0x1_29_30_EQ_m2_l_ETC___d133,
       m2_load_req_EQ_m2_load_ack___d3,
       m2_rx_state_9_EQ_0x3_11_AND_m2_rx_clk_4_EQ_0xA_ETC___d143,
       m2_rx_state_9_EQ_0x3_11_AND_m2_rx_clk_4_EQ_0xA_ETC___d145,
       m2_rx_state_9_EQ_0x3_11_AND_m2_rx_clk_4_EQ_0xA_ETC___d163;

  // action method rxSample
  assign RDY_rxSample = 1'd1 ;

  // actionvalue method getTx
  assign getTx =
	     !m2_tx_active ||
	     m2_tx_bit != 4'h0 && (m2_tx_bit == 4'h9 || m2_tx_shift[0]) ;
  assign RDY_getTx = 1'd1 ;

  // actionvalue method getLeds
  assign getLeds =
	     { m2_ld_phase != 2'h3,
	       m2_seen_bianchi,
	       m2_seen_err,
	       m2_seen_halted } ;
  assign RDY_getLeds = 1'd1 ;

  // submodule m1
  mkModule1 m1(.CLK(CLK),
	       .RST_N(RST_N),
	       .apbReadData_x_0(m1$apbReadData_x_0),
	       .apbReadErr_x_0(m1$apbReadErr_x_0),
	       .apbWrite_x_0(m1$apbWrite_x_0),
	       .getCertDescBase_x_0(m1$getCertDescBase_x_0),
	       .getCertDescCount_x_0(m1$getCertDescCount_x_0),
	       .getCertDescValid_x_0(m1$getCertDescValid_x_0),
	       .getCouplingDescBase_x_0(m1$getCouplingDescBase_x_0),
	       .getCouplingDescCount_x_0(m1$getCouplingDescCount_x_0),
	       .getCouplingDescValid_x_0(m1$getCouplingDescValid_x_0),
	       .getCouplingPairDst_x_0(m1$getCouplingPairDst_x_0),
	       .getCouplingPairSrc_x_0(m1$getCouplingPairSrc_x_0),
	       .getCouplingPairValid_x_0(m1$getCouplingPairValid_x_0),
	       .getDescMetaAux_x_0(m1$getDescMetaAux_x_0),
	       .getDescMetaInlineLen_x_0(m1$getDescMetaInlineLen_x_0),
	       .getDescMetaKind_x_0(m1$getDescMetaKind_x_0),
	       .getDescMetaSubtype_x_0(m1$getDescMetaSubtype_x_0),
	       .getDescMetaValid_x_0(m1$getDescMetaValid_x_0),
	       .getFormulaDescBase_x_0(m1$getFormulaDescBase_x_0),
	       .getFormulaDescCount_x_0(m1$getFormulaDescCount_x_0),
	       .getFormulaDescValid_x_0(m1$getFormulaDescValid_x_0),
	       .getLassertCbufWord_x_0(m1$getLassertCbufWord_x_0),
	       .getLassertFbufWord_x_0(m1$getLassertFbufWord_x_0),
	       .getMorphCouplingDesc_x_0(m1$getMorphCouplingDesc_x_0),
	       .getMorphDst_x_0(m1$getMorphDst_x_0),
	       .getMorphIdentity_x_0(m1$getMorphIdentity_x_0),
	       .getMorphSrc_x_0(m1$getMorphSrc_x_0),
	       .getMorphValid_x_0(m1$getMorphValid_x_0),
	       .getPtSize_x_0(m1$getPtSize_x_0),
	       .loadInstr_x_0(m1$loadInstr_x_0),
	       .setActiveModule_x_0(m1$setActiveModule_x_0),
	       .setTrapVector_x_0(m1$setTrapVector_x_0),
	       .EN_loadInstr(m1$EN_loadInstr),
	       .EN_start(m1$EN_start),
	       .EN_getPC(m1$EN_getPC),
	       .EN_getMu(m1$EN_getMu),
	       .EN_getErr(m1$EN_getErr),
	       .EN_getHalted(m1$EN_getHalted),
	       .EN_getCertified(m1$EN_getCertified),
	       .EN_getWcSame00(m1$EN_getWcSame00),
	       .EN_getWcDiff00(m1$EN_getWcDiff00),
	       .EN_getWcSame01(m1$EN_getWcSame01),
	       .EN_getWcDiff01(m1$EN_getWcDiff01),
	       .EN_getWcSame10(m1$EN_getWcSame10),
	       .EN_getWcDiff10(m1$EN_getWcDiff10),
	       .EN_getWcSame11(m1$EN_getWcSame11),
	       .EN_getWcDiff11(m1$EN_getWcDiff11),
	       .EN_getPartitionOps(m1$EN_getPartitionOps),
	       .EN_getMdlOps(m1$EN_getMdlOps),
	       .EN_getInfoGain(m1$EN_getInfoGain),
	       .EN_getErrorCode(m1$EN_getErrorCode),
	       .EN_getMstatus(m1$EN_getMstatus),
	       .EN_getMcycleLo(m1$EN_getMcycleLo),
	       .EN_getMcycleHi(m1$EN_getMcycleHi),
	       .EN_getMinstretLo(m1$EN_getMinstretLo),
	       .EN_getMinstretHi(m1$EN_getMinstretHi),
	       .EN_getLogicAcc(m1$EN_getLogicAcc),
	       .EN_getCertAddr(m1$EN_getCertAddr),
	       .EN_getMuTensor0(m1$EN_getMuTensor0),
	       .EN_getMuTensor1(m1$EN_getMuTensor1),
	       .EN_getMuTensor2(m1$EN_getMuTensor2),
	       .EN_getMuTensor3(m1$EN_getMuTensor3),
	       .EN_setActiveModule(m1$EN_setActiveModule),
	       .EN_setTrapVector(m1$EN_setTrapVector),
	       .EN_apbReadData(m1$EN_apbReadData),
	       .EN_apbReadErr(m1$EN_apbReadErr),
	       .EN_apbWrite(m1$EN_apbWrite),
	       .EN_getBianchiAlarm(m1$EN_getBianchiAlarm),
	       .EN_getPtNextId(m1$EN_getPtNextId),
	       .EN_getPtSize(m1$EN_getPtSize),
	       .EN_getMorphNextId(m1$EN_getMorphNextId),
	       .EN_getMorphSrc(m1$EN_getMorphSrc),
	       .EN_getMorphDst(m1$EN_getMorphDst),
	       .EN_getMorphCouplingDesc(m1$EN_getMorphCouplingDesc),
	       .EN_getMorphValid(m1$EN_getMorphValid),
	       .EN_getMorphIdentity(m1$EN_getMorphIdentity),
	       .EN_getCouplingDescBase(m1$EN_getCouplingDescBase),
	       .EN_getCouplingDescCount(m1$EN_getCouplingDescCount),
	       .EN_getCouplingDescValid(m1$EN_getCouplingDescValid),
	       .EN_getCouplingDescNextId(m1$EN_getCouplingDescNextId),
	       .EN_getCouplingPairSrc(m1$EN_getCouplingPairSrc),
	       .EN_getCouplingPairDst(m1$EN_getCouplingPairDst),
	       .EN_getCouplingPairValid(m1$EN_getCouplingPairValid),
	       .EN_getCouplingPairNextId(m1$EN_getCouplingPairNextId),
	       .EN_getFormulaDescBase(m1$EN_getFormulaDescBase),
	       .EN_getFormulaDescCount(m1$EN_getFormulaDescCount),
	       .EN_getFormulaDescValid(m1$EN_getFormulaDescValid),
	       .EN_getFormulaDescNextId(m1$EN_getFormulaDescNextId),
	       .EN_getCertDescBase(m1$EN_getCertDescBase),
	       .EN_getCertDescCount(m1$EN_getCertDescCount),
	       .EN_getCertDescValid(m1$EN_getCertDescValid),
	       .EN_getCertDescNextId(m1$EN_getCertDescNextId),
	       .EN_getDescMetaSubtype(m1$EN_getDescMetaSubtype),
	       .EN_getDescMetaKind(m1$EN_getDescMetaKind),
	       .EN_getDescMetaInlineLen(m1$EN_getDescMetaInlineLen),
	       .EN_getDescMetaAux(m1$EN_getDescMetaAux),
	       .EN_getDescMetaValid(m1$EN_getDescMetaValid),
	       .EN_getDescMetaNextId(m1$EN_getDescMetaNextId),
	       .EN_getLassertPhase(m1$EN_getLassertPhase),
	       .EN_getLassertKind(m1$EN_getLassertKind),
	       .EN_getLassertFBase(m1$EN_getLassertFBase),
	       .EN_getLassertCBase(m1$EN_getLassertCBase),
	       .EN_getLassertFLen(m1$EN_getLassertFLen),
	       .EN_getLassertCLen(m1$EN_getLassertCLen),
	       .EN_getLassertFPtr(m1$EN_getLassertFPtr),
	       .EN_getLassertCPtr(m1$EN_getLassertCPtr),
	       .EN_getLassertClauseSat(m1$EN_getLassertClauseSat),
	       .EN_getLassertFbufWord(m1$EN_getLassertFbufWord),
	       .EN_getLassertCbufWord(m1$EN_getLassertCbufWord),
	       .RDY_loadInstr(m1$RDY_loadInstr),
	       .RDY_start(),
	       .getPC(m1$getPC),
	       .RDY_getPC(),
	       .getMu(m1$getMu),
	       .RDY_getMu(),
	       .getErr(m1$getErr),
	       .RDY_getErr(),
	       .getHalted(m1$getHalted),
	       .RDY_getHalted(),
	       .getCertified(m1$getCertified),
	       .RDY_getCertified(),
	       .getWcSame00(),
	       .RDY_getWcSame00(),
	       .getWcDiff00(),
	       .RDY_getWcDiff00(),
	       .getWcSame01(),
	       .RDY_getWcSame01(),
	       .getWcDiff01(),
	       .RDY_getWcDiff01(),
	       .getWcSame10(),
	       .RDY_getWcSame10(),
	       .getWcDiff10(),
	       .RDY_getWcDiff10(),
	       .getWcSame11(),
	       .RDY_getWcSame11(),
	       .getWcDiff11(),
	       .RDY_getWcDiff11(),
	       .getPartitionOps(),
	       .RDY_getPartitionOps(),
	       .getMdlOps(),
	       .RDY_getMdlOps(),
	       .getInfoGain(),
	       .RDY_getInfoGain(),
	       .getErrorCode(m1$getErrorCode),
	       .RDY_getErrorCode(),
	       .getMstatus(),
	       .RDY_getMstatus(),
	       .getMcycleLo(),
	       .RDY_getMcycleLo(),
	       .getMcycleHi(),
	       .RDY_getMcycleHi(),
	       .getMinstretLo(),
	       .RDY_getMinstretLo(),
	       .getMinstretHi(),
	       .RDY_getMinstretHi(),
	       .getLogicAcc(),
	       .RDY_getLogicAcc(),
	       .getCertAddr(),
	       .RDY_getCertAddr(),
	       .getMuTensor0(),
	       .RDY_getMuTensor0(),
	       .getMuTensor1(),
	       .RDY_getMuTensor1(),
	       .getMuTensor2(),
	       .RDY_getMuTensor2(),
	       .getMuTensor3(),
	       .RDY_getMuTensor3(),
	       .RDY_setActiveModule(),
	       .RDY_setTrapVector(),
	       .apbReadData(),
	       .RDY_apbReadData(),
	       .apbReadErr(),
	       .RDY_apbReadErr(),
	       .apbWrite(),
	       .RDY_apbWrite(),
	       .getBianchiAlarm(),
	       .RDY_getBianchiAlarm(),
	       .getPtNextId(),
	       .RDY_getPtNextId(),
	       .getPtSize(),
	       .RDY_getPtSize(),
	       .getMorphNextId(),
	       .RDY_getMorphNextId(),
	       .getMorphSrc(),
	       .RDY_getMorphSrc(),
	       .getMorphDst(),
	       .RDY_getMorphDst(),
	       .getMorphCouplingDesc(),
	       .RDY_getMorphCouplingDesc(),
	       .getMorphValid(),
	       .RDY_getMorphValid(),
	       .getMorphIdentity(),
	       .RDY_getMorphIdentity(),
	       .getCouplingDescBase(),
	       .RDY_getCouplingDescBase(),
	       .getCouplingDescCount(),
	       .RDY_getCouplingDescCount(),
	       .getCouplingDescValid(),
	       .RDY_getCouplingDescValid(),
	       .getCouplingDescNextId(),
	       .RDY_getCouplingDescNextId(),
	       .getCouplingPairSrc(),
	       .RDY_getCouplingPairSrc(),
	       .getCouplingPairDst(),
	       .RDY_getCouplingPairDst(),
	       .getCouplingPairValid(),
	       .RDY_getCouplingPairValid(),
	       .getCouplingPairNextId(),
	       .RDY_getCouplingPairNextId(),
	       .getFormulaDescBase(),
	       .RDY_getFormulaDescBase(),
	       .getFormulaDescCount(),
	       .RDY_getFormulaDescCount(),
	       .getFormulaDescValid(),
	       .RDY_getFormulaDescValid(),
	       .getFormulaDescNextId(),
	       .RDY_getFormulaDescNextId(),
	       .getCertDescBase(),
	       .RDY_getCertDescBase(),
	       .getCertDescCount(),
	       .RDY_getCertDescCount(),
	       .getCertDescValid(),
	       .RDY_getCertDescValid(),
	       .getCertDescNextId(),
	       .RDY_getCertDescNextId(),
	       .getDescMetaSubtype(),
	       .RDY_getDescMetaSubtype(),
	       .getDescMetaKind(),
	       .RDY_getDescMetaKind(),
	       .getDescMetaInlineLen(),
	       .RDY_getDescMetaInlineLen(),
	       .getDescMetaAux(),
	       .RDY_getDescMetaAux(),
	       .getDescMetaValid(),
	       .RDY_getDescMetaValid(),
	       .getDescMetaNextId(),
	       .RDY_getDescMetaNextId(),
	       .getLassertPhase(),
	       .RDY_getLassertPhase(),
	       .getLassertKind(),
	       .RDY_getLassertKind(),
	       .getLassertFBase(),
	       .RDY_getLassertFBase(),
	       .getLassertCBase(),
	       .RDY_getLassertCBase(),
	       .getLassertFLen(),
	       .RDY_getLassertFLen(),
	       .getLassertCLen(),
	       .RDY_getLassertCLen(),
	       .getLassertFPtr(),
	       .RDY_getLassertFPtr(),
	       .getLassertCPtr(),
	       .RDY_getLassertCPtr(),
	       .getLassertClauseSat(),
	       .RDY_getLassertClauseSat(),
	       .getLassertFbufWord(),
	       .RDY_getLassertFbufWord(),
	       .getLassertCbufWord(),
	       .RDY_getLassertCbufWord());

  // register m2_ld_accum
  assign m2_ld_accum$D_IN =
	     m2_rx_state_9_EQ_0x3_11_AND_m2_rx_clk_4_EQ_0xA_ETC___d145 ?
	       ((m2_ld_byte == 4'hF) ? 128'h0 : x_19__h3043) :
	       m2_ld_accum ;
  assign m2_ld_accum$EN = EN_rxSample ;

  // register m2_ld_byte
  assign m2_ld_byte$D_IN =
	     m2_rx_state_9_EQ_0x3_11_AND_m2_rx_clk_4_EQ_0xA_ETC___d145 ?
	       ((m2_ld_byte == 4'hF) ? 4'h0 : m2_ld_byte + 4'h1) :
	       m2_ld_byte ;
  assign m2_ld_byte$EN = EN_rxSample ;

  // register m2_ld_count_hi
  assign m2_ld_count_hi$D_IN =
	     m2_rx_state_9_EQ_0x3_11_AND_m2_rx_clk_4_EQ_0xA_ETC___d143 ?
	       m2_rx_shift :
	       m2_ld_count_hi ;
  assign m2_ld_count_hi$EN = EN_rxSample ;

  // register m2_ld_count_lo
  assign m2_ld_count_lo$D_IN =
	     (m2_rx_state == 2'h3 && m2_rx_clk == 8'hAD && m2_rx_sync2 &&
	      m2_ld_phase == 2'h0) ?
	       m2_rx_shift :
	       m2_ld_count_lo ;
  assign m2_ld_count_lo$EN = EN_rxSample ;

  // register m2_ld_index
  assign m2_ld_index$D_IN =
	     (m2_rx_state_9_EQ_0x3_11_AND_m2_rx_clk_4_EQ_0xA_ETC___d145 &&
	      m2_ld_byte == 4'hF) ?
	       x_21__h3045 :
	       m2_ld_index ;
  assign m2_ld_index$EN = EN_rxSample ;

  // register m2_ld_phase
  assign m2_ld_phase$D_IN =
	     (m2_rx_state != 2'h3 || m2_rx_clk != 8'hAD || !m2_rx_sync2) ?
	       m2_ld_phase :
	       CASE_m2_ld_phase_0x0_0x1_0x1_IF_m2_rx_shift_CO_ETC__q1 ;
  assign m2_ld_phase$EN = EN_rxSample ;

  // register m2_load_ack
  assign m2_load_ack$D_IN = m2_load_req ;
  assign m2_load_ack$EN =
	     !m2_load_req_EQ_m2_load_ack___d3 && m1$RDY_loadInstr ;

  // register m2_load_addr
  assign m2_load_addr$D_IN =
	     (m2_rx_state_9_EQ_0x3_11_AND_m2_rx_clk_4_EQ_0xA_ETC___d145 &&
	      m2_ld_byte == 4'hF) ?
	       m2_ld_index[6:0] :
	       m2_load_addr ;
  assign m2_load_addr$EN = EN_rxSample ;

  // register m2_load_data
  assign m2_load_data$D_IN =
	     (m2_rx_state_9_EQ_0x3_11_AND_m2_rx_clk_4_EQ_0xA_ETC___d145 &&
	      m2_ld_byte == 4'hF) ?
	       x_19__h3043 :
	       m2_load_data ;
  assign m2_load_data$EN = EN_rxSample ;

  // register m2_load_req
  assign m2_load_req$D_IN =
	     (m2_rx_state_9_EQ_0x3_11_AND_m2_rx_clk_4_EQ_0xA_ETC___d145 &&
	      m2_ld_byte == 4'hF) ^
	     m2_load_req ;
  assign m2_load_req$EN = EN_rxSample ;

  // register m2_rx_bit
  assign m2_rx_bit$D_IN =
	     (m2_rx_state == 2'h2) ?
	       ((m2_rx_clk == 8'hAD) ? m2_rx_bit + 3'h1 : m2_rx_bit) :
	       3'h0 ;
  assign m2_rx_bit$EN = EN_rxSample ;

  // register m2_rx_clk
  assign m2_rx_clk$D_IN =
	     (m2_rx_state == 2'h0 ||
	      m2_rx_state == 2'h1 && m2_rx_clk == 8'h56 ||
	      m2_rx_clk == 8'hAD) ?
	       8'h0 :
	       m2_rx_clk + 8'h01 ;
  assign m2_rx_clk$EN = EN_rxSample ;

  // register m2_rx_shift
  assign m2_rx_shift$D_IN =
	     (m2_rx_state == 2'h2 && m2_rx_clk == 8'hAD) ?
	       x_10__h2836 :
	       m2_rx_shift ;
  assign m2_rx_shift$EN = EN_rxSample ;

  // register m2_rx_state
  always@(m2_rx_state or
	  IF_m2_rx_clk_4_EQ_0xAD_9_THEN_0x0_ELSE_0x3___d94 or
	  m2_rx_sync2 or m2_rx_clk or m2_rx_bit)
  begin
    case (m2_rx_state)
      2'h0: m2_rx_state$D_IN = m2_rx_sync2 ? 2'h0 : 2'h1;
      2'h1:
	  m2_rx_state$D_IN =
	      (m2_rx_clk == 8'h56) ? (m2_rx_sync2 ? 2'h0 : 2'h2) : 2'h1;
      2'h2:
	  m2_rx_state$D_IN =
	      (m2_rx_clk == 8'hAD && m2_rx_bit == 3'h7) ? 2'h3 : 2'h2;
      2'd3:
	  m2_rx_state$D_IN = IF_m2_rx_clk_4_EQ_0xAD_9_THEN_0x0_ELSE_0x3___d94;
    endcase
  end
  assign m2_rx_state$EN = EN_rxSample ;

  // register m2_rx_sync1
  assign m2_rx_sync1$D_IN = rxSample_x_0 ;
  assign m2_rx_sync1$EN = EN_rxSample ;

  // register m2_rx_sync2
  assign m2_rx_sync2$D_IN = m2_rx_sync1 ;
  assign m2_rx_sync2$EN = EN_rxSample ;

  // register m2_seen_bianchi
  assign m2_seen_bianchi$D_IN = m1$getErrorCode == 32'h0B1A4C81 ;
  assign m2_seen_bianchi$EN = 1'd1 ;

  // register m2_seen_err
  assign m2_seen_err$D_IN = m1$getErr ;
  assign m2_seen_err$EN = 1'd1 ;

  // register m2_seen_halted
  assign m2_seen_halted$D_IN = m1$getHalted ;
  assign m2_seen_halted$EN = 1'd1 ;

  // register m2_start_ack
  assign m2_start_ack$D_IN = m2_start_req ;
  assign m2_start_ack$EN =
	     m2_start_req != m2_start_ack && m2_load_req_EQ_m2_load_ack___d3 ;

  // register m2_start_req
  assign m2_start_req$D_IN =
	     m2_rx_state_9_EQ_0x3_11_AND_m2_rx_clk_4_EQ_0xA_ETC___d163 ^
	     m2_start_req ;
  assign m2_start_req$EN = EN_rxSample ;

  // register m2_started
  assign m2_started$D_IN = 1'd1 ;
  assign m2_started$EN =
	     m2_start_req != m2_start_ack && m2_load_req_EQ_m2_load_ack___d3 ;

  // register m2_tx_active
  assign m2_tx_active$D_IN =
	     NOT_m2_tx_active_5_6_AND_NOT_m2_tx_done_7_8_9__ETC___d25 ||
	     (m2_tx_clk != 8'hAD || m2_tx_bit != 4'h9 ||
	      m2_tx_index != 4'hE) &&
	     m2_tx_active ;
  assign m2_tx_active$EN = 1'd1 ;

  // register m2_tx_bit
  assign m2_tx_bit$D_IN =
	     NOT_m2_tx_active_5_6_AND_NOT_m2_tx_done_7_8_9__ETC___d25 ?
	       4'h0 :
	       IF_m2_tx_active_5_AND_m2_tx_clk_6_EQ_0xAD_7_0__ETC___d64 ;
  assign m2_tx_bit$EN = 1'd1 ;

  // register m2_tx_bytes
  assign m2_tx_bytes$D_IN =
	     NOT_m2_tx_active_5_6_AND_NOT_m2_tx_done_7_8_9__ETC___d25 ?
	       x_16__h2290 :
	       IF_m2_tx_active_5_AND_m2_tx_clk_6_EQ_0xAD_7_0__ETC___d57 ;
  assign m2_tx_bytes$EN = 1'd1 ;

  // register m2_tx_clk
  assign m2_tx_clk$D_IN =
	     NOT_m2_tx_active_5_6_AND_NOT_m2_tx_done_7_8_9__ETC___d25 ?
	       8'h0 :
	       (m2_tx_active ?
		  ((m2_tx_clk == 8'hAD) ? 8'h0 : m2_tx_clk + 8'h01) :
		  m2_tx_clk) ;
  assign m2_tx_clk$EN = 1'd1 ;

  // register m2_tx_done
  assign m2_tx_done$D_IN =
	     m2_tx_active && m2_tx_clk == 8'hAD && m2_tx_bit == 4'h9 &&
	     m2_tx_index == 4'hE ||
	     m2_tx_done ;
  assign m2_tx_done$EN = 1'd1 ;

  // register m2_tx_index
  assign m2_tx_index$D_IN =
	     NOT_m2_tx_active_5_6_AND_NOT_m2_tx_done_7_8_9__ETC___d25 ?
	       4'h0 :
	       IF_m2_tx_active_5_AND_m2_tx_clk_6_EQ_0xAD_7_0__ETC___d60 ;
  assign m2_tx_index$EN = 1'd1 ;

  // register m2_tx_shift
  assign m2_tx_shift$D_IN =
	     (m2_tx_active && m2_tx_clk == 8'hAD && m2_tx_bit == 4'h0) ?
	       m2_tx_bytes[7:0] :
	       ((m2_tx_active && m2_tx_clk == 8'hAD) ?
		  { 1'h0, m2_tx_shift[7:1] } :
		  m2_tx_shift) ;
  assign m2_tx_shift$EN = 1'd1 ;

  // submodule m1
  assign m1$apbReadData_x_0 = 32'h0 ;
  assign m1$apbReadErr_x_0 = 32'h0 ;
  assign m1$apbWrite_x_0 = 160'h0 ;
  assign m1$getCertDescBase_x_0 = 4'h0 ;
  assign m1$getCertDescCount_x_0 = 4'h0 ;
  assign m1$getCertDescValid_x_0 = 4'h0 ;
  assign m1$getCouplingDescBase_x_0 = 4'h0 ;
  assign m1$getCouplingDescCount_x_0 = 4'h0 ;
  assign m1$getCouplingDescValid_x_0 = 4'h0 ;
  assign m1$getCouplingPairDst_x_0 = 4'h0 ;
  assign m1$getCouplingPairSrc_x_0 = 4'h0 ;
  assign m1$getCouplingPairValid_x_0 = 4'h0 ;
  assign m1$getDescMetaAux_x_0 = 4'h0 ;
  assign m1$getDescMetaInlineLen_x_0 = 4'h0 ;
  assign m1$getDescMetaKind_x_0 = 4'h0 ;
  assign m1$getDescMetaSubtype_x_0 = 4'h0 ;
  assign m1$getDescMetaValid_x_0 = 4'h0 ;
  assign m1$getFormulaDescBase_x_0 = 4'h0 ;
  assign m1$getFormulaDescCount_x_0 = 4'h0 ;
  assign m1$getFormulaDescValid_x_0 = 4'h0 ;
  assign m1$getLassertCbufWord_x_0 = 6'h0 ;
  assign m1$getLassertFbufWord_x_0 = 6'h0 ;
  assign m1$getMorphCouplingDesc_x_0 = 4'h0 ;
  assign m1$getMorphDst_x_0 = 4'h0 ;
  assign m1$getMorphIdentity_x_0 = 4'h0 ;
  assign m1$getMorphSrc_x_0 = 4'h0 ;
  assign m1$getMorphValid_x_0 = 4'h0 ;
  assign m1$getPtSize_x_0 = 6'h0 ;
  assign m1$loadInstr_x_0 = { m2_load_addr, m2_load_data } ;
  assign m1$setActiveModule_x_0 = 6'h0 ;
  assign m1$setTrapVector_x_0 = 32'h0 ;
  assign m1$EN_loadInstr =
	     !m2_load_req_EQ_m2_load_ack___d3 && m1$RDY_loadInstr ;
  assign m1$EN_start =
	     m2_start_req != m2_start_ack && m2_load_req_EQ_m2_load_ack___d3 ;
  assign m1$EN_getPC = 1'd1 ;
  assign m1$EN_getMu = 1'd1 ;
  assign m1$EN_getErr = 1'd1 ;
  assign m1$EN_getHalted = 1'd1 ;
  assign m1$EN_getCertified = 1'd1 ;
  assign m1$EN_getWcSame00 = 1'b0 ;
  assign m1$EN_getWcDiff00 = 1'b0 ;
  assign m1$EN_getWcSame01 = 1'b0 ;
  assign m1$EN_getWcDiff01 = 1'b0 ;
  assign m1$EN_getWcSame10 = 1'b0 ;
  assign m1$EN_getWcDiff10 = 1'b0 ;
  assign m1$EN_getWcSame11 = 1'b0 ;
  assign m1$EN_getWcDiff11 = 1'b0 ;
  assign m1$EN_getPartitionOps = 1'b0 ;
  assign m1$EN_getMdlOps = 1'b0 ;
  assign m1$EN_getInfoGain = 1'b0 ;
  assign m1$EN_getErrorCode = 1'd1 ;
  assign m1$EN_getMstatus = 1'b0 ;
  assign m1$EN_getMcycleLo = 1'b0 ;
  assign m1$EN_getMcycleHi = 1'b0 ;
  assign m1$EN_getMinstretLo = 1'b0 ;
  assign m1$EN_getMinstretHi = 1'b0 ;
  assign m1$EN_getLogicAcc = 1'b0 ;
  assign m1$EN_getCertAddr = 1'b0 ;
  assign m1$EN_getMuTensor0 = 1'b0 ;
  assign m1$EN_getMuTensor1 = 1'b0 ;
  assign m1$EN_getMuTensor2 = 1'b0 ;
  assign m1$EN_getMuTensor3 = 1'b0 ;
  assign m1$EN_setActiveModule = 1'b0 ;
  assign m1$EN_setTrapVector = 1'b0 ;
  assign m1$EN_apbReadData = 1'b0 ;
  assign m1$EN_apbReadErr = 1'b0 ;
  assign m1$EN_apbWrite = 1'b0 ;
  assign m1$EN_getBianchiAlarm = 1'b0 ;
  assign m1$EN_getPtNextId = 1'b0 ;
  assign m1$EN_getPtSize = 1'b0 ;
  assign m1$EN_getMorphNextId = 1'b0 ;
  assign m1$EN_getMorphSrc = 1'b0 ;
  assign m1$EN_getMorphDst = 1'b0 ;
  assign m1$EN_getMorphCouplingDesc = 1'b0 ;
  assign m1$EN_getMorphValid = 1'b0 ;
  assign m1$EN_getMorphIdentity = 1'b0 ;
  assign m1$EN_getCouplingDescBase = 1'b0 ;
  assign m1$EN_getCouplingDescCount = 1'b0 ;
  assign m1$EN_getCouplingDescValid = 1'b0 ;
  assign m1$EN_getCouplingDescNextId = 1'b0 ;
  assign m1$EN_getCouplingPairSrc = 1'b0 ;
  assign m1$EN_getCouplingPairDst = 1'b0 ;
  assign m1$EN_getCouplingPairValid = 1'b0 ;
  assign m1$EN_getCouplingPairNextId = 1'b0 ;
  assign m1$EN_getFormulaDescBase = 1'b0 ;
  assign m1$EN_getFormulaDescCount = 1'b0 ;
  assign m1$EN_getFormulaDescValid = 1'b0 ;
  assign m1$EN_getFormulaDescNextId = 1'b0 ;
  assign m1$EN_getCertDescBase = 1'b0 ;
  assign m1$EN_getCertDescCount = 1'b0 ;
  assign m1$EN_getCertDescValid = 1'b0 ;
  assign m1$EN_getCertDescNextId = 1'b0 ;
  assign m1$EN_getDescMetaSubtype = 1'b0 ;
  assign m1$EN_getDescMetaKind = 1'b0 ;
  assign m1$EN_getDescMetaInlineLen = 1'b0 ;
  assign m1$EN_getDescMetaAux = 1'b0 ;
  assign m1$EN_getDescMetaValid = 1'b0 ;
  assign m1$EN_getDescMetaNextId = 1'b0 ;
  assign m1$EN_getLassertPhase = 1'b0 ;
  assign m1$EN_getLassertKind = 1'b0 ;
  assign m1$EN_getLassertFBase = 1'b0 ;
  assign m1$EN_getLassertCBase = 1'b0 ;
  assign m1$EN_getLassertFLen = 1'b0 ;
  assign m1$EN_getLassertCLen = 1'b0 ;
  assign m1$EN_getLassertFPtr = 1'b0 ;
  assign m1$EN_getLassertCPtr = 1'b0 ;
  assign m1$EN_getLassertClauseSat = 1'b0 ;
  assign m1$EN_getLassertFbufWord = 1'b0 ;
  assign m1$EN_getLassertCbufWord = 1'b0 ;

  // remaining internal signals
  assign IF_m2_rx_clk_4_EQ_0xAD_9_THEN_0x0_ELSE_0x3___d94 =
	     (m2_rx_clk == 8'hAD) ? 2'h0 : 2'h3 ;
  assign IF_m2_tx_active_5_AND_m2_tx_clk_6_EQ_0xAD_7_0__ETC___d57 =
	     (m2_tx_active && m2_tx_clk == 8'hAD && m2_tx_bit == 4'h9) ?
	       { 8'h0, m2_tx_bytes[119:8] } :
	       m2_tx_bytes ;
  assign IF_m2_tx_active_5_AND_m2_tx_clk_6_EQ_0xAD_7_0__ETC___d60 =
	     (m2_tx_active && m2_tx_clk == 8'hAD && m2_tx_bit == 4'h9) ?
	       m2_tx_index + 4'h1 :
	       m2_tx_index ;
  assign IF_m2_tx_active_5_AND_m2_tx_clk_6_EQ_0xAD_7_0__ETC___d64 =
	     (m2_tx_active && m2_tx_clk == 8'hAD) ?
	       ((m2_tx_bit == 4'h9) ? 4'h0 : m2_tx_bit + 4'h1) :
	       m2_tx_bit ;
  assign NOT_m2_tx_active_5_6_AND_NOT_m2_tx_done_7_8_9__ETC___d25 =
	     !m2_tx_active && !m2_tx_done && m2_started &&
	     (m1$getHalted || m1$getErr) ;
  assign _0_CONCAT_m2_ld_index_28_PLUS_0x1_29_30_EQ_m2_l_ETC___d133 =
	     { 8'd0, x_21__h3045 } == x_18__h3042 ;
  assign m2_load_req_EQ_m2_load_ack___d3 = m2_load_req == m2_load_ack ;
  assign m2_rx_state_9_EQ_0x3_11_AND_m2_rx_clk_4_EQ_0xA_ETC___d143 =
	     m2_rx_state == 2'h3 && m2_rx_clk == 8'hAD && m2_rx_sync2 &&
	     m2_ld_phase == 2'h1 ;
  assign m2_rx_state_9_EQ_0x3_11_AND_m2_rx_clk_4_EQ_0xA_ETC___d145 =
	     m2_rx_state == 2'h3 && m2_rx_clk == 8'hAD && m2_rx_sync2 &&
	     m2_ld_phase == 2'h2 ;
  assign m2_rx_state_9_EQ_0x3_11_AND_m2_rx_clk_4_EQ_0xA_ETC___d163 =
	     m2_rx_state_9_EQ_0x3_11_AND_m2_rx_clk_4_EQ_0xA_ETC___d145 &&
	     m2_ld_byte == 4'hF &&
	     _0_CONCAT_m2_ld_index_28_PLUS_0x1_29_30_EQ_m2_l_ETC___d133 ||
	     m2_rx_state_9_EQ_0x3_11_AND_m2_rx_clk_4_EQ_0xA_ETC___d143 &&
	     { m2_rx_shift, m2_ld_count_lo } == 16'h0 ;
  assign x_10__h2836 = { m2_rx_sync2, m2_rx_shift[7:1] } ;
  assign x_15__h2289 = { 5'h0, m1$getCertified, m1$getErr, m1$getHalted } ;
  assign x_16__h2290 =
	     { 8'hAD,
	       m1$getErrorCode,
	       m1$getMu,
	       m1$getPC,
	       x_15__h2289,
	       8'hDE } ;
  assign x_18__h3042 = { m2_ld_count_hi, m2_ld_count_lo } ;
  assign x_19__h3043 = { m2_rx_shift, m2_ld_accum[127:8] } ;
  assign x_21__h3045 = m2_ld_index + 8'h01 ;
  always@(m2_ld_phase or
	  m2_ld_byte or
	  _0_CONCAT_m2_ld_index_28_PLUS_0x1_29_30_EQ_m2_l_ETC___d133 or
	  m2_rx_shift or m2_ld_count_lo)
  begin
    case (m2_ld_phase)
      2'h0: CASE_m2_ld_phase_0x0_0x1_0x1_IF_m2_rx_shift_CO_ETC__q1 = 2'h1;
      2'h1:
	  CASE_m2_ld_phase_0x0_0x1_0x1_IF_m2_rx_shift_CO_ETC__q1 =
	      ({ m2_rx_shift, m2_ld_count_lo } == 16'h0) ? 2'h3 : 2'h2;
      default: CASE_m2_ld_phase_0x0_0x1_0x1_IF_m2_rx_shift_CO_ETC__q1 =
		   (m2_ld_phase == 2'h2 && m2_ld_byte == 4'hF &&
		    _0_CONCAT_m2_ld_index_28_PLUS_0x1_29_30_EQ_m2_l_ETC___d133) ?
		     2'h3 :
		     m2_ld_phase;
    endcase
  end

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        m2_ld_accum <= `BSV_ASSIGNMENT_DELAY 128'd0;
	m2_ld_byte <= `BSV_ASSIGNMENT_DELAY 4'd0;
	m2_ld_count_hi <= `BSV_ASSIGNMENT_DELAY 8'd0;
	m2_ld_count_lo <= `BSV_ASSIGNMENT_DELAY 8'd0;
	m2_ld_index <= `BSV_ASSIGNMENT_DELAY 8'd0;
	m2_ld_phase <= `BSV_ASSIGNMENT_DELAY 2'd0;
	m2_load_ack <= `BSV_ASSIGNMENT_DELAY 1'd0;
	m2_load_addr <= `BSV_ASSIGNMENT_DELAY 7'd0;
	m2_load_data <= `BSV_ASSIGNMENT_DELAY 128'd0;
	m2_load_req <= `BSV_ASSIGNMENT_DELAY 1'd0;
	m2_rx_bit <= `BSV_ASSIGNMENT_DELAY 3'd0;
	m2_rx_clk <= `BSV_ASSIGNMENT_DELAY 8'd0;
	m2_rx_shift <= `BSV_ASSIGNMENT_DELAY 8'd0;
	m2_rx_state <= `BSV_ASSIGNMENT_DELAY 2'd0;
	m2_rx_sync1 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	m2_rx_sync2 <= `BSV_ASSIGNMENT_DELAY 1'd1;
	m2_seen_bianchi <= `BSV_ASSIGNMENT_DELAY 1'd0;
	m2_seen_err <= `BSV_ASSIGNMENT_DELAY 1'd0;
	m2_seen_halted <= `BSV_ASSIGNMENT_DELAY 1'd0;
	m2_start_ack <= `BSV_ASSIGNMENT_DELAY 1'd0;
	m2_start_req <= `BSV_ASSIGNMENT_DELAY 1'd0;
	m2_started <= `BSV_ASSIGNMENT_DELAY 1'd0;
	m2_tx_active <= `BSV_ASSIGNMENT_DELAY 1'd0;
	m2_tx_bit <= `BSV_ASSIGNMENT_DELAY 4'd0;
	m2_tx_bytes <= `BSV_ASSIGNMENT_DELAY 120'd0;
	m2_tx_clk <= `BSV_ASSIGNMENT_DELAY 8'd0;
	m2_tx_done <= `BSV_ASSIGNMENT_DELAY 1'd0;
	m2_tx_index <= `BSV_ASSIGNMENT_DELAY 4'd0;
	m2_tx_shift <= `BSV_ASSIGNMENT_DELAY 8'd0;
      end
    else
      begin
        if (m2_ld_accum$EN)
	  m2_ld_accum <= `BSV_ASSIGNMENT_DELAY m2_ld_accum$D_IN;
	if (m2_ld_byte$EN)
	  m2_ld_byte <= `BSV_ASSIGNMENT_DELAY m2_ld_byte$D_IN;
	if (m2_ld_count_hi$EN)
	  m2_ld_count_hi <= `BSV_ASSIGNMENT_DELAY m2_ld_count_hi$D_IN;
	if (m2_ld_count_lo$EN)
	  m2_ld_count_lo <= `BSV_ASSIGNMENT_DELAY m2_ld_count_lo$D_IN;
	if (m2_ld_index$EN)
	  m2_ld_index <= `BSV_ASSIGNMENT_DELAY m2_ld_index$D_IN;
	if (m2_ld_phase$EN)
	  m2_ld_phase <= `BSV_ASSIGNMENT_DELAY m2_ld_phase$D_IN;
	if (m2_load_ack$EN)
	  m2_load_ack <= `BSV_ASSIGNMENT_DELAY m2_load_ack$D_IN;
	if (m2_load_addr$EN)
	  m2_load_addr <= `BSV_ASSIGNMENT_DELAY m2_load_addr$D_IN;
	if (m2_load_data$EN)
	  m2_load_data <= `BSV_ASSIGNMENT_DELAY m2_load_data$D_IN;
	if (m2_load_req$EN)
	  m2_load_req <= `BSV_ASSIGNMENT_DELAY m2_load_req$D_IN;
	if (m2_rx_bit$EN) m2_rx_bit <= `BSV_ASSIGNMENT_DELAY m2_rx_bit$D_IN;
	if (m2_rx_clk$EN) m2_rx_clk <= `BSV_ASSIGNMENT_DELAY m2_rx_clk$D_IN;
	if (m2_rx_shift$EN)
	  m2_rx_shift <= `BSV_ASSIGNMENT_DELAY m2_rx_shift$D_IN;
	if (m2_rx_state$EN)
	  m2_rx_state <= `BSV_ASSIGNMENT_DELAY m2_rx_state$D_IN;
	if (m2_rx_sync1$EN)
	  m2_rx_sync1 <= `BSV_ASSIGNMENT_DELAY m2_rx_sync1$D_IN;
	if (m2_rx_sync2$EN)
	  m2_rx_sync2 <= `BSV_ASSIGNMENT_DELAY m2_rx_sync2$D_IN;
	if (m2_seen_bianchi$EN)
	  m2_seen_bianchi <= `BSV_ASSIGNMENT_DELAY m2_seen_bianchi$D_IN;
	if (m2_seen_err$EN)
	  m2_seen_err <= `BSV_ASSIGNMENT_DELAY m2_seen_err$D_IN;
	if (m2_seen_halted$EN)
	  m2_seen_halted <= `BSV_ASSIGNMENT_DELAY m2_seen_halted$D_IN;
	if (m2_start_ack$EN)
	  m2_start_ack <= `BSV_ASSIGNMENT_DELAY m2_start_ack$D_IN;
	if (m2_start_req$EN)
	  m2_start_req <= `BSV_ASSIGNMENT_DELAY m2_start_req$D_IN;
	if (m2_started$EN)
	  m2_started <= `BSV_ASSIGNMENT_DELAY m2_started$D_IN;
	if (m2_tx_active$EN)
	  m2_tx_active <= `BSV_ASSIGNMENT_DELAY m2_tx_active$D_IN;
	if (m2_tx_bit$EN) m2_tx_bit <= `BSV_ASSIGNMENT_DELAY m2_tx_bit$D_IN;
	if (m2_tx_bytes$EN)
	  m2_tx_bytes <= `BSV_ASSIGNMENT_DELAY m2_tx_bytes$D_IN;
	if (m2_tx_clk$EN) m2_tx_clk <= `BSV_ASSIGNMENT_DELAY m2_tx_clk$D_IN;
	if (m2_tx_done$EN)
	  m2_tx_done <= `BSV_ASSIGNMENT_DELAY m2_tx_done$D_IN;
	if (m2_tx_index$EN)
	  m2_tx_index <= `BSV_ASSIGNMENT_DELAY m2_tx_index$D_IN;
	if (m2_tx_shift$EN)
	  m2_tx_shift <= `BSV_ASSIGNMENT_DELAY m2_tx_shift$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    m2_ld_accum = 128'hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
    m2_ld_byte = 4'hA;
    m2_ld_count_hi = 8'hAA;
    m2_ld_count_lo = 8'hAA;
    m2_ld_index = 8'hAA;
    m2_ld_phase = 2'h2;
    m2_load_ack = 1'h0;
    m2_load_addr = 7'h2A;
    m2_load_data = 128'hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
    m2_load_req = 1'h0;
    m2_rx_bit = 3'h2;
    m2_rx_clk = 8'hAA;
    m2_rx_shift = 8'hAA;
    m2_rx_state = 2'h2;
    m2_rx_sync1 = 1'h0;
    m2_rx_sync2 = 1'h0;
    m2_seen_bianchi = 1'h0;
    m2_seen_err = 1'h0;
    m2_seen_halted = 1'h0;
    m2_start_ack = 1'h0;
    m2_start_req = 1'h0;
    m2_started = 1'h0;
    m2_tx_active = 1'h0;
    m2_tx_bit = 4'hA;
    m2_tx_bytes = 120'hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
    m2_tx_clk = 8'hAA;
    m2_tx_done = 1'h0;
    m2_tx_index = 4'hA;
    m2_tx_shift = 8'hAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkThieleSystem

