# GitLab CI Template for Thiele Receipts
#
# Add this to your .gitlab-ci.yml to automatically generate
# receipts for your build artifacts on every release.
#
# Usage:
#   1. Copy this file to .gitlab-ci.yml or merge with your existing config
#   2. Customize the "build" stage for your project
#   3. Push and tag a release

stages:
  - build
  - receipts
  - release

variables:
  # Customize these for your project
  PYTHON_VERSION: "3.12"
  RECEIPT_OUTPUT_DIR: "receipts"

# Example build stage - customize for your project
build:
  stage: build
  image: python:${PYTHON_VERSION}
  script:
    # Replace with your build commands
    - pip install build
    - python -m build
  artifacts:
    paths:
      - dist/*
    expire_in: 1 week

# Generate receipts for all build artifacts
generate-receipts:
  stage: receipts
  image: python:${PYTHON_VERSION}
  dependencies:
    - build
  before_script:
    # Install Thiele tools
    - pip install git+https://github.com/sethirus/The-Thiele-Machine.git
    - pip install PyNaCl cryptography
  script:
    # Option 1: Auto-discovery mode (recommended)
    # Automatically finds artifacts in dist/, target/, build/, etc.
    - python3 -m create_receipt --project . --output ${RECEIPT_OUTPUT_DIR}
    
    # Option 2: Specific files mode
    # - python3 -m create_receipt dist/*.whl dist/*.tar.gz --output receipt.json
    
    # Option 3: With signing (requires key in CI variables)
    # - echo "$THIELE_SIGNING_KEY" > signing.key
    # - python3 -m create_receipt --project . --sign signing.key --output ${RECEIPT_OUTPUT_DIR}
    # - rm signing.key  # cleanup
    
    - echo "✅ Created receipts in ${RECEIPT_OUTPUT_DIR}/"
    - ls -lh ${RECEIPT_OUTPUT_DIR}/
  artifacts:
    paths:
      - ${RECEIPT_OUTPUT_DIR}/*.receipt.json
      - ${RECEIPT_OUTPUT_DIR}/MANIFEST.receipt.json
    expire_in: 1 year
  only:
    - tags

# Upload receipts to GitLab Release
release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  dependencies:
    - build
    - generate-receipts
  script:
    - echo "Creating release ${CI_COMMIT_TAG}"
  release:
    tag_name: ${CI_COMMIT_TAG}
    name: 'Release ${CI_COMMIT_TAG}'
    description: |
      ## Verification
      
      This release includes cryptographic receipts for all artifacts.
      
      ### Browser Verification (Easiest)
      1. Visit https://sethirus.github.io/The-Thiele-Machine/verify.html
      2. Drag and drop any `.receipt.json` file
      3. Get instant verification ✅
      
      ### CLI Verification
      ```bash
      pip install git+https://github.com/sethirus/The-Thiele-Machine.git
      thiele-verify artifact.receipt.json
      ```
      
      Or fetch directly:
      ```bash
      thiele-fetch ${CI_PROJECT_PATH}
      ```
    assets:
      links:
        # Build artifacts
        - name: 'Build Artifacts'
          url: '${CI_PROJECT_URL}/-/jobs/artifacts/${CI_COMMIT_TAG}/browse/dist?job=build'
        # Receipts
        - name: 'Verification Receipts'
          url: '${CI_PROJECT_URL}/-/jobs/artifacts/${CI_COMMIT_TAG}/browse/receipts?job=generate-receipts'
  only:
    - tags

# Optional: Verification step to test receipts after creation
verify-receipts:
  stage: receipts
  image: python:${PYTHON_VERSION}
  dependencies:
    - generate-receipts
  before_script:
    - pip install git+https://github.com/sethirus/The-Thiele-Machine.git
  script:
    # Verify each receipt
    - |
      for receipt in ${RECEIPT_OUTPUT_DIR}/*.receipt.json; do
        if [ "$receipt" != "${RECEIPT_OUTPUT_DIR}/MANIFEST.receipt.json" ]; then
          echo "Verifying $receipt..."
          python3 -m verifier.replay "$receipt" || exit 1
        fi
      done
    - echo "✅ All receipts verified successfully"
  only:
    - tags
  allow_failure: true  # Don't block release if verification optional

# Optional: Add verification instructions to README
add-badge:
  stage: receipts
  image: python:${PYTHON_VERSION}
  dependencies: []
  script:
    - |
      cat >> README.md << 'EOF'
      
      ## Verifying Releases
      
      All releases include cryptographic receipts for verification.
      
      **Browser**: Visit [Thiele Verifier](https://sethirus.github.io/The-Thiele-Machine/verify.html)  
      **CLI**: `thiele-fetch ${CI_PROJECT_PATH}`
      
      EOF
    - echo "✅ Added verification instructions to README"
  artifacts:
    paths:
      - README.md
  only:
    - tags
  when: manual  # Run manually to update README
