# HARNESS — not normative semantics. Delegates all execution to build/extracted_vm_runner (OCaml).
"""DO NOT EDIT. GENERATED FROM COQ PROOFS by scripts/forge_vm.py.

Source: build/thiele_core.ml (generated by coq/Extraction.v via `make -C coq`)
Ground truth: coq/kernel/VMStep.v (47 opcodes), coq/kernel/VMState.v
Authoritative VM: build/extracted_vm_runner (OCaml binary from Coq extraction)

Regenerate: python3 scripts/forge_vm.py --input build/thiele_core.ml --output thielecpu/vm.py

Architecture: this file is a PROTOCOL LAYER, not a VM implementor.
All opcode semantics live in build/extracted_vm_runner (OCaml binary).
vm_run() and vm_apply() call that binary via subprocess. No opcode bodies here.
"""
from __future__ import annotations

import dataclasses
import json
import os
import subprocess
import sys
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

# ---------------------------------------------------------------------------
# Constants (extracted from Coq via Peano tower collapse)
# ---------------------------------------------------------------------------
REG_COUNT: int = 32
MEM_SIZE: int = 65536
TENSOR_SIZE: int = 16
WORD64_MASK: int = 0xFFFFFFFFFFFFFFFF
SP_REG: int = 31

# State integrity MAC constants (must match build/extracted_vm_runner.ml)
_STATE_INTEGRITY_SALT = "thiele_mu_guard_v1_2026"
_FNV_OFFSET_BASIS = 0xcbf29ce484222325
_FNV_PRIME = 0x100000001b3
_MASK64 = 0xFFFFFFFFFFFFFFFF


def _compute_state_mac(json_body: str) -> str:
    # FNV-1a 64-bit keyed hash for state integrity (tamper detection, not cryptographic).
    s = _STATE_INTEGRITY_SALT + json_body
    h = _FNV_OFFSET_BASIS
    for c in s:
        h = (h ^ ord(c)) & _MASK64
        h = (h * _FNV_PRIME) & _MASK64
    return "%016x" % h


# Hardware constants from coq/kami_hw/ThieleTypes.v
CHSH_X1_SURCHARGE: int = 256       # 0x00000100
BIANCHI_VIOLATION_ERROR_CODE: int = 0x0B1A4C81

# ---------------------------------------------------------------------------
# Data types (CSRState, moduleState, partitionGraph, VMState)
# These mirror the Coq record types in thiele_core.ml.
# ---------------------------------------------------------------------------

@dataclass
class CSRState:
    csr_cert_addr: int = 0
    csr_status: int = 0
    csr_err: int = 0
    csr_heap_base: int = 0


@dataclass
class moduleState:
    module_region: List[int] = field(default_factory=list)
    module_axioms: List[str] = field(default_factory=list)
    module_mu_tensor: List[int] = field(default_factory=lambda: [0] * TENSOR_SIZE)


@dataclass
class partitionGraph:
    pg_next_id: int = 1
    pg_modules: List[Tuple[int, moduleState]] = field(default_factory=list)


@dataclass
class VMState:
    vm_pc: int = 0
    vm_mu: int = 0
    vm_err: bool = False
    vm_regs: List[int] = field(default_factory=lambda: [0] * REG_COUNT)
    vm_mem: List[int] = field(default_factory=lambda: [0] * MEM_SIZE)
    vm_csrs: CSRState = field(default_factory=CSRState)
    vm_graph: partitionGraph = field(default_factory=partitionGraph)
    vm_mu_tensor: List[int] = field(default_factory=lambda: [0] * TENSOR_SIZE)
    vm_logic_acc: int = 0
    vm_mstatus: int = 0
    vm_witness: List[int] = field(default_factory=lambda: [0] * 8)
    vm_certified: bool = False

    @classmethod
    def default(cls) -> "VMState":
        return cls(
            vm_pc=0,
            vm_mu=0,
            vm_err=False,
            vm_regs=[0] * REG_COUNT,
            vm_mem=[0] * MEM_SIZE,
            vm_csrs=CSRState(),
            vm_graph=partitionGraph(),
            vm_mu_tensor=[0] * TENSOR_SIZE,
            vm_logic_acc=0,
            vm_mstatus=0,
            vm_witness=[0] * 8,
            vm_certified=False,
        )

    def to_json_dict(self) -> dict:
        mods = []
        for mid, ms in self.vm_graph.pg_modules:
            mods.append({
                "id": mid,
                "region": ms.module_region,
                "axioms": len(ms.module_axioms),
                "axiom_strings": ms.module_axioms,
                "mu_tensor": list(ms.module_mu_tensor),
            })
        return {
            "pc": self.vm_pc,
            "mu": self.vm_mu,
            "err": self.vm_err,
            "csr_err_code": self.vm_csrs.csr_err,
            "regs": list(self.vm_regs),
            "mem": (lambda m: m[:next((len(m)-i for i,v in enumerate(reversed(m)) if v!=0), 0)])(list(self.vm_mem)),
            "mu_tensor": list(self.vm_mu_tensor),
            "logic_acc": self.vm_logic_acc,
            "mstatus": self.vm_mstatus,
            "certified": self.vm_certified,
            "witness": list(self.vm_witness),
            "csrs": {
                "cert_addr": self.vm_csrs.csr_cert_addr,
                "status": self.vm_csrs.csr_status,
                "err": self.vm_csrs.csr_err,
                "heap_base": self.vm_csrs.csr_heap_base,
            },
            "graph": {
                "next_id": self.vm_graph.pg_next_id,
                "modules": mods,
            },
        }

    def to_json(self) -> str:
        # Use compact JSON (no spaces) so OCaml parse_json_int_array finds "key":[ correctly
        body = json.dumps(self.to_json_dict(), separators=(',', ':'))
        mac = _compute_state_mac(body)
        return body[:-1] + ',"_mac":"' + mac + '"' + '}'

    @classmethod
    def from_json(cls, text: str) -> "VMState":
        d = json.loads(text)
        csrs = d.get("csrs", {})
        graph = d.get("graph", {})
        mods = []
        for m in graph.get("modules", []):
            ms = moduleState(
                module_region=list(m.get("region", [])),
                module_axioms=list(m.get("axiom_strings", [])),
                module_mu_tensor=list(m.get("mu_tensor", [0] * TENSOR_SIZE)),
            )
            mods.append((int(m["id"]), ms))
        return cls(
            vm_pc=int(d.get("pc", 0)),
            vm_mu=int(d.get("mu", 0)),
            vm_err=bool(d.get("err", False)),
            vm_regs=list(d.get("regs", [0] * REG_COUNT)),
            vm_mem=(lambda m: (m + [0] * MEM_SIZE)[:MEM_SIZE])(list(d.get("mem", []))),
            vm_csrs=CSRState(
                csr_cert_addr=int(csrs.get("cert_addr", 0)),
                csr_status=int(csrs.get("status", 0)),
                csr_err=int(d.get("csr_err_code", csrs.get("err", 0))),
                csr_heap_base=int(csrs.get("heap_base", 0)),
            ),
            vm_graph=partitionGraph(
                pg_next_id=int(graph.get("next_id", 1)),
                pg_modules=mods,
            ),
            vm_mu_tensor=list(d.get("mu_tensor", [0] * TENSOR_SIZE)),
            vm_logic_acc=int(d.get("logic_acc", 0)),
            vm_mstatus=int(d.get("mstatus", 0)),
            vm_witness=list(d.get("witness", [0] * 8)),
            vm_certified=bool(d.get("certified", False)),
        )

# ---------------------------------------------------------------------------
# Cert-setter opcodes (from is_cert_setterb in thiele_core.ml)
# These require positive cost (NoFI enforcement).
# ---------------------------------------------------------------------------
_CERT_SETTERS: frozenset = frozenset({"certify", "emit", "lassert", "ljoin", "morph_assert", "read_port", "reveal"})

# ---------------------------------------------------------------------------
# instr_dict_to_text: serializes instruction dict to OCaml runner text format.
# Derived from CONSTRUCTOR_FIELD_MAP in forge_vm.py — the field order matches
# the constructor argument order in build/thiele_core.ml.
# ---------------------------------------------------------------------------

_LIST_FIELDS: frozenset = frozenset({'region', 'left', 'right', 'evidence'})
_STR_FIELDS: frozenset = frozenset({'payload', 'label'})

# On-chip LASSERT: formula/cert written to reserved memory; freg/creg point there.
_LASSERT_FORMULA_ADDR: int = 0xE000
_LASSERT_CERT_ADDR:    int = 0xF000
_LASSERT_FREG:         int = 28
_LASSERT_CREG:         int = 29

# On-chip LJOIN: cert1/cert2 written to reserved memory when provided as strings.
_LJOIN_CERT1_ADDR: int = 0xC000
_LJOIN_CERT2_ADDR: int = 0xD000
_LJOIN_C1REG:      int = 26
_LJOIN_C2REG:      int = 27

def _decode_formula(s: str) -> str:
    """Decode underscore-encoded formula: __ -> newline, _ -> space."""
    result: list = []
    i = 0
    while i < len(s):
        if i + 1 < len(s) and s[i] == "_" and s[i+1] == "_":
            result.append("\n"); i += 2
        elif s[i] == "_":
            result.append(" "); i += 1
        else:
            result.append(s[i]); i += 1
    return "".join(result)

def _fmt_list(val: Any) -> str:
    """Format a list field as {v1,v2,...} for OCaml runner."""
    if not val:
        return "{}"
    return "{" + ",".join(str(x) for x in val) + "}"

def instr_dict_to_text(instr: Dict[str, Any]) -> str:
    """Convert instruction dict to text format for extracted_vm_runner."""
    op = str(instr.get("op", "")).lower()
    if op == "pnew":
        return "PNEW" + " " + _fmt_list(instr.get("region", [])) + " " + str(instr.get("cost", 0))
    if op == "psplit":
        return "PSPLIT" + " " + str(int(instr.get("module", 0))) + " " + _fmt_list(instr.get("left", [])) + " " + _fmt_list(instr.get("right", [])) + " " + str(instr.get("cost", 0))
    if op == "pmerge":
        return "PMERGE" + " " + str(int(instr.get("m1", 0))) + " " + str(int(instr.get("m2", 0))) + " " + str(instr.get("cost", 0))
    if op == "mdlacc":
        return "MDLACC" + " " + str(int(instr.get("module", 0))) + " " + str(instr.get("cost", 0))
    if op == "pdiscover":
        return "PDISCOVER" + " " + str(int(instr.get("module", 0))) + " " + _fmt_list(instr.get("evidence", [])) + " " + str(instr.get("cost", 0))
    if op == "xfer":
        return "XFER" + " " + str(int(instr.get("dst", 0))) + " " + str(int(instr.get("src", 0))) + " " + str(instr.get("cost", 0))
    if op == "load_imm":
        return "LOAD_IMM" + " " + str(int(instr.get("dst", 0))) + " " + str(int(instr.get("imm", 0))) + " " + str(instr.get("cost", 0))
    if op == "load":
        return "LOAD" + " " + str(int(instr.get("dst", 0))) + " " + str(int(instr.get("addr", 0))) + " " + str(instr.get("cost", 0))
    if op == "store":
        return "STORE" + " " + str(int(instr.get("addr", 0))) + " " + str(int(instr.get("src", 0))) + " " + str(instr.get("cost", 0))
    if op == "add":
        return "ADD" + " " + str(int(instr.get("dst", 0))) + " " + str(int(instr.get("rs1", 0))) + " " + str(int(instr.get("rs2", 0))) + " " + str(instr.get("cost", 0))
    if op == "sub":
        return "SUB" + " " + str(int(instr.get("dst", 0))) + " " + str(int(instr.get("rs1", 0))) + " " + str(int(instr.get("rs2", 0))) + " " + str(instr.get("cost", 0))
    if op == "jump":
        return "JUMP" + " " + str(int(instr.get("target", 0))) + " " + str(instr.get("cost", 0))
    if op == "jnez":
        return "JNEZ" + " " + str(int(instr.get("rs", 0))) + " " + str(int(instr.get("target", 0))) + " " + str(instr.get("cost", 0))
    if op == "call":
        return "CALL" + " " + str(int(instr.get("target", 0))) + " " + str(instr.get("cost", 0))
    if op == "ret":
        return "RET" + " " + str(instr.get("cost", 0))
    if op == "chsh_trial":
        return "CHSH_TRIAL" + " " + str(int(instr.get("x", 0))) + " " + str(int(instr.get("y", 0))) + " " + str(int(instr.get("a", 0))) + " " + str(int(instr.get("b", 0))) + " " + str(instr.get("cost", 0))
    if op == "xor_load":
        return "XOR_LOAD" + " " + str(int(instr.get("dst", 0))) + " " + str(int(instr.get("addr", 0))) + " " + str(instr.get("cost", 0))
    if op == "xor_add":
        return "XOR_ADD" + " " + str(int(instr.get("dst", 0))) + " " + str(int(instr.get("src", 0))) + " " + str(instr.get("cost", 0))
    if op == "xor_swap":
        return "XOR_SWAP" + " " + str(int(instr.get("a", 0))) + " " + str(int(instr.get("b", 0))) + " " + str(instr.get("cost", 0))
    if op == "xor_rank":
        return "XOR_RANK" + " " + str(int(instr.get("dst", 0))) + " " + str(int(instr.get("src", 0))) + " " + str(instr.get("cost", 0))
    if op == "emit":
        return "EMIT" + " " + str(int(instr.get("module", 0))) + " " + str(instr.get("payload", ".")) + " " + str(instr.get("cost", 0))
    if op == "oracle_halts":
        return "ORACLE_HALTS" + " " + str(instr.get("payload", ".")) + " " + str(instr.get("cost", 0))
    if op == "halt":
        return "HALT" + " " + str(instr.get("cost", 0))
    if op == "checkpoint":
        return "CHECKPOINT" + " " + str(instr.get("label", ".")) + " " + str(instr.get("cost", 0))
    if op == "read_port":
        return "READ_PORT" + " " + str(int(instr.get("dst", 0))) + " " + str(int(instr.get("channel", 0))) + " " + str(int(instr.get("value", 0))) + " " + str(int(instr.get("bits", 0))) + " " + str(instr.get("cost", 0))
    if op == "write_port":
        return "WRITE_PORT" + " " + str(int(instr.get("channel", 0))) + " " + str(int(instr.get("src", 0))) + " " + str(instr.get("cost", 0))
    if op == "heap_load":
        return "HEAP_LOAD" + " " + str(int(instr.get("dst", 0))) + " " + str(int(instr.get("addr", 0))) + " " + str(instr.get("cost", 0))
    if op == "heap_store":
        return "HEAP_STORE" + " " + str(int(instr.get("addr", 0))) + " " + str(int(instr.get("src", 0))) + " " + str(instr.get("cost", 0))
    if op == "certify":
        return "CERTIFY" + " " + str(instr.get("cost", 0))
    if op == "and":
        return "AND" + " " + str(int(instr.get("dst", 0))) + " " + str(int(instr.get("rs1", 0))) + " " + str(int(instr.get("rs2", 0))) + " " + str(instr.get("cost", 0))
    if op == "or":
        return "OR" + " " + str(int(instr.get("dst", 0))) + " " + str(int(instr.get("rs1", 0))) + " " + str(int(instr.get("rs2", 0))) + " " + str(instr.get("cost", 0))
    if op == "shl":
        return "SHL" + " " + str(int(instr.get("dst", 0))) + " " + str(int(instr.get("rs1", 0))) + " " + str(int(instr.get("rs2", 0))) + " " + str(instr.get("cost", 0))
    if op == "shr":
        return "SHR" + " " + str(int(instr.get("dst", 0))) + " " + str(int(instr.get("rs1", 0))) + " " + str(int(instr.get("rs2", 0))) + " " + str(instr.get("cost", 0))
    if op == "mul":
        return "MUL" + " " + str(int(instr.get("dst", 0))) + " " + str(int(instr.get("rs1", 0))) + " " + str(int(instr.get("rs2", 0))) + " " + str(instr.get("cost", 0))
    if op == "lui":
        return "LUI" + " " + str(int(instr.get("dst", 0))) + " " + str(int(instr.get("imm", 0))) + " " + str(instr.get("cost", 0))
    if op == "tensor_set":
        return "TENSOR_SET" + " " + str(int(instr.get("module", 0))) + " " + str(int(instr.get("i", 0))) + " " + str(int(instr.get("j", 0))) + " " + str(int(instr.get("value", 0))) + " " + str(int(instr.get("mu_delta", 0)))
    if op == "tensor_get":
        return "TENSOR_GET" + " " + str(int(instr.get("dst", 0))) + " " + str(int(instr.get("module", 0))) + " " + str(int(instr.get("i", 0))) + " " + str(int(instr.get("j", 0))) + " " + str(int(instr.get("mu_delta", 0)))
    if op == "morph":
        return "MORPH" + " " + str(int(instr.get("dst", 0))) + " " + str(int(instr.get("src_mod", 0))) + " " + str(int(instr.get("dst_mod", 0))) + " " + str(int(instr.get("coupling_idx", 0))) + " " + str(int(instr.get("mu_delta", 0)))
    if op == "compose":
        return "COMPOSE" + " " + str(int(instr.get("dst", 0))) + " " + str(int(instr.get("m1", 0))) + " " + str(int(instr.get("m2", 0))) + " " + str(int(instr.get("mu_delta", 0)))
    if op == "morph_id":
        return "MORPH_ID" + " " + str(int(instr.get("dst", 0))) + " " + str(int(instr.get("module", 0))) + " " + str(int(instr.get("mu_delta", 0)))
    if op == "morph_delete":
        return "MORPH_DELETE" + " " + str(int(instr.get("morph_id", 0))) + " " + str(int(instr.get("mu_delta", 0)))
    if op == "morph_assert":
        return "MORPH_ASSERT" + " " + str(int(instr.get("morph_id", 0))) + " " + str(int(instr.get("property", 0))) + " " + str(int(instr.get("cert", 0))) + " " + str(int(instr.get("mu_delta", 0)))
    if op == "morph_tensor":
        return "MORPH_TENSOR" + " " + str(int(instr.get("dst", 0))) + " " + str(int(instr.get("f", 0))) + " " + str(int(instr.get("g", 0))) + " " + str(int(instr.get("mu_delta", 0)))
    if op == "morph_get":
        return "MORPH_GET" + " " + str(int(instr.get("dst", 0))) + " " + str(int(instr.get("morph_id", 0))) + " " + str(int(instr.get("selector", 0))) + " " + str(int(instr.get("mu_delta", 0)))
    if op == "lassert":
        formula = str(instr.get("formula", ""))
        cost = int(instr.get("cost", 0))
        raw_cert = instr.get("cert", "")
        if isinstance(raw_cert, dict):
            cert_type = raw_cert.get("type", "sat")
            cert_data = raw_cert.get("proof", raw_cert.get("model", ""))
        else:
            cert_type = str(instr.get("cert_type", "sat"))
            cert_data = str(raw_cert or "")
        kind = 0 if cert_type == "unsat" else 1
        flen = len(_decode_formula(formula))
        parts = [
            f"INIT_MEM_STR {_LASSERT_FORMULA_ADDR} {formula}",
            f"INIT_REG {_LASSERT_FREG} {_LASSERT_FORMULA_ADDR}",
            f"INIT_MEM_STR {_LASSERT_CERT_ADDR} {cert_data}",
            f"INIT_REG {_LASSERT_CREG} {_LASSERT_CERT_ADDR}",
            f"LASSERT {_LASSERT_FREG} {_LASSERT_CREG} {kind} {flen} {cost}",
        ]
        return "\n".join(parts)
    if op == "ljoin":
        cost = int(instr.get("cost", 1))
        cert1_raw = instr.get("cert1")
        cert2_raw = instr.get("cert2")
        c1reg_v = instr.get("c1reg")
        c2reg_v = instr.get("c2reg")
        if cert1_raw is not None or cert2_raw is not None:
            c1 = str(cert1_raw or "")
            c2 = str(cert2_raw or "")
            parts = [
                f"INIT_MEM_STR {_LJOIN_CERT1_ADDR} {c1}",
                f"INIT_REG {_LJOIN_C1REG} {_LJOIN_CERT1_ADDR}",
                f"INIT_MEM_STR {_LJOIN_CERT2_ADDR} {c2}",
                f"INIT_REG {_LJOIN_C2REG} {_LJOIN_CERT2_ADDR}",
                f"LJOIN {_LJOIN_C1REG} {_LJOIN_C2REG} {cost}",
            ]
            return "\n".join(parts)
        c1i = int(c1reg_v) if c1reg_v is not None else 0
        c2i = int(c2reg_v) if c2reg_v is not None else 0
        return f"LJOIN {c1i} {c2i} {cost}"
    if op == "reveal":
        m = int(instr.get("module", 0))
        ti, tj = m // 4, m % 4
        delta = int(instr.get("cost", instr.get("bits", 0)))
        cert = str(instr.get("cert", "") or "")
        if cert and cert not in ("None", ""):
            return f"REVEAL {ti} {tj} {delta} {cert}"
        return f"REVEAL {ti} {tj} {delta}"
    raise ValueError(f"instr_dict_to_text: unknown opcode: {op!r}")

# ---------------------------------------------------------------------------
# OCaml binary runner — the AUTHORITATIVE VM implementation
# ---------------------------------------------------------------------------

_RUNNER_PATH = Path(__file__).parent.parent / "build" / "extracted_vm_runner"


def _runner_available() -> bool:
    p = _RUNNER_PATH
    if not p.exists() or not p.is_file():
        return False
    if not os.access(str(p), os.X_OK):
        return False
    try:
        first = p.read_bytes().splitlines()[0]
        if first.startswith(b"#!/usr/bin/ocamlrun"):
            return Path("/usr/bin/ocamlrun").exists()
    except Exception:
        pass
    return True


def _call_runner(state: VMState, prog_lines: List[str], max_steps: int) -> VMState:
    """Call build/extracted_vm_runner with --resume state.json trace.txt.

    Writes state to a temp JSON file and program to a temp trace file,
    calls the binary, and parses the JSON output back to VMState.
    """
    if not _runner_available():
        raise RuntimeError(
            f"build/extracted_vm_runner not available at {_RUNNER_PATH}\n"
            "Run: cd build && ocamlfind ocamlc -package str -linkpkg "
            "thiele_core.ml extracted_vm_runner.ml -o extracted_vm_runner"
        )

    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".json", delete=False, prefix="thiele_state_"
    ) as sf:
        state_path = sf.name
        sf.write(state.to_json())
        sf.write("\n")

    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".txt", delete=False, prefix="thiele_prog_"
    ) as pf:
        prog_path = pf.name
        pf.write(f"FUEL {max_steps}\n")
        for line_group in prog_lines:
            for line in line_group.split("\n"):
                line = line.strip()
                if line and not line.startswith("#") and not line.startswith(";"):
                    pf.write(line + "\n")

    try:
        result = subprocess.run(
            [str(_RUNNER_PATH), "--resume", state_path, prog_path],
            capture_output=True,
            text=True,
            timeout=60,
        )
        stdout = result.stdout.strip()
        if result.returncode not in (0, 5):
            raise RuntimeError(
                f"extracted_vm_runner failed (exit {result.returncode}):\n"
                f"stderr: {result.stderr[-1000:]}"
            )
        # stdout is a single-line JSON; skip any debug lines starting with "["
        json_line = ""
        for line in stdout.splitlines():
            line = line.strip()
            if line.startswith("{"):
                json_line = line
                break
        if not json_line:
            raise RuntimeError(
                f"extracted_vm_runner: no JSON in output.\nstdout: {stdout[:500]}"
            )
        return VMState.from_json(json_line)
    finally:
        Path(state_path).unlink(missing_ok=True)
        Path(prog_path).unlink(missing_ok=True)


# ---------------------------------------------------------------------------
# Public VM API
# ---------------------------------------------------------------------------

def vm_run(state: VMState, program: List[Dict[str, Any]], max_steps: int = 10000) -> VMState:
    """Execute a list of instruction dicts starting from state.

    Delegates entirely to the OCaml extracted VM binary.
    No opcode semantics are implemented here.
    """
    prog_lines = [instr_dict_to_text(i) for i in program]
    return _call_runner(state, prog_lines, max_steps)


def vm_apply_unsafe(state: VMState, instr: Dict[str, Any]) -> VMState:
    """Apply a single instruction to state.

    Normalizes vm_pc to 0 so the OCaml runner executes the instruction
    at position 0 of a one-instruction program.
    """
    s0 = dataclasses.replace(state, vm_pc=0)
    return vm_run(s0, [instr], max_steps=2)


def vm_apply_nofi(state: VMState, instr: Dict[str, Any]) -> VMState:
    """Apply with NoFI enforcement.

    NoFI is enforced by the OCaml binary (CertCheck + SimulationProof).
    This function delegates entirely to the extracted runner.
    """
    return vm_apply_unsafe(state, instr)


def vm_apply_runtime(state: VMState, instr: Dict[str, Any]) -> VMState:
    """Runtime-safe apply (same as vm_apply_nofi)."""
    return vm_apply_nofi(state, instr)


def vm_apply(state: VMState, instr: Dict[str, Any]) -> VMState:
    """Apply a single instruction (alias for vm_apply_unsafe)."""
    return vm_apply_unsafe(state, instr)


# ---------------------------------------------------------------------------
# VM compatibility wrapper class
# ---------------------------------------------------------------------------

class VM:
    """Thin compatibility wrapper around vm_run for legacy call sites.

    All execution is delegated to build/extracted_vm_runner via vm_run().
    No PYEXEC, no hand-written opcode bodies, no independent semantics.
    """

    def __init__(self, state: Optional[VMState] = None):
        self.state: VMState = state if state is not None else VMState.default()

    def apply(self, instr: Dict[str, Any]) -> None:
        self.state = vm_apply(self.state, instr)

    def run_program(
        self,
        program: List[Dict[str, Any]],
        max_steps: int = 10000,
    ) -> VMState:
        self.state = vm_run(self.state, program, max_steps=max_steps)
        return self.state
