# Thiele Machine - Makefile
# ==========================
# Builds and checks the Coq proofs of the abstract model and the small
# machine, and runs the test suite.

.PHONY: help install_deps organize clean deep-clean purge
.PHONY: test test-seq install-hooks
.PHONY: coq-gate coq-core coq-kernel coq-clean proof-gate-repro proof-undeniable
.PHONY: assumption-receipt assumption-receipt-check vacuity-audit
.PHONY: check-sensitive-files check-sensitive-files-strict
.PHONY: verify verify-research

help:
	@echo "Thiele Machine - Available Targets"
	@echo "==================================="
	@echo ""
	@echo "SETUP:"
	@echo "  make install_deps   - Install required dependencies"
	@echo "  make install-hooks  - Point git at the in-repo pre-commit hook"
	@echo ""
	@echo "QUICK CHECK:"
	@echo "  make verify         - Compile the axiom-free core (minimal/) and run the clean-room measurement"
	@echo ""
	@echo "TESTS:"
	@echo "  make test           - Run the pytest suite"
	@echo "  make test-seq       - Run the pytest suite without xdist"
	@echo ""
	@echo "COQ PROOFS:"
	@echo "  make coq-core       - Build every Coq proof in coq/_CoqProject"
	@echo "  make coq-gate       - Build every proof and fail on any Admitted"
	@echo "  make coq-kernel     - Build the Turing-machine kernel files"
	@echo "  make proof-gate-repro - Clean rebuild, zero-Admitted gate, coqchk of every module"
	@echo "  make proof-undeniable - Formal proof gate (build + audit + coqchk)"
	@echo "  make assumption-receipt - Re-derive the Print Assumptions receipt"
	@echo "  make vacuity-audit  - Kernel-conversion vacuity gate"
	@echo ""

# Install dependencies
install_deps:
	@echo "Installing dependencies..."
	@sudo apt-get update -qq && sudo apt-get install -y -qq coq coinor-csdp
	@pip install -r requirements.txt --quiet
	@echo "✓ Dependencies installed"

# Default test: auto-parallel via conftest.py (xdist workers)
test: install-hooks
	pytest tests/ -q

# Sequential test (disable xdist)
test-seq: install-hooks
	pytest tests/ -p no:xdist -q

# Re-derive the full-corpus Print Assumptions receipt from source.
#
# This is the check behind the "0 project-local axioms" badge. The receipt
# is regenerated by this target alone: the probe file is excluded from
# _CoqProject and no other CI step invokes the probe scripts. A test that
# compares committed JSON against committed README prose compares two files
# written together, not a re-derivation.
#
# Requires a built corpus, because Print Assumptions loads .vo files.
assumption-receipt:
	@echo "[assumption-receipt] Building corpus first (Print Assumptions needs .vo)..."
	$(MAKE) -C coq -j1
	@bash scripts/generate_assumption_receipt.sh

# Validate the receipt. The check reuses it for an unchanged semantic corpus
# and re-derives the full corpus automatically when its fingerprint changes.
assumption-receipt-check:
	@python3 scripts/check_assumption_receipt.py

# Install the Thiele Machine git hooks (one-time per checkout).
install-hooks:
	@bash scripts/install-git-hooks.sh

coq-gate: install-hooks
	@echo "[coq-gate] Building all Coq proofs..."
	$(MAKE) -C coq -j1
	@echo "[coq-gate] Checking for Admitted..."
	@count=$$(grep -rnE '^\s*Admitted\.' coq/ minimal/ --include='*.v' | grep -v patches | wc -l); \
	 if [ "$$count" -ne 0 ]; then \
	   echo "FAIL: $$count Admitted. found:"; \
	   grep -rnE '^\s*Admitted\.' coq/ minimal/ --include='*.v' | grep -v patches; \
	   exit 1; \
	 fi
	@echo "[coq-gate] PASS: zero Admitted, all proofs compile"

coq-core:
	@echo "Building Coq proofs..."
	@$(MAKE) -C coq
	@echo "✓ Coq proofs built"

coq-kernel:
	@$(MAKE) -C coq kernel/foundation/Kernel.vo kernel/foundation/KernelTM.vo
	@echo "✓ Coq kernel proofs built"

proof-gate-repro:
	@bash scripts/proof_gate_reproducible.sh

vacuity-audit: ## Kernel-conversion vacuity gate over the manifest in scripts/vacuity_targets.json
	@python3 scripts/vacuity_gate.py \
		--manifest scripts/vacuity_targets.json \
		--output artifacts/vacuity_audit.json

# The files the rest of the proof tree stands on: the certification system
# and its floor, the record-carrying machine, the record axis, and the small
# machine with its links into the abstract results.
SENSITIVE_FILES := coq/kernel/nfi/UniversalCertificationCost.v \
	coq/kernel/foundation/StructuralCore.v \
	coq/kernel/foundation/StructuralRecordAxis.v \
	coq/kernel/nfi/PermanentCertification.v \
	coq/kernel/nfi/PermanentRecordPricing.v \
	minimal/EarnedCore.v minimal/ThieleComplete.v \
	coq/kernel/foundation/EarnedCoreLinks.v coq/kernel/foundation/EarnedGenericLinks.v

# Red-flag diff gate: warns when proof-sensitive files are modified.
check-sensitive-files:
	@echo "[check-sensitive-files] Checking for uncommitted changes to proof-sensitive files..."
	@CHANGED=""; \
	 for f in $(SENSITIVE_FILES); do \
	   if ! git diff --quiet HEAD -- "$$f" 2>/dev/null; then \
	     CHANGED="$$CHANGED $$f"; \
	   fi; \
	 done; \
	 if [ -n "$$CHANGED" ]; then \
	   echo ""; \
	   echo "⚠  WARNING: Proof-sensitive files have uncommitted changes:$$CHANGED"; \
	   echo ""; \
	   echo "   Required actions before committing:"; \
	   echo "     1. make -C coq -j1              (rebuild proofs)"; \
	   echo "     2. python3 scripts/inquisitor.py  (zero Admitted check)"; \
	   echo ""; \
	 else \
	   echo "[check-sensitive-files] No uncommitted changes to proof-sensitive files. OK"; \
	 fi

# Hard-fail variant for proof-undeniable and CI.
check-sensitive-files-strict:
	@CHANGED=""; \
	 for f in $(SENSITIVE_FILES); do \
	   if ! git diff --quiet HEAD -- "$$f" 2>/dev/null; then \
	     CHANGED="$$CHANGED $$f"; \
	   fi; \
	 done; \
	 if [ -n "$$CHANGED" ]; then \
	   echo ""; \
	   echo "✗ ERROR: Proof-sensitive files have uncommitted changes:$$CHANGED"; \
	   echo ""; \
	   echo "  proof-undeniable requires a clean proof-sensitive file state."; \
	   echo "  Required actions before re-running:"; \
	   echo "    1. make -C coq -j1              (rebuild proofs)"; \
	   echo "    2. python3 scripts/inquisitor.py  (zero Admitted check)"; \
	   echo "    3. git add + git commit the changed files"; \
	   echo ""; \
	   exit 1; \
	 else \
	   echo "[check-sensitive-files-strict] No uncommitted changes to proof-sensitive files. OK"; \
	 fi

proof-undeniable:
	@echo "Running formal proof gate (compile + audit + independent checker)..."
	@$(MAKE) coq-gate
	@$(MAKE) check-sensitive-files-strict
	@python3 scripts/inquisitor.py
	@bash scripts/proof_gate_reproducible.sh
	@echo "✓ Formal proof gate PASSED (inquisitor + coqchk)"

# Clean build artifacts and cache files
clean:
	@echo "Cleaning build artifacts and cache files..."
	@rm -rf .build_cache/ .test_artifacts/ .generated/
	@rm -rf build/vacuity_probes/ .pytest_cache/ outputs/
	@rm -f /tmp/*.log
	@find coq minimal -name "*.vo" -delete
	@find coq minimal -name "*.vos" -delete
	@find coq minimal -name "*.vok" -delete
	@find coq minimal -name "*.glob" -delete
	@find coq minimal -name "*.aux" -delete
	@find . -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null || true
	@echo "✓ Clean complete (audit artifacts preserved)"

deep-clean: clean
	@echo "Running deep clean (includes audit artifacts)..."
	@rm -rf artifacts/
	@echo "✓ Deep clean complete"

# Organize workspace (clean transient caches, write a folder audit)
organize:
	@echo "Organizing workspace..."
	@./scripts/auto_organize.sh

# Clean everything including local environments
purge: deep-clean
	@echo "Purging all generated files..."
	@rm -rf node_modules/ .venv/ venv/ thiele_env/
	@make -C coq clean
	@echo "✓ Purge complete"

# Purge ONLY the project's Coq build artefacts under coq/ and minimal/ —
# leaves vendor/ alone so the vendored library cache stays valid. Use this
# in CI before invoking the Coq build to drop tracked-but-stale .vo files
# (which `make` would otherwise treat as up-to-date and skip rebuilding).
coq-clean:
	@echo "[coq-clean] purging coq/ and minimal/ *.{vo,vos,vok,glob,aux} (vendor/ untouched)"
	@find coq minimal -type f \( -name '*.vo' -o -name '*.vos' -o -name '*.vok' -o -name '*.glob' -o -name '*.aux' \) -delete
	@echo "[coq-clean] done"

verify: install-hooks ## Don't take my word: compile the axiom-free Coq core and run the clean-room measurement
	bash scripts/verify_core.sh

verify-research: install-hooks ## Check observation policies and the window theorem
	$(MAKE) -C coq kernel/frontier/ObservationPolicy.vo kernel/nfi/ShadowPricing.vo ../minimal/ThieleCompleteWindow.vo
