"""
Unified pipeline integration tests.

Validates the single-machine architecture:
  Coq proof → OCaml extraction → Python VM → hardware equivalence

All through SimulationProof.vm_apply — the ONE canonical step function:
  - Proven ≡ vm_step (SimulationProof.vm_step_vm_apply)
  - Extracted to OCaml (Extraction.v)
  - Proven ≡ kami_step for supported opcodes (EmbedStep.v)
"""

import json
import os
import subprocess
import tempfile
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]
COQ = REPO / "coq"
BUILD = REPO / "build"
RUNNER = BUILD / "extracted_vm_runner"


def _kernel_v(name: str) -> Path:
    flat = COQ / "kernel" / name
    if flat.exists():
        return flat
    kernel_root = COQ / "kernel"
    if kernel_root.exists():
        for p in kernel_root.rglob(name):
            return p
    return flat
THIELE_CORE = BUILD / "thiele_core.ml"


# ---------------------------------------------------------------------------
# Gate: Extraction targets SimulationProof.vm_apply
# ---------------------------------------------------------------------------

@pytest.mark.coq
def test_extraction_uses_simulation_proof_vm_apply():
    """Extraction.v must extract SimulationProof.vm_apply, not TMC's."""
    text = (COQ / "Extraction.v").read_text(encoding="utf-8")
    assert "SimulationProof.vm_apply" in text, (
        "Extraction.v must reference SimulationProof.vm_apply"
    )
    # The string may appear in comments, but not in Extraction command
    extraction_cmd = text[text.rfind("Extraction \""):]
    assert "ThieleMachineComplete.vm_apply" not in extraction_cmd, (
        "Extraction command must not extract ThieleMachineComplete.vm_apply"
    )


@pytest.mark.coq
def test_extraction_includes_proof_anchors():
    """Extraction.v pins NoFI proof anchors (zero-Admitted theorems)."""
    text = (COQ / "Extraction.v").read_text(encoding="utf-8")
    anchors = [
        "extraction_nofi_supra_boundary_anchor",
        "extraction_canonical_source_anchor",
        "extraction_c3_born_rule_anchor",
        "extraction_c4_tsirelson_model_anchor",
        "extraction_honest_nofi_anchor",
    ]
    for anchor in anchors:
        assert anchor in text, f"Missing proof anchor: {anchor}"


# ---------------------------------------------------------------------------
# Gate: Extracted OCaml artefacts exist and are well-formed
# ---------------------------------------------------------------------------

def test_thiele_core_ml_exists():
    """build/thiele_core.ml must exist (generated by Extraction.v)."""
    assert THIELE_CORE.is_file(), "build/thiele_core.ml not found"


def test_thiele_core_contains_vm_apply():
    """Extracted OCaml must contain a vm_apply function."""
    text = THIELE_CORE.read_text(encoding="utf-8")
    assert "let vm_apply" in text, (
        "build/thiele_core.ml must contain 'let vm_apply'"
    )


def test_extracted_runner_exists():
    """build/extracted_vm_runner must be a compiled executable."""
    assert RUNNER.is_file(), "build/extracted_vm_runner not found"
    assert os.access(str(RUNNER), os.X_OK), (
        "build/extracted_vm_runner must be executable"
    )


# ---------------------------------------------------------------------------
# Gate: Runner executes basic programs
# ---------------------------------------------------------------------------

def _run_trace(trace_lines, timeout=10):
    """Write a trace file, run the extracted VM runner, return parsed JSON."""
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".txt", delete=False
    ) as f:
        f.write("\n".join(trace_lines) + "\n")
        trace_path = f.name
    try:
        result = subprocess.run(
            [str(RUNNER), trace_path],
            capture_output=True, text=True, timeout=timeout,
        )
        if result.returncode != 0:
            pytest.fail(
                f"Runner failed (rc={result.returncode}):\n"
                f"stdout: {result.stdout[:500]}\n"
                f"stderr: {result.stderr[:500]}"
            )
        return json.loads(result.stdout)
    finally:
        os.unlink(trace_path)


@pytest.mark.strict_extracted
def test_runner_halt():
    """HALT instruction should produce mu = cost."""
    state = _run_trace(["HALT 5"])
    assert state["mu"] == 5, f"Expected mu=5, got {state['mu']}"
    assert state["pc"] == 1


@pytest.mark.strict_extracted
def test_runner_pnew_mu_conservation():
    """PNEW charges exactly its cost."""
    state = _run_trace(["PNEW {0} 3", "HALT 1"])
    assert state["mu"] == 4, f"Expected mu=4 (3+1), got {state['mu']}"


@pytest.mark.strict_extracted
def test_runner_load_imm_and_add():
    """LOAD_IMM + ADD computes correctly."""
    state = _run_trace([
        "LOAD_IMM 0 10 1",    # r0 = 10, cost=1
        "LOAD_IMM 1 20 1",    # r1 = 20, cost=1
        "ADD 2 0 1 1",        # r2 = r0+r1 = 30, cost=1
        "HALT 1",
    ])
    assert state["mu"] == 4
    assert state["regs"][2] == 30


@pytest.mark.strict_extracted
def test_runner_multi_pnew():
    """Multiple PNEW instructions accumulate mu."""
    state = _run_trace([
        "PNEW {0} 2",
        "PNEW {0} 2",
        "PNEW {0} 2",
        "HALT 1",
    ])
    assert state["mu"] == 7, f"Expected mu=7 (2+2+2+1), got {state['mu']}"


# ---------------------------------------------------------------------------
# Gate: SimulationProof.vm_apply is the canonical source
# ---------------------------------------------------------------------------

@pytest.mark.coq
def test_simulation_proof_vm_apply_is_axiom_free():
    """SimulationProof.v must not use Axiom or admit for vm_apply."""
    text = (_kernel_v("SimulationProof.v")).read_text(encoding="utf-8")
    # Find the vm_apply definition section
    idx = text.find("Definition vm_apply")
    assert idx >= 0, "SimulationProof.v must define vm_apply"
    # The vm_step_vm_apply equivalence theorem must exist
    assert "vm_step_vm_apply" in text, (
        "SimulationProof.v must contain vm_step_vm_apply "
        "proving vm_apply ≡ vm_step"
    )


@pytest.mark.coq
def test_simulation_proof_has_run_vm():
    """SimulationProof.v must define run_vm (fuel-bounded execution)."""
    text = (_kernel_v("SimulationProof.v")).read_text(encoding="utf-8")
    assert "Fixpoint run_vm" in text or "Definition run_vm" in text


@pytest.mark.coq
def test_tmc_has_architectural_note():
    """TMC must note that SimulationProof.vm_apply is canonical."""
    text = (COQ / "ThieleMachineComplete.v").read_text(encoding="utf-8")
    assert "SimulationProof.vm_apply" in text, (
        "TMC must reference SimulationProof.vm_apply as canonical"
    )


# ---------------------------------------------------------------------------
# Gate: Hardware equivalence chain
# ---------------------------------------------------------------------------

@pytest.mark.coq
def test_embed_step_exists():
    """EmbedStep.v must exist and contain embed_step_supported."""
    text = (COQ / "kami_hw" / "EmbedStep.v").read_text(encoding="utf-8")
    assert "embed_step_supported" in text or "embed_step_compute" in text


@pytest.mark.coq
def test_abstraction_has_kami_step():
    """Abstraction.v must define kami_step."""
    text = (COQ / "kami_hw" / "Abstraction.v").read_text(encoding="utf-8")
    assert "Definition kami_step" in text or "Fixpoint kami_step" in text


@pytest.mark.coq
def test_rich_state_commutation_exists():
    """RichStateCommutation.v must exist with commutation lemmas."""
    path = COQ / "kami_hw" / "RichStateCommutation.v"
    assert path.is_file(), "RichStateCommutation.v not found"
    text = path.read_text(encoding="utf-8")
    assert "snap_pt_to_graph_psplit" in text
    assert "snap_pt_to_graph_pmerge" in text


# ---------------------------------------------------------------------------
# Gate: Python VM wrapper
# ---------------------------------------------------------------------------

def test_python_vm_delegates_to_runner():
    """thielecpu/vm.py must delegate to extracted_vm_runner."""
    vm_py = REPO / "thielecpu" / "vm.py"
    assert vm_py.is_file(), "thielecpu/vm.py not found"
    text = vm_py.read_text(encoding="utf-8")
    assert "extracted_vm_runner" in text, (
        "thielecpu/vm.py must delegate to build/extracted_vm_runner"
    )
