"""Stress and differential tests of the verified compiler, run on the code
EXTRACTED from the Coq definitions (ocaml/CmpExtract.v, ocaml/cmp_driver.ml).

What is compared, for every program and input:

  A  the answer against ordinary mathematics (math.gcd, factorial, a plain
     ackermann, sorted(), a python simulation of the tiny machine ...)
  B  the extracted source interpreter (CmpLang.v cmp_interp): operation count
     and every variable, against an independent python interpreter written
     from the semantics (tests/cmp_src.py)
  C  the extracted runner of the compiled host program (CmpRun.v cmp_exec):
     every variable (registers 1 .. nv0) and the answer, against B
  D  the dumped counter machine program and host program, executed by python
     virtual machines (tests/cmp_src.py): the host machine's step count and
     registers equal those of the extracted runner, and the counter machine's
     registers equal the host's (one source program, two machines)
  E  coqc vm_compute of the Coq definitions themselves (shape check,
     interpreter, runner) on small cases
  F  bounded runs: a program that does not halt uses all its fuel and is
     reported unhalted; a program that halts after exactly k host steps is
     unhalted with fuel k - 1 and halted with fuel k (cmp_exec_complete,
     cmp_exec_unhalted)

Random programs (terminating, and with wild loops that may not terminate)
are generated by tests/cmp_corpus.py. Measured steps and times go to the
report file named by THIELE_CMP_REPORT, when set.

The compiler, the interpreter and the runner are never reimplemented here
for the comparison of C: they come out of the extraction; python only
supplies independent values to compare with.
"""

from __future__ import annotations

import json
import math
import os
import random
import sys
from pathlib import Path

import pytest

TESTS = Path(__file__).resolve().parent
sys.path.insert(0, str(TESTS))

import cmp_corpus as cc  # noqa: E402
import cmp_harness as ch  # noqa: E402
import cmp_src as cs  # noqa: E402

coq = pytest.mark.coq
slow = pytest.mark.slow

# Every test here runs the compiler extracted by coqc, so every test carries the
# coq marker and with it the coq per-test timeout, as in test_realize.py.
pytestmark = coq

VM_LIMIT = 4_000_000          # steps up to which the python virtual machines are run
REPORT = []                   # measurements, written at the end


def _missing(why, config=None):
    """A missing toolchain fails the test, it does not skip it, whenever CI is set
    (every automated run sets it), under GitHub Actions, with --strict-backends and
    with THIELE_STRICT_BACKENDS, so a lost install cannot turn into a pass. Without
    those the test skips with the reason (THIELE_CMP_ALLOW_SKIP lets a CI run skip)."""
    on = {"1", "true", "yes", "on"}
    strict = (
        os.environ.get("CI", "").strip().lower() in on
        or bool(os.environ.get("GITHUB_ACTIONS"))
        or os.environ.get("THIELE_STRICT_BACKENDS", "0").strip().lower() in on
        or bool(config is not None and config.getoption("--strict-backends", default=False))
    )
    if strict and not os.environ.get("THIELE_CMP_ALLOW_SKIP"):
        pytest.fail(why)
    pytest.skip(why)


@pytest.fixture(scope="session")
def exe(tmp_path_factory, request):
    try:
        return ch.build_driver(tmp_path_factory.mktemp("cmp_extract"))
    except (RuntimeError, AssertionError) as e:
        _missing("cannot build the extracted compiler: %s" % e, request.config)


@pytest.fixture(scope="session", autouse=True)
def write_report():
    yield
    path = os.environ.get("THIELE_CMP_REPORT")
    if path and REPORT:
        Path(path).write_text(json.dumps(REPORT, indent=1), encoding="utf-8", newline="\n")


def interp_fuel(prog, ops):
    return 2 * ops + 2 * cs.size_nodes(prog) + 200


def run_cases(exe, cases):
    """cases: list of dicts id, prog, nin, out, xs, ifuel, hfuel. Returns
    parsed results in order."""
    text = "\n".join(cs.case_text(c["id"], c["nin"], c["out"], c["ifuel"], c["hfuel"], c["xs"], c["prog"]) for c in cases)
    blocks = ch.run_driver(exe, text)
    assert len(blocks) == len(cases)
    return [ch.Result(b) for b in blocks]


def run_one_adaptive(exe, cid, prog, nin, out, xs, ops, start=3_000_000, cap=10**9):
    """Run until the host halts (the theorems say it does once the fuel is
    enough) with a fuel growing tenfold from start. ops is the python
    operation count. Returns the Result."""
    hf = start
    while True:
        r = run_cases(exe, [dict(id=cid, prog=prog, nin=nin, out=out, xs=xs, ifuel=interp_fuel(prog, ops), hfuel=hf)])[0]
        if r.halted or hf >= cap:
            return r
        hf *= 10


def check_against_python(res, prog, nin, out, xs, py):
    """B and C: the extracted interpreter and runner against the python
    interpreter's result py = (env, ops)."""
    env, ops = py
    n0 = cs.nv0(prog, nin, out)
    want = [env.get(i, 0) for i in range(n0)]
    assert res.wf
    assert res.nv0 == n0
    assert res.interp_ok, "extracted interpreter gave up"
    assert res.interp_ops == ops, ("operation counts differ", res.interp_ops, ops)
    assert res.interp_vars == want, ("interpreter variables differ", res.interp_vars, want)
    assert res.halted, "the compiled program did not halt (fuel too small?)"
    assert res.vars == want, ("compiled program variables differ", res.vars, want)
    assert res.answer == env.get(out, 0)
    assert res.pc == 1 + res.host_len


def check_vms(exe, res, prog, nin, out, xs, label):
    """D: the dumped programs on the python machines."""
    if res.steps > VM_LIMIT:
        return None
    blocks = ch.run_driver(exe, cs.dump_text(nin, out, prog))
    mm, host = cs.parse_dump("\n".join(blocks[0] + ["END"]))
    assert len(mm) == res.mm_len and len(host) == res.host_len
    regs = cs.load_regs(xs, res.nvf)
    hh, hsteps, hpc, hregs = cs.run_host(host, regs, res.steps + 10)
    assert hh and hsteps == res.steps and hpc == res.pc, (label, hh, hsteps, res.steps)
    mh, msteps, mpc, mregs = cs.run_mm(mm, regs, res.steps + 10)
    assert mh and mpc == 1 + len(mm)
    for r in range(1, res.nvf + 1):
        assert hregs.get(r, 0) == mregs.get(r, 0), (label, "register", r)
    for x in range(res.nv0):
        assert hregs.get(x + 1, 0) == res.vars[x], (label, "variable", x)
    return msteps


def record(name, xs, res, ops, msteps):
    REPORT.append(dict(name=name, inputs=list(xs), source_ops=ops, mm_steps=msteps, host_steps=res.steps,
                       mm_len=res.mm_len, host_len=res.host_len, t_compile=res.t_compile, t_run=res.t_run))


def full_check(exe, name, prog, nin, out, xs, ref=None, vms=True, start=3_000_000):
    py = cs.interp(prog, xs, max_ops=5 * 10**7, max_value=10**12)
    assert py is not None, "python interpreter budget exceeded for %s%s" % (name, xs)
    res = run_one_adaptive(exe, name, prog, nin, out, xs, py[1], start=start)
    check_against_python(res, prog, nin, out, xs, py)
    if ref is not None:
        want = ref(*xs)
        got = py[0].get(out, 0)
        if isinstance(want, tuple):
            assert (py[0].get(out, 0), py[0].get(out + 1, 0)) == want, (name, xs)
        else:
            assert got == want, (name, xs, got, want)
    msteps = check_vms(exe, res, prog, nin, out, xs, "%s%s" % (name, xs)) if vms else None
    record(name, xs, res, py[1], msteps)
    return res, py


# ---------------------------------------------------------------------------
# the shape check
# ---------------------------------------------------------------------------


def test_shape_check_rejects_recursion_and_missing_calls(exe):
    cases = [dict(id=n, prog=p, nin=nin, out=out, xs=[1], ifuel=100, hfuel=100) for n, p, nin, out in cc.ill_formed()]
    for c, r in zip(cases, run_cases(exe, cases)):
        assert not r.wf, c["id"]
        assert not cs.well_formed(c["prog"])


def test_shape_check_accepts_the_corpus(exe):
    entries = [cc.e_add(), cc.e_mul_loop(), cc.e_mul_call(), cc.e_fact(), cc.e_gcd(), cc.e_prime(), cc.e_divmod(),
               cc.e_sort5(), cc.e_tiny_interp()] + [cc.e_ack(m) for m in range(4)]
    cases = [dict(id=e[0], prog=e[1], nin=e[2], out=e[3], xs=[0] * e[2], ifuel=10, hfuel=10) for e in entries]
    for c, r in zip(cases, run_cases(exe, cases)):
        assert r.wf, c["id"]
        assert cs.well_formed(c["prog"])


# ---------------------------------------------------------------------------
# the corpus
# ---------------------------------------------------------------------------

CORPUS_SMALL = [
    (cc.e_add, [(0, 0), (3, 4), (17, 25), (100, 1)]),
    (cc.e_mul_loop, [(0, 5), (5, 0), (6, 7), (12, 11)]),
    (cc.e_mul_call, [(0, 0), (3, 9), (13, 17)]),
    (cc.e_fact, [(0,), (1,), (2,), (3,), (5,), (6,)]),
    (cc.e_gcd, [(12, 18), (35, 14), (17, 5), (9, 9), (100, 75), (89, 55)]),
    (cc.e_prime, [(0,), (1,), (2,), (3,), (4,), (9,), (13,), (25,), (29,), (49,), (97,), (91,)]),
    (cc.e_divmod, [(17, 5), (5, 17), (0, 3), (9, 0), (100, 7)]),
]


@pytest.mark.parametrize("make,inputs", CORPUS_SMALL, ids=[m.__name__ for m, _ in CORPUS_SMALL])
def test_corpus_small(exe, make, inputs):
    name, prog, nin, out, ref = make()
    for xs in inputs:
        if name == "divmod":
            # the answer is the pair (quotient, remainder) in variables 2 and 3
            full_check(exe, name, prog, nin, out, list(xs), ref=None)
            py = cs.interp(prog, list(xs))
            q = xs[0] // xs[1] if xs[1] else 0
            r = xs[0] % xs[1] if xs[1] else xs[0]
            assert (py[0][2], py[0][3]) == (q, r)
        else:
            full_check(exe, name, prog, nin, out, list(xs), ref=ref)


@pytest.mark.parametrize("m,ns", [(0, [0, 1, 5]), (1, [0, 1, 7]), (2, [0, 1, 4, 9]), (3, [0, 1, 2, 3])])
def test_ackermann_tower(exe, m, ns):
    name, prog, nin, out, ref = cc.e_ack(m)
    for n in ns:
        full_check(exe, name, prog, nin, out, [n], ref=ref)


def test_ackermann_four_zero(exe):
    # ackermann(4, 0) = 13 = ackermann(3, 1)
    _, prog, nin, out, ref = cc.e_ack(4)
    res, py = full_check(exe, "ack4", prog, nin, out, [0], ref=ref)
    assert res.answer == 13


def _pack(digits):
    return sum(d * cc.BASE ** i for i, d in enumerate(digits))


def test_packed_list_sort(exe):
    name, prog, nin, out, ref = cc.e_sort5()
    rng = random.Random(20261005)
    cases = [[0], [_pack([3, 2, 1, 0, 3])], [_pack([0, 1, 2, 3, 0])], [1023]] + \
            [[rng.randrange(cc.BASE ** 5)] for _ in range(6)]
    for xs in cases:
        res, py = full_check(exe, name, prog, nin, out, xs, ref=ref)
        digits = []
        v = res.answer
        for _ in range(5):
            digits.append(v % cc.BASE)
            v //= cc.BASE
        assert digits == sorted(digits)


@pytest.mark.parametrize("machine,a,b", [("adder", 5, 7), ("adder", 0, 3), ("doubler", 4, 0), ("drain", 6, 1),
                                         ("mover", 9, 2)])
def test_tiny_interpreter(exe, machine, a, b):
    name, prog, nin, out, ref = cc.e_tiny_interp()
    xs = cc.machine_inputs(machine, a, b)
    res, py = full_check(exe, name, prog, nin, out, xs, ref=None)
    want = ref(*xs)
    assert (py[0][8], py[0][9]) == want
    assert res.vars[9] == want[1] and res.vars[8] == want[0]


def test_tiny_interpreter_random_machines(exe):
    """Random four-instruction machine programs, run by the compiled
    interpreter. The compiled code is fixed; the machine program is data."""
    name, prog, nin, out, ref = cc.e_tiny_interp()
    rng = random.Random(77)
    seen_halting = 0
    for _ in range(25):
        xs = []
        for _ in range(4):
            xs += [rng.randrange(0, 6), rng.randrange(0, 5)]
        xs += [rng.randrange(0, 6), rng.randrange(0, 6)]
        want = ref(*xs)
        if want is None:
            continue
        py = cs.interp(prog, xs, max_ops=10**6)
        if py is None:
            continue
        seen_halting += 1
        res, py = full_check(exe, name, prog, nin, out, xs, ref=None, vms=False)
        assert (res.vars[8], res.vars[9]) == want
    assert seen_halting >= 10


# ---------------------------------------------------------------------------
# bounded runs
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("fuel", [1, 1000, 250000])
def test_non_halting_programs_use_all_their_fuel(exe, fuel):
    cases = []
    for n, p, nin, out in cc.nonhalting():
        cases.append(dict(id=n, prog=p, nin=nin, out=out, xs=[0] * nin, ifuel=fuel, hfuel=fuel))
    for c, r in zip(cases, run_cases(exe, cases)):
        assert r.wf and not r.halted, c["id"]
        assert r.steps == fuel, (c["id"], r.steps, fuel)      # cr_left = 0: every unit of fuel was a step
        assert 1 <= r.pc <= r.host_len                         # still inside the program
        assert not r.interp_ok                                 # the interpreter also runs out of fuel
        assert cs.interp(c["prog"], [0] * c["nin"], max_ops=fuel * 3) is None


def test_exact_fuel_boundary(exe):
    """A program that halts after exactly k host steps is not halted with
    fuel k - 1 and halted with fuel k and every larger fuel."""
    _, prog, nin, out, ref = cc.e_mul_loop()
    xs = [9, 13]
    res, py = full_check(exe, "mul_boundary", prog, nin, out, xs, ref=ref)
    k = res.steps
    assert k > 100
    cases = [dict(id="f%d" % f, prog=prog, nin=nin, out=out, xs=xs, ifuel=10**6, hfuel=f) for f in (k - 1, k, k + 1, 2 * k)]
    r = run_cases(exe, cases)
    assert not r[0].halted and r[0].steps == k - 1
    for x in r[1:]:
        assert x.halted and x.answer == 117
    assert r[1].steps == k and r[2].steps == k and r[3].steps == k
    # fuel k - 1 left the program one step short of its end: still inside it
    assert 1 <= r[0].pc <= r[0].host_len


def test_unhalted_state_is_a_prefix_of_the_run(exe):
    """With fuel f < k the runner stops in a state the python host machine
    reaches after exactly f steps (pc and registers)."""
    _, prog, nin, out, ref = cc.e_gcd()
    xs = [48, 18]
    res, _ = full_check(exe, "gcd_prefix", prog, nin, out, xs, ref=ref)
    k = res.steps
    blocks = ch.run_driver(exe, cs.dump_text(nin, out, prog))
    mm, host = cs.parse_dump("\n".join(blocks[0] + ["END"]))
    regs = cs.load_regs(xs, res.nvf)
    for f in (0, 1, 7, k // 3, k // 2, k - 1):
        r = run_cases(exe, [dict(id="p", prog=prog, nin=nin, out=out, xs=xs, ifuel=10**6, hfuel=f)])[0]
        h, steps, pc, rg = cs.run_host(host, regs, f)
        assert (h, steps) == (False, f)
        assert r.pc == pc and not r.halted
        assert r.vars == [rg.get(x + 1, 0) for x in range(r.nv0)]


# ---------------------------------------------------------------------------
# harness sensitivity: a wrong machine is noticed
# ---------------------------------------------------------------------------


def test_the_comparison_notices_a_corrupted_program(exe):
    _, prog, nin, out, ref = cc.e_gcd()
    xs = [24, 36]
    res, py = full_check(exe, "gcd", prog, nin, out, xs, ref=ref)
    blocks = ch.run_driver(exe, cs.dump_text(nin, out, prog))
    mm, host = cs.parse_dump("\n".join(blocks[0] + ["END"]))
    regs = cs.load_regs(xs, res.nvf)
    # flip one jump target of the host program: the run must differ
    changed = 0
    for i, ins in enumerate(host):
        if ins[0] == "dec" and ins[2] > 1:
            bad = list(host)
            bad[i] = ("dec", ins[1], ins[2] - 1)
            h, steps, pc, rg = cs.run_host(bad, regs, 20000)
            same = h and steps == res.steps and all(rg.get(x + 1, 0) == res.vars[x] for x in range(res.nv0))
            if not same:
                changed += 1
    assert changed >= 3
    # change one counter machine instruction: the machines disagree
    bad = list(mm)
    for i, ins in enumerate(bad):
        if ins[0] == "inc":
            bad[i] = ("inc", ins[1] + 1)
            break
    h, steps, pc, rg = cs.run_mm(bad, regs, 20000)
    assert not (h and all(rg.get(x + 1, 0) == res.vars[x] for x in range(res.nv0)))


# ---------------------------------------------------------------------------
# random programs
# ---------------------------------------------------------------------------


def _fuzz_cases(rng, count, wild):
    out = []
    g = cc.Gen(rng, nvars=5, wild=wild)
    for i in range(count):
        nin = rng.randint(1, 4)
        prog = g.program(nin)
        xs = [rng.randint(0, 6) for _ in range(nin)]
        out.append((i, prog, nin, rng.randrange(0, 5), xs))
    return out


def test_random_terminating_programs(exe):
    rng = random.Random(20261005)
    done = skipped = 0
    batch = []
    for i, prog, nin, outv, xs in _fuzz_cases(rng, 220, wild=0.0):
        py = cs.interp(prog, xs, max_ops=4000, max_value=300)
        if py is None:
            skipped += 1
            continue
        batch.append((i, prog, nin, outv, xs, py))
    assert len(batch) >= 100, (len(batch), skipped)
    cases = [dict(id="r%d" % i, prog=prog, nin=nin, out=outv, xs=xs, ifuel=interp_fuel(prog, py[1]), hfuel=40_000_000)
             for i, prog, nin, outv, xs, py in batch]
    results = run_cases(exe, cases)
    nontrivial = 0
    for (i, prog, nin, outv, xs, py), res in zip(batch, results):
        check_against_python(res, prog, nin, outv, xs, py)
        msteps = check_vms(exe, res, prog, nin, outv, xs, "r%d" % i)
        record("fuzz%d" % i, xs, res, py[1], msteps)
        done += 1
        if py[1] > 5:
            nontrivial += 1
    assert done >= 100 and nontrivial >= 60


def test_random_programs_with_wild_loops(exe):
    """Loops that may not end. When the python interpreter finishes within its
    budget, everything must agree; when it does not, the runner either halts
    (and then agrees with a bigger python budget) or reports unhalted with
    all its fuel used."""
    rng = random.Random(4242)
    batch = []
    for i, prog, nin, outv, xs in _fuzz_cases(rng, 160, wild=0.35):
        py = cs.interp(prog, xs, max_ops=3000, max_value=300)
        batch.append((i, prog, nin, outv, xs, py))
    fin = [b for b in batch if b[5] is not None]
    inf = [b for b in batch if b[5] is None]
    assert len(fin) >= 40 and len(inf) >= 5, (len(fin), len(inf))
    hf = 2_000_000
    cases = [dict(id="w%d" % i, prog=prog, nin=nin, out=outv, xs=xs,
                  ifuel=interp_fuel(prog, py[1]) if py else 20000, hfuel=hf) for i, prog, nin, outv, xs, py in batch]
    results = run_cases(exe, cases)
    halted_wild = 0
    for (i, prog, nin, outv, xs, py), res in zip(batch, results):
        if py is not None:
            check_against_python(res, prog, nin, outv, xs, py)
        else:
            if res.halted:
                # the runner finished a program the small python budget did not: check with a big budget
                halted_wild += 1
                py2 = cs.interp(prog, xs, max_ops=10**8, max_value=10**15)
                assert py2 is not None
                assert res.vars == [py2[0].get(x, 0) for x in range(res.nv0)]
            else:
                assert res.steps == hf
                assert 1 <= res.pc <= res.host_len
    assert halted_wild >= 0


# ---------------------------------------------------------------------------
# Coq evaluation of the same definitions
# ---------------------------------------------------------------------------


@coq
def test_coq_vm_compute_agrees_on_small_cases(exe, tmp_path, request):
    coqc = ch.find_coqc()
    flags, why = ch.prebuilt_flags()
    if not coqc or flags is None:
        _missing(why or "coqc not found", request.config)
    entries = []
    for make, xs in [(cc.e_add, [3, 4]), (cc.e_mul_loop, [4, 5]), (cc.e_mul_call, [3, 3]), (cc.e_fact, [3]),
                     (cc.e_gcd, [6, 4]), (cc.e_prime, [11]), (cc.e_prime, [9]), (lambda: cc.e_ack(1), [2])]:
        name, prog, nin, out, ref = make()
        entries.append((name, prog, nin, out, xs))
    rng = random.Random(5)
    g = cc.Gen(rng, nvars=4)
    k = 0
    while k < 8:
        prog = g.program(2)
        xs = [rng.randint(0, 4), rng.randint(0, 4)]
        py = cs.interp(prog, xs, max_ops=300, max_value=40)
        if py is None:
            continue
        entries.append(("rand%d" % k, prog, 2, 1, xs))
        k += 1
    cases = []
    for name, prog, nin, out, xs in entries:
        py = cs.interp(prog, xs, max_ops=10**6)
        cases.append((prog, nin, out, xs, interp_fuel(prog, py[1]), 300000))
    got = ch.coq_eval_cases(coqc, flags, cases, tmp_path)
    ext = run_cases(exe, [dict(id=e[0], prog=e[1], nin=e[2], out=e[3], xs=e[4], ifuel=c[4], hfuel=c[5])
                          for e, c in zip(entries, cases)])
    for (name, prog, nin, out, xs), (wf, interp, run), r in zip(entries, got, ext):
        assert wf is True
        assert interp[0] is True and r.interp_ok
        assert interp[1] == r.interp_ops
        assert interp[2] == r.interp_vars
        halted, steps, answer, vars_ = run
        assert halted is True and r.halted
        assert steps == r.steps and answer == r.answer and vars_ == r.vars, name


# ---------------------------------------------------------------------------
# long runs and large values
# ---------------------------------------------------------------------------


@slow
@pytest.mark.parametrize("name,make,xs", [
    ("add_big", cc.e_add, [4000, 7000]),
    ("mul_big", cc.e_mul_loop, [200, 150]),
    ("gcd_fib", cc.e_gcd, [610, 377]),
    ("prime_1009", cc.e_prime, [1009]),
    ("ack3_5", None, [5]),
])
def test_large_inputs_and_long_runs(exe, name, make, xs):
    if name == "ack3_5":
        entry = cc.e_ack(3)
    else:
        entry = make()
    ename, prog, nin, out, ref = entry
    res, py = full_check(exe, name, prog, nin, out, xs, ref=ref, start=3 * 10**9)
    assert res.steps >= 10_000


@slow
def test_runner_speed_on_a_forty_million_step_run(exe):
    """Not a correctness test: how many host steps per second the extracted
    runner makes on a long run (40 million steps: the cost of multiplying
    200 by 100 by repeated addition, because every addition copies the
    running total). The answer is still checked."""
    _, prog, nin, out, ref = cc.e_mul_loop()
    res, py = full_check(exe, "mul_long", prog, nin, out, [200, 100], ref=ref, vms=False, start=3 * 10**9)
    assert res.steps >= 40_000_000
    assert res.t_run > 0
    REPORT.append(dict(name="speed", host_steps=res.steps, seconds=res.t_run, steps_per_second=res.steps / res.t_run))
