(* NOTE: This file is part of the core simulation stack and is currently*)
(* admit-free.  The earlier no-rule backlog has been discharged; the   *)
(* catalogue of FindRule helper lemmas remains in place as             *)
(* documentation of the verified trace.                                *)
(*   - Blind predicate: defined concretely (no LASSERT/MDLACC) ✓       *)
(* AXIOM/ADMITTED INVENTORY (Nov 2025 snapshot, refreshed after bridge *)
(* updates):                                                            *)
(*   - run1, run_n, setup_state: defined in ThieleUniversalBridge      *)
(*   Remaining ADMITTED: none (no-rule helper catalogue is fully       *)
(*   proved; see `utm_no_rule_preserves_*` family for the completed    *)
(*   symbolic execution across the FindRule loop).                     *)
(*   This header is kept in sync with `coq/ADMIT_REPORT.txt` and the   *)
(*   audit documents so contributors can quickly see the admit status  *)
(*   of the core containment proof.                                    *)
              cpu0 Hinv Hfetch eq_refl Hfetch Hregs_len
              Hinv_full Hfetch eq_refl Hfetch Hregs_len
