// genesys2_top_tb.v: drives the Genesys 2 board top (thiele_cpu_top_genesys2)
// only through its pins, the way the board and a host computer would.
//
// The same file runs against two designs:
//   - the RTL: thiele_cpu_top_genesys2.v with the extracted mkThieleSystem,
//     mkModule1 and RegFile, and
//   - the gate netlist synthesized for the bitstream (synth_xc7.ys), written
//     back to Verilog and simulated with yosys's xilinx cells_sim.v.
// In both, IBUFDS, MMCME2_BASE and BUFGCE are the behavioural models in
// rtl_harness/gls/xilinx_board_cells.v.
//
// Pins driven: the 200 MHz differential clock (clk_p/clk_n), the CPU_RESETN
// button (cpu_reset_n, active low), and the USB-UART receive line (uart_rx).
// Pins read: uart_tx and the four LEDs.
//
// Sequence. The button starts released, as after FPGA configuration. Once
// the MMCM has locked and the CPU clock runs, the button is pressed for 16
// CPU clock cycles and released, unless +NO_RESET_PRESS is given (then the
// design runs from the state configuration leaves it in). After 2000 CPU
// cycles (the CPU clears its memories after reset) the program is sent as
// serial frames: two bytes of instruction count, then sixteen bytes per
// instruction, least significant first, 8N1 at CPB CPU cycles per bit. The
// fifteen-byte report is received at the same time. Then the testbench
// prints one JSON line: the report, the LEDs, and the architectural state
// read through gls_probes.vh, which scripts/board_gls.py generates for the
// design being simulated (hierarchical names into the RTL, or wires the
// script adds to the netlist's top module that only read existing nets).
`timescale 1ns/1ps

module genesys2_top_tb;
  localparam CPB = 174;  // ClksPerBit in coq/kami_hw/ThieleLoader.v

  reg clk_p = 1'b0;
  wire clk_n = ~clk_p;
  always #2.5 clk_p = ~clk_p;   // 200 MHz board oscillator

  reg cpu_reset_n = 1'b1;
  reg uart_rx = 1'b1;
  wire uart_tx;
  wire led_halted, led_err, led_bianchi, led_loading;

  thiele_cpu_top_genesys2 dut (
    .clk_p(clk_p), .clk_n(clk_n),
    .cpu_reset_n(cpu_reset_n),
    .uart_rx(uart_rx), .uart_tx(uart_tx),
    .LED_HALTED(led_halted), .LED_ERR(led_err),
    .LED_BIANCHI(led_bianchi), .LED_LOADING(led_loading)
  );

  // Generated by scripts/board_gls.py: defines `GLS_CPU_CLK, the shadow
  // write-port trackers and task dump_state.
  `include "gls_probes.vh"

  reg [7:0] stream [0:4095];
  reg [7:0] report [0:14];
  reg [1023:0] bytes_path;
  integer n_bytes, i, j, ks, kr, max_in_cycles, settle;
  reg [7:0] v;

  task send_byte(input [7:0] value);
    begin
      uart_rx = 1'b0;
      repeat (CPB) @(posedge `GLS_CPU_CLK);
      for (ks = 0; ks < 8; ks = ks + 1) begin
        uart_rx = value[ks];
        repeat (CPB) @(posedge `GLS_CPU_CLK);
      end
      uart_rx = 1'b1;
      repeat (CPB) @(posedge `GLS_CPU_CLK);
    end
  endtask

  task recv_byte(output [7:0] value);
    begin
      @(negedge uart_tx);
      repeat (CPB / 2) @(posedge `GLS_CPU_CLK);
      for (kr = 0; kr < 8; kr = kr + 1) begin
        repeat (CPB) @(posedge `GLS_CPU_CLK);
        value[kr] = uart_tx;
      end
      repeat (CPB) @(posedge `GLS_CPU_CLK);
    end
  endtask

  // Watchdog on the board oscillator, so a CPU clock that never starts is
  // reported rather than hanging the simulation.
  initial begin
    if (!$value$plusargs("MAX_IN_CYCLES=%d", max_in_cycles)) max_in_cycles = 200000000;
    repeat (max_in_cycles) @(posedge clk_p);
    $display("{\"timeout\": 1}");
    $finish;
  end

  initial begin
    if (!$value$plusargs("BYTES=%s", bytes_path)) begin
      $display("{\"error\": \"no +BYTES\"}");
      $finish;
    end
    if (!$value$plusargs("N_BYTES=%d", n_bytes)) n_bytes = 0;
    if (!$value$plusargs("SETTLE=%d", settle)) settle = 2000;
    $readmemh(bytes_path, stream);
    // The CPU clock exists only after the MMCM locks (BUFGCE gates it).
    repeat (32) @(posedge `GLS_CPU_CLK);
    if (!$test$plusargs("NO_RESET_PRESS")) begin
      cpu_reset_n = 1'b0;
      repeat (16) @(posedge `GLS_CPU_CLK);
      cpu_reset_n = 1'b1;
    end
    repeat (2000) @(posedge `GLS_CPU_CLK);
    fork
      for (i = 0; i < n_bytes; i = i + 1) send_byte(stream[i]);
      for (j = 0; j < 15; j = j + 1) begin
        recv_byte(v);
        report[j] = v;
      end
    join
    repeat (settle) @(posedge `GLS_CPU_CLK);
    $write("{\"report\": {\"sync\": %0d, \"status\": %0d, \"pc\": %0d, \"mu\": %0d, \"error_code\": %0d, \"end\": %0d}",
           report[0], report[1],
           {report[5], report[4], report[3], report[2]},
           {report[9], report[8], report[7], report[6]},
           {report[13], report[12], report[11], report[10]},
           report[14]);
    $write(", \"leds\": {\"halted\": %0d, \"err\": %0d, \"bianchi\": %0d, \"loading\": %0d}",
           led_halted, led_err, led_bianchi, led_loading);
    $write(", \"state\": ");
    dump_state;
    $display("}");
    $finish;
  end
endmodule
