From Kernel Require Import UniversalCertificationCost MuInitiality ThieleInitiality
  A2Payoff ElliptopeGate PointerObservableReductions PointerObservableCounterexamples
  F1_StrongForm.
From KamiHW Require Import GraphReconstructionBridge VerilogSemantics.

Print Assumptions universal_nfi_any_substrate.
Print Assumptions mu_is_initial_monotone.
Print Assumptions thiele_is_initial_a2_substrate.
Print Assumptions a2_equal_trust_substitution_payoff.
Print Assumptions elliptope_check_full_sound.
Print Assumptions five_disciplines_are_pointers.
Print Assumptions F1_physical_premises_incompatible.
Print Assumptions driven_trace_commutes.
Print Assumptions coq_kami_model_trace_correct_wf.
