(** Realize.v: the entry points of the extracted machines, and the proof that
    they are the functions the theorems are about.

    The small machine (minimal/EarnedCore.v), the multi-register host with
    and without PAY (minimal/EarnedMulti.v, minimal/EarnedMultiPriced.v), the
    fixed host program U (UniversalLayout.v) with its loader (UniversalSim.v)
    and the host property PSlot (UniversalCodes.v) are extracted to OCaml
    from RealizeExtract.v. The only things extracted are the names defined
    in this file and in RealizePriced.v, all prefixed rlz_. This file shows
    that each of them is, by conversion (Coq's own equality check, eq_refl),
    the object that the theorems speak of.

    How the names are made.
      * Where the original function lives in a file that Coq's extraction can
        use (EarnedCore.v, EarnedMulti.v, EarnedMultiPriced.v), the rlz_ name
        is a Definition equal to the original at the original arguments.
      * Coq's monolithic extraction refuses any constant that lives in a file
        containing a module alias, and any term that names a constant through
        a module alias. UniversalCodes.v is such a file. For its functions
        (the pairing, the codes of instructions, the property PSlot) and for
        the loader hregs the rlz_ name is a copy written out with canonical
        names, followed by an eq_refl proof that it is the original, so Coq's
        kernel checks each copy.
      * The program U is a list of thousands of instructions, built in files
        Coq's extraction cannot read. RealizePrograms.v holds U as a literal
        list, generated by scripts/realize_gen_programs.py from Coq's own
        evaluation of U, with an eq_refl proof that it is U.

    The statements rlz_small_halting_correspondence,
    rlz_small_mu_conservation_trace and rlz_host_halting_statement restate
    theorems or definitions of the originals with the rlz_ names, and are
    proved by the originals themselves.

    Dependencies: the Coq standard library, the files named above. No axioms,
    no Admitted.                                                           *)

(* SCOPE NOTE: foundation connectivity gap suppressed, on purpose: this
   file only renames and re-proves; the claims about these machines are in
   the files named above. *)

From Coq Require Import List Arith Lia Bool.
Import ListNotations.
Require Import Kernel.RealizeNames.
Require Kernel.RealizePrograms.

(* ================================================================= *)
(* 1. The small machine.                                              *)
(* ================================================================= *)

Definition rlz_small_exec := Minimal.EarnedCore.exec.
Definition rlz_small_run := Minimal.EarnedCore.run.
Definition rlz_small_step := Minimal.EarnedCore.step.
Definition rlz_small_run_prog := Minimal.EarnedCore.run_prog.
Definition rlz_small_trace_of := Minimal.EarnedCore.trace_of.
Definition rlz_small_compile := Minimal.EarnedCore.compile.
Definition rlz_small_start := Minimal.EarnedCore.start.

Lemma rlz_small_exec_is : rlz_small_exec = E.exec. Proof. reflexivity. Qed.
Lemma rlz_small_run_is : rlz_small_run = E.run. Proof. reflexivity. Qed.
Lemma rlz_small_step_is : rlz_small_step = E.step. Proof. reflexivity. Qed.
Lemma rlz_small_run_prog_is : rlz_small_run_prog = E.run_prog. Proof. reflexivity. Qed.
Lemma rlz_small_trace_of_is : rlz_small_trace_of = E.trace_of. Proof. reflexivity. Qed.
Lemma rlz_small_compile_is : rlz_small_compile = E.compile. Proof. reflexivity. Qed.
Lemma rlz_small_start_is : rlz_small_start = E.start. Proof. reflexivity. Qed.

(* The theorems of EarnedCore.v, stated with the extracted names. *)
Theorem rlz_small_halting_correspondence : forall M a b,
  (exists n, E.mstep M (E.mrun n M (1, (a, b))) = None) <->
  (exists n, E.halted (rlz_small_compile M)
               (E.core_of (rlz_small_run_prog n (rlz_small_compile M) (rlz_small_start a b)))).
Proof. exact E.halting_correspondence. Qed.

Theorem rlz_small_mu_conservation_trace : forall tr s,
  E.mu (rlz_small_run tr s) = E.mu s + E.total_cost tr.
Proof. exact E.mu_conservation_trace. Qed.

Theorem rlz_small_run_prog_trace : forall n P s,
  rlz_small_run_prog n P s = rlz_small_run (rlz_small_trace_of n P s) s.
Proof. exact E.run_prog_trace. Qed.

(* ================================================================= *)
(* 2. The multi-register host over the counter language, with and     *)
(*    without PAY.                                                    *)
(* ================================================================= *)

Definition rlz_multi_exec :=
  Minimal.EarnedMulti.exec Minimal.EarnedCore.prop_eqb Minimal.EarnedCore.eval.
Definition rlz_multi_run :=
  Minimal.EarnedMulti.run Minimal.EarnedCore.prop_eqb Minimal.EarnedCore.eval.
Definition rlz_multi_step :=
  Minimal.EarnedMulti.step Minimal.EarnedCore.prop_eqb Minimal.EarnedCore.eval.
Definition rlz_multi_run_prog :=
  Minimal.EarnedMulti.run_prog Minimal.EarnedCore.prop_eqb Minimal.EarnedCore.eval.
Definition rlz_multi_trace_of :=
  Minimal.EarnedMulti.trace_of Minimal.EarnedCore.prop_eqb Minimal.EarnedCore.eval.
Definition rlz_multi_start := @Minimal.EarnedMulti.start Minimal.EarnedCore.prop.

Lemma rlz_multi_run_prog_is : rlz_multi_run_prog = M.run_prog E.prop_eqb E.eval.
Proof. reflexivity. Qed.
Lemma rlz_multi_step_is : rlz_multi_step = M.step E.prop_eqb E.eval.
Proof. reflexivity. Qed.
Lemma rlz_multi_exec_is : rlz_multi_exec = M.exec E.prop_eqb E.eval.
Proof. reflexivity. Qed.
Lemma rlz_multi_run_is : rlz_multi_run = M.run E.prop_eqb E.eval.
Proof. reflexivity. Qed.

Theorem rlz_multi_mu_conservation_trace : forall tr s,
  M.mu (rlz_multi_run tr s) = M.mu s + M.total_cost tr.
Proof. exact (M.multi_mu_conservation_trace E.prop_eqb E.eval). Qed.

Definition rlz_pmulti_exec :=
  Minimal.EarnedMultiPriced.pu_exec Minimal.EarnedCore.prop_eqb Minimal.EarnedCore.eval.
Definition rlz_pmulti_run :=
  Minimal.EarnedMultiPriced.pu_run Minimal.EarnedCore.prop_eqb Minimal.EarnedCore.eval.
Definition rlz_pmulti_step :=
  Minimal.EarnedMultiPriced.pu_step Minimal.EarnedCore.prop_eqb Minimal.EarnedCore.eval.
Definition rlz_pmulti_run_prog :=
  Minimal.EarnedMultiPriced.pu_run_prog Minimal.EarnedCore.prop_eqb Minimal.EarnedCore.eval.
Definition rlz_pmulti_trace_of :=
  Minimal.EarnedMultiPriced.pu_trace_of Minimal.EarnedCore.prop_eqb Minimal.EarnedCore.eval.
Definition rlz_pmulti_start := @Minimal.EarnedMultiPriced.pu_start Minimal.EarnedCore.prop.

Lemma rlz_pmulti_run_prog_is : rlz_pmulti_run_prog = PM.pu_run_prog E.prop_eqb E.eval.
Proof. reflexivity. Qed.
Lemma rlz_pmulti_step_is : rlz_pmulti_step = PM.pu_step E.prop_eqb E.eval.
Proof. reflexivity. Qed.
Lemma rlz_pmulti_exec_is : rlz_pmulti_exec = PM.pu_exec E.prop_eqb E.eval.
Proof. reflexivity. Qed.
Lemma rlz_pmulti_run_is : rlz_pmulti_run = PM.pu_run E.prop_eqb E.eval.
Proof. reflexivity. Qed.

(* ================================================================= *)
(* 3. The two-counter guest over the counter language, with and       *)
(*    without PAY (EarnedGeneric.v, EarnedPriced.v). These are named   *)
(*    here for the unit tests; EarnedPriced.v contains a module       *)
(*    alias, so they are not extracted.                               *)
(* ================================================================= *)

Definition rlz_gen_exec := G.exec G.cprop_eqb G.ceval.
Definition rlz_gen_run := G.run G.cprop_eqb G.ceval.
Definition rlz_gen_step := G.step G.cprop_eqb G.ceval.
Definition rlz_gen_run_prog := G.run_prog G.cprop_eqb G.ceval.
Definition rlz_gen_trace_of := G.trace_of G.cprop_eqb G.ceval.
Definition rlz_gen_start := @G.start G.cprop.

Definition rlz_pgen_exec := PG.pr_exec G.cprop_eqb G.ceval.
Definition rlz_pgen_run := PG.pr_run G.cprop_eqb G.ceval.
Definition rlz_pgen_step := PG.pr_step G.cprop_eqb G.ceval.
Definition rlz_pgen_run_prog := PG.pr_run_prog G.cprop_eqb G.ceval.
Definition rlz_pgen_trace_of := PG.pr_trace_of G.cprop_eqb G.ceval.

(* A program without PAY runs on the priced guest exactly as on the
   generic one: EarnedPriced.v priced_extends_generic, with the rlz names. *)
Theorem rlz_pgen_extends_gen : forall n P s,
  rlz_pgen_run_prog n (map PG.pr_embed P) s = rlz_gen_run_prog n P s.
Proof.
  intros n P s. exact (proj1 (PG.priced_extends_generic G.cprop_eqb G.ceval n P s)).
Qed.


(* ================================================================= *)
(* 4. The host that runs U: PSlot over the counter language.          *)
(* ================================================================= *)

(* Copies of the functions of UniversalCodes.v that the host and its loader
   use, written with canonical names so that extraction can read them. Each
   is followed by the eq_refl proof that it is the original. *)

Definition rlz_pair (m n : nat) : nat := (n + n + 1) * 2 ^ m.

Fixpoint rlz_unp (fuel x m : nat) : option (nat * nat) :=
  match fuel with
  | 0 => None
  | S f =>
      match x with
      | 0 => None
      | S _ => if Nat.odd x then Some (m, Nat.div2 x) else rlz_unp f (Nat.div2 x) (S m)
      end
  end.

Definition rlz_unpair (x : nat) : option (nat * nat) := rlz_unp x x 0.

Definition rlz_pcode (p : Minimal.EarnedCore.prop) : nat :=
  match p with
  | Minimal.EarnedCore.PZero => 0
  | Minimal.EarnedCore.PEven => 1
  | Minimal.EarnedCore.PGe n => n + 2
  end.

Definition rlz_pdec (n : nat) : Minimal.EarnedCore.prop :=
  match n with
  | 0 => Minimal.EarnedCore.PZero
  | 1 => Minimal.EarnedCore.PEven
  | S (S m) => Minimal.EarnedCore.PGe m
  end.

Definition rlz_ccode (c : Minimal.EarnedCore.ctr) : nat :=
  match c with Minimal.EarnedCore.CA => 0 | Minimal.EarnedCore.CB => 1 end.

Definition rlz_icode (i : Minimal.EarnedCore.instr) : nat :=
  match i with
  | Minimal.EarnedCore.INC c => rlz_pair 0 (rlz_ccode c)
  | Minimal.EarnedCore.DEC c j => rlz_pair 1 (rlz_pair (rlz_ccode c) j)
  | Minimal.EarnedCore.HALT => rlz_pair 2 0
  | Minimal.EarnedCore.CHECK p c => rlz_pair 3 (rlz_pair (rlz_ccode c) (rlz_pcode p))
  | Minimal.EarnedCore.COMMIT p c => rlz_pair 4 (rlz_pair (rlz_ccode c) (rlz_pcode p))
  | Minimal.EarnedCore.CERTIFY => rlz_pair 5 0
  end.

Definition rlz_prog_code (P : list Minimal.EarnedCore.instr) : nat :=
  Minimal.EarnedGeneric.encode (map rlz_icode P).

Lemma rlz_pair_is : rlz_pair = UC.pair. Proof. reflexivity. Qed.
Lemma rlz_unp_is : rlz_unp = UC.unp. Proof. reflexivity. Qed.
Lemma rlz_unpair_is : rlz_unpair = UC.unpair. Proof. reflexivity. Qed.
Lemma rlz_pcode_is : rlz_pcode = UC.pcode. Proof. reflexivity. Qed.
Lemma rlz_pdec_is : rlz_pdec = UC.pdec. Proof. reflexivity. Qed.
Lemma rlz_ccode_is : rlz_ccode = UC.ccode. Proof. reflexivity. Qed.
Lemma rlz_icode_is : rlz_icode = UC.icode. Proof. reflexivity. Qed.
Lemma rlz_prog_code_is : rlz_prog_code = UC.prog_code. Proof. reflexivity. Qed.

(* The property language of the host (UniversalCodes.v): the one property
   PSlot, which holds of a counter holding pair (pcode p) v with p true of
   v. *)
Definition rlz_host_prop_eqb (p q : Minimal.UniversalCodes.hprop) : bool :=
  match p, q with Minimal.UniversalCodes.PSlot, Minimal.UniversalCodes.PSlot => true end.

Definition rlz_host_eval (p : Minimal.UniversalCodes.hprop) (x : nat) : bool :=
  match rlz_unpair x with
  | Some (m, v) => Minimal.EarnedCore.eval (rlz_pdec m) v
  | None => false
  end.

Lemma rlz_host_prop_eqb_is : rlz_host_prop_eqb = UC.hprop_eqb. Proof. reflexivity. Qed.
Lemma rlz_host_eval_is : rlz_host_eval = UC.heval. Proof. reflexivity. Qed.

Definition rlz_host_exec :=
  Minimal.EarnedMulti.exec rlz_host_prop_eqb rlz_host_eval.
Definition rlz_host_run :=
  Minimal.EarnedMulti.run rlz_host_prop_eqb rlz_host_eval.
Definition rlz_host_step :=
  Minimal.EarnedMulti.step rlz_host_prop_eqb rlz_host_eval.
Definition rlz_host_run_prog :=
  Minimal.EarnedMulti.run_prog rlz_host_prop_eqb rlz_host_eval.
Definition rlz_host_trace_of :=
  Minimal.EarnedMulti.trace_of rlz_host_prop_eqb rlz_host_eval.
Definition rlz_host_start := @Minimal.EarnedMulti.start Minimal.UniversalCodes.hprop.

(* The program U: the literal list of RealizePrograms.v, proved equal to U. *)
Definition rlz_host_program :
  list (@Minimal.EarnedMulti.instr Minimal.UniversalCodes.hprop) :=
  Kernel.RealizePrograms.rlz_host_program.

Lemma rlz_host_program_is : rlz_host_program = UL.U.
Proof. exact Kernel.RealizePrograms.rlz_host_program_is. Qed.

(* The loader: RA and RB hold the guest's inputs, PROG the program code,
   GPC the guest pc 1; every other register 0 (UniversalSim.v hregs, hload). *)
Definition rlz_host_regs (P : list Minimal.EarnedCore.instr) (x y r : nat) : nat :=
  if Nat.eqb r 0 then x else
  if Nat.eqb r 1 then y else
  if Nat.eqb r 2 then rlz_prog_code P else
  if Nat.eqb r 3 then 1 else 0.

Definition rlz_host_load (P : list Minimal.EarnedCore.instr) (x y : nat)
  : @Minimal.EarnedMulti.state Minimal.UniversalCodes.hprop :=
  rlz_host_start (rlz_host_regs P x y).

Lemma rlz_host_regs_is : rlz_host_regs = US.hregs. Proof. reflexivity. Qed.
Lemma rlz_host_load_is : rlz_host_load = US.hload. Proof. reflexivity. Qed.

(* The extracted host run is the run of the theorems. *)
Lemma rlz_host_run_prog_is :
  rlz_host_run_prog = M.run_prog UC.hprop_eqb UC.heval.
Proof. reflexivity. Qed.

(* The host after n steps of U from the loaded guest P, inputs x, y: the
   term the theorems of UniversalRun.v call hrun P x y n. *)
Definition rlz_host_at (P : list Minimal.EarnedCore.instr) (x y n : nat)
  : @Minimal.EarnedMulti.state Minimal.UniversalCodes.hprop :=
  rlz_host_run_prog n rlz_host_program (rlz_host_load P x y).

Lemma rlz_host_at_is : forall P x y n,
  rlz_host_at P x y n = M.run_prog UC.hprop_eqb UC.heval n UL.U (US.hload P x y).
Proof. intros. unfold rlz_host_at. rewrite rlz_host_program_is. reflexivity. Qed.

(* The guest the host simulates: the small machine after m steps from
   start x y. *)
Definition rlz_guest_at (P : list Minimal.EarnedCore.instr) (x y m : nat)
  : Minimal.EarnedCore.state :=
  rlz_small_run_prog m P (rlz_small_start x y).

(* The statement of UniversalRun.v universal_halting, with the extracted
   names: the guest halts exactly when the host halts. *)
Definition rlz_host_halting_statement (P : list E.instr) (x y : nat) : Prop :=
  (exists m, E.halted P (E.core_of (rlz_guest_at P x y m))) <->
  (exists n, M.halted UL.U (M.core_of (rlz_host_at P x y n))).
