Require Import Kernel.VMAlternativeCounterAccess.
Print Kernel.VMAlternativeCounterAccess.diagonal_counter_witness.
Print Kernel.VMAlternativeCounterAccess.diagonal_sos_condition.
Check Kernel.VMAlternativeCounterAccess.diagonal_base_guard.
Print Assumptions Kernel.VMAlternativeCounterAccess.diagonal_base_guard.
Check Kernel.VMAlternativeCounterAccess.diagonal_increment_first.
Print Assumptions Kernel.VMAlternativeCounterAccess.diagonal_increment_first.
Check Kernel.VMAlternativeCounterAccess.diagonal_decrement_first.
Print Assumptions Kernel.VMAlternativeCounterAccess.diagonal_decrement_first.
Check Kernel.VMAlternativeCounterAccess.diagonal_increment_second.
Print Assumptions Kernel.VMAlternativeCounterAccess.diagonal_increment_second.
Check Kernel.VMAlternativeCounterAccess.diagonal_decrement_second.
Print Assumptions Kernel.VMAlternativeCounterAccess.diagonal_decrement_second.
Check Kernel.VMAlternativeCounterAccess.diagonal_combined_guard.
Print Assumptions Kernel.VMAlternativeCounterAccess.diagonal_combined_guard.
Check Kernel.VMAlternativeCounterAccess.diagonal_combined_symmetric.
Print Assumptions Kernel.VMAlternativeCounterAccess.diagonal_combined_symmetric.
Check Kernel.VMAlternativeCounterAccess.diagonal_nonzero_counters_can_pass.
Print Assumptions Kernel.VMAlternativeCounterAccess.diagonal_nonzero_counters_can_pass.
Check Kernel.VMAlternativeCounterAccess.diagonal_nonzero_counters_can_fail.
Print Assumptions Kernel.VMAlternativeCounterAccess.diagonal_nonzero_counters_can_fail.
Check Kernel.VMAlternativeCounterAccess.diagonal_swapped_zero_tests_collide.
Print Assumptions Kernel.VMAlternativeCounterAccess.diagonal_swapped_zero_tests_collide.
