From Kernel Require Import VMUnboundedMinskyInterpreter.
From Kernel Require Import VMUnboundedMinskyInterpreterProof.
From Kernel Require Import VMUnboundedMinskyEncoding.
From Kernel Require Import VMUnboundedMinskyCorrectness.

Print minsky_interpreter_program_length.
Print Assumptions minsky_interpreter_program_length.
Print minsky_program_fits_encoding_width.
Print Assumptions minsky_program_fits_encoding_width.
Print encode_minsky_program_fetch.
Print Assumptions encode_minsky_program_fetch.
Print uniform_interpreter_simulation_total.
Print Assumptions uniform_interpreter_simulation_total.
Print uniform_interpreter_run_simulation.
Print Assumptions uniform_interpreter_run_simulation.
Print interpreter_boundary_run_sound.
Print Assumptions interpreter_boundary_run_sound.
Print interpreter_boundary_run_complete.
Print Assumptions interpreter_boundary_run_complete.
Print uniform_interpreter_correct_total.
Print Assumptions uniform_interpreter_correct_total.
Print uniform_interpreter_correct_complete_total.
Print Assumptions uniform_interpreter_correct_complete_total.
Print uniform_interpreter_divergence_total.
Print Assumptions uniform_interpreter_divergence_total.
Print uniform_interpreter_malformed.
Print Assumptions uniform_interpreter_malformed.
Print total_encoding_never_malformed_opcode.
Print Assumptions total_encoding_never_malformed_opcode.
Print minsky_halt_malformed_disjoint.
Print Assumptions minsky_halt_malformed_disjoint.
Print minsky_guest_trap_unreachable.
Print Assumptions minsky_guest_trap_unreachable.

Print minsky_result.
Print interpreter_raw_produces.
Print interpreter_raw_diverges.
Print minsky_rep.
Print minsky_halt_rep.
Print minsky_total_config_encoding.
Print uniform_interpreter_raw_sound.
Print Assumptions uniform_interpreter_raw_sound.
Print uniform_interpreter_raw_correct_total.
Print Assumptions uniform_interpreter_raw_correct_total.
Print uniform_interpreter_raw_never_malformed.
Print Assumptions uniform_interpreter_raw_never_malformed.
Print uniform_interpreter_raw_divergence_total.
Print Assumptions uniform_interpreter_raw_divergence_total.
Print minsky_ambient.
Print uniform_interpreter_raw_frame.
Print Assumptions uniform_interpreter_raw_frame.
Print uniform_interpreter_raw_pc_bound.
Print Assumptions uniform_interpreter_raw_pc_bound.
Print uniform_interpreter_divergence_live_prefixes.
Print Assumptions uniform_interpreter_divergence_live_prefixes.
