Require Import Kernel.VMCounterBranch.
Print Kernel.VMUnboundedCounterAccess.counter_witness.
Print Kernel.VMCounterBranch.counter_branch_result.
Print Kernel.VMCounterBranch.counter_iteration_result.
Print Kernel.VMCounterBranch.counter_rounds.
Print Kernel.VMCounterBranch.counter_drain_program.
Print Kernel.SimulationProof.run_vm.
Print Kernel.VMUnboundedExec.vm_halts_at.
Check Kernel.VMCounterBranch.counter_branch_correct.
Print Assumptions Kernel.VMCounterBranch.counter_branch_correct.
Check Kernel.VMCounterBranch.counter_drain_iteration.
Print Assumptions Kernel.VMCounterBranch.counter_drain_iteration.
Check Kernel.VMCounterBranch.counter_drain_exit.
Print Assumptions Kernel.VMCounterBranch.counter_drain_exit.
Check Kernel.VMCounterBranch.counter_drain_correct.
Print Assumptions Kernel.VMCounterBranch.counter_drain_correct.
Check Kernel.VMCounterBranch.counter_rounds_fields.
Print Assumptions Kernel.VMCounterBranch.counter_rounds_fields.
Check Kernel.VMCounterBranch.counter_rounds_frame.
Print Assumptions Kernel.VMCounterBranch.counter_rounds_frame.
Check Kernel.VMCounterBranch.counter_drain_halts.
Print Assumptions Kernel.VMCounterBranch.counter_drain_halts.
Check Kernel.VMCounterBranch.counter_branch_repeats_after_error.
Print Assumptions Kernel.VMCounterBranch.counter_branch_repeats_after_error.
Check Kernel.VMCounterBranch.counter_equal_preserves_existing_error_and_data.
Print Assumptions Kernel.VMCounterBranch.counter_equal_preserves_existing_error_and_data.
Check Kernel.VMCounterBranch.counter_unequal_reaches_equal_witness.
Print Assumptions Kernel.VMCounterBranch.counter_unequal_reaches_equal_witness.
Print Kernel.VMCounterBranch.counter_update_result.
Check Kernel.VMCounterBranch.counter_increment_correct.
Print Assumptions Kernel.VMCounterBranch.counter_increment_correct.
Check Kernel.VMCounterBranch.counter_decrement_correct.
Print Assumptions Kernel.VMCounterBranch.counter_decrement_correct.
