Require Import KamiHW.MorphRetirement.
Print KamiHW.MorphRetirement.raw_memory_pairs.
Print KamiHW.MorphRetirement.morph_precommit_footprint.
Check KamiHW.MorphRetirement.morph_nonempty_retirement.
Print Assumptions KamiHW.MorphRetirement.morph_nonempty_retirement.
Check KamiHW.MorphRetirement.morph_nonempty_retirement_firing_bound.
Print Assumptions KamiHW.MorphRetirement.morph_nonempty_retirement_firing_bound.
Check KamiHW.MorphRetirement.morph_retirement.
Print Assumptions KamiHW.MorphRetirement.morph_retirement.
Check KamiHW.MorphRetirement.morph_retirement_final_frame.
Print Assumptions KamiHW.MorphRetirement.morph_retirement_final_frame.
