Require Import KamiHW.NormalizationSteps.
Print KamiHW.NormalizationSteps.normalization_rule.
Print KamiHW.NormalizationSteps.PairTable.
Print KamiHW.NormalizationSteps.regpairs.
Print KamiHW.NormalizationSteps.word_eqb.
Print KamiHW.NormalizationSteps.word_ltb.
Print KamiHW.NormalizationSteps.pair_index.
Print KamiHW.NormalizationSteps.put_vector.
Print KamiHW.NormalizationSteps.normalization_scan_updates.
Print KamiHW.NormalizationSteps.normalization_emit_updates.
Print KamiHW.NormalizationSteps.normalization_commit_updates.
Check KamiHW.NormalizationSteps.normalization_scan_rule_name.
Print Assumptions KamiHW.NormalizationSteps.normalization_scan_rule_name.
Check KamiHW.NormalizationSteps.normalization_scan_rule_in.
Print Assumptions KamiHW.NormalizationSteps.normalization_scan_rule_in.
Check KamiHW.NormalizationSteps.normalization_scan_actual_action.
Print Assumptions KamiHW.NormalizationSteps.normalization_scan_actual_action.
Check KamiHW.NormalizationSteps.normalization_scan_actual_substep.
Print Assumptions KamiHW.NormalizationSteps.normalization_scan_actual_substep.
Check KamiHW.NormalizationSteps.normalization_emit_rule_name.
Print Assumptions KamiHW.NormalizationSteps.normalization_emit_rule_name.
Check KamiHW.NormalizationSteps.normalization_emit_rule_in.
Print Assumptions KamiHW.NormalizationSteps.normalization_emit_rule_in.
Check KamiHW.NormalizationSteps.normalization_emit_actual_action.
Print Assumptions KamiHW.NormalizationSteps.normalization_emit_actual_action.
Check KamiHW.NormalizationSteps.normalization_emit_actual_substep.
Print Assumptions KamiHW.NormalizationSteps.normalization_emit_actual_substep.
Check KamiHW.NormalizationSteps.normalization_commit_rule_name.
Print Assumptions KamiHW.NormalizationSteps.normalization_commit_rule_name.
Check KamiHW.NormalizationSteps.normalization_commit_rule_in.
Print Assumptions KamiHW.NormalizationSteps.normalization_commit_rule_in.
Check KamiHW.NormalizationSteps.normalization_commit_actual_action.
Print Assumptions KamiHW.NormalizationSteps.normalization_commit_actual_action.
Check KamiHW.NormalizationSteps.normalization_commit_actual_substep.
Print Assumptions KamiHW.NormalizationSteps.normalization_commit_actual_substep.
Check KamiHW.NormalizationSteps.normalization_scan_frame.
Print Assumptions KamiHW.NormalizationSteps.normalization_scan_frame.
Check KamiHW.NormalizationSteps.normalization_emit_frame.
Print Assumptions KamiHW.NormalizationSteps.normalization_emit_frame.
Check KamiHW.NormalizationSteps.normalization_commit_frame.
Print Assumptions KamiHW.NormalizationSteps.normalization_commit_frame.
Check KamiHW.NormalizationSteps.normalization_pointer_increment_no_wrap.
Print Assumptions KamiHW.NormalizationSteps.normalization_pointer_increment_no_wrap.
Check KamiHW.NormalizationSteps.normalization_pair_index_exact.
Print Assumptions KamiHW.NormalizationSteps.normalization_pair_index_exact.
Check KamiHW.NormalizationSteps.normalization_distinct_pair_indices.
Print Assumptions KamiHW.NormalizationSteps.normalization_distinct_pair_indices.
Check KamiHW.NormalizationSteps.normalization_emit_preserves_other_pair.
Print Assumptions KamiHW.NormalizationSteps.normalization_emit_preserves_other_pair.
Check KamiHW.NormalizationSteps.normalization_emit_preserves_unread_suffix.
Print Assumptions KamiHW.NormalizationSteps.normalization_emit_preserves_unread_suffix.
