Require Import KamiHW.NormalizationLoop.
Print KamiHW.NormalizationLoop.coupling_pair.
Print KamiHW.NormalizationLoop.table_pair.
Print KamiHW.NormalizationLoop.table_slice.
Print KamiHW.NormalizationLoop.scan_seen.
Print KamiHW.NormalizationLoop.retained_indices.
Print KamiHW.NormalizationLoop.retained_pairs.
Print KamiHW.NormalizationLoop.emitted_table.
Check KamiHW.NormalizationLoop.coupling_pair_eqb_true.
Print Assumptions KamiHW.NormalizationLoop.coupling_pair_eqb_true.
Check KamiHW.NormalizationLoop.scan_match_pair.
Print Assumptions KamiHW.NormalizationLoop.scan_match_pair.
Check KamiHW.NormalizationLoop.scan_seen_empty.
Print Assumptions KamiHW.NormalizationLoop.scan_seen_empty.
Check KamiHW.NormalizationLoop.scan_seen_extend.
Print Assumptions KamiHW.NormalizationLoop.scan_seen_extend.
Check KamiHW.NormalizationLoop.scan_seen_iff.
Print Assumptions KamiHW.NormalizationLoop.scan_seen_iff.
Check KamiHW.NormalizationLoop.scan_seen_slice.
Print Assumptions KamiHW.NormalizationLoop.scan_seen_slice.
Check KamiHW.NormalizationLoop.bounded_word_ltb.
Print Assumptions KamiHW.NormalizationLoop.bounded_word_ltb.
Check KamiHW.NormalizationLoop.normalization_scan_extends_seen.
Print Assumptions KamiHW.NormalizationLoop.normalization_scan_extends_seen.
Check KamiHW.NormalizationLoop.normalization_scan_terminal_seen.
Print Assumptions KamiHW.NormalizationLoop.normalization_scan_terminal_seen.
Check KamiHW.NormalizationLoop.normalization_scan_terminal_phase.
Print Assumptions KamiHW.NormalizationLoop.normalization_scan_terminal_phase.
Check KamiHW.NormalizationLoop.normalization_retained_pairs_nodup.
Print Assumptions KamiHW.NormalizationLoop.normalization_retained_pairs_nodup.
Check KamiHW.NormalizationLoop.normalization_retained_pairs_nodup_property.
Print Assumptions KamiHW.NormalizationLoop.normalization_retained_pairs_nodup_property.
Check KamiHW.NormalizationLoop.normalization_retained_pairs_membership.
Print Assumptions KamiHW.NormalizationLoop.normalization_retained_pairs_membership.
Check KamiHW.NormalizationLoop.scan_seen_agrees.
Print Assumptions KamiHW.NormalizationLoop.scan_seen_agrees.
Check KamiHW.NormalizationLoop.emitted_table_is_actual_src_update.
Print Assumptions KamiHW.NormalizationLoop.emitted_table_is_actual_src_update.
Check KamiHW.NormalizationLoop.emitted_table_is_actual_dst_update.
Print Assumptions KamiHW.NormalizationLoop.emitted_table_is_actual_dst_update.
Check KamiHW.NormalizationLoop.table_pair_after_emit_unread.
Print Assumptions KamiHW.NormalizationLoop.table_pair_after_emit_unread.
Check KamiHW.NormalizationLoop.normalization_emit_preserves_future_scan.
Print Assumptions KamiHW.NormalizationLoop.normalization_emit_preserves_future_scan.
Check KamiHW.NormalizationLoop.normalization_scan_advances_pointer.
Print Assumptions KamiHW.NormalizationLoop.normalization_scan_advances_pointer.
Check KamiHW.NormalizationLoop.normalization_scan_continues_phase.
Print Assumptions KamiHW.NormalizationLoop.normalization_scan_continues_phase.
Check KamiHW.NormalizationLoop.normalization_terminal_emit_selection.
Print Assumptions KamiHW.NormalizationLoop.normalization_terminal_emit_selection.
