Require Import KamiHW.NormalizationPrefix.
Print KamiHW.NormalizationPrefix.selected_prefix.
Print KamiHW.NormalizationPrefix.next_output.
Print KamiHW.NormalizationPrefix.normalization_prefix_invariant.
Check KamiHW.NormalizationPrefix.selected_prefix_start.
Print Assumptions KamiHW.NormalizationPrefix.selected_prefix_start.
Check KamiHW.NormalizationPrefix.selected_prefix_succ.
Print Assumptions KamiHW.NormalizationPrefix.selected_prefix_succ.
Check KamiHW.NormalizationPrefix.table_slice_succ.
Print Assumptions KamiHW.NormalizationPrefix.table_slice_succ.
Check KamiHW.NormalizationPrefix.table_pair_after_emit_other.
Print Assumptions KamiHW.NormalizationPrefix.table_pair_after_emit_other.
Check KamiHW.NormalizationPrefix.table_pair_after_emit_target.
Print Assumptions KamiHW.NormalizationPrefix.table_pair_after_emit_target.
Check KamiHW.NormalizationPrefix.table_slice_emit_prefix.
Print Assumptions KamiHW.NormalizationPrefix.table_slice_emit_prefix.
Check KamiHW.NormalizationPrefix.normalization_prefix_established.
Print Assumptions KamiHW.NormalizationPrefix.normalization_prefix_established.
Check KamiHW.NormalizationPrefix.normalization_prefix_scan_agrees.
Print Assumptions KamiHW.NormalizationPrefix.normalization_prefix_scan_agrees.
Check KamiHW.NormalizationPrefix.normalization_prefix_preserved.
Print Assumptions KamiHW.NormalizationPrefix.normalization_prefix_preserved.
Check KamiHW.NormalizationPrefix.normalization_actual_emit_preserves_prefix.
Print Assumptions KamiHW.NormalizationPrefix.normalization_actual_emit_preserves_prefix.
Check KamiHW.NormalizationPrefix.normalization_prefix_terminal_nodup.
Print Assumptions KamiHW.NormalizationPrefix.normalization_prefix_terminal_nodup.
Check KamiHW.NormalizationPrefix.normalization_prefix_terminal_nodup_property.
Print Assumptions KamiHW.NormalizationPrefix.normalization_prefix_terminal_nodup_property.
Check KamiHW.NormalizationPrefix.normalization_emit_output_nat.
Print Assumptions KamiHW.NormalizationPrefix.normalization_emit_output_nat.
Check KamiHW.NormalizationPrefix.normalization_actual_emit_output_pointer.
Print Assumptions KamiHW.NormalizationPrefix.normalization_actual_emit_output_pointer.
Check KamiHW.NormalizationPrefix.normalization_actual_emit_candidate_pointer.
Print Assumptions KamiHW.NormalizationPrefix.normalization_actual_emit_candidate_pointer.
Check KamiHW.NormalizationPrefix.normalization_actual_emit_terminal_end.
Print Assumptions KamiHW.NormalizationPrefix.normalization_actual_emit_terminal_end.
Check KamiHW.NormalizationPrefix.normalization_prefix_output_in_range.
Print Assumptions KamiHW.NormalizationPrefix.normalization_prefix_output_in_range.
