Require Import KamiHW.NormalizationScanExecution.
Print KamiHW.NormalizationScanExecution.scan_registers.
Print KamiHW.NormalizationScanExecution.scan_accumulated.
Print KamiHW.NormalizationScanExecution.scan_prefix_state.
Print KamiHW.NormalizationScanExecution.scan_complete_state.
Print KamiHW.NormalizationScanExecution.scan_rule_label.
Check KamiHW.NormalizationScanExecution.scan_prefix_frame.
Print Assumptions KamiHW.NormalizationScanExecution.scan_prefix_frame.
Check KamiHW.NormalizationScanExecution.scan_prefix_registers_advance.
Print Assumptions KamiHW.NormalizationScanExecution.scan_prefix_registers_advance.
Check KamiHW.NormalizationScanExecution.normalization_scan_prefix_execution.
Print Assumptions KamiHW.NormalizationScanExecution.normalization_scan_prefix_execution.
Check KamiHW.NormalizationScanExecution.normalization_scan_complete_execution.
Print Assumptions KamiHW.NormalizationScanExecution.normalization_scan_complete_execution.
Check KamiHW.NormalizationScanExecution.normalization_scan_complete_phase.
Print Assumptions KamiHW.NormalizationScanExecution.normalization_scan_complete_phase.
Check KamiHW.NormalizationScanExecution.normalization_scan_complete_duplicate.
Print Assumptions KamiHW.NormalizationScanExecution.normalization_scan_complete_duplicate.
Check KamiHW.NormalizationScanExecution.normalization_scan_complete_pointer.
Print Assumptions KamiHW.NormalizationScanExecution.normalization_scan_complete_pointer.
Check KamiHW.NormalizationScanExecution.normalization_scan_complete_frame.
Print Assumptions KamiHW.NormalizationScanExecution.normalization_scan_complete_frame.
Check KamiHW.NormalizationScanExecution.normalization_scan_complete_tables.
Print Assumptions KamiHW.NormalizationScanExecution.normalization_scan_complete_tables.
Check KamiHW.NormalizationScanExecution.normalization_scan_complete_firing_count.
Print Assumptions KamiHW.NormalizationScanExecution.normalization_scan_complete_firing_count.
