Require Import KamiHW.NormalizationExecution.
Print KamiHW.NormalizationExecution.normalization_label.
Check KamiHW.NormalizationExecution.no_call_rule_substep_is_step.
Print Assumptions KamiHW.NormalizationExecution.no_call_rule_substep_is_step.
Check KamiHW.NormalizationExecution.normalization_step_extends_execution.
Print Assumptions KamiHW.NormalizationExecution.normalization_step_extends_execution.
Check KamiHW.NormalizationExecution.normalization_substep_execution.
Print Assumptions KamiHW.NormalizationExecution.normalization_substep_execution.
Check KamiHW.NormalizationExecution.normalization_start_actual_step.
Print Assumptions KamiHW.NormalizationExecution.normalization_start_actual_step.
Check KamiHW.NormalizationExecution.normalization_scan_actual_step.
Print Assumptions KamiHW.NormalizationExecution.normalization_scan_actual_step.
Check KamiHW.NormalizationExecution.normalization_emit_actual_step.
Print Assumptions KamiHW.NormalizationExecution.normalization_emit_actual_step.
Check KamiHW.NormalizationExecution.normalization_commit_actual_step.
Print Assumptions KamiHW.NormalizationExecution.normalization_commit_actual_step.
Check KamiHW.NormalizationExecution.normalization_empty_execution.
Print Assumptions KamiHW.NormalizationExecution.normalization_empty_execution.
Check KamiHW.NormalizationExecution.normalization_commit_phase_zero.
Print Assumptions KamiHW.NormalizationExecution.normalization_commit_phase_zero.
Check KamiHW.NormalizationExecution.normalization_empty_descriptor_count.
Print Assumptions KamiHW.NormalizationExecution.normalization_empty_descriptor_count.
