Require Import KamiHW.NormalizationRetirement.
Print KamiHW.NormalizationRetirement.outer_footprint.
Print KamiHW.NormalizationRetirement.outer_frame.
Print KamiHW.NormalizationRetirement.outer_emitted.
Print KamiHW.NormalizationRetirement.normalization_started.
Check KamiHW.NormalizationRetirement.outer_emitted_frame.
Print Assumptions KamiHW.NormalizationRetirement.outer_emitted_frame.
Check KamiHW.NormalizationRetirement.outer_emit_execution.
Print Assumptions KamiHW.NormalizationRetirement.outer_emit_execution.
Check KamiHW.NormalizationRetirement.bounded_word_eqb.
Print Assumptions KamiHW.NormalizationRetirement.bounded_word_eqb.
Check KamiHW.NormalizationRetirement.outer_emitted_phase.
Print Assumptions KamiHW.NormalizationRetirement.outer_emitted_phase.
Check KamiHW.NormalizationRetirement.outer_emitted_end.
Print Assumptions KamiHW.NormalizationRetirement.outer_emitted_end.
Check KamiHW.NormalizationRetirement.outer_emitted_scan_registers.
Print Assumptions KamiHW.NormalizationRetirement.outer_emitted_scan_registers.
Check KamiHW.NormalizationRetirement.normalization_multistep_trans.
Print Assumptions KamiHW.NormalizationRetirement.normalization_multistep_trans.
Check KamiHW.NormalizationRetirement.normalization_outer_execution.
Print Assumptions KamiHW.NormalizationRetirement.normalization_outer_execution.
Check KamiHW.NormalizationRetirement.normalization_started_frame.
Print Assumptions KamiHW.NormalizationRetirement.normalization_started_frame.
Check KamiHW.NormalizationRetirement.normalization_started_reads.
Print Assumptions KamiHW.NormalizationRetirement.normalization_started_reads.
Check KamiHW.NormalizationRetirement.normalization_nonempty_retirement.
Print Assumptions KamiHW.NormalizationRetirement.normalization_nonempty_retirement.
Check KamiHW.NormalizationRetirement.normalization_commit_pair_tables.
Print Assumptions KamiHW.NormalizationRetirement.normalization_commit_pair_tables.
Check KamiHW.NormalizationRetirement.normalization_retirement.
Print Assumptions KamiHW.NormalizationRetirement.normalization_retirement.
Check KamiHW.NormalizationRetirement.normalization_committed_descriptor.
Print Assumptions KamiHW.NormalizationRetirement.normalization_committed_descriptor.
Check KamiHW.NormalizationRetirement.normalization_committed_frame.
Print Assumptions KamiHW.NormalizationRetirement.normalization_committed_frame.
Check KamiHW.NormalizationRetirement.normalization_descriptor_count_nat.
Print Assumptions KamiHW.NormalizationRetirement.normalization_descriptor_count_nat.
Check KamiHW.NormalizationRetirement.normalization_descriptor_count_exact.
Print Assumptions KamiHW.NormalizationRetirement.normalization_descriptor_count_exact.
Check KamiHW.NormalizationRetirement.normalization_outer_firing_formula.
Print Assumptions KamiHW.NormalizationRetirement.normalization_outer_firing_formula.
Check KamiHW.NormalizationRetirement.normalization_retirement_firing_bound.
Print Assumptions KamiHW.NormalizationRetirement.normalization_retirement_firing_bound.
