Require Import KamiHW.NormalizationExclusivity.
Print KamiHW.NormalizationExclusivity.normalization_rule_kind.
Print KamiHW.NormalizationExclusivity.normalization_kind_rule.
Print KamiHW.NormalizationExclusivity.normalization_kind_phase.
Print KamiHW.NormalizationExclusivity.normalization_action_enabled.
Print KamiHW.NormalizationExclusivity.normalization_register_bit_value.
Print KamiHW.NormalizationExclusivity.normalization_optional_bit_value.
Check KamiHW.NormalizationExclusivity.normalization_start_requires_phase.
Print Assumptions KamiHW.NormalizationExclusivity.normalization_start_requires_phase.
Check KamiHW.NormalizationExclusivity.normalization_scan_requires_phase.
Print Assumptions KamiHW.NormalizationExclusivity.normalization_scan_requires_phase.
Check KamiHW.NormalizationExclusivity.normalization_emit_requires_phase.
Print Assumptions KamiHW.NormalizationExclusivity.normalization_emit_requires_phase.
Check KamiHW.NormalizationExclusivity.normalization_commit_requires_phase.
Print Assumptions KamiHW.NormalizationExclusivity.normalization_commit_requires_phase.
Check KamiHW.NormalizationExclusivity.normalization_enabled_requires_phase.
Print Assumptions KamiHW.NormalizationExclusivity.normalization_enabled_requires_phase.
Check KamiHW.NormalizationExclusivity.normalization_enabled_unique_kind.
Print Assumptions KamiHW.NormalizationExclusivity.normalization_enabled_unique_kind.
Check KamiHW.NormalizationExclusivity.normalization_distinct_actions_mutually_exclusive.
Print Assumptions KamiHW.NormalizationExclusivity.normalization_distinct_actions_mutually_exclusive.
