Require Import KamiHW.NormalizationFrame.
Print KamiHW.NormalizationFrame.table_prefix_agrees.
Print KamiHW.NormalizationFrame.descriptor_pair_readout.
Check KamiHW.NormalizationFrame.table_prefix_agrees_refl.
Print Assumptions KamiHW.NormalizationFrame.table_prefix_agrees_refl.
Check KamiHW.NormalizationFrame.normalization_emit_preserves_low_prefix.
Print Assumptions KamiHW.NormalizationFrame.normalization_emit_preserves_low_prefix.
Check KamiHW.NormalizationFrame.normalization_outer_execution_with_prefix.
Print Assumptions KamiHW.NormalizationFrame.normalization_outer_execution_with_prefix.
Check KamiHW.NormalizationFrame.normalization_nonempty_retirement_with_prefix.
Print Assumptions KamiHW.NormalizationFrame.normalization_nonempty_retirement_with_prefix.
Check KamiHW.NormalizationFrame.normalization_retirement_with_prefix.
Print Assumptions KamiHW.NormalizationFrame.normalization_retirement_with_prefix.
Check KamiHW.NormalizationFrame.normalization_prefix_preserves_range_readout.
Print Assumptions KamiHW.NormalizationFrame.normalization_prefix_preserves_range_readout.
Check KamiHW.NormalizationFrame.normalization_commit_preserves_prefix_reads.
Print Assumptions KamiHW.NormalizationFrame.normalization_commit_preserves_prefix_reads.
Check KamiHW.NormalizationFrame.normalization_commit_other_descriptor.
Print Assumptions KamiHW.NormalizationFrame.normalization_commit_other_descriptor.
Check KamiHW.NormalizationFrame.normalization_commit_old_descriptor_readout.
Print Assumptions KamiHW.NormalizationFrame.normalization_commit_old_descriptor_readout.
