Require Import Kernel.VMTwoCounterAccess.
Print Kernel.VMTwoCounterAccess.two_counter_witness.
Print Kernel.VMTwoCounterAccess.two_counter_update_result.
Print Kernel.VMTwoCounterAccess.two_counter_next.
Check Kernel.VMTwoCounterAccess.first_test.
Print Assumptions Kernel.VMTwoCounterAccess.first_test.
Check Kernel.VMTwoCounterAccess.second_test_when_first_zero.
Print Assumptions Kernel.VMTwoCounterAccess.second_test_when_first_zero.
Check Kernel.VMTwoCounterAccess.combined_test.
Print Assumptions Kernel.VMTwoCounterAccess.combined_test.
Check Kernel.VMTwoCounterAccess.increment_first.
Print Assumptions Kernel.VMTwoCounterAccess.increment_first.
Check Kernel.VMTwoCounterAccess.decrement_first.
Print Assumptions Kernel.VMTwoCounterAccess.decrement_first.
Check Kernel.VMTwoCounterAccess.increment_second.
Print Assumptions Kernel.VMTwoCounterAccess.increment_second.
Check Kernel.VMTwoCounterAccess.decrement_second.
Print Assumptions Kernel.VMTwoCounterAccess.decrement_second.
Check Kernel.VMTwoCounterAccess.first_nonzero_rejects.
Print Assumptions Kernel.VMTwoCounterAccess.first_nonzero_rejects.
Check Kernel.VMTwoCounterAccess.all_extended_guards_reject.
Print Assumptions Kernel.VMTwoCounterAccess.all_extended_guards_reject.
Check Kernel.VMTwoCounterAccess.second_branch_when_first_zero.
Print Assumptions Kernel.VMTwoCounterAccess.second_branch_when_first_zero.
Check Kernel.VMTwoCounterAccess.two_counter_update_correct.
Print Assumptions Kernel.VMTwoCounterAccess.two_counter_update_correct.
