From Kernel Require Import VMUnboundedCM2Interpreter.
From Kernel Require Import VMUnboundedCM2InterpreterProof.
From Kernel Require Import VMUnboundedCM2Encoding.
From Kernel Require Import VMUnboundedCM2Correctness.

Print cm2_interpreter_program_length.
Print Assumptions cm2_interpreter_program_length.
Print cm2_program_fits_encoding_width.
Print Assumptions cm2_program_fits_encoding_width.
Print encode_cm2_program_fetch.
Print Assumptions encode_cm2_program_fetch.
Print cm2_uniform_interpreter_simulation_total.
Print Assumptions cm2_uniform_interpreter_simulation_total.
Print cm2_uniform_interpreter_run_simulation.
Print Assumptions cm2_uniform_interpreter_run_simulation.
Print interpreter_boundary_run_sound.
Print Assumptions interpreter_boundary_run_sound.
Print interpreter_boundary_run_complete.
Print Assumptions interpreter_boundary_run_complete.
Print cm2_uniform_interpreter_correct_total.
Print Assumptions cm2_uniform_interpreter_correct_total.
Print cm2_uniform_interpreter_correct_complete_total.
Print Assumptions cm2_uniform_interpreter_correct_complete_total.
Print cm2_uniform_interpreter_divergence_total.
Print Assumptions cm2_uniform_interpreter_divergence_total.
Print cm2_uniform_interpreter_malformed.
Print Assumptions cm2_uniform_interpreter_malformed.
Print total_encoding_never_malformed_opcode.
Print Assumptions total_encoding_never_malformed_opcode.
Print cm2_halt_malformed_disjoint.
Print Assumptions cm2_halt_malformed_disjoint.
Print cm2_guest_trap_unreachable.
Print Assumptions cm2_guest_trap_unreachable.

Print cm2_result.
Print interpreter_raw_produces.
Print interpreter_raw_diverges.
Print cm2_rep.
Print cm2_halt_rep.
Print cm2_total_config_encoding.
Print cm2_uniform_interpreter_raw_sound.
Print Assumptions cm2_uniform_interpreter_raw_sound.
Print cm2_uniform_interpreter_raw_correct_total.
Print Assumptions cm2_uniform_interpreter_raw_correct_total.
Print cm2_uniform_interpreter_raw_never_malformed.
Print Assumptions cm2_uniform_interpreter_raw_never_malformed.
Print cm2_uniform_interpreter_raw_divergence_total.
Print Assumptions cm2_uniform_interpreter_raw_divergence_total.
Print cm2_ambient.
Print cm2_uniform_interpreter_raw_frame.
Print Assumptions cm2_uniform_interpreter_raw_frame.
Print cm2_uniform_interpreter_raw_pc_bound.
Print Assumptions cm2_uniform_interpreter_raw_pc_bound.
Print cm2_uniform_interpreter_divergence_live_prefixes.
Print Assumptions cm2_uniform_interpreter_divergence_live_prefixes.

From Kernel Require Import VMUnboundedCM2Bridge VMUnboundedCM2Limitative VMUnboundedCM2Applicability.
Print mm2_guest_program.
Print Assumptions mm2_guest_program.
Print mm2_host_input.
Print Assumptions mm2_host_input.
Print cm2_host_halts.
Print Assumptions cm2_host_halts.
Print mm2_halting_host_iff.
Print Assumptions mm2_halting_host_iff.
Print mm2_to_actual_unbounded_host.
Print Assumptions mm2_to_actual_unbounded_host.
Print actual_unbounded_host_synthetic_undecidability.
Print Assumptions actual_unbounded_host_synthetic_undecidability.
Print Undecidability.undecidable.
Print Assumptions Undecidability.undecidable.
Print cm2_loop_host_never_halts.
Print Assumptions cm2_loop_host_never_halts.
Print zero_branch_pair_terminates.
Print Assumptions zero_branch_pair_terminates.
