Require Import Kernel.UniversalCertificationCost.
Require Import Kernel.CommitmentPredicateAdequacy.
Require Import Kernel.MuInitiality Kernel.NecessityAbstract.
Require Import VerifierExhaustiveness.
Require Import Kernel.HonestNoFI_TheoremsWithoutAssumptions.
Require Import Kernel.StructuralUndecidability Kernel.NatSubstrateInstance.
Require Import Kernel.VMSubstrateEncoded Kernel.VMBoundedDecidability.
Require Import Kernel.VMUnboundedExec Kernel.StructuralAxisOrthogonality.
Require Import Kernel.TuringClassicalEmbedding Kernel.ElliptopeGate.
Require Import Kernel.MuHierarchyTheorem.
Require Import KamiHW.GraphReconstructionBridge.
Print Kernel.UniversalCertificationCost.CertificationSystem.
Print Kernel.UniversalCertificationCost.CertCostMachine.
Print Kernel.CommitmentPredicateAdequacy.LocalPredicatePricedSystem.
Print Kernel.MuInitiality.CostFunctional.
Print Kernel.HonestNoFI_TheoremsWithoutAssumptions.SoundStructuralShortcut.
Print Kernel.VMSubstrateInstance.vm_run.
Print Kernel.StructuralUndecidability.vm_admits_shortcut_extensional.
Print Kernel.VMUnboundedExec.vm_halts_at.
Print KamiHW.GraphReconstructionBridge.extended_hw_invariant.
Print KamiHW.GraphReconstructionBridge.WFDrivenPrecondition.
Print KamiHW.GraphReconstructionBridge.WFDrivenRun.
Check Kernel.UniversalCertificationCost.universal_nfi_any_substrate.
Print Assumptions Kernel.UniversalCertificationCost.universal_nfi_any_substrate.
Check Kernel.CommitmentPredicateAdequacy.exact_commitment_pricing_characterization.
Print Assumptions Kernel.CommitmentPredicateAdequacy.exact_commitment_pricing_characterization.
Check Kernel.MuInitiality.mu_is_initial_monotone.
Print Assumptions Kernel.MuInitiality.mu_is_initial_monotone.
Check Kernel.NecessityAbstract.mu_ledger_mutual_independence.
Print Assumptions Kernel.NecessityAbstract.mu_ledger_mutual_independence.
Check VerifierExhaustiveness.V_does_not_factor_through_classical.
Print Assumptions VerifierExhaustiveness.V_does_not_factor_through_classical.
Check Kernel.HonestNoFI_TheoremsWithoutAssumptions.structural_entitlement_representation.
Print Assumptions Kernel.HonestNoFI_TheoremsWithoutAssumptions.structural_entitlement_representation.
Check Kernel.StructuralUndecidability.structural_shortcut_undecidable.
Print Assumptions Kernel.StructuralUndecidability.structural_shortcut_undecidable.
Check Kernel.NatSubstrateInstance.nat_self_undecidable.
Print Assumptions Kernel.NatSubstrateInstance.nat_self_undecidable.
Check Kernel.VMSubstrateEncoded.vm_structural_shortcut_undecidable_encoded.
Print Assumptions Kernel.VMSubstrateEncoded.vm_structural_shortcut_undecidable_encoded.
Check Kernel.VMBoundedDecidability.vm_bounded_shortcut_decide_correct.
Print Assumptions Kernel.VMBoundedDecidability.vm_bounded_shortcut_decide_correct.
Check Kernel.VMBoundedDecidability.vm_bounded_decider_flip_not_representable.
Print Assumptions Kernel.VMBoundedDecidability.vm_bounded_decider_flip_not_representable.
Check Kernel.VMUnboundedExec.vm_halts_at_deterministic.
Print Assumptions Kernel.VMUnboundedExec.vm_halts_at_deterministic.
Check Kernel.StructuralAxisOrthogonality.structural_shortcut_not_function_of_classical.
Print Assumptions Kernel.StructuralAxisOrthogonality.structural_shortcut_not_function_of_classical.
Check Kernel.TuringClassicalEmbedding.D2_classical_shadow_preserved.
Print Assumptions Kernel.TuringClassicalEmbedding.D2_classical_shadow_preserved.
Check Kernel.ElliptopeGate.elliptope_check_full_sound.
Print Assumptions Kernel.ElliptopeGate.elliptope_check_full_sound.
Check Kernel.MuHierarchyTheorem.level_k_certification_cost_floor.
Print Assumptions Kernel.MuHierarchyTheorem.level_k_certification_cost_floor.
Check KamiHW.GraphReconstructionBridge.driven_step_wf.
Print Assumptions KamiHW.GraphReconstructionBridge.driven_step_wf.
Check KamiHW.GraphReconstructionBridge.driven_trace_commutes.
Print Assumptions KamiHW.GraphReconstructionBridge.driven_trace_commutes.

Require Import Kernel.CHSH Kernel.QuantumPartitionPSD Kernel.CategoryLaws Kernel.DiscreteGaussBonnet.
Check Kernel.CHSH.KernelCHSH.local_strategy_chsh_between_neg2_2.
Print Assumptions Kernel.CHSH.KernelCHSH.local_strategy_chsh_between_neg2_2.
Check Kernel.QuantumPartitionPSD.column_contractive_iff_quantum_realizable.
Print Assumptions Kernel.QuantumPartitionPSD.column_contractive_iff_quantum_realizable.
Check Kernel.QuantumPartitionPSD.chsh_lassert_no_trap_implies_quantum_realizable.
Print Assumptions Kernel.QuantumPartitionPSD.chsh_lassert_no_trap_implies_quantum_realizable.
Check Kernel.CategoryLaws.relational_compose_assoc.
Print Assumptions Kernel.CategoryLaws.relational_compose_assoc.
Check Kernel.MuHierarchyTheorem.mu_hierarchy_theorem.
Print Assumptions Kernel.MuHierarchyTheorem.mu_hierarchy_theorem.
Check Kernel.DiscreteGaussBonnet.discrete_gauss_bonnet.
Print Assumptions Kernel.DiscreteGaussBonnet.discrete_gauss_bonnet.
Print Kernel.DiscreteTopology.well_formed_triangulated.

Require Import Kernel.VMEncodedInputAccess.
Check Kernel.VMEncodedInputAccess.vm_apply_logic_acc_commutes.
Print Assumptions Kernel.VMEncodedInputAccess.vm_apply_logic_acc_commutes.
Check Kernel.VMEncodedInputAccess.run_vm_logic_acc_commutes.
Print Assumptions Kernel.VMEncodedInputAccess.run_vm_logic_acc_commutes.
Check Kernel.VMEncodedInputAccess.no_logic_acc_encoded_interpreter.
Print Assumptions Kernel.VMEncodedInputAccess.no_logic_acc_encoded_interpreter.
