# Example: Simple Receipt Generation on Push
#
# This workflow generates receipts every time you push to main.
# Useful for continuous verification of your codebase.

name: Generate Receipts

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  create-receipt:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Create receipt for source code
        uses: ./.github/actions/create-receipt
        with:
          files: 'src/**/*.py'
          output: 'source-receipt.json'
          metadata: '{"commit":"${{ github.sha }}"}'
      
      - name: Upload receipt
        uses: actions/upload-artifact@v3
        with:
          name: receipts
          path: source-receipt.json
