# Example: Generate Receipts on Release
#
# This workflow demonstrates how to automatically generate
# Thiele receipts for your release artifacts.
#
# Copy this file to .github/workflows/receipts.yml to use it.

name: Generate Release Receipts

on:
  release:
    types: [published]
  workflow_dispatch: # Manual trigger for testing

jobs:
  generate-receipts:
    name: Generate Thiele Receipts
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Example: Build your project
      - name: Build project
        run: |
          # Replace with your actual build steps
          echo "Building project..."
          mkdir -p dist
          echo "print('Hello from receipt!')" > dist/app.py
          echo "# My Project" > dist/README.md
      
      # Generate receipt for all build artifacts
      - name: Create receipt for build artifacts
        uses: ./.github/actions/create-receipt
        with:
          files: 'dist/*'
          output: 'dist/receipt.json'
          metadata: |
            {
              "project": "${{ github.repository }}",
              "version": "${{ github.ref_name }}",
              "commit": "${{ github.sha }}",
              "build_date": "${{ github.event.head_commit.timestamp }}",
              "author": "${{ github.actor }}"
            }
      
      # Upload receipt as artifact
      - name: Upload receipt
        uses: actions/upload-artifact@v3
        with:
          name: thiele-receipts
          path: dist/receipt.json
      
      # Optionally: Attach receipt to release
      - name: Attach receipt to release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/receipt.json
          asset_name: receipt.json
          asset_content_type: application/json
      
      # Optionally: Verify the receipt
      - name: Verify receipt
        run: |
          python3 verifier/replay.py dist/receipt.json --dry-run
