(** ChshStepFields.v: generated by scripts/generate_chsh_step_fields.py.
    Field equations of [step_next] at the canonical CHSH_LASSERT encoding,
    including the CHSH latch registers the FSM later reads. *)
Require Import Kami.Kami Kami.Semantics.
From Coq Require Import String NArith Eqdep_dec Arith.PeanoNat.
From KamiHW Require Import ThieleTypes ThieleCPUCore HWBoundary RuleNext RuleStep
  BoundaryDecoded ActionObservation DispatchObservation StepEval StepFields ChshArith.
Open Scope string_scope.

Definition chsh_lassert_word (a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 : bool) : word InstrSz :=
  legacy_word OP_CHSH_LASSERT (bits8 a0 a1 a2 a3 a4 a5 a6 a7) (bits8 b0 b1 b2 b3 b4 b5 b6 b7) (bits8 c0 c1 c2 c3 c4 c5 c6 c7).
Lemma step_chsh_lassert_pc : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_pc (step_next b) = wplus (hw_pc b) (natToWord WordSz 1).
Proof. hw_field. Qed.
Lemma step_chsh_lassert_mu : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_mu (step_next b) = wplus (wplus (hw_mu b) (zext (bits8 c0 c1 c2 c3 c4 c5 c6 c7) 24)) (natToWord WordSz 1).
Proof. hw_field. Qed.
Lemma step_chsh_lassert_err : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_err (step_next b) = false.
Proof. hw_field. Qed.
Lemma step_chsh_lassert_halted : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_halted (step_next b) = false.
Proof. hw_field. Qed.
Lemma step_chsh_lassert_regs : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_regs (step_next b) = hw_regs b.
Proof. hw_field. Qed.
Lemma step_chsh_lassert_mem : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_mem (step_next b) = hw_mem b.
Proof. hw_field. Qed.
Lemma step_chsh_lassert_error_code : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_error_code (step_next b) = hw_error_code b.
Proof. hw_field. Qed.
Lemma step_chsh_lassert_cert_addr : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_cert_addr (step_next b) = hw_cert_addr b.
Proof. hw_field. Qed.
Lemma step_chsh_lassert_partition_ops : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_partition_ops (step_next b) = hw_partition_ops b.
Proof. hw_field. Qed.
Lemma step_chsh_lassert_mdl_ops : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_mdl_ops (step_next b) = hw_mdl_ops b.
Proof. hw_field. Qed.
Lemma step_chsh_lassert_info_gain : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_info_gain (step_next b) = hw_info_gain b.
Proof. hw_field. Qed.
Lemma step_chsh_lassert_mu_tensor : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_mu_tensor (step_next b) = hw_mu_tensor b.
Proof. hw_field. Qed.
Lemma step_chsh_lassert_module_tensors : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_module_tensors (step_next b) = hw_module_tensors b.
Proof. hw_field. Qed.
Lemma step_chsh_lassert_ptTable : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_ptTable (step_next b) = hw_ptTable b.
Proof. hw_field. Qed.
Lemma step_chsh_lassert_pt_next_id : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_pt_next_id (step_next b) = hw_pt_next_id b.
Proof. hw_field. Qed.
Lemma step_chsh_lassert_certified : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_certified (step_next b) = hw_certified b.
Proof. hw_field. Qed.
Lemma step_chsh_lassert_wc_same_00 : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_wc_same_00 (step_next b) = hw_wc_same_00 b.
Proof. hw_field. Qed.
Lemma step_chsh_lassert_wc_diff_00 : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_wc_diff_00 (step_next b) = hw_wc_diff_00 b.
Proof. hw_field. Qed.
Lemma step_chsh_lassert_wc_same_01 : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_wc_same_01 (step_next b) = hw_wc_same_01 b.
Proof. hw_field. Qed.
Lemma step_chsh_lassert_wc_diff_01 : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_wc_diff_01 (step_next b) = hw_wc_diff_01 b.
Proof. hw_field. Qed.
Lemma step_chsh_lassert_wc_same_10 : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_wc_same_10 (step_next b) = hw_wc_same_10 b.
Proof. hw_field. Qed.
Lemma step_chsh_lassert_wc_diff_10 : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_wc_diff_10 (step_next b) = hw_wc_diff_10 b.
Proof. hw_field. Qed.
Lemma step_chsh_lassert_wc_same_11 : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_wc_same_11 (step_next b) = hw_wc_same_11 b.
Proof. hw_field. Qed.
Lemma step_chsh_lassert_wc_diff_11 : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_wc_diff_11 (step_next b) = hw_wc_diff_11 b.
Proof. hw_field. Qed.
Lemma step_chsh_lassert_morph_src_table : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_morph_src_table (step_next b) = hw_morph_src_table b.
Proof. hw_field. Qed.
Lemma step_chsh_lassert_morph_dst_table : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_morph_dst_table (step_next b) = hw_morph_dst_table b.
Proof. hw_field. Qed.
Lemma step_chsh_lassert_morph_coupling_desc_table : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_morph_coupling_desc_table (step_next b) = hw_morph_coupling_desc_table b.
Proof. hw_field. Qed.
Lemma step_chsh_lassert_morph_identity_table : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_morph_identity_table (step_next b) = hw_morph_identity_table b.
Proof. hw_field. Qed.
Lemma step_chsh_lassert_morph_valid_table : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_morph_valid_table (step_next b) = hw_morph_valid_table b.
Proof. hw_field. Qed.
Lemma step_chsh_lassert_morph_next_id : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_morph_next_id (step_next b) = hw_morph_next_id b.
Proof. hw_field. Qed.
Lemma step_chsh_lassert_coupling_desc_label_table : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_coupling_desc_label_table (step_next b) = hw_coupling_desc_label_table b.
Proof. hw_field. Qed.
Lemma step_chsh_lassert_coupling_desc_label_len_table : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_coupling_desc_label_len_table (step_next b) = hw_coupling_desc_label_len_table b.
Proof. hw_field. Qed.
Lemma step_chsh_lassert_lassert_phase : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_lassert_phase (step_next b) = natToWord 3 0.
Proof. hw_field. Qed.
Lemma step_chsh_lassert_chsh_phase : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_chsh_phase (step_next b) = natToWord 5 1.
Proof. hw_field. Qed.
Lemma step_chsh_lassert_mc_phase : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_mc_phase (step_next b) = natToWord 4 0.
Proof. hw_field. Qed.
Lemma step_chsh_lassert_chsh_n00 : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_chsh_n00 (step_next b) = chsh_latch_n (hw_wc_same_00 b) (hw_wc_diff_00 b).
Proof. hw_field. Qed.
Lemma step_chsh_lassert_chsh_d00 : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_chsh_d00 (step_next b) = chsh_latch_abs (hw_wc_same_00 b) (hw_wc_diff_00 b).
Proof. hw_field. Qed.
Lemma step_chsh_lassert_chsh_sign00 : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_chsh_sign00 (step_next b) = chsh_latch_sign (hw_wc_same_00 b) (hw_wc_diff_00 b).
Proof. hw_field. Qed.
Lemma step_chsh_lassert_chsh_n01 : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_chsh_n01 (step_next b) = chsh_latch_n (hw_wc_same_01 b) (hw_wc_diff_01 b).
Proof. hw_field. Qed.
Lemma step_chsh_lassert_chsh_d01 : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_chsh_d01 (step_next b) = chsh_latch_abs (hw_wc_same_01 b) (hw_wc_diff_01 b).
Proof. hw_field. Qed.
Lemma step_chsh_lassert_chsh_sign01 : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_chsh_sign01 (step_next b) = chsh_latch_sign (hw_wc_same_01 b) (hw_wc_diff_01 b).
Proof. hw_field. Qed.
Lemma step_chsh_lassert_chsh_n10 : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_chsh_n10 (step_next b) = chsh_latch_n (hw_wc_same_10 b) (hw_wc_diff_10 b).
Proof. hw_field. Qed.
Lemma step_chsh_lassert_chsh_d10 : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_chsh_d10 (step_next b) = chsh_latch_abs (hw_wc_same_10 b) (hw_wc_diff_10 b).
Proof. hw_field. Qed.
Lemma step_chsh_lassert_chsh_sign10 : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_chsh_sign10 (step_next b) = chsh_latch_sign (hw_wc_same_10 b) (hw_wc_diff_10 b).
Proof. hw_field. Qed.
Lemma step_chsh_lassert_chsh_n11 : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_chsh_n11 (step_next b) = chsh_latch_n (hw_wc_same_11 b) (hw_wc_diff_11 b).
Proof. hw_field. Qed.
Lemma step_chsh_lassert_chsh_d11 : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_chsh_d11 (step_next b) = chsh_latch_abs (hw_wc_same_11 b) (hw_wc_diff_11 b).
Proof. hw_field. Qed.
Lemma step_chsh_lassert_chsh_sign11 : forall a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = chsh_lassert_word a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_chsh_sign11 (step_next b) = chsh_latch_sign (hw_wc_same_11 b) (hw_wc_diff_11 b).
Proof. hw_field. Qed.
