(** LassertStepFields.v: generated by scripts/generate_lassert_step_fields.py.
    Field equations of [step_next] at the canonical LASSERT encodings, with the
    kind bit fixed to SAT (the FSM starts) and to UNSAT (immediate trap). *)
Require Import Kami.Kami Kami.Semantics.
From Coq Require Import String NArith Eqdep_dec Arith.PeanoNat.
From KamiHW Require Import ThieleTypes ThieleCPUCore HWBoundary RuleNext RuleStep
  BoundaryDecoded ActionObservation DispatchObservation StepEval StepFields.
Open Scope string_scope.

Definition lassert_sat_word (a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 : bool) : word InstrSz :=
  legacy_word OP_LASSERT (bits8 a0 a1 a2 a3 a4 true a6 a7) (bits8 b0 b1 b2 b3 b4 b5 b6 b7) (bits8 c0 c1 c2 c3 c4 c5 c6 c7).
Lemma step_lassert_sat_pc : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_sat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_pc (step_next b) = hw_pc b.
Proof. hw_field. Qed.
Lemma step_lassert_sat_mu : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_sat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_mu (step_next b) = hw_mu b.
Proof. hw_field. Qed.
Lemma step_lassert_sat_err : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_sat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_err (step_next b) = false.
Proof. hw_field. Qed.
Lemma step_lassert_sat_halted : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_sat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_halted (step_next b) = false.
Proof. hw_field. Qed.
Lemma step_lassert_sat_regs : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_sat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_regs (step_next b) = hw_regs b.
Proof. hw_field. Qed.
Lemma step_lassert_sat_mem : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_sat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_mem (step_next b) = hw_mem b.
Proof. hw_field. Qed.
Lemma step_lassert_sat_error_code : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_sat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_error_code (step_next b) = hw_error_code b.
Proof. hw_field. Qed.
Lemma step_lassert_sat_cert_addr : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_sat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_cert_addr (step_next b) = hw_cert_addr b.
Proof. hw_field. Qed.
Lemma step_lassert_sat_partition_ops : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_sat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_partition_ops (step_next b) = hw_partition_ops b.
Proof. hw_field. Qed.
Lemma step_lassert_sat_mdl_ops : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_sat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_mdl_ops (step_next b) = hw_mdl_ops b.
Proof. hw_field. Qed.
Lemma step_lassert_sat_info_gain : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_sat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_info_gain (step_next b) = hw_info_gain b.
Proof. hw_field. Qed.
Lemma step_lassert_sat_mu_tensor : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_sat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_mu_tensor (step_next b) = hw_mu_tensor b.
Proof. hw_field. Qed.
Lemma step_lassert_sat_module_tensors : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_sat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_module_tensors (step_next b) = hw_module_tensors b.
Proof. hw_field. Qed.
Lemma step_lassert_sat_ptTable : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_sat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_ptTable (step_next b) = hw_ptTable b.
Proof. hw_field. Qed.
Lemma step_lassert_sat_pt_next_id : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_sat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_pt_next_id (step_next b) = hw_pt_next_id b.
Proof. hw_field. Qed.
Lemma step_lassert_sat_certified : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_sat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_certified (step_next b) = hw_certified b.
Proof. hw_field. Qed.
Lemma step_lassert_sat_wc_same_00 : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_sat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_wc_same_00 (step_next b) = hw_wc_same_00 b.
Proof. hw_field. Qed.
Lemma step_lassert_sat_wc_diff_00 : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_sat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_wc_diff_00 (step_next b) = hw_wc_diff_00 b.
Proof. hw_field. Qed.
Lemma step_lassert_sat_wc_same_01 : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_sat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_wc_same_01 (step_next b) = hw_wc_same_01 b.
Proof. hw_field. Qed.
Lemma step_lassert_sat_wc_diff_01 : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_sat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_wc_diff_01 (step_next b) = hw_wc_diff_01 b.
Proof. hw_field. Qed.
Lemma step_lassert_sat_wc_same_10 : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_sat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_wc_same_10 (step_next b) = hw_wc_same_10 b.
Proof. hw_field. Qed.
Lemma step_lassert_sat_wc_diff_10 : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_sat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_wc_diff_10 (step_next b) = hw_wc_diff_10 b.
Proof. hw_field. Qed.
Lemma step_lassert_sat_wc_same_11 : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_sat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_wc_same_11 (step_next b) = hw_wc_same_11 b.
Proof. hw_field. Qed.
Lemma step_lassert_sat_wc_diff_11 : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_sat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_wc_diff_11 (step_next b) = hw_wc_diff_11 b.
Proof. hw_field. Qed.
Lemma step_lassert_sat_morph_src_table : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_sat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_morph_src_table (step_next b) = hw_morph_src_table b.
Proof. hw_field. Qed.
Lemma step_lassert_sat_morph_dst_table : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_sat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_morph_dst_table (step_next b) = hw_morph_dst_table b.
Proof. hw_field. Qed.
Lemma step_lassert_sat_morph_coupling_desc_table : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_sat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_morph_coupling_desc_table (step_next b) = hw_morph_coupling_desc_table b.
Proof. hw_field. Qed.
Lemma step_lassert_sat_morph_identity_table : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_sat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_morph_identity_table (step_next b) = hw_morph_identity_table b.
Proof. hw_field. Qed.
Lemma step_lassert_sat_morph_valid_table : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_sat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_morph_valid_table (step_next b) = hw_morph_valid_table b.
Proof. hw_field. Qed.
Lemma step_lassert_sat_morph_next_id : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_sat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_morph_next_id (step_next b) = hw_morph_next_id b.
Proof. hw_field. Qed.
Lemma step_lassert_sat_coupling_desc_label_table : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_sat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_coupling_desc_label_table (step_next b) = hw_coupling_desc_label_table b.
Proof. hw_field. Qed.
Lemma step_lassert_sat_coupling_desc_label_len_table : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_sat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_coupling_desc_label_len_table (step_next b) = hw_coupling_desc_label_len_table b.
Proof. hw_field. Qed.
Lemma step_lassert_sat_lassert_phase : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_sat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_lassert_phase (step_next b) = natToWord 3 1.
Proof. hw_field. Qed.
Lemma step_lassert_sat_chsh_phase : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_sat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_chsh_phase (step_next b) = natToWord 5 0.
Proof. hw_field. Qed.
Lemma step_lassert_sat_mc_phase : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_sat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_mc_phase (step_next b) = natToWord 4 0.
Proof. hw_field. Qed.
Lemma step_lassert_sat_lassert_kind : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_sat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_lassert_kind (step_next b) = true.
Proof. hw_field. Qed.
Lemma step_lassert_sat_lassert_fbase : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_sat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_lassert_fbase (step_next b) = hw_regs b (bits4 a0 a1 a2 a3).
Proof. hw_field. Qed.
Lemma step_lassert_sat_lassert_cbase : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_sat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_lassert_cbase (step_next b) = hw_regs b (bits4 b0 b1 b2 b3).
Proof. hw_field. Qed.
Lemma step_lassert_sat_lassert_cptr : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_sat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_lassert_cptr (step_next b) = zext (bits8 c0 c1 c2 c3 c4 c5 c6 c7) 24.
Proof. hw_field. Qed.
Lemma step_lassert_sat_lassert_fptr : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_sat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_lassert_fptr (step_next b) = natToWord WordSz 0.
Proof. hw_field. Qed.
Lemma step_lassert_sat_lassert_flen : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_sat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_lassert_flen (step_next b) = natToWord WordSz 0.
Proof. hw_field. Qed.
Lemma step_lassert_sat_lassert_clen : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_sat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_lassert_clen (step_next b) = natToWord WordSz 0.
Proof. hw_field. Qed.
Lemma step_lassert_sat_lassert_nvars : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_sat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_lassert_nvars (step_next b) = natToWord WordSz 0.
Proof. hw_field. Qed.
Lemma step_lassert_sat_lassert_clause_sat : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_sat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_lassert_clause_sat (step_next b) = false.
Proof. hw_field. Qed.
Lemma step_lassert_sat_lassert_counter_clause_sat : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_sat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_lassert_counter_clause_sat (step_next b) = false.
Proof. hw_field. Qed.
Lemma step_lassert_sat_lassert_counter_seen_fail : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_sat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_lassert_counter_seen_fail (step_next b) = false.
Proof. hw_field. Qed.

Definition lassert_unsat_word (a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 : bool) : word InstrSz :=
  legacy_word OP_LASSERT (bits8 a0 a1 a2 a3 a4 false a6 a7) (bits8 b0 b1 b2 b3 b4 b5 b6 b7) (bits8 c0 c1 c2 c3 c4 c5 c6 c7).
Lemma step_lassert_unsat_pc : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_unsat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_pc (step_next b) = hw_trap_vector b.
Proof. hw_field. Qed.
Lemma step_lassert_unsat_mu : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_unsat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_mu (step_next b) = wplus (wplus (wplus (hw_mu b) (wlshift (hw_mem b (split1 7 25 (hw_regs b (bits4 a0 a1 a2 a3)))) (wordToNat (WO~0~0~0~0~1~1)))) (zext (bits8 c0 c1 c2 c3 c4 c5 c6 c7) 24)) (natToWord WordSz 1).
Proof. hw_field. Qed.
Lemma step_lassert_unsat_err : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_unsat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_err (step_next b) = true.
Proof. hw_field. Qed.
Lemma step_lassert_unsat_halted : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_unsat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_halted (step_next b) = false.
Proof. hw_field. Qed.
Lemma step_lassert_unsat_regs : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_unsat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_regs (step_next b) = hw_regs b.
Proof. hw_field. Qed.
Lemma step_lassert_unsat_mem : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_unsat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_mem (step_next b) = hw_mem b.
Proof. hw_field. Qed.
Lemma step_lassert_unsat_error_code : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_unsat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_error_code (step_next b) = ERR_LOGIC_VAL.
Proof. hw_field. Qed.
Lemma step_lassert_unsat_cert_addr : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_unsat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_cert_addr (step_next b) = hw_cert_addr b.
Proof. hw_field. Qed.
Lemma step_lassert_unsat_partition_ops : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_unsat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_partition_ops (step_next b) = hw_partition_ops b.
Proof. hw_field. Qed.
Lemma step_lassert_unsat_mdl_ops : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_unsat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_mdl_ops (step_next b) = hw_mdl_ops b.
Proof. hw_field. Qed.
Lemma step_lassert_unsat_info_gain : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_unsat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_info_gain (step_next b) = hw_info_gain b.
Proof. hw_field. Qed.
Lemma step_lassert_unsat_mu_tensor : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_unsat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_mu_tensor (step_next b) = hw_mu_tensor b.
Proof. hw_field. Qed.
Lemma step_lassert_unsat_module_tensors : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_unsat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_module_tensors (step_next b) = hw_module_tensors b.
Proof. hw_field. Qed.
Lemma step_lassert_unsat_ptTable : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_unsat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_ptTable (step_next b) = hw_ptTable b.
Proof. hw_field. Qed.
Lemma step_lassert_unsat_pt_next_id : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_unsat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_pt_next_id (step_next b) = hw_pt_next_id b.
Proof. hw_field. Qed.
Lemma step_lassert_unsat_certified : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_unsat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_certified (step_next b) = hw_certified b.
Proof. hw_field. Qed.
Lemma step_lassert_unsat_wc_same_00 : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_unsat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_wc_same_00 (step_next b) = hw_wc_same_00 b.
Proof. hw_field. Qed.
Lemma step_lassert_unsat_wc_diff_00 : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_unsat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_wc_diff_00 (step_next b) = hw_wc_diff_00 b.
Proof. hw_field. Qed.
Lemma step_lassert_unsat_wc_same_01 : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_unsat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_wc_same_01 (step_next b) = hw_wc_same_01 b.
Proof. hw_field. Qed.
Lemma step_lassert_unsat_wc_diff_01 : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_unsat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_wc_diff_01 (step_next b) = hw_wc_diff_01 b.
Proof. hw_field. Qed.
Lemma step_lassert_unsat_wc_same_10 : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_unsat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_wc_same_10 (step_next b) = hw_wc_same_10 b.
Proof. hw_field. Qed.
Lemma step_lassert_unsat_wc_diff_10 : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_unsat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_wc_diff_10 (step_next b) = hw_wc_diff_10 b.
Proof. hw_field. Qed.
Lemma step_lassert_unsat_wc_same_11 : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_unsat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_wc_same_11 (step_next b) = hw_wc_same_11 b.
Proof. hw_field. Qed.
Lemma step_lassert_unsat_wc_diff_11 : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_unsat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_wc_diff_11 (step_next b) = hw_wc_diff_11 b.
Proof. hw_field. Qed.
Lemma step_lassert_unsat_morph_src_table : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_unsat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_morph_src_table (step_next b) = hw_morph_src_table b.
Proof. hw_field. Qed.
Lemma step_lassert_unsat_morph_dst_table : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_unsat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_morph_dst_table (step_next b) = hw_morph_dst_table b.
Proof. hw_field. Qed.
Lemma step_lassert_unsat_morph_coupling_desc_table : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_unsat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_morph_coupling_desc_table (step_next b) = hw_morph_coupling_desc_table b.
Proof. hw_field. Qed.
Lemma step_lassert_unsat_morph_identity_table : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_unsat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_morph_identity_table (step_next b) = hw_morph_identity_table b.
Proof. hw_field. Qed.
Lemma step_lassert_unsat_morph_valid_table : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_unsat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_morph_valid_table (step_next b) = hw_morph_valid_table b.
Proof. hw_field. Qed.
Lemma step_lassert_unsat_morph_next_id : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_unsat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_morph_next_id (step_next b) = hw_morph_next_id b.
Proof. hw_field. Qed.
Lemma step_lassert_unsat_coupling_desc_label_table : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_unsat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_coupling_desc_label_table (step_next b) = hw_coupling_desc_label_table b.
Proof. hw_field. Qed.
Lemma step_lassert_unsat_coupling_desc_label_len_table : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_unsat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_coupling_desc_label_len_table (step_next b) = hw_coupling_desc_label_len_table b.
Proof. hw_field. Qed.
Lemma step_lassert_unsat_lassert_phase : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_unsat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_lassert_phase (step_next b) = natToWord 3 0.
Proof. hw_field. Qed.
Lemma step_lassert_unsat_chsh_phase : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_unsat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_chsh_phase (step_next b) = natToWord 5 0.
Proof. hw_field. Qed.
Lemma step_lassert_unsat_mc_phase : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_unsat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_mc_phase (step_next b) = natToWord 4 0.
Proof. hw_field. Qed.
Lemma step_lassert_unsat_lassert_kind : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_unsat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_lassert_kind (step_next b) = false.
Proof. hw_field. Qed.
Lemma step_lassert_unsat_lassert_fbase : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_unsat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_lassert_fbase (step_next b) = natToWord WordSz 0.
Proof. hw_field. Qed.
Lemma step_lassert_unsat_lassert_cbase : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_unsat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_lassert_cbase (step_next b) = natToWord WordSz 0.
Proof. hw_field. Qed.
Lemma step_lassert_unsat_lassert_cptr : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_unsat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_lassert_cptr (step_next b) = natToWord WordSz 0.
Proof. hw_field. Qed.
Lemma step_lassert_unsat_lassert_fptr : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_unsat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_lassert_fptr (step_next b) = natToWord WordSz 0.
Proof. hw_field. Qed.
Lemma step_lassert_unsat_lassert_flen : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_unsat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_lassert_flen (step_next b) = natToWord WordSz 0.
Proof. hw_field. Qed.
Lemma step_lassert_unsat_lassert_clen : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_unsat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_lassert_clen (step_next b) = natToWord WordSz 0.
Proof. hw_field. Qed.
Lemma step_lassert_unsat_lassert_nvars : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_unsat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_lassert_nvars (step_next b) = natToWord WordSz 0.
Proof. hw_field. Qed.
Lemma step_lassert_unsat_lassert_clause_sat : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_unsat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_lassert_clause_sat (step_next b) = false.
Proof. hw_field. Qed.
Lemma step_lassert_unsat_lassert_counter_clause_sat : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_unsat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_lassert_counter_clause_sat (step_next b) = false.
Proof. hw_field. Qed.
Lemma step_lassert_unsat_lassert_counter_seen_fail : forall a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 b,
  step_fetched b = lassert_unsat_word a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7 -> hwb_bianchi b = false ->
  hw_lassert_counter_seen_fail (step_next b) = false.
Proof. hw_field. Qed.

