From KamiHW Require Import RuleNext RuleStep StepEval StepFields StepWordFacts StepRefineCommon PopcountSWAR StepRefine.
Check rule_next_correct. Print Assumptions rule_next_correct.
Check hwb_after_union. Print Assumptions hwb_after_union.
Check step_next_correct. Print Assumptions step_next_correct.
Check hw_popcount32_correct. Print Assumptions hw_popcount32_correct.
Check step_add_refines. Print Assumptions step_add_refines.
Check step_sub_refines. Print Assumptions step_sub_refines.
Check step_and_refines. Print Assumptions step_and_refines.
Check step_or_refines. Print Assumptions step_or_refines.
Check step_xor_add_refines. Print Assumptions step_xor_add_refines.
Check step_mul_refines. Print Assumptions step_mul_refines.
Check step_xfer_refines. Print Assumptions step_xfer_refines.
Check step_load_imm_refines. Print Assumptions step_load_imm_refines.
Check step_shl_refines. Print Assumptions step_shl_refines.
Check step_shr_refines. Print Assumptions step_shr_refines.
Check step_lui_refines. Print Assumptions step_lui_refines.
Check step_xor_load_refines. Print Assumptions step_xor_load_refines.
Check step_jump_refines. Print Assumptions step_jump_refines.
Check step_jnez_refines. Print Assumptions step_jnez_refines.
Check step_mdlacc_refines. Print Assumptions step_mdlacc_refines.
Check step_ljoin_refines. Print Assumptions step_ljoin_refines.
Check step_certify_refines. Print Assumptions step_certify_refines.
Check step_read_port_refines. Print Assumptions step_read_port_refines.
Check step_emit_refines. Print Assumptions step_emit_refines.
Check step_reveal_refines. Print Assumptions step_reveal_refines.
Check step_xor_swap_refines. Print Assumptions step_xor_swap_refines.
Check step_tensor_set_refines. Print Assumptions step_tensor_set_refines.
Check step_tensor_get_refines. Print Assumptions step_tensor_get_refines.
Check step_pdiscover_refines. Print Assumptions step_pdiscover_refines.
Check step_load_refines. Print Assumptions step_load_refines.
Check step_store_refines. Print Assumptions step_store_refines.
Check step_heap_load_refines. Print Assumptions step_heap_load_refines.
Check step_heap_store_refines. Print Assumptions step_heap_store_refines.
Check step_call_refines. Print Assumptions step_call_refines.
Check step_ret_refines. Print Assumptions step_ret_refines.
Check step_pnew_refines. Print Assumptions step_pnew_refines.
Check step_psplit_refines. Print Assumptions step_psplit_refines.
Check step_pmerge_refines. Print Assumptions step_pmerge_refines.
Check step_chsh_trial_refines. Print Assumptions step_chsh_trial_refines.
Check step_xor_rank_refines. Print Assumptions step_xor_rank_refines.
Check step_halt_refines. Print Assumptions step_halt_refines.
Check step_checkpoint_refines. Print Assumptions step_checkpoint_refines.
Check step_write_port_refines. Print Assumptions step_write_port_refines.
From KamiHW Require Import StepFieldsMorph StepRefineMorph.
Check step_rich_alloc. Print Assumptions step_rich_alloc.
Check step_rich_delete. Print Assumptions step_rich_delete.
Check morph_get_value_nat. Print Assumptions morph_get_value_nat.
Check step_morph_id_refines. Print Assumptions step_morph_id_refines.
Check step_morph_id_ext_refines. Print Assumptions step_morph_id_ext_refines.
Check step_morph_delete_refines. Print Assumptions step_morph_delete_refines.
Check step_morph_delete_ext_refines. Print Assumptions step_morph_delete_ext_refines.
Check step_morph_assert_refines. Print Assumptions step_morph_assert_refines.
Check step_morph_assert_ext_refines. Print Assumptions step_morph_assert_ext_refines.
Check step_morph_get_refines. Print Assumptions step_morph_get_refines.
Check step_morph_get_ext_refines. Print Assumptions step_morph_get_ext_refines.
From KamiHW Require Import RuleEnabled.
Check total_from_eval. Print Assumptions total_from_eval.
Check step_rule_enabled. Print Assumptions step_rule_enabled.
Check step_rule_gated. Print Assumptions step_rule_gated.
Check step_rule_disabled. Print Assumptions step_rule_disabled.
Check live_fsm_rules_disabled. Print Assumptions live_fsm_rules_disabled.
Check live_selects_step. Print Assumptions live_selects_step.
Check live_only_step_enabled. Print Assumptions live_only_step_enabled.
Check live_boundary_hw_live. Print Assumptions live_boundary_hw_live.
Check live_step_multistep. Print Assumptions live_step_multistep.
From KamiHW Require Import ChshArith ChshDecoded ChshRun ChshRetire.
Check chsh_check_nat_correct. Print Assumptions chsh_check_nat_correct.
Check chsh_check_word_correct. Print Assumptions chsh_check_word_correct.
Check chsh_check_word_hw_spec. Print Assumptions chsh_check_word_hw_spec.
Check chsh_rule_enabled. Print Assumptions chsh_rule_enabled.
Check chsh_run_result. Print Assumptions chsh_run_result.
Check chsh_lassert_refines. Print Assumptions chsh_lassert_refines.
Check chsh_lassert_execution. Print Assumptions chsh_lassert_execution.
Check chsh_only_rule_enabled. Print Assumptions chsh_only_rule_enabled.
From KamiHW Require Import FsmDecoded LassertSpec LassertWord LassertRetire.
Check lhdr_enabled. Print Assumptions lhdr_enabled.
Check lscan_enabled. Print Assumptions lscan_enabled.
Check hw_scan_certcheck. Print Assumptions hw_scan_certcheck.
Check lscan_loop. Print Assumptions lscan_loop.
Check lassert_unsat_refines. Print Assumptions lassert_unsat_refines.
Check lassert_sat_refines. Print Assumptions lassert_sat_refines.
Check lassert_unsat_execution. Print Assumptions lassert_unsat_execution.
Check lassert_sat_execution. Print Assumptions lassert_sat_execution.
Check lassert_only_rule_enabled. Print Assumptions lassert_only_rule_enabled.
From KamiHW Require Import MorphTensorGap CouplingFsmRun CouplingMorphRich CouplingMorphKami CouplingMorphRetire.
Check snap_graph_tensor_none. Print Assumptions snap_graph_tensor_none.
Check step_morph_tensor_refines. Print Assumptions step_morph_tensor_refines.
Check step_morph_tensor_ext_refines. Print Assumptions step_morph_tensor_ext_refines.
Check morph_fsm_run. Print Assumptions morph_fsm_run.
Check rich_after_morph_commit. Print Assumptions rich_after_morph_commit.
Check kami_step_morph_success. Print Assumptions kami_step_morph_success.
Check morph_ext_execution. Print Assumptions morph_ext_execution.

From KamiHW Require Import CouplingFsmCopy CouplingFsmJoin BoundaryRun.
Check copy_run. Print Assumptions copy_run.
Check copy_multistep. Print Assumptions copy_multistep.
Check join_run. Print Assumptions join_run.
Check join_multistep. Print Assumptions join_multistep.
Check select_boundary_rule_correct. Print Assumptions select_boundary_rule_correct.
Check run_boundary_rules_correct. Print Assumptions run_boundary_rules_correct.
Check run_boundary_rules_actual. Print Assumptions run_boundary_rules_actual.
Check run_boundary_rules_firing_bound. Print Assumptions run_boundary_rules_firing_bound.
Check run_boundary_rules_short_trace_disabled. Print Assumptions run_boundary_rules_short_trace_disabled.

From KamiHW Require Import ImplementationContract.
Check atom_label_compose. Print Assumptions atom_label_compose.
