From KamiHW Require Import ActionObservation DispatchObservation DispatchAbstractionBridge.
Set Printing Depth 1000.
Print observe_action_write.
Check observe_action_write_correct.
Print Assumptions observe_action_write_correct.
Print dispatch_add_state.
Print dispatch_add_post.
Check dispatch_add_actual_execution.
Print Assumptions dispatch_add_actual_execution.
Print regs_core_observation.
Print snapshot_core_observation.
Print dispatch_add_snapshot.
Check dispatch_add_typed_refinement.
Print Assumptions dispatch_add_typed_refinement.
Check dispatch_preserves_register_schema.
Print Assumptions dispatch_preserves_register_schema.
