Require Import Minimal.Presentation Minimal.CompilerGuest Minimal.CompilerGuestRun.
Print Assumptions Minimal.Presentation.cg_read_val_code.
Print Assumptions Minimal.Presentation.cg_read_val_junk.
Print Assumptions Minimal.Presentation.cg_mlatch_succ.
Print Assumptions Minimal.Presentation.cg_mlatch_false_rd.
Print Assumptions Minimal.Presentation.cg_first_raise_succ.
Print Assumptions Minimal.Presentation.cg_account_step.
Print Assumptions Minimal.Presentation.cg_account_start.
Print Assumptions Minimal.CompilerGuest.cg_maxreg_in.
Print Assumptions Minimal.CompilerGuest.cg_xmax_in.
Print Assumptions Minimal.CompilerGuest.cg_sc_cons.
Print Assumptions Minimal.CompilerGuest.cg_sc_app.
Print Assumptions Minimal.CompilerGuest.cg_sc_here1.
Print Assumptions Minimal.CompilerGuest.cg_sc_here.
Print Assumptions Minimal.CompilerGuest.cg_sc_in.
Print Assumptions Minimal.CompilerGuest.cg_set_rf.
Print Assumptions Minimal.CompilerGuest.cg_Pn_spec.
Print Assumptions Minimal.CompilerGuest.cg_Ps_spec.
Print Assumptions Minimal.CompilerGuest.cg_Pc_spec.
Print Assumptions Minimal.CompilerGuest.cg_Pr_spec.
Print Assumptions Minimal.CompilerGuest.cg_T_ge.
Print Assumptions Minimal.CompilerGuest.cg_T_fresh.
Print Assumptions Minimal.CompilerGuest.cg_src_reg.
Print Assumptions Minimal.CompilerGuest.cg_sc_jmp0.
Print Assumptions Minimal.CompilerGuest.cg_sc_next.
Print Assumptions Minimal.CompilerGuest.cg_sc_dech.
Print Assumptions Minimal.CompilerGuest.cg_sc_tr1.
Print Assumptions Minimal.CompilerGuest.cg_sc_step.
Print Assumptions Minimal.CompilerGuest.cg_sc_cost.
Print Assumptions Minimal.CompilerGuest.cg_sc_erI.
Print Assumptions Minimal.CompilerGuest.cg_sc_erS.
Print Assumptions Minimal.CompilerGuest.cg_sc_tr2.
Print Assumptions Minimal.CompilerGuest.cg_sc_jmp1.
Print Assumptions Minimal.CompilerGuest.cg_sc_erT.
Print Assumptions Minimal.CompilerGuest.cg_sc_read.
Print Assumptions Minimal.CompilerGuest.cg_sc_decB.
Print Assumptions Minimal.CompilerGuest.cg_sc_decE.
Print Assumptions Minimal.CompilerGuest.cg_sc_incE1.
Print Assumptions Minimal.CompilerGuest.cg_sc_jmp2.
Print Assumptions Minimal.CompilerGuest.cg_sc_earn.
Print Assumptions Minimal.CompilerGuest.cg_sc_incE2.
Print Assumptions Minimal.CompilerGuest.cg_sc_decC1.
Print Assumptions Minimal.CompilerGuest.cg_sc_decC2.
Print Assumptions Minimal.CompilerGuest.cg_sc_decC3.
Print Assumptions Minimal.CompilerGuest.cg_sc_erT2.
Print Assumptions Minimal.CompilerGuest.cg_sc_pl.
Print Assumptions Minimal.CompilerGuest.cg_sc_pay.
Print Assumptions Minimal.CompilerGuest.cg_sc_jmp3.
Print Assumptions Minimal.CompilerGuest.cg_sc_halt.
Print Assumptions Minimal.CompilerGuest.cg_k_gt.
Print Assumptions Minimal.CompilerGuest.cg_rf_high.
Print Assumptions Minimal.CompilerGuest.cg_rf_spare.
Print Assumptions Minimal.CompilerGuest.cg_eqv_zero_high.
Print Assumptions Minimal.CompilerGuest.cg_eqv_spare.
Print Assumptions Minimal.CompilerGuest.cg_in1.
Print Assumptions Minimal.CompilerGuest.cg_in2.
Print Assumptions Minimal.CompilerGuest.cg_x_block.
Print Assumptions Minimal.CompilerGuest.cg_x_block_p.
Print Assumptions Minimal.CompilerGuest.cg_x_one.
Print Assumptions Minimal.CompilerGuest.cg_x_dec0.
Print Assumptions Minimal.CompilerGuest.cg_x_decS.
Print Assumptions Minimal.CompilerGuest.cg_x_inc.
Print Assumptions Minimal.CompilerGuest.cg_x_pay.
Print Assumptions Minimal.CompilerGuest.cg_x_earn.
Print Assumptions Minimal.CompilerGuest.cg_x_dec_next.
Print Assumptions Minimal.CompilerGuest.cg_x_erase.
Print Assumptions Minimal.CompilerGuest.cg_x_transfert.
Print Assumptions Minimal.CompilerGuest.cg_x_payloop.
Print Assumptions Minimal.CompilerGuest.cg_set2_rf.
Print Assumptions Minimal.CompilerGuest.cg_x_move.
Print Assumptions Minimal.CompilerGuest.cg_x_halt.
Print Assumptions Minimal.CompilerGuest.cg_x_read.
Print Assumptions Minimal.CompilerGuest.cg_x_noraise.
Print Assumptions Minimal.CompilerGuest.cg_x_tail_new.
Print Assumptions Minimal.CompilerGuest.cg_x_tail.
Print Assumptions Minimal.CompilerGuest.cg_x_check.
Print Assumptions Minimal.CompilerGuest.cg_x_to_new.
Print Assumptions Minimal.CompilerGuest.cg_e0_rf.
Print Assumptions Minimal.CompilerGuest.cg_e0_high.
Print Assumptions Minimal.CompilerGuest.cg_x_prologue.
Print Assumptions Minimal.CompilerGuest.cg_x_step.
Print Assumptions Minimal.CompilerGuest.cg_x_stop.
Print Assumptions Minimal.CompilerGuestRun.cg_compile_steps.
Print Assumptions Minimal.CompilerGuestRun.cg_run_prog_add.
Print Assumptions Minimal.CompilerGuestRun.cg_run_prog_stay.
Print Assumptions Minimal.CompilerGuestRun.cg_cert_mono.
Print Assumptions Minimal.CompilerGuestRun.cg_trace_succ.
Print Assumptions Minimal.CompilerGuestRun.cg_passing_app.
Print Assumptions Minimal.CompilerGuestRun.cg_passing_sum.
Print Assumptions Minimal.CompilerGuestRun.cg_psum_mono.
Print Assumptions Minimal.CompilerGuestRun.cg_psum_ge.
Print Assumptions Minimal.CompilerGuestRun.cg_psum_two.
Print Assumptions Minimal.CompilerGuestRun.cg_y_phase.
Print Assumptions Minimal.CompilerGuestRun.cg_fetch_at.
Print Assumptions Minimal.CompilerGuestRun.cg_fetch_halt.
Print Assumptions Minimal.CompilerGuestRun.cg_fetch_new.
Print Assumptions Minimal.CompilerGuestRun.cg_head_instr.
Print Assumptions Minimal.CompilerGuestRun.cg_fetch_head.
Print Assumptions Minimal.CompilerGuestRun.cg_ystart_simul.
Print Assumptions Minimal.CompilerGuestRun.cg_y_head.
Print Assumptions Minimal.CompilerGuestRun.cg_point_facts.
Print Assumptions Minimal.CompilerGuestRun.cg_point_live.
Print Assumptions Minimal.CompilerGuestRun.cg_y_stop.
Print Assumptions Minimal.CompilerGuestRun.cg_yhalt_facts.
Print Assumptions Minimal.CompilerGuestRun.cg_first_halt.
Print Assumptions Minimal.CompilerGuestRun.cg_cover.
Print Assumptions Minimal.CompilerGuestRun.cg_guest_matching_points.
Print Assumptions Minimal.CompilerGuestRun.cg_guest_halts_at.
Print Assumptions Minimal.CompilerGuestRun.cg_guest_halting_iff.
Print Assumptions Minimal.CompilerGuestRun.cg_guest_flag_iff.
Print Assumptions Minimal.CompilerGuestRun.cg_first_true.
Print Assumptions Minimal.CompilerGuestRun.cg_not_halted_before.
Print Assumptions Minimal.CompilerGuestRun.cg_latch_before.
Print Assumptions Minimal.CompilerGuestRun.cg_y_new.
Print Assumptions Minimal.CompilerGuestRun.cg_guest_earned.
Print Assumptions Minimal.CompilerGuestRun.cg_x_reach_head.
Print Assumptions Minimal.CompilerGuestRun.cg_x_halted.
Print Assumptions Minimal.CompilerGuestRun.cg_source_halts_of_guest.
Print Assumptions Minimal.CompilerGuestRun.cg_source_certifies_of_guest.
