#!/usr/bin/env python3
"""Generate live Python and Verilog instruction-surface artifacts from extracted OCaml."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

OPCODES: dict[str, int] = {
    "PNEW": 0x00,
    "PSPLIT": 0x01,
    "PMERGE": 0x02,
    "LASSERT": 0x03,
    "LJOIN": 0x04,
    "MDLACC": 0x05,
    "PDISCOVER": 0x06,
    "XFER": 0x07,
    "LOAD_IMM": 0x08,
    "CHSH_TRIAL": 0x09,
    "XOR_LOAD": 0x0A,
    "XOR_ADD": 0x0B,
    "XOR_SWAP": 0x0C,
    "XOR_RANK": 0x0D,
    "EMIT": 0x0E,
    "REVEAL": 0x0F,
    "LOAD": 0x11,
    "STORE": 0x12,
    "ADD": 0x13,
    "SUB": 0x14,
    "JUMP": 0x15,
    "JNEZ": 0x16,
    "CALL": 0x17,
    "RET": 0x18,
    "CHECKPOINT": 0x19,
    "READ_PORT": 0x1A,
    "WRITE_PORT": 0x1B,
    "HEAP_LOAD": 0x1C,
    "HEAP_STORE": 0x1D,
    "CERTIFY": 0x1E,
    "AND": 0x1F,
    "OR": 0x20,
    "SHL": 0x21,
    "SHR": 0x22,
    "MUL": 0x23,
    "LUI": 0x24,
    "TENSOR_SET": 0x25,
    "TENSOR_GET": 0x26,
    # Phase 5: categorical morphism opcodes
    "MORPH": 0x27,
    "COMPOSE": 0x28,
    "MORPH_ID": 0x29,
    "MORPH_DELETE": 0x2A,
    "MORPH_ASSERT": 0x2B,
    "MORPH_TENSOR": 0x2C,
    "MORPH_GET": 0x2D,
    "CHSH_LASSERT": 0x2E,
    "CHSH_LASSERT_1AB": 0x2F,
    "CHSH_LASSERT_1AB_G5": 0x30,
    "CHSH_LASSERT_1AB_G345": 0x31,
    "CHSH_LASSERT_1AB_G12345": 0x32,
    "HALT": 0xFF,
}

TYPE_RE = re.compile(r"^\s*type\s+vm_instruction\s*=\s*$")
CTOR_RE = re.compile(r"^\s*\|\s*([A-Za-z0-9_']+)\b")


def _coq_tag_to_mnemonic(tag: str) -> str:
    if tag.startswith("Coq_instr_"):
        stem = tag[len("Coq_instr_"):]
    elif tag.startswith("coq_instr_"):
        stem = tag[len("coq_instr_"):]
    else:
        stem = tag
    return stem.replace("'", "").upper()


def parse_vm_instruction_constructors(ml_text: str) -> list[str]:
    lines = ml_text.splitlines()
    in_type = False
    constructors: list[str] = []

    for line in lines:
        if not in_type:
            if TYPE_RE.match(line):
                in_type = True
            continue
        if line.strip() == "":
            if constructors:
                break
            continue
        if line.lstrip().startswith("type ") and constructors:
            break
        if line.lstrip().startswith("let ") and constructors:
            break
        match = CTOR_RE.match(line)
        if match:
            constructors.append(match.group(1))

    if not constructors:
        raise SystemExit("forge.py: could not find vm_instruction constructors in extracted OCaml")
    return constructors


def render_python(tags: list[str], mnemonic_to_opcode: dict[str, int]) -> str:
    tags_repr = ",\n    ".join(repr(tag) for tag in tags)
    tag_to_mnemonic_src = ",\n    ".join(
        f"{tag!r}: {_coq_tag_to_mnemonic(tag)!r}" for tag in tags
    )
    mnemonic_to_opcode_src = ",\n    ".join(
        f"{mnemonic!r}: {opcode}" for mnemonic, opcode in sorted(mnemonic_to_opcode.items())
    )
    tag_to_opcode_src = ",\n    ".join(
        f"{tag!r}: {mnemonic_to_opcode[_coq_tag_to_mnemonic(tag)]}" for tag in tags
    )
    return "\n".join([
        '"""DO NOT EDIT. GENERATED FROM COQ PROOFS.',
        'Generated by scripts/forge.py from Coq-extracted OCaml.',
        '"""',
        '',
        'from __future__ import annotations',
        '',
        'COQ_INSTRUCTION_TAGS: tuple[str, ...] = (',
        f'    {tags_repr},',
        ')',
        '',
        'COQ_TAG_TO_MNEMONIC: dict[str, str] = {',
        f'    {tag_to_mnemonic_src},',
        '}',
        '',
        'MNEMONIC_TO_OPCODE_BYTE: dict[str, int] = {',
        f'    {mnemonic_to_opcode_src},',
        '}',
        '',
        'COQ_TAG_TO_OPCODE_BYTE: dict[str, int] = {',
        f'    {tag_to_opcode_src},',
        '}',
        '',
        'def sanity_check() -> None:',
        '    assert len(COQ_INSTRUCTION_TAGS) == len(set(COQ_INSTRUCTION_TAGS))',
        '    assert set(COQ_TAG_TO_MNEMONIC) == set(COQ_INSTRUCTION_TAGS)',
        '    assert set(COQ_TAG_TO_OPCODE_BYTE) == set(COQ_INSTRUCTION_TAGS)',
        '    assert all(0 <= value <= 0xFF for value in COQ_TAG_TO_OPCODE_BYTE.values())',
        '',
    ]) + "\n"


def render_verilog_header(tags: list[str], mnemonic_to_opcode: dict[str, int]) -> str:
    lines = [
        "// DO NOT EDIT. GENERATED FROM COQ PROOFS.",
        "// Generated by scripts/forge.py from Coq-extracted OCaml.",
        "",
        "// Instruction opcodes",
    ]
    seen: set[str] = set()
    for tag in tags:
        mnemonic = _coq_tag_to_mnemonic(tag)
        if mnemonic in seen:
            continue
        seen.add(mnemonic)
        lines.append(f"localparam [7:0] OPCODE_{mnemonic} = 8'h{mnemonic_to_opcode[mnemonic]:02X};")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True)
    parser.add_argument("--out-python", required=True)
    parser.add_argument("--out-verilog", default=None,
                        help="Optional: write Verilog opcode header. RTL is generated by the Kami chain; this output is only used by synthesis_repro_gate for diff-based reproducibility.")
    parser.add_argument("--check-only", action="store_true")
    args = parser.parse_args()

    ml_path = Path(args.input)
    tags = parse_vm_instruction_constructors(ml_path.read_text(encoding="utf-8", errors="replace"))
    mnemonic_to_opcode: dict[str, int] = {}
    missing: list[str] = []
    for tag in tags:
        mnemonic = _coq_tag_to_mnemonic(tag)
        if mnemonic not in OPCODES:
            missing.append(mnemonic)
            continue
        mnemonic_to_opcode[mnemonic] = OPCODES[mnemonic]
    if missing:
        raise SystemExit(
            "forge.py: Coq-extracted mnemonics missing from live opcode table: " + ", ".join(sorted(set(missing)))
        )

    if not args.check_only:
        out_py = Path(args.out_python)
        out_py.parent.mkdir(parents=True, exist_ok=True)
        out_py.write_text(render_python(tags, mnemonic_to_opcode), encoding="utf-8")
        if args.out_verilog is not None:
            out_v = Path(args.out_verilog)
            out_v.parent.mkdir(parents=True, exist_ok=True)
            out_v.write_text(render_verilog_header(tags, mnemonic_to_opcode), encoding="utf-8")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())