#!/usr/bin/env python3
"""forge_vm.py: Generate thielecpu/vm.py as an OCaml-runner subprocess wrapper.

Reads:  build/thiele_core.ml (generated by coq/Extraction.v)
Writes: thielecpu/vm.py (FULLY GENERATED — never hand-edit)

Pipeline:
  Coq proofs → coq/Extraction.v → build/thiele_core.ml (OCaml)
                                 → build/extracted_vm_runner.ml
                                 → build/extracted_vm_runner  (binary — authoritative VM)
                                 → forge_vm.py (this script)
                                 → thielecpu/vm.py  (Python protocol wrapper)

What this script does:
  1. Reads build/thiele_core.ml and verifies all 37 constructors are present
  2. Parses is_cert_setterb to derive _CERT_SETTERS
  3. Derives instr_dict_to_text() serializer from CONSTRUCTOR_FIELD_MAP
  4. Emits thielecpu/vm.py — a pure subprocess wrapper around build/extracted_vm_runner
     with NO hand-written opcode semantics

Architecture invariant: all VM execution goes through build/extracted_vm_runner.
thielecpu/vm.py is a protocol/serialization layer, not a VM implementor.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

# ---------------------------------------------------------------------------
# Phase A: Peano tower collapse (for constant extraction)
# ---------------------------------------------------------------------------

def collapse_peano_towers(text: str) -> str:
    """Collapse (fun x -> x + 1) ... 0 towers to integer literals."""
    prev = ""
    while prev != text:
        prev = text
        # Match (fun x -> x + 1) followed by 0 with any whitespace between
        text = re.sub(r"\(fun x -> x \+ 1\)\s+0", "1", text)
        # Strip redundant parens around bare integers: (123) -> 123
        text = re.sub(r"\((\d+)\)", r"\1", text)
        text = re.sub(
            r"\(fun x -> x \+ 1\)\s+(\d+)",
            lambda m: str(int(m.group(1)) + 1),
            text,
        )
    return text


# ---------------------------------------------------------------------------
# Phase B: Parse structural info from OCaml IR
# ---------------------------------------------------------------------------

def parse_constructor_fields(ml_text: str) -> dict[str, list[str]]:
    """Parse vm_instruction constructor names and their field types."""
    ctors: dict[str, list[str]] = {}
    in_type = False
    for line in ml_text.splitlines():
        if not in_type:
            if re.match(r"\s*type\s+vm_instruction\s*=\s*$", line):
                in_type = True
            continue
        stripped = line.strip()
        if not stripped:
            if ctors:
                break
            continue
        if stripped.startswith("type ") and ctors:
            break
        if stripped.startswith("let ") and ctors:
            break
        m = re.match(r"\|\s*(\w+)(?:\s+of\s+(.+))?$", stripped)
        if m:
            name = m.group(1)
            fields_str = m.group(2) or ""
            if fields_str:
                fields = [f.strip() for f in fields_str.split("*")]
            else:
                fields = []
            ctors[name] = fields
    return ctors


def parse_cert_setters(ml_text: str) -> set[str]:
    """Parse is_cert_setterb to find which constructors are cert-setters."""
    setters: set[str] = set()
    in_func = False
    for line in ml_text.splitlines():
        if "let is_cert_setterb" in line:
            in_func = True
            continue
        if in_func:
            m = re.match(r"\s*\|\s*(\w+)\s+.*->\s*true", line)
            if m:
                setters.add(m.group(1))
            if "| _ -> false" in line:
                break
    return setters


def extract_constants(ml_text: str) -> dict[str, int]:
    """Extract named integer constants from preprocessed OCaml."""
    constants: dict[str, int] = {}
    for name in ["rEG_COUNT", "mEM_SIZE", "mAX_MODULES", "tENSOR_SIZE"]:
        # Try plain integer (post Peano-collapse)
        m = re.search(rf"let\s+{name}\s*=\s*(\d+)", ml_text)
        if m:
            constants[name] = int(m.group(1))
            continue
        # Try of_num_uint(UIntDecimal(D...Nil)) format (Coq 8.18+ extraction)
        m = re.search(
            rf"let\s+{name}\s*=\s*\n?\s*of_num_uint\s+\(UIntDecimal\s+\((.+?Nil)\)\)",
            ml_text, re.DOTALL,
        )
        if m:
            digits = re.findall(r'D(\d)', m.group(1))
            if digits:
                constants[name] = int(''.join(digits))
    return constants


# ---------------------------------------------------------------------------
# CONSTRUCTOR_FIELD_MAP: maps OCaml constructor to Python dict keys (in order)
#
# This is the ONLY curated table — verified against OCaml IR at generation time.
# Maps each Coq_instr_X constructor to Python dict key names.
# ---------------------------------------------------------------------------

CONSTRUCTOR_FIELD_MAP: dict[str, list[tuple[str, str]]] = {
    # (ocaml_positional_name, python_dict_key)
    "Coq_instr_pnew":         [("region", "region"), ("cost", "cost")],
    "Coq_instr_psplit":       [("module0", "module"), ("left_region", "left"),
                               ("right_region", "right"), ("cost", "cost")],
    "Coq_instr_pmerge":       [("m1", "m1"), ("m2", "m2"), ("cost", "cost")],
    "Coq_instr_lassert":      [("module0", "module"), ("formula", "formula"),
                               ("cert", "cert"), ("cost", "cost")],
    "Coq_instr_ljoin":        [("cert1", "cert1"), ("cert2", "cert2"), ("cost", "cost")],
    "Coq_instr_mdlacc":       [("module0", "module"), ("cost", "cost")],
    "Coq_instr_pdiscover":    [("module0", "module"), ("evidence", "evidence"),
                               ("cost", "cost")],
    "Coq_instr_xfer":         [("dst", "dst"), ("src", "src"), ("cost", "cost")],
    "Coq_instr_load_imm":     [("dst", "dst"), ("imm", "imm"), ("cost", "cost")],
    "Coq_instr_load":         [("dst", "dst"), ("rs_addr", "addr"), ("cost", "cost")],
    "Coq_instr_store":        [("rs_addr", "addr"), ("src", "src"), ("cost", "cost")],
    "Coq_instr_add":          [("dst", "dst"), ("rs1", "rs1"), ("rs2", "rs2"),
                               ("cost", "cost")],
    "Coq_instr_sub":          [("dst", "dst"), ("rs1", "rs1"), ("rs2", "rs2"),
                               ("cost", "cost")],
    "Coq_instr_jump":         [("target", "target"), ("cost", "cost")],
    "Coq_instr_jnez":         [("rs", "rs"), ("target", "target"), ("cost", "cost")],
    "Coq_instr_call":         [("target", "target"), ("cost", "cost")],
    "Coq_instr_ret":          [("cost", "cost")],
    "Coq_instr_chsh_trial":   [("x", "x"), ("y", "y"), ("a", "a"), ("b", "b"),
                               ("cost", "cost")],
    "Coq_instr_xor_load":     [("dst", "dst"), ("addr", "addr"), ("cost", "cost")],
    "Coq_instr_xor_add":      [("dst", "dst"), ("src", "src"), ("cost", "cost")],
    "Coq_instr_xor_swap":     [("a", "a"), ("b", "b"), ("cost", "cost")],
    "Coq_instr_xor_rank":     [("dst", "dst"), ("src", "src"), ("cost", "cost")],
    "Coq_instr_emit":         [("module0", "module"), ("payload", "payload"),
                               ("cost", "cost")],
    "Coq_instr_reveal":       [("module0", "module"), ("bits", "bits"),
                               ("cert", "cert"), ("cost", "cost")],
    "Coq_instr_oracle_halts": [("payload", "payload"), ("cost", "cost")],
    "Coq_instr_halt":         [("cost", "cost")],
    "Coq_instr_checkpoint":   [("label", "label"), ("cost", "cost")],
    "Coq_instr_read_port":    [("dst", "dst"), ("channel_idx", "channel"),
                               ("value", "value"), ("bits", "bits"), ("cost", "cost")],
    "Coq_instr_write_port":   [("channel_idx", "channel"), ("src", "src"),
                               ("cost", "cost")],
    "Coq_instr_heap_load":    [("dst", "dst"), ("rs_addr", "addr"), ("cost", "cost")],
    "Coq_instr_heap_store":   [("rs_addr", "addr"), ("src", "src"), ("cost", "cost")],
    "Coq_instr_certify":      [("delta_mu", "cost")],
    "Coq_instr_and":          [("dst", "dst"), ("rs1", "rs1"), ("rs2", "rs2"),
                               ("cost", "cost")],
    "Coq_instr_or":           [("dst", "dst"), ("rs1", "rs1"), ("rs2", "rs2"),
                               ("cost", "cost")],
    "Coq_instr_shl":          [("dst", "dst"), ("rs1", "rs1"), ("rs2", "rs2"),
                               ("cost", "cost")],
    "Coq_instr_shr":          [("dst", "dst"), ("rs1", "rs1"), ("rs2", "rs2"),
                               ("cost", "cost")],
    "Coq_instr_mul":          [("dst", "dst"), ("rs1", "rs1"), ("rs2", "rs2"),
                               ("cost", "cost")],
    "Coq_instr_lui":          [("dst", "dst"), ("imm", "imm"), ("cost", "cost")],
}


def ctor_to_opname(ctor: str) -> str:
    assert ctor.startswith("Coq_instr_"), f"unexpected constructor: {ctor}"
    return ctor[len("Coq_instr_"):]


# ---------------------------------------------------------------------------
# Phase C: Code generation
# ---------------------------------------------------------------------------

HEADER = '''\
"""DO NOT EDIT. GENERATED FROM COQ PROOFS by scripts/forge_vm.py.

Source: build/thiele_core.ml (generated by coq/Extraction.v via `make -C coq`)
Ground truth: coq/kernel/VMStep.v (38 opcodes), coq/kernel/VMState.v
Authoritative VM: build/extracted_vm_runner (OCaml binary from Coq extraction)

Regenerate: python3 scripts/forge_vm.py --input build/thiele_core.ml --output thielecpu/vm.py

Architecture: this file is a PROTOCOL LAYER, not a VM implementor.
All opcode semantics live in build/extracted_vm_runner (OCaml binary).
vm_run() and vm_apply() call that binary via subprocess. No opcode bodies here.
"""
from __future__ import annotations

import dataclasses
import json
import os
import subprocess
import sys
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple
'''


def generate_constants(constants: dict[str, int]) -> str:
    reg_count = constants.get("rEG_COUNT", 32)
    mem_size = constants.get("mEM_SIZE", 4096)
    tensor_size = constants.get("tENSOR_SIZE", 16)
    return f"""\
# ---------------------------------------------------------------------------
# Constants (extracted from Coq via Peano tower collapse)
# ---------------------------------------------------------------------------
REG_COUNT: int = {reg_count}
MEM_SIZE: int = {mem_size}
TENSOR_SIZE: int = {tensor_size}
WORD32_MASK: int = 0xFFFFFFFF
SP_REG: int = 31

# Hardware constants from coq/kami_hw/ThieleTypes.v
CHSH_X1_SURCHARGE: int = 256       # 0x00000100
BIANCHI_VIOLATION_ERROR_CODE: int = 0x0B1A4C81
"""


def generate_types() -> str:
    return '''\
# ---------------------------------------------------------------------------
# Data types (CSRState, moduleState, partitionGraph, VMState)
# These mirror the Coq record types in thiele_core.ml.
# ---------------------------------------------------------------------------

@dataclass
class CSRState:
    csr_cert_addr: int = 0
    csr_status: int = 0
    csr_err: int = 0
    csr_heap_base: int = 0


@dataclass
class moduleState:
    module_region: List[int] = field(default_factory=list)
    module_axioms: List[str] = field(default_factory=list)


@dataclass
class partitionGraph:
    pg_next_id: int = 1
    pg_modules: List[Tuple[int, moduleState]] = field(default_factory=list)


@dataclass
class VMState:
    vm_pc: int = 0
    vm_mu: int = 0
    vm_err: bool = False
    vm_regs: List[int] = field(default_factory=lambda: [0] * REG_COUNT)
    vm_mem: List[int] = field(default_factory=lambda: [0] * MEM_SIZE)
    vm_csrs: CSRState = field(default_factory=CSRState)
    vm_graph: partitionGraph = field(default_factory=partitionGraph)
    vm_mu_tensor: List[int] = field(default_factory=lambda: [0] * TENSOR_SIZE)
    vm_logic_acc: int = 0
    vm_mstatus: int = 0
    vm_witness: List[int] = field(default_factory=lambda: [0] * 8)
    vm_certified: bool = False

    @classmethod
    def default(cls) -> "VMState":
        return cls(
            vm_pc=0,
            vm_mu=0,
            vm_err=False,
            vm_regs=[0] * REG_COUNT,
            vm_mem=[0] * MEM_SIZE,
            vm_csrs=CSRState(),
            vm_graph=partitionGraph(),
            vm_mu_tensor=[0] * TENSOR_SIZE,
            vm_logic_acc=0,
            vm_mstatus=0,
            vm_witness=[0] * 8,
            vm_certified=False,
        )

    def to_json_dict(self) -> dict:
        mods = []
        for mid, ms in self.vm_graph.pg_modules:
            mods.append({
                "id": mid,
                "region": ms.module_region,
                "axioms": len(ms.module_axioms),
                "axiom_strings": ms.module_axioms,
            })
        return {
            "pc": self.vm_pc,
            "mu": self.vm_mu,
            "err": self.vm_err,
            "csr_err_code": self.vm_csrs.csr_err,
            "regs": list(self.vm_regs),
            "mem": list(self.vm_mem),
            "mu_tensor": list(self.vm_mu_tensor),
            "logic_acc": self.vm_logic_acc,
            "mstatus": self.vm_mstatus,
            "certified": self.vm_certified,
            "witness": list(self.vm_witness),
            "csrs": {
                "cert_addr": self.vm_csrs.csr_cert_addr,
                "status": self.vm_csrs.csr_status,
                "err": self.vm_csrs.csr_err,
                "heap_base": self.vm_csrs.csr_heap_base,
            },
            "graph": {
                "next_id": self.vm_graph.pg_next_id,
                "modules": mods,
            },
        }

    def to_json(self) -> str:
        # Use compact JSON (no spaces) so OCaml parse_json_int_array finds "key":[ correctly
        return json.dumps(self.to_json_dict(), separators=(',', ':'))

    @classmethod
    def from_json(cls, text: str) -> "VMState":
        d = json.loads(text)
        csrs = d.get("csrs", {})
        graph = d.get("graph", {})
        mods = []
        for m in graph.get("modules", []):
            ms = moduleState(
                module_region=list(m.get("region", [])),
                module_axioms=list(m.get("axiom_strings", [])),
            )
            mods.append((int(m["id"]), ms))
        return cls(
            vm_pc=int(d.get("pc", 0)),
            vm_mu=int(d.get("mu", 0)),
            vm_err=bool(d.get("err", False)),
            vm_regs=list(d.get("regs", [0] * REG_COUNT)),
            vm_mem=list(d.get("mem", [0] * MEM_SIZE)),
            vm_csrs=CSRState(
                csr_cert_addr=int(csrs.get("cert_addr", 0)),
                csr_status=int(csrs.get("status", 0)),
                csr_err=int(d.get("csr_err_code", csrs.get("err", 0))),
                csr_heap_base=int(csrs.get("heap_base", 0)),
            ),
            vm_graph=partitionGraph(
                pg_next_id=int(graph.get("next_id", 1)),
                pg_modules=mods,
            ),
            vm_mu_tensor=list(d.get("mu_tensor", [0] * TENSOR_SIZE)),
            vm_logic_acc=int(d.get("logic_acc", 0)),
            vm_mstatus=int(d.get("mstatus", 0)),
            vm_witness=list(d.get("witness", [0] * 8)),
            vm_certified=bool(d.get("certified", False)),
        )
'''


def generate_cert_setters(cert_setters: set[str]) -> str:
    """Generate _CERT_SETTERS from parsed is_cert_setterb arms."""
    opnames = sorted(ctor_to_opname(c) for c in cert_setters if c.startswith("Coq_instr_"))
    items = ", ".join(f'"{n}"' for n in opnames)
    return f'''\
# ---------------------------------------------------------------------------
# Cert-setter opcodes (from is_cert_setterb in thiele_core.ml)
# These require positive cost (NoFI enforcement).
# ---------------------------------------------------------------------------
_CERT_SETTERS: frozenset = frozenset({{{items}}})
'''


def _fmt_list_field(val: Any) -> str:
    """Format a region/list field as {v1,v2,...}."""
    if not val:
        return "{}"
    return "{" + ",".join(str(x) for x in val) + "}"


def generate_instr_dict_to_text() -> str:
    """Generate instr_dict_to_text() from CONSTRUCTOR_FIELD_MAP.

    This function converts a Python instruction dict to the text format
    expected by build/extracted_vm_runner.
    """
    # Special cases that need custom serialization
    # lassert: OCaml format is "LASSERT mid axiom cost" — cert is OMITTED (hardcoded internally)
    # reveal: OCaml format is "REVEAL ti tj bits [cert]" where bits is used as both bits and cost
    SPECIAL_OPS = {"reveal", "lassert"}

    lines = [
        "# ---------------------------------------------------------------------------",
        "# instr_dict_to_text: serializes instruction dict to OCaml runner text format.",
        "# Derived from CONSTRUCTOR_FIELD_MAP in forge_vm.py — the field order matches",
        "# the constructor argument order in build/thiele_core.ml.",
        "# ---------------------------------------------------------------------------",
        "",
        "_LIST_FIELDS: frozenset = frozenset({'region', 'left', 'right', 'evidence'})",
        "_STR_FIELDS: frozenset = frozenset({'formula', 'cert', 'cert1', 'cert2', 'payload', 'label'})",
        "",
        "def _fmt_list(val: Any) -> str:",
        '    """Format a list field as {v1,v2,...} for OCaml runner."""',
        "    if not val:",
        '        return "{}"',
        '    return "{" + ",".join(str(x) for x in val) + "}"',
        "",
        "def instr_dict_to_text(instr: Dict[str, Any]) -> str:",
        '    """Convert instruction dict to text format for extracted_vm_runner."""',
        '    op = str(instr.get("op", "")).lower()',
    ]

    for ctor, field_pairs in CONSTRUCTOR_FIELD_MAP.items():
        opname = ctor_to_opname(ctor)
        op_upper = opname.upper()

        if opname in SPECIAL_OPS:
            continue  # handled separately below

        # Build the format string for this opcode
        # Each field is retrieved from the dict by its python_dict_key
        parts = [f'"{op_upper}"']
        for _ocaml_name, py_key in field_pairs:
            if py_key == "cost":
                parts.append(f'str(instr.get("cost", 0))')
            elif py_key in ("region", "left", "right", "evidence"):
                parts.append(f'_fmt_list(instr.get("{py_key}", []))')
            elif py_key in ("formula", "cert", "cert1", "cert2", "payload", "label"):
                parts.append(f'str(instr.get("{py_key}", "."))')
            else:
                parts.append(f'str(int(instr.get("{py_key}", 0)))')

        expr_parts = " + \" \" + ".join(parts)
        lines.append(f'    if op == "{opname}":')
        lines.append(f'        return {expr_parts}')

    # Special case for LASSERT: supports three text formats per extracted_vm_runner.ml:
    #   LASSERT mid axiom cost              — legacy (empty SAT model)
    #   LASSERT_SAT mid axiom model cost    — SAT with explicit model
    #   LASSERT_UNSAT mid axiom proof cost  — UNSAT with LRAT proof
    lines.append('    if op == "lassert":')
    lines.append('        m = int(instr.get("module", 0))')
    lines.append('        formula = str(instr.get("formula", "."))')
    lines.append('        cost = int(instr.get("cost", 0))')
    lines.append('        raw_cert = instr.get("cert", "")')
    lines.append('        if isinstance(raw_cert, dict):')
    lines.append('            cert_type = raw_cert.get("type", "sat")')
    lines.append('            cert_data = raw_cert.get("proof", raw_cert.get("model", ""))')
    lines.append('        else:')
    lines.append('            cert_type = str(instr.get("cert_type", "sat"))')
    lines.append('            cert_data = str(raw_cert or "")')
    lines.append('        if cert_type == "unsat" and cert_data:')
    lines.append('            return f"LASSERT_UNSAT {m} {formula} {cert_data} {cost}"')
    lines.append('        elif cert_data:')
    lines.append('            return f"LASSERT_SAT {m} {formula} {cert_data} {cost}"')
    lines.append('        return f"LASSERT {m} {formula} {cost}"')

    # Special case for REVEAL: OCaml runner uses "REVEAL ti tj bits [cert]" format
    # where module (flat_index) = ti*4 + tj; bits arg is used as BOTH bits AND cost (delta).
    # We use the dict's "cost" field as delta so NoFI enforcement works correctly.
    lines.append('    if op == "reveal":')
    lines.append('        m = int(instr.get("module", 0))')
    lines.append('        ti, tj = m // 4, m % 4')
    lines.append('        delta = int(instr.get("cost", instr.get("bits", 0)))')
    lines.append('        cert = str(instr.get("cert", "") or "")')
    lines.append('        if cert and cert not in ("None", ""):')
    lines.append('            return f"REVEAL {ti} {tj} {delta} {cert}"')
    lines.append('        return f"REVEAL {ti} {tj} {delta}"')

    lines.append('    raise ValueError(f"instr_dict_to_text: unknown opcode: {op!r}")')
    lines.append("")

    return "\n".join(lines)


def generate_runner_and_vm() -> str:
    return '''\
# ---------------------------------------------------------------------------
# OCaml binary runner — the AUTHORITATIVE VM implementation
# ---------------------------------------------------------------------------

_RUNNER_PATH = Path(__file__).parent.parent / "build" / "extracted_vm_runner"


def _runner_available() -> bool:
    p = _RUNNER_PATH
    if not p.exists() or not p.is_file():
        return False
    if not os.access(str(p), os.X_OK):
        return False
    try:
        first = p.read_bytes().splitlines()[0]
        if first.startswith(b"#!/usr/bin/ocamlrun"):
            return Path("/usr/bin/ocamlrun").exists()
    except Exception:
        pass
    return True


def _call_runner(state: VMState, prog_lines: List[str], max_steps: int) -> VMState:
    """Call build/extracted_vm_runner with --resume state.json trace.txt.

    Writes state to a temp JSON file and program to a temp trace file,
    calls the binary, and parses the JSON output back to VMState.
    """
    if not _runner_available():
        raise RuntimeError(
            f"build/extracted_vm_runner not available at {_RUNNER_PATH}\\n"
            "Run: cd build && ocamlfind ocamlc -package str -linkpkg "
            "thiele_core.ml extracted_vm_runner.ml -o extracted_vm_runner"
        )

    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".json", delete=False, prefix="thiele_state_"
    ) as sf:
        state_path = sf.name
        sf.write(state.to_json())
        sf.write("\\n")

    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".txt", delete=False, prefix="thiele_prog_"
    ) as pf:
        prog_path = pf.name
        pf.write(f"FUEL {max_steps}\\n")
        for line in prog_lines:
            line = line.strip()
            if line and not line.startswith("#") and not line.startswith(";"):
                pf.write(line + "\\n")

    try:
        result = subprocess.run(
            [str(_RUNNER_PATH), "--resume", state_path, prog_path],
            capture_output=True,
            text=True,
            timeout=60,
        )
        stdout = result.stdout.strip()
        if result.returncode not in (0, 5):
            raise RuntimeError(
                f"extracted_vm_runner failed (exit {result.returncode}):\\n"
                f"stderr: {result.stderr[-1000:]}"
            )
        # stdout is a single-line JSON; skip any debug lines starting with "["
        json_line = ""
        for line in stdout.splitlines():
            line = line.strip()
            if line.startswith("{"):
                json_line = line
                break
        if not json_line:
            raise RuntimeError(
                f"extracted_vm_runner: no JSON in output.\\nstdout: {stdout[:500]}"
            )
        return VMState.from_json(json_line)
    finally:
        Path(state_path).unlink(missing_ok=True)
        Path(prog_path).unlink(missing_ok=True)


# ---------------------------------------------------------------------------
# Public VM API
# ---------------------------------------------------------------------------

def vm_run(state: VMState, program: List[Dict[str, Any]], max_steps: int = 10000) -> VMState:
    """Execute a list of instruction dicts starting from state.

    Delegates entirely to the OCaml extracted VM binary.
    No opcode semantics are implemented here.
    """
    prog_lines = [instr_dict_to_text(i) for i in program]
    return _call_runner(state, prog_lines, max_steps)


def vm_apply_unsafe(state: VMState, instr: Dict[str, Any]) -> VMState:
    """Apply a single instruction to state.

    Normalizes vm_pc to 0 so the OCaml runner executes the instruction
    at position 0 of a one-instruction program.
    """
    s0 = dataclasses.replace(state, vm_pc=0)
    return vm_run(s0, [instr], max_steps=2)


def vm_apply_nofi(state: VMState, instr: Dict[str, Any]) -> VMState:
    """Apply with NoFI enforcement.

    NoFI is enforced by the OCaml binary (CertCheck + SimulationProof).
    This function delegates entirely to the extracted runner.
    """
    return vm_apply_unsafe(state, instr)


def vm_apply_runtime(state: VMState, instr: Dict[str, Any]) -> VMState:
    """Runtime-safe apply (same as vm_apply_nofi)."""
    return vm_apply_nofi(state, instr)


def vm_apply(state: VMState, instr: Dict[str, Any]) -> VMState:
    """Apply a single instruction (alias for vm_apply_unsafe)."""
    return vm_apply_unsafe(state, instr)


# ---------------------------------------------------------------------------
# VM compatibility wrapper class
# ---------------------------------------------------------------------------

class VM:
    """Thin compatibility wrapper around vm_run for legacy call sites.

    All execution is delegated to build/extracted_vm_runner via vm_run().
    No PYEXEC, no hand-written opcode bodies, no independent semantics.
    """

    def __init__(self, state: Optional[VMState] = None):
        self.state: VMState = state if state is not None else VMState.default()

    def apply(self, instr: Dict[str, Any]) -> None:
        self.state = vm_apply(self.state, instr)

    def run_program(
        self,
        program: List[Dict[str, Any]],
        max_steps: int = 10000,
    ) -> VMState:
        self.state = vm_run(self.state, program, max_steps=max_steps)
        return self.state
'''


def generate_full_vm(ml_text: str) -> str:
    """Generate the complete thielecpu/vm.py from OCaml IR text."""
    preprocessed = collapse_peano_towers(ml_text)

    constructors = parse_constructor_fields(preprocessed)
    if not constructors:
        raise SystemExit("forge_vm.py: could not parse vm_instruction constructors")

    n_opcodes = len(constructors)
    print(f"forge_vm.py: found {n_opcodes} opcodes in OCaml IR")

    unknown = set(constructors.keys()) - set(CONSTRUCTOR_FIELD_MAP.keys())
    if unknown:
        raise SystemExit(
            f"forge_vm.py: unknown constructors in OCaml IR: {', '.join(sorted(unknown))}\n"
            f"Add them to CONSTRUCTOR_FIELD_MAP in forge_vm.py"
        )

    missing = set(CONSTRUCTOR_FIELD_MAP.keys()) - set(constructors.keys())
    if missing:
        raise SystemExit(
            f"forge_vm.py: constructors in CONSTRUCTOR_FIELD_MAP not found in OCaml IR: "
            f"{', '.join(sorted(missing))}\n"
            f"Update CONSTRUCTOR_FIELD_MAP in forge_vm.py"
        )

    cert_setters = parse_cert_setters(preprocessed)
    constants = extract_constants(preprocessed)

    print(f"forge_vm.py: cert_setters = {sorted(ctor_to_opname(c) for c in cert_setters if c.startswith('Coq_instr_'))}")

    sections = [
        HEADER,
        generate_constants(constants),
        generate_types(),
        generate_cert_setters(cert_setters),
        generate_instr_dict_to_text(),
        generate_runner_and_vm(),
    ]

    return "\n".join(sections)


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Generate thielecpu/vm.py OCaml-runner wrapper from Coq-extracted OCaml"
    )
    ap.add_argument("--input", required=True, help="Path to build/thiele_core.ml")
    ap.add_argument("--output", required=True, help="Path to thielecpu/vm.py")
    ap.add_argument(
        "--check-only",
        action="store_true",
        help="Don't write; verify committed file matches regeneration",
    )
    args = ap.parse_args()

    ml_path = Path(args.input)
    out_path = Path(args.output)

    ml_text = ml_path.read_text(encoding="utf-8", errors="replace")
    generated = generate_full_vm(ml_text)

    if args.check_only:
        if not out_path.exists():
            raise SystemExit(f"forge_vm.py: --check-only but {out_path} does not exist")
        existing = out_path.read_text(encoding="utf-8")
        if existing != generated:
            raise SystemExit(
                f"forge_vm.py: {out_path} is stale — regenerate with:\n"
                f"  python3 scripts/forge_vm.py --input {args.input} --output {args.output}"
            )
        print(f"forge_vm.py: {out_path} is up to date")
        return 0

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(generated, encoding="utf-8")
    print(f"forge_vm.py: wrote {out_path} ({len(generated)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
