#!/usr/bin/env python3
"""Generate ChshRun.v: the 23 firings of the CHSH_LASSERT FSM rule composed.

From a boundary at CHSH phase 1, [chsh_iter m b] (m applications of
[chsh_next]) has phase m+1 for m <= 22 and phase 0 at m = 23. After 23
firings every scratch register holds the product the FSM schedules for it,
expressed over the latched sums, magnitudes and signs of [b]; the check result
is [chsh_check_word_hw] of those latches; pc, err and error_code are the trap
commit on failure and unchanged on success; every register the rule never
writes is unchanged. Operands are read from ThieleCPUCore.v.
"""
import argparse
import re
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'scripts'))
from generate_chsh_phases import parse  # noqa: E402
from generate_chsh_fsm import hw_fields, parse as parse_fsm  # noqa: E402

TARGET = ROOT / 'coq/kami_hw/ChshRun.v'
LATCHES = [f'chsh_{p}{k}' for k in ['00', '01', '10', '11'] for p in ['n', 'd', 'sign']]


def generate():
    opa, opb, scratch = parse()
    _, _, writes = parse_fsm()
    written = {r for r, _ in writes}
    by_phase = {k: (reg, w) for reg, (k, w) in scratch.items()}
    ideal = {}

    def op(v, m):
        """(ideal term, rewrite tactics) for operand v read at state m."""
        base = v[:-len('_384')]
        if base == 'abs_C':
            parts = [ideal['chsh_abs_C1'], ideal['chsh_abs_C2']]
            s = [f'(hw_chsh_sign{k} b)' for k in ['00', '01', '10', '11']]
            term = (f'(if (if bool_dec (hw_bool_neq {s[0]} {s[1]}) (hw_bool_neq {s[2]} {s[3]}) then true else false) '
                    f'then wplus {parts[0]} {parts[1]} else hw_absdiffw {parts[0]} {parts[1]})')
            tac = (f'rewrite ?chsh_abs_C_form, ?(V_chsh_abs_C1_{m}), ?(V_chsh_abs_C2_{m}), '
                   + ', '.join(f'?(iter_keeps_chsh_sign{k} {m} b)' for k in ['00', '01', '10', '11']) + '.')
            return term, tac
        if base in ('abs_A', 'abs_B'):
            x = base[-1]
            term = (f'(hw_absdiffw {ideal[f"chsh_{x}_pos"]} (wplus {ideal[f"chsh_{x}_neg_a"]} '
                    f'{ideal[f"chsh_{x}_neg_b"]}))')
            tac = (f'rewrite ?chsh_abs_{x}_form, ?(V_chsh_{x}_pos_{m}), ?(V_chsh_{x}_neg_a_{m}), '
                   f'?(V_chsh_{x}_neg_b_{m}).')
            return term, tac
        reg = f'chsh_{base}'
        if reg in LATCHES:
            return f'(hw_{reg} b)', f'rewrite ?(iter_keeps_{reg} {m} b).'
        return ideal[reg], f'rewrite ?(V_{reg}_{m}).'

    t = '''(** ChshRun.v: generated by scripts/generate_chsh_run.py.
    The 23 firings of the CHSH_LASSERT FSM rule from phase 1, composed. *)
Require Import Kami.Kami Kami.Semantics.
From Coq Require Import String Lia.
From KamiHW Require Import ThieleTypes ThieleCPUCore HWBoundary RuleNext ChshDecoded ChshArith ChshFsm
  ChshPhases.

Fixpoint chsh_iter (n : nat) (b : HWB) : HWB :=
  match n with
  | O => b
  | S m => chsh_next (chsh_iter m b)
  end.

'''
    for f in hw_fields():
        if f in written:
            continue
        t += (f'Lemma iter_keeps_{f} : forall n b, hw_{f} (chsh_iter n b) = hw_{f} b.\n'
              f'Proof. induction n as [|n IH]; intro b; [reflexivity|cbn [chsh_iter]; '
              f'rewrite chsh_keeps_{f}; apply IH]. Qed.\n')
    t += '''
Lemma chsh_abs_C_form : forall c, chsh_abs_C_256 c =
  if (if bool_dec (hw_bool_neq (hw_chsh_sign00 c) (hw_chsh_sign01 c))
                  (hw_bool_neq (hw_chsh_sign10 c) (hw_chsh_sign11 c)) then true else false)
  then wplus (hw_chsh_abs_C1 c) (hw_chsh_abs_C2 c) else hw_absdiffw (hw_chsh_abs_C1 c) (hw_chsh_abs_C2 c).
Proof. intro c. kernel_refl. Qed.

Lemma chsh_abs_A_form : forall c, chsh_abs_A_256 c =
  hw_absdiffw (hw_chsh_A_pos c) (wplus (hw_chsh_A_neg_a c) (hw_chsh_A_neg_b c)).
Proof. intro c. kernel_refl. Qed.

Lemma chsh_abs_B_form : forall c, chsh_abs_B_256 c =
  hw_absdiffw (hw_chsh_B_pos c) (wplus (hw_chsh_B_neg_a c) (hw_chsh_B_neg_b c)).
Proof. intro c. kernel_refl. Qed.

Lemma chsh_final_form : forall c, chsh_final_ok c =
  andb (andb (andb (andb (andb (andb (negb (hw_eqb (hw_chsh_n00 c) (natToWord 64 0)))
                                      (negb (hw_eqb (hw_chsh_n01 c) (natToWord 64 0))))
                                (negb (hw_eqb (hw_chsh_n10 c) (natToWord 64 0))))
                          (negb (hw_eqb (hw_chsh_n11 c) (natToWord 64 0))))
                    (negb (hw_ltb (hw_chsh_A_pos c) (wplus (hw_chsh_A_neg_a c) (hw_chsh_A_neg_b c)))))
              (negb (hw_ltb (hw_chsh_B_pos c) (wplus (hw_chsh_B_neg_a c) (hw_chsh_B_neg_b c)))))
       (negb (hw_ltb (hw_chsh_A_times_B c) (hw_chsh_C_sq c))).
Proof. intro c. kernel_refl. Qed.

'''
    latch_args = ' '.join(f'(hw_{l} b)' for l in
                          [f'chsh_n{k}' for k in ['00', '01', '10', '11']] +
                          [f'chsh_d{k}' for k in ['00', '01', '10', '11']] +
                          [f'chsh_sign{k}' for k in ['00', '01', '10', '11']])
    ok = f'chsh_check_word_hw {latch_args}'
    t += ('Theorem chsh_run_result : forall b, hw_chsh_phase b = natToWord 5 1 ->\n'
          '  (forall m, (m <= 22)%nat -> hw_chsh_phase (chsh_iter m b) = natToWord 5 (S m)) /\\\n'
          '  hw_chsh_phase (chsh_iter 23 b) = natToWord 5 0 /\\\n'
          f'  hw_chsh_check_result (chsh_iter 23 b) = {ok} /\\\n'
          f'  hw_pc (chsh_iter 23 b) = (if negb ({ok}) then hw_trap_vector b else hw_pc b) /\\\n'
          f'  hw_err (chsh_iter 23 b) = (if negb ({ok}) then true else hw_err b) /\\\n'
          f'  hw_error_code (chsh_iter 23 b) = (if negb ({ok}) then ERR_LOGIC_VAL else hw_error_code b).\n'
          'Proof.\n  intros b Ph0.\n')
    # phases
    for m in range(1, 24):
        rhs = f'natToWord 5 {m + 1}' if m < 23 else 'natToWord 5 0'
        t += (f'  assert (Ph{m} : hw_chsh_phase (chsh_iter {m} b) = {rhs})\n'
              f'    by (change (chsh_iter {m} b) with (chsh_next (chsh_iter {m - 1} b)); '
              f'exact (chsh_phase{m}_chsh_phase (chsh_iter {m - 1} b) Ph{m - 1})).\n')
    # pc, err, error_code frames through phase 22
    for reg in ['pc', 'err', 'error_code']:
        t += f'  assert (V_{reg}_0 : hw_{reg} (chsh_iter 0 b) = hw_{reg} b) by reflexivity.\n'
        for m in range(1, 23):
            t += (f'  assert (V_{reg}_{m} : hw_{reg} (chsh_iter {m} b) = hw_{reg} b)\n'
                  f'    by (change (chsh_iter {m} b) with (chsh_next (chsh_iter {m - 1} b)); '
                  f'rewrite (chsh_phase{m}_{reg} (chsh_iter {m - 1} b) Ph{m - 1}); exact V_{reg}_{m - 1}).\n')
    # scratch registers in phase order
    for k in range(1, 23):
        reg, w = by_phase[k]
        ta, taca = op(opa[k], k - 1)
        tb, tacb = op(opb[k], k - 1)
        ideal[reg] = f'(m{w} {ta} {tb})'
        t += (f'  assert (V_{reg}_{k} : hw_{reg} (chsh_iter {k} b) = {ideal[reg]}).\n'
              f'  {{ change (chsh_iter {k} b) with (chsh_next (chsh_iter {k - 1} b)).\n'
              f'    rewrite (chsh_phase{k}_{reg} (chsh_iter {k - 1} b) Ph{k - 1}). {taca} {tacb} reflexivity. }}\n')
        for m in range(k + 1, 23):
            t += (f'  assert (V_{reg}_{m} : hw_{reg} (chsh_iter {m} b) = {ideal[reg]})\n'
                  f'    by (change (chsh_iter {m} b) with (chsh_next (chsh_iter {m - 1} b)); '
                  f'rewrite (chsh_phase{m}_{reg} (chsh_iter {m - 1} b) Ph{m - 1}); exact V_{reg}_{m - 1}).\n')
    finals = ', '.join(f'?(V_{reg}_22)' for reg in scratch) + ', ' + \
        ', '.join(f'?(iter_keeps_{l} 22 b)' for l in LATCHES if l.startswith('chsh_n'))
    t += (f'  assert (Eok : chsh_final_ok (chsh_iter 22 b) = {ok}).\n'
          f'  {{ rewrite chsh_final_form, {finals}. unfold chsh_check_word_hw. kernel_refl. }}\n')
    t += '  split.\n  { intros m Hm.\n'
    t += '    assert (Hc : ' + ' \\/ '.join(f'm = {m}%nat' for m in range(23)) + ') by lia.\n'
    t += '    destruct Hc as ' + '[E|' * 22 + 'E' + ']' * 22 + '; subst m; assumption. }\n'
    t += '  split; [exact Ph23|].\n'
    t += ('  change (chsh_iter 23 b) with (chsh_next (chsh_iter 22 b)).\n'
          '  rewrite (chsh_phase23_chsh_check_result (chsh_iter 22 b) Ph22), (chsh_phase23_pc (chsh_iter 22 b) Ph22),\n'
          '    (chsh_phase23_err (chsh_iter 22 b) Ph22), (chsh_phase23_error_code (chsh_iter 22 b) Ph22), Eok,\n'
          '    V_pc_22, V_err_22, V_error_code_22, (iter_keeps_trap_vector 22 b).\n'
          '  repeat split; reflexivity.\nQed.\n')
    return t


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--out')
    args = parser.parse_args()
    generated = generate()
    target = Path(args.out) if args.out else TARGET
    if args.check:
        if target.read_text() != generated:
            raise SystemExit('ChshRun.v is stale; regenerate it')
    else:
        target.write_text(generated)
    print('ChshRun: composed CHSH FSM retirement')
