#!/usr/bin/env python3
"""Generate RuleNext.v: the typed boundary after a set of register writes.

For every register of the actual CPU, the generated [hwb_after] takes the
written value when the observation supplies one of the declared kind and keeps
the old field otherwise. [hwb_after_union] proves that applying any update map
whose writes have the declared kinds to [hwb_regs b] yields [hwb_regs] of that
record. No rule, opcode or invariant is assumed.
"""
import argparse
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'coq/kami_hw/ThieleCPUCore.v'
TARGET = ROOT / 'coq/kami_hw/RuleNext.v'
HEADER = '''(** RuleNext.v: generated by scripts/generate_rule_next.py.
    The typed boundary after register writes. [hwb_after b obs] replaces each
    field by the value [obs] supplies for its register name, when that value has
    the declared kind, and keeps the field otherwise. *)

Require Import Kami.Kami Kami.Semantics.
From Coq Require Import String List.
From KamiHW Require Import ThieleTypes ThieleCPUCore HWBoundary ActionEvaluator
  ActionObservation CoreTyping DispatchExecution CoreExecution HWBoundaryCompleteness.
Import ListNotations.
Open Scope string_scope.

Definition write_value (k : Kind)
    (w : option {k : FullKind & fullType type k}) (old : type k) : type k :=
  match w with
  | Some (existT _ (SyntaxKind actual) v) =>
      match decKind actual k with
      | left e => eq_rect actual type v k e
      | right _ => old
      end
  | _ => old
  end.

'''


def fields():
    source = re.sub(r'\(\*.*?\*\)', '', SOURCE.read_text(), flags=re.S)
    declarations = re.findall(r'\bRegister\s+"(\w+)"\s*:\s*(.*?)\s*<-', source, re.S)
    result = [(name, ' '.join(kind.split())) for name, kind in declarations]
    if not result or len({n for n, _ in result}) != len(result):
        raise ValueError('Missing or duplicate CPU register declarations')
    return result


def generate():
    fs = fields()
    others = ' '.join(f'N_{n}' for n, _ in fs)
    t = HEADER
    t += 'Definition hwb_after (b : HWB)\n'
    t += '    (obs : string -> option {k : FullKind & fullType type k}) : HWB :=\n'
    t += '  {| ' + ';\n     '.join(
        f'hw_{n} := write_value ({k}) (obs "{n}") (hw_{n} b)' for n, k in fs) + ' |}.\n\n'

    t += 'Lemma hwb_after_ext : forall b f g,\n'
    t += '  (forall key, f key = g key) -> hwb_after b f = hwb_after b g.\n'
    t += 'Proof.\n  intros b f g H. unfold hwb_after.\n'
    t += '  ' + ' '.join(f'rewrite (H "{n}").' for n, _ in fs) + '\n'
    t += '  reflexivity.\nQed.\n\n'

    t += '(** Every register name outside the declared schema has no kind. *)\n'
    t += 'Lemma cpu_register_kind_other : forall name,\n'
    t += ''.join(f'  name <> "{n}" ->\n' for n, _ in fs)
    t += '  cpu_register_kind name = None.\nProof.\n'
    t += f'  intros name {others}.\n'
    t += '  unfold cpu_register_kind, register_kind, dispatch_reset_state, initRegs.\n'
    t += '  assert (Habs : ~ List.In name (namesOf (rawInitRegs (getRegInits thieleCore)))).\n'
    t += '  { rewrite <- rawInitRegs_namesOf. rewrite cpu_register_names. cbn. intro Hin.\n'
    for n, _ in fs:
        t += f'    destruct Hin as [Hin|Hin]. {{ apply N_{n}. symmetry. exact Hin. }}\n'
    t += '    exact Hin. }\n'
    t += '  erewrite M.find_KeysSubset.\n  - reflexivity.\n'
    t += '  - apply makeMap_KeysSubset.\n  - exact Habs.\nQed.\n\n'

    for n, k in fs:
        t += f'Lemma find_hwb_regs_{n} : forall b,\n'
        t += f'  M.find "{n}" (hwb_regs b) = Some (hwb_reg ({k}) (hw_{n} b)).\n'
        t += 'Proof. intro b. vm_compute. reflexivity. Qed.\n'
    t += '\nLemma find_hwb_regs_other : forall b name,\n'
    t += ''.join(f'  name <> "{n}" ->\n' for n, _ in fs)
    t += '  M.find name (hwb_regs b) = None.\nProof.\n'
    t += f'  intros b name {others}.\n  unfold hwb_regs.\n'
    t += ''.join(f'  rewrite M.find_add_2 by exact N_{n}.\n' for n, _ in fs)
    t += '  apply M.find_empty.\nQed.\n\n'

    t += 'Theorem hwb_after_union : forall b u,\n'
    t += '  updates_match cpu_register_kind u ->\n'
    t += '  M.union u (hwb_regs b) = hwb_regs (hwb_after b (fun key => M.find key u)).\n'
    t += 'Proof.\n  intros b u Hu. M.ext name. rewrite M.find_union.\n'
    for n, _ in fs:
        t += f'  destruct (string_dec name "{n}") as [E|N_{n}].\n'
        t += f'  {{ subst name. rewrite !find_hwb_regs_{n}. cbn [hwb_after hw_{n}]. unfold write_value.\n'
        t += f'    destruct (M.find "{n}" u) as [[fk v]|] eqn:F; [|reflexivity].\n'
        t += f'    pose proof (Hu "{n}" _ F) as Hk. rewrite cpu_kind_{n} in Hk.\n'
        t += '    cbn [projT1] in Hk. inversion Hk; subst fk. cbn. try rewrite kind_eq. reflexivity. }\n'
    t += f'  rewrite !(find_hwb_regs_other _ name {others}).\n'
    t += f'  pose proof (cpu_register_kind_other name {others}) as Hnone.\n'
    t += '  destruct (M.find name u) as [v|] eqn:F; [|reflexivity].\n'
    t += '  pose proof (Hu name v F) as Hk. rewrite Hnone in Hk. discriminate.\nQed.\n'
    return t, len(fs)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    generated, count = generate()
    if args.check:
        if TARGET.read_text() != generated:
            raise SystemExit('RuleNext.v differs from the CPU declarations; regenerate it')
    else:
        TARGET.write_text(generated)
    print(f'RuleNext: {count} CPU register declarations')
