#!/usr/bin/env python3
"""Generate ChshDecoded.v: the CHSH_LASSERT FSM rule as register reads followed
by the pure action [chsh_fsm_decoded], its read-free observation at a typed
boundary, the next-state function [chsh_next], and enabledness whenever the
CHSH phase is nonzero. The reads are copied from ThieleCPUCore.v, so the
factored action cannot drift from the rule; [chsh_rule_action] checks it by
conversion.
"""
import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / 'coq/kami_hw/ChshDecoded.v'
CPU = ROOT / 'coq/kami_hw/ThieleCPUCore.v'

READ = re.compile(r'^\s*Read (\w+)\s*:\s*(.+?)\s*<-\s*"(\w+)";\s*$')


def rule_prefix():
    text = CPU.read_text()
    start = text.index('with Rule "chsh_lassert_fsm" :=')
    end = text.index('chsh_fsm_decoded ', start)
    call_end = text.index('\n', end)
    lines = text[start:call_end].split('\n')[1:]
    reads = [READ.match(l).groups() for l in lines if READ.match(l)]
    body = '\n'.join(lines)
    return body, reads


def generate():
    body, reads = rule_prefix()
    names = [n for n, _, _ in reads]
    regs = list(dict.fromkeys(r for _, _, r in reads))
    alts = '\n  '.join(f'| rewrite hwb_read_{r}' for r in regs)
    args = ' '.join(f'(hw_{r} b)' for _, _, r in reads)
    return f'''(** ChshDecoded.v: generated by scripts/generate_chsh_decoded.py.
    The CHSH_LASSERT FSM rule is its register reads followed by the pure
    action [chsh_fsm_decoded]. At a typed boundary its observations are
    those of the decoded action applied to the boundary fields, which gives
    the total next-state function [chsh_next]. The rule evaluates whenever
    the CHSH phase is nonzero. *)
Require Import Kami.Kami Kami.Semantics.
From Coq Require Import String List Bool.
From KamiHW Require Import ThieleTypes ThieleCPUCore HWBoundary HWBoundaryReads ActionEvaluator
  ActionObservation ReadFreeObservation NormalizationSteps CoreRules CoreExecution CoreTyping
  RuleNext RuleStep RuleEnabled.
Import ListNotations.
Open Scope string_scope.

Definition chsh_rule : cpu_rule := normalization_rule 11.

Definition chsh_fetch_action : Action Void :=
  fun ty => ({body})%kami_action.

Lemma chsh_rule_action : attrType chsh_rule type = chsh_fetch_action type.
Proof. reflexivity. Qed.

Lemma chsh_rule_in : In chsh_rule (getRules thieleCore).
Proof. rewrite cpu_rules_listed. apply in_map. cbn [In]. auto 13. Qed.

Lemma chsh_fsm_decoded_read_free : forall {' '.join(names)},
  read_free_action (chsh_fsm_decoded (ty := type) {' '.join(names)}).
Proof.
  intros. unfold chsh_fsm_decoded.
  repeat (cbn [read_free_action]; intro).
  exact I.
Qed.

Lemma chsh_fsm_decoded_total : forall {' '.join(names)},
  total_from nil (chsh_fsm_decoded (ty := type) {' '.join(names)}).
Proof.
  intros. unfold chsh_fsm_decoded.
  repeat (cbn [total_from existsb String.eqb Ascii.eqb Bool.eqb]; intro).
  exact I.
Qed.

Definition hwb_chsh_decoded (b : HWB) : ActionT type Void :=
  chsh_fsm_decoded {args}.

Local Opaque chsh_fsm_decoded.
Theorem chsh_observer : forall b key,
  observe_action_write (hwb_regs b) key (attrType chsh_rule type) =
  observe_action_write (M.empty _) key (hwb_chsh_decoded b).
Proof.
  intros b key. rewrite chsh_rule_action. unfold chsh_fetch_action, hwb_chsh_decoded.
  repeat first [progress cbn [observe_action_write]
  {alts}].
  apply observe_read_free_action. apply chsh_fsm_decoded_read_free.
Qed.

Definition chsh_next (b : HWB) : HWB :=
  hwb_after b (fun key => observe_action_write (M.empty _) key (hwb_chsh_decoded b)).

Lemma chsh_rule_next : forall b, rule_next chsh_rule b = chsh_next b.
Proof.
  intro b. unfold rule_next, chsh_next. apply hwb_after_ext. intro key. apply chsh_observer.
Qed.

Theorem chsh_rule_enabled : forall b,
  hw_chsh_phase b <> natToWord 5 0 ->
  exists u, eval_cpu_rule (hwb_regs b) chsh_rule = Some u /\\
    M.union u (hwb_regs b) = hwb_regs (chsh_next b).
Proof.
  intros b Hp.
  assert (He : exists u, eval_cpu_rule (hwb_regs b) chsh_rule = Some u).
  {{ unfold eval_cpu_rule. rewrite chsh_rule_action. unfold chsh_fetch_action.
    repeat first [progress cbn [eval_linear_action evalExpr evalUniBool evalConstT]
    {alts}].
    unfold isEq. destruct (weq (hw_chsh_phase b) _) as [E|E]; [contradiction|]. cbn [negb].
    match goal with |- context [eval_linear_action ?o ?a] =>
      assert (T : total_from nil a) by apply chsh_fsm_decoded_total;
      destruct (total_from_eval _ a nil o T) as [u [ret [E' _]]]; rewrite E'
    end.
    exists u. reflexivity. }}
  destruct He as [u Hu]. exists u. split; [exact Hu|].
  rewrite <- chsh_rule_next. apply rule_next_correct; [exact chsh_rule_in|exact Hu].
Qed.
'''


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--out')
    args = parser.parse_args()
    generated = generate()
    target = Path(args.out) if args.out else TARGET
    if args.check:
        if target.read_text() != generated:
            raise SystemExit('ChshDecoded.v is stale; regenerate it')
    else:
        target.write_text(generated)
    print('ChshDecoded: observation, next state and enabledness of the CHSH FSM rule')
