#!/usr/bin/env python3
"""Generate CouplingFaults.v: single-cycle retirement of the fault branches
of MORPH and COMPOSE at their extended encodings.

On a fault branch the step rule leaves the coupling FSM idle, so the step
firing alone retires the instruction. MORPH faults when a source or target
module is absent (ERR_COUPLING_INVALID); COMPOSE faults when either morphism
is missing (ERR_MORPH_NOT_FOUND) or the first morphism's target is not the
second's source (ERR_COMPOSE_TYPE). Table overflow stays excluded by the room
premises, as for the success branches in CouplingMorphRetire.v and
CouplingComposeRetire.v.
"""
import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'scripts'))
from generate_step_fields import FIELDS, BITS  # noqa: E402
from generate_step_fields_morph import EBITS, inline  # noqa: E402
import generate_step_refine_morph as srm  # noqa: E402

TARGET = ROOT / 'coq/kami_hw/CouplingFaults.v'

HEADER = r'''(** CouplingFaults.v: generated by scripts/generate_coupling_faults.py.
    Fault branches of MORPH and COMPOSE at the extended encoding retire in the
    step firing alone: the next boundary observes [kami_step] and the
    coupling FSM stays idle. *)
Require Import Kami.Kami Kami.Semantics Kami.Lib.NatLib.
From Coq Require Import String NArith Arith Lia FunctionalExtensionality.
From KamiHW Require Import ThieleTypes HWBoundary RuleNext RuleStep BoundaryDecoded StepEval
  StepWordFacts StepFields StepRefineCommon StepRefine StepFieldsMorph StepRefineMorph
  ImplementationContract Abstraction CouplingMorphRetire.
Require Import Kernel.VMState Kernel.VMStep.
Import VMStep.VMStep.
Open Scope string_scope.

Lemma wordToNat_err_compose_type : wordToNat ERR_COMPOSE_TYPE = KAMI_ERR_COMPOSE_TYPE.
Proof.
  unfold KAMI_ERR_COMPOSE_TYPE. destruct kami_err_compose_type_witness as [n E].
  cbn [proj1_sig]. subst n. rewrite <- N_to_nat_wordToN. f_equal; vm_compute; reflexivity.
Qed.

Lemma wordToNat_neq : forall sz (x y : word sz), x <> y -> Nat.eqb (wordToNat x) (wordToNat y) = false.
Proof.
  intros sz x y H. apply Nat.eqb_neq. intro E. apply H. apply wordToNat_inj. exact E.
Qed.

'''

M2 = '(split1 4 28 E)'

SPECS = {
    'MORPH_EXT': dict(
        instr='instr_morph (wordToNat AL) (wordToNat (split1 6 2 Bw)) (wordToNat (split1 6 26 E)) '
              '(wordToNat (split1 7 19 (split2 6 26 E))) (wordToNat C)',
        prem=srm.COST_PREM + [
            ('Hroom', 'wordToNat (hw_morph_next_id b) < 16'),
            ('Hdesc', 'wordToNat (hw_coupling_desc_next_id b) < 16'),
            ('Hfail', 'wordToNat (hw_ptTable b (split1 6 2 Bw)) = 0 \\/ wordToNat (hw_ptTable b (split1 6 26 E)) = 0')],
        cases='rewrite (morph_room_of_lt b Hroom), (desc_room_of_lt b Hdesc) in *. cbv beta iota in F_*. '
              'rewrite !module_present_eqb in *. '
              'destruct (Nat.eqb (wordToNat (hw_ptTable b (split1 6 2 Bw))) 0) eqn:G1; '
              'destruct (Nat.eqb (wordToNat (hw_ptTable b (split1 6 26 E))) 0) eqn:G2; '
              '[ | | | exfalso; destruct Hfail as [H|H]; [apply Nat.eqb_neq in G1; exact (G1 H)|apply Nat.eqb_neq in G2; exact (G2 H)] ]; '
              'cbv beta iota delta [negb] in F_*.',
        rich=srm.FRAME, unfold='kami_advance_err_code',
        kami='rewrite ?(hwb_vector_nat_at 6), ?G1, ?G2; cbv beta iota delta [negb andb].',
        close=srm.FAULT_CLOSE, fmt=3, phase_cases='the same'),
    'COMPOSE_EXT': dict(
        instr=f'instr_compose (wordToNat AL) (wordToNat BL) (wordToNat {M2}) (wordToNat C)',
        prem=srm.COST_PREM + srm.INV + [
            ('Hroom', 'wordToNat (hw_morph_next_id b) < 16'),
            ('Hfail', f'hw_morph_valid_table b BL = false \\/ hw_morph_valid_table b {M2} = false \\/ '
                      f'hw_morph_dst_table b BL <> hw_morph_src_table b {M2}')],
        cases=f'rewrite (morph_room_of_lt b Hroom), (morph_live_valid b BL Hinv), (morph_live_valid b {M2} Hinv) in *. '
              f'destruct (hw_morph_valid_table b BL) eqn:G1; destruct (hw_morph_valid_table b {M2}) eqn:G2; '
              f'[ destruct (weq (hw_morph_dst_table b BL) (hw_morph_src_table b {M2})) as [Heq|Hne]; '
              f'[ exfalso; destruct Hfail as [H|[H|H]]; [discriminate H|discriminate H|exact (H Heq)] | ] | | | ]; '
              'cbv beta iota delta [negb] in F_*.',
        rich=srm.FRAME, unfold='kami_advance_err_code',
        kami='rewrite ?rich_morph_table_at, ?G1, ?G2; cbv beta iota delta [negb]; '
             'cbn [morph_entry_source morph_entry_target morph_entry_coupling_desc morph_entry_is_identity]; '
             'try rewrite (wordToNat_neq _ _ _ Hne); cbv beta iota.',
        close=srm.FAULT_CLOSE + ['exact wordToNat_err_compose_type'], fmt=3),
}


def idle_lemma(name, spec):
    low = name.lower()
    bits = f'{BITS} {EBITS}'
    prem = srm.COMMON_PREM + spec['prem']
    t = f'Lemma step_{low}_fault_idle : forall {bits} (b : HWB),\n'
    t += f'  step_fetched b = {low}_word {bits} ->\n'
    t += '  hwb_bianchi b = false -> hw_err b = false -> hw_halted b = false ->\n'
    for _, stmt in prem:
        t += f'  {inline(stmt)} ->\n'
    t += '  hw_mc_phase (step_next b) = natToWord 4 0.\n'
    names = ' '.join(n for n, _ in prem)
    t += f'Proof.\n  intros {bits} b Hf Hb Herr Hhalt {names}.\n'
    for f in FIELDS:
        t += f'  pose proof (step_{low}_{f} {bits} b Hf Hb) as F_{f}.\n'
    allf = ', '.join(f'F_{f}' for f in FIELDS)
    t += '  ' + inline(spec['cases']).replace('F_*', allf) + '\n'
    t += '  all: exact F_mc_phase.\nQed.\n\n'
    return t


def generate():
    t = HEADER
    for name, spec in SPECS.items():
        thm = srm.theorem(name, spec)
        thm = thm.replace(f'Theorem step_{name.lower()}_refines', f'Theorem step_{name.lower()}_fault_refines', 1)
        t += thm
        t += idle_lemma(name, spec)
    return t


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    generated = generate()
    if args.check:
        if TARGET.read_text() != generated:
            raise SystemExit('CouplingFaults.v is stale; regenerate it')
    else:
        TARGET.write_text(generated)
    print(f'CouplingFaults: {len(SPECS)} fault refinements')
