#!/usr/bin/env python3
"""Generate ChshStepFields.v: field equations of the actual step rule at the
canonical CHSH_LASSERT encoding (legacy format, symbolic operand and cost
bits). Besides the refinement fields, the twelve CHSH latch registers are
stated in terms of [chsh_latch_n], [chsh_latch_abs] and [chsh_latch_sign]
from ChshArith.v. Each lemma is proved by reducing the actual decoded action.
"""
import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'scripts'))
from generate_step_fields import FIELDS, BITS, default, inline  # noqa: E402

TARGET = ROOT / 'coq/kami_hw/ChshStepFields.v'

HEADER = '''(** ChshStepFields.v: generated by scripts/generate_chsh_step_fields.py.
    Field equations of [step_next] at the canonical CHSH_LASSERT encoding,
    including the CHSH latch registers the FSM later reads. *)
Require Import Kami.Kami Kami.Semantics.
From Coq Require Import String NArith Eqdep_dec Arith.PeanoNat.
From KamiHW Require Import ThieleTypes ThieleCPUCore HWBoundary RuleNext RuleStep
  BoundaryDecoded ActionObservation DispatchObservation StepEval StepFields ChshArith.
Open Scope string_scope.

'''

MU1 = 'wplus (wplus (hw_mu b) (zext C 24)) (natToWord WordSz 1)'
SPEC = {'mu': MU1, 'chsh_phase': 'natToWord 5 1'}
LATCH = []
for k in ['00', '01', '10', '11']:
    s, d = f'(hw_wc_same_{k} b)', f'(hw_wc_diff_{k} b)'
    LATCH += [(f'chsh_n{k}', f'chsh_latch_n {s} {d}'),
              (f'chsh_d{k}', f'chsh_latch_abs {s} {d}'),
              (f'chsh_sign{k}', f'chsh_latch_sign {s} {d}')]


def generate():
    t = HEADER
    t += (f'Definition chsh_lassert_word ({BITS} : bool) : word InstrSz :=\n'
          '  legacy_word OP_CHSH_LASSERT (bits8 a0 a1 a2 a3 a4 a5 a6 a7) '
          '(bits8 b0 b1 b2 b3 b4 b5 b6 b7) (bits8 c0 c1 c2 c3 c4 c5 c6 c7).\n')
    rows = [(f, SPEC.get(f, default(f))) for f in FIELDS] + LATCH
    for f, rhs in rows:
        t += (f'Lemma step_chsh_lassert_{f} : forall {BITS} b,\n'
              f'  step_fetched b = chsh_lassert_word {BITS} -> hwb_bianchi b = false ->\n'
              f'  hw_{f} (step_next b) = {inline(rhs)}.\n'
              'Proof. hw_field. Qed.\n')
    return t, len(rows)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--out')
    args = parser.parse_args()
    generated, count = generate()
    target = Path(args.out) if args.out else TARGET
    if args.check:
        if target.read_text() != generated:
            raise SystemExit('ChshStepFields.v is stale; regenerate it')
    else:
        target.write_text(generated)
    print(f'ChshStepFields: {count} field equations')
