#!/usr/bin/env python3
"""Generate RetireMaster.v: one admission relation over the retirement
theorems of all 47 opcodes, and the master single-instruction theorem.

[admitted b i] has one constructor per refinement theorem. Each constructor
carries that theorem's premises verbatim: the canonical fetched word, the
Bianchi guard, a live boundary, and the theorem's admission premises. The
master theorem [admitted_retires] states that from such a boundary the
concrete scheduler fires the step rule and then a busy FSM run to an idle
boundary whose snapshot is [kami_step (hwb_snapshot b) i].
"""
import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HW = ROOT / 'coq/kami_hw'
TARGET = HW / 'RetireMaster.v'

SOURCES = ['StepRefine.v', 'StepRefineMorph.v', 'CouplingFaults.v', 'LassertRetire.v',
           'ChshRetire.v', 'CouplingMorphRetire.v', 'CouplingComposeRetire.v']

HEADER = r'''(** RetireMaster.v: generated by scripts/generate_retire_master.py.

    [Retire b i d]: at the live boundary [b] the scheduler selects the step
    rule; from [step_next b] every further firing starts at a busy boundary
    and ends at the idle boundary [d]; and [d] observes
    [kami_step (hwb_snapshot b) i]. [retire_unique]: [d] is determined by
    [b]. [retire_runner]: the concrete runner reaches [d].

    [admitted b i] has one constructor per retirement theorem, carrying its
    premises. [admitted_retires] is the master single-instruction theorem. *)
Require Import Kami.Kami Kami.Semantics Kami.Lib.NatLib.
From Coq Require Import String List Arith Lia Bool FunctionalExtensionality.
Import ListNotations.
Require Import Kernel.VMState Kernel.VMStep Kernel.CertCheck.
Import VMStep.VMStep.
From KamiHW Require Import ThieleTypes ThieleCPUCore HWBoundary RuleNext RuleStep BoundaryDecoded StepEval
  StepWordFacts StepFields StepRefineCommon StepRefine StepFieldsMorph StepRefineMorph
  ImplementationContract Abstraction EmbedStep NormalizationSteps NormalizationLoop MorphLoading
  RuleEnabled FsmDecoded ChshDecoded ChshRun ChshStepFields ChshRetire
  LassertSpec LassertWord LassertStepFields LassertRetire CouplingFsmEnds CouplingFsmRun
  CouplingMorphRich CouplingMorphKami CouplingMorphRetire
  CouplingComposeRun CouplingComposeKami CouplingComposeRetire CouplingFaults
  BoundaryRun RetireRuns RetireRunsFsm RetireRunsOps.
Local Open Scope nat_scope.
Local Open Scope list_scope.

Definition Retire (b : HWB) (i : vm_instruction) (d : HWB) : Prop :=
  hw_live b /\ (exists n, Busy_runs (step_next b) d n) /\ hw_idle d /\
  hwb_snapshot d = kami_step (hwb_snapshot b) i.

Theorem retire_runner : forall b i d, Retire b i d ->
  exists k, fst (run_boundary_rules k b) = d.
Proof.
  intros b i d [Hl [[n Hn] _]]. exists (S n).
  apply runs_runner_exact.
  exact (runs_fire b "step" (step_next b) d n (live_step_selected b Hl) (busy_runs_runs _ _ _ Hn)).
Qed.

Theorem retire_unique : forall b i j d d', Retire b i d -> Retire b j d' -> d = d'.
Proof.
  intros b i j d d' [_ [[n Hn] [Hd _]]] [_ [[n' Hn'] [Hd' _]]].
  exact (proj1 (busy_runs_unique _ _ _ Hn Hd _ _ Hn' Hd')).
Qed.

Theorem retire_multistep : forall b i d, Retire b i d ->
  exists l, Multistep thieleCore (hwb_regs b) (hwb_regs d) l.
Proof.
  intros b i d H. destruct (retire_runner b i d H) as [k Hk].
  exists (snd (run_boundary_rules k b)). rewrite <- Hk. apply run_boundary_rules_actual.
Qed.

Lemma step_idle : forall b, hw_lassert_phase (step_next b) = natToWord 3 0 ->
  hw_chsh_phase (step_next b) = natToWord 5 0 -> hw_mc_phase (step_next b) = natToWord 4 0 ->
  hw_idle (step_next b).
Proof. intros b H1 H2 H3. exact (conj H1 (conj H2 H3)). Qed.

'''


def top_split(text):
    """Split a premise chain on top-level arrows."""
    parts, depth, cur, i = [], 0, [], 0
    while i < len(text):
        ch = text[i]
        if ch == '(':
            depth += 1
        elif ch == ')':
            depth -= 1
        if depth == 0 and text.startswith(' -> ', i):
            parts.append(''.join(cur).strip())
            cur = []
            i += 4
            continue
        cur.append(ch)
        i += 1
    parts.append(''.join(cur).strip())
    return parts


def binder_names(binders):
    names = []
    for tok in re.findall(r'\(([^()]*)\)|(\S+)', binders):
        grp, bare = tok
        if grp:
            names.extend(grp.split(':')[0].split())
        else:
            names.append(bare)
    return names


def theorems():
    out = []
    for fn in SOURCES:
        s = (HW / fn).read_text()
        for m in re.finditer(r'Theorem (\w+) : forall ([^,]*),\n(.*?)\nProof', s, re.S):
            name, binders, body = m.groups()
            body = re.sub(r'\s+', ' ', body).strip()
            if 'kami_step (hwb_snapshot b)' not in body:
                continue
            parts = top_split(body)
            concl = parts[-1]
            cm = re.match(r'hwb_snapshot \((.*)\) = kami_step \(hwb_snapshot b\) (.*)\.$', concl)
            if not cm:
                continue
            final, instr = cm.groups()
            out.append(dict(file=fn, name=name, binders=binders.strip(), prem=parts[:-1],
                            final=final, instr=instr))
    return out


def fields_prefix(t):
    word = t['prem'][0]
    wm = re.match(r'step_fetched b = (\w+)_word ', word)
    return wm.group(1)


def word_args(t):
    return re.match(r'step_fetched b = \w+_word (.*)$', t['prem'][0]).group(1)


def constructor_name(t):
    return 'adm_' + re.sub(r'^step_|_refines$|_retire$', '', t['name'])


def generate():
    ths = [t for t in theorems() if t['name'] not in ('lassert_sat_refines',)]
    ctors, lemmas, branches = [], [], []
    for t in ths:
        prem = list(t['prem'])
        live_form = 'hw_live b' in prem
        if not live_form:
            assert prem[1:4] == ['hwb_bianchi b = false', 'hw_err b = false', 'hw_halted b = false'], t['name']
            prem = prem[:2] + ['hw_live b'] + prem[4:]
        cname = constructor_name(t)
        binders = t['binders']
        bnames = ' '.join(binder_names(binders))
        stmt = ' ->\n    '.join(prem)
        ctors.append(f'| {cname} : forall {binders},\n    {stmt} ->\n    admitted b {t["instr"]}')
        extra = [f'P{k}' for k in range(len(prem) - 3)]
        pnames = ' '.join(['Hf', 'Hb', 'Hlive'] + extra)
        low = fields_prefix(t)
        lem = f'Lemma retire_{cname[4:]} : forall {binders},\n  {" ->".join(chr(10) + "  " + p for p in prem).strip()} ->\n'
        lem = f'Lemma retire_{cname[4:]} : forall {binders},\n  ' + ' ->\n  '.join(prem) + \
              f' ->\n  exists d, Retire b {t["instr"]} d.\nProof.\n  intros {bnames} {pnames}.\n' \
              '  pose proof Hlive as [Hh [He _]].\n'
        call_args = f'{bnames} Hf Hb ' + ('Hlive ' if live_form else 'He Hh ') + ' '.join(extra)
        if t['final'] == 'step_next b':
            wa = word_args(t)
            if t['name'].endswith('_fault_refines'):
                idle_mc = f'(step_{low}_fault_idle {bnames} Hf Hb He Hh {" ".join(extra)})'
            else:
                idle_mc = f'(step_{low}_mc_phase {wa} b Hf Hb)'
            lem += ('  exists (step_next b). split; [exact Hlive|]. split; [exists 0; apply busy_done|].\n'
                    f'  split; [apply step_idle; [exact (step_{low}_lassert_phase {wa} b Hf Hb)|'
                    f'exact (step_{low}_chsh_phase {wa} b Hf Hb)|exact {idle_mc}]|].\n'
                    f'  exact ({t["name"]} {call_args}).\nQed.\n')
        elif t['name'] == 'chsh_lassert_refines':
            bb = bnames_bits(bnames)
            lem += ('  exists (chsh_iter 23 (step_next b)). split; [exact Hlive|].\n'
                    f'  split; [exists 23; exact (chsh_lassert_runs {bb} b Hf Hb Hlive)|].\n'
                    f'  destruct (chsh_run_result (step_next b) (step_chsh_lassert_chsh_phase {bb} b Hf Hb)) as [_ [Hc _]].\n'
                    f'  split; [split; [rewrite iter_keeps_lassert_phase; exact (step_chsh_lassert_lassert_phase {bb} b Hf Hb)|'
                    f'split; [exact Hc|rewrite iter_keeps_mc_phase; exact (step_chsh_lassert_mc_phase {bb} b Hf Hb)]]|].\n'
                    f'  exact ({t["name"]} {call_args}).\nQed.\n')
        elif t['name'] == 'morph_ext_retire':
            bb = bnames_bits(bnames)
            lem = lem.replace(f'intros {bnames} {pnames}.',
                              f'intros {bnames} Hf Hb Hlive Hpc Hmu Hroom Hdesc Hsrc Hdst Hcount Hfit HP16 Hbase Hlab128 Hlabel Hreg.')
            lem += ('  exists (morph_fsm_final count (step_next b)). split; [exact Hlive|].\n'
                    f'  split; [destruct (morph_ext_runs {bb} b count Hf Hb Hlive Hroom Hdesc Hsrc Hdst Hcount Hfit Hbase) as [k Hk]; exists k; exact Hk|].\n'
                    '  split; [split; [|split]|].\n'
                    f'  - rewrite morph_fsm_keeps_lassert_phase. exact (step_morph_ext_lassert_phase {bb} b Hf Hb).\n'
                    f'  - rewrite morph_fsm_keeps_chsh_phase. exact (step_morph_ext_chsh_phase {bb} b Hf Hb).\n'
                    '  - apply mccommit_phase.\n'
                    f'  - exact (morph_ext_retire {bb} b count Hf Hb Hlive Hpc Hmu Hroom Hdesc Hsrc Hdst Hcount Hfit HP16 Hbase Hlab128 Hlabel Hreg).\nQed.\n')
        elif t['name'] == 'compose_ext_retire':
            bb = bnames_bits(bnames)
            names = 'Hf Hb Hlive Hpc Hmu Hroom Hdesc HP16 Imv Iref Iz Iz0 Idp Ipv Iid Ilab V1 V2 Hmatch Hlab Hcap'
            lem = lem.replace(f'intros {bnames} {pnames}.', f'intros {bnames} {names}.')
            lem += ('  exists (compose_fsm_final (step_next b)). split; [exact Hlive|].\n'
                    f'  split; [destruct (compose_ext_runs {bb} b {names}) as [k Hk]; exists k; exact Hk|].\n'
                    '  split; [split; [|split]|].\n'
                    f'  - rewrite compose_fsm_keeps_lassert_phase. exact (step_compose_ext_lassert_phase {bb} b Hf Hb).\n'
                    f'  - rewrite compose_fsm_keeps_chsh_phase. exact (step_compose_ext_chsh_phase {bb} b Hf Hb).\n'
                    '  - unfold compose_fsm_final. cbv zeta. destruct (weq _ _); apply mccommit_phase.\n'
                    f'  - exact (compose_ext_retire {bb} b {names}).\nQed.\n')
        else:
            raise SystemExit(f'no retirement pattern for {t["name"]}')
        lemmas.append(lem)
        branches.append(f'eapply retire_{cname[4:]}; eassumption')
    # LASSERT SAT, through lassert_sat_runs
    lb = 'a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7'
    sat_prem = [
        f'step_fetched b = lassert_sat_word {lb}', 'hwb_bianchi b = false', 'hw_live b',
        'wordToNat (hw_pc b) + 1 < pow2 WordSz', 'wordToNat (hw_trap_vector b) = LASSERT_TRAP_PC',
        'mem_at b (wordToNat (hw_regs b (bits4 a0 a1 a2 a3))) = flen',
        'wordToNat (hw_regs b (bits4 a0 a1 a2 a3)) + 3 + flen < pow2 32',
        '1 <= mem_at b (wordToNat (hw_regs b (bits4 a0 a1 a2 a3)) + 2)',
        'mem_at b (wordToNat (hw_regs b (bits4 a0 a1 a2 a3)) + 2) <= count_zeros (lassert_words b (wordToNat (hw_regs b (bits4 a0 a1 a2 a3))))',
        'wordToNat (hw_mu b) + flen * 8 + wordToNat (bits8 c0 c1 c2 c3 c4 c5 c6 c7) + 1 < pow2 32']
    sat_instr = '(instr_lassert (wordToNat (bits4 a0 a1 a2 a3)) (wordToNat (bits4 b0 b1 b2 b3)) true flen (wordToNat (bits8 c0 c1 c2 c3 c4 c5 c6 c7)))'
    ctors.append(f'| adm_lassert_sat : forall {lb} (b : HWB) flen,\n    ' + ' ->\n    '.join(sat_prem) +
                 f' ->\n    admitted b {sat_instr}')
    lemmas.append(f'Lemma retire_lassert_sat : forall {lb} (b : HWB) flen,\n  ' + ' ->\n  '.join(sat_prem) +
                  f' ->\n  exists d, Retire b {sat_instr} d.\nProof.\n'
                  f'  intros {lb} b flen Hf Hb Hlive Hpc Htrap Hflen Hfit Hcl1 Hcl2 Hmu.\n'
                  f'  destruct (lassert_sat_runs {lb} b flen Hf Hb Hlive Hpc Htrap Hflen Hfit Hcl1 Hcl2 Hmu)\n'
                  '    as [n [_ [Hr [Hi Hs]]]].\n'
                  '  exists (lscan_iter n (lhdr_next (step_next b))). split; [exact Hlive|].\n'
                  '  split; [exists (1 + n); exact Hr|]. split; [exact Hi|exact Hs].\nQed.\n')
    branches.append('eapply retire_lassert_sat; eassumption')
    t = HEADER
    t += 'Inductive admitted : HWB -> vm_instruction -> Prop :=\n' + '\n'.join(ctors) + '.\n\n'
    t += '\n'.join(lemmas) + '\n'
    t += ('Theorem admitted_retires : forall b i, admitted b i -> exists d, Retire b i d.\n'
          'Proof.\n  intros b i H. destruct H.\n  all: first [ ' + '\n    | '.join(branches) + ' ].\nQed.\n')
    return t, len(ctors)


def bnames_bits(bnames):
    """Binder names up to and including b."""
    toks = bnames.split()
    return ' '.join(toks[:toks.index('b')])


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    generated, count = generate()
    if args.check:
        if TARGET.read_text() != generated:
            raise SystemExit('RetireMaster.v is stale; regenerate it')
    else:
        TARGET.write_text(generated)
    print(f'RetireMaster: {count} admission constructors')
