#!/usr/bin/env python3
"""Generate PartitionRefine.v: single-cycle retirement refinement of PNEW,
PSPLIT and PMERGE, which scan and rewrite the partition table.

Each theorem has the shape of the [StepRefine] theorems: at a boundary whose
fetched word is the canonical encoding, with the Bianchi guard false, err and
halted clear and the listed admission premises, the actual step rule's next
boundary observes exactly [kami_step (hwb_snapshot b) i]. The step rule's
range checks are rewritten to [kami_step]'s natural-number checks with the
lemmas of PartitionScan.v.
"""
import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'scripts'))
from generate_step_refine import theorem, COST_PREM  # noqa: E402

TARGET = ROOT / 'coq/kami_hw/PartitionRefine.v'

HEADER = r'''(** PartitionRefine.v: generated by scripts/generate_partition_refine.py.
    Single-cycle retirement refinement of the actual step rule against
    [kami_step] for PNEW, PSPLIT and PMERGE, at their canonical encodings. *)
Require Import Kami.Kami Kami.Semantics Kami.Lib.NatLib.
From Coq Require Import String NArith Arith Lia FunctionalExtensionality.
From KamiHW Require Import ThieleTypes HWBoundary RuleNext RuleStep BoundaryDecoded StepEval
  StepWordFacts StepFields StepRefineCommon PartitionScan ImplementationContract Abstraction
  StepRefine.
Require Import Kernel.VMState Kernel.VMStep.
Import VMStep.VMStep.
Open Scope string_scope.

Lemma wordToNat_err_partition_overlap :
  wordToNat ERR_PARTITION_OVERLAP_VAL = KAMI_ERR_PARTITION_OVERLAP.
Proof.
  unfold KAMI_ERR_PARTITION_OVERLAP. destruct kami_err_partition_overlap_witness as [n E].
  cbn [proj1_sig]. subst n. rewrite <- N_to_nat_wordToN. f_equal; vm_compute; reflexivity.
Qed.

'''

REFINE = {
    'PNEW': dict(
        instr='instr_pnew region (wordToNat C)', vars=['region : list nat'],
        prem=COST_PREM + [('Hreg', 'List.length (normalize_region region) = wordToNat Bw'),
                          ('Hbase', 'hd 0 (normalize_region region) = wordToNat A'),
                          ('Hnext', 'wordToNat (hw_pt_next_id b) < 64'),
                          ('Hpo', 'wordToNat (hw_partition_ops b) + 1 < pow2 WordSz'),
                          ('Htrap', 'wordToNat (hw_trap_vector b) = LASSERT_TRAP_PC')],
        pre='rewrite (pt_room_one_of_lt b Hnext). '
            'rewrite !hw_pnew_conflict_nat, !hw_pnew_present_nat, !wordToNat_zext8_32.',
        post='rewrite <- Hreg, <- Hbase. '
             'destruct (snap_pt_conflict _ _ _ _ _) eqn:Hc; '
             'cbn [negb andb]; try destruct (snap_pt_present _ _ _ _ _) eqn:Hp; cbn [negb andb].',
        close=['exact Htrap', 'exact wordToNat_err_partition_overlap',
               'lazymatch goal with |- hwb_vector_nat _ = _ => '
               'refine (eq_trans (hwb_vector_nat_update _ _ _ _ _) _); unfold PTableIdxSz; '
               'rewrite wordToNat_trunc6_small by exact Hnext; rewrite wordToNat_zext8_32; '
               'rewrite ?Hreg, ?Hbase; reflexivity end',
               'lazymatch goal with |- wordToNat (wplus (hw_pt_next_id _) _) = _ => '
               'rewrite wordToNat_wplus_7 by lia; lia end',
               'lazymatch goal with |- wordToNat (wplus (hw_partition_ops _) _) = _ => '
               'rewrite wordToNat_wplus_one_bounded by exact Hpo; lia end']),
}

M1 = '(split1 6 2 A)'
M2 = '(split1 6 2 Bw)'

REFINE['PMERGE'] = dict(
    instr='instr_pmerge (wordToNat A) (wordToNat Bw) (wordToNat C)',
    prem=COST_PREM + [('Hnext', 'wordToNat (hw_pt_next_id b) < 64'),
                      ('Hpo', 'wordToNat (hw_partition_ops b) + 1 < pow2 WordSz'),
                      ('Hsum', 'wordToNat (hw_ptTable b (split1 6 2 A)) + wordToNat (hw_ptTable b (split1 6 2 Bw)) < pow2 WordSz'),
                      ('Htrap', 'wordToNat (hw_trap_vector b) = LASSERT_TRAP_PC')],
    rich_tac=(
        'assert (Hrich : hwb_rich (step_next b) = '
        f'if hw_pmerge_adjacent b {M1} {M2} then rich_state_cascade (hwb_rich b) (wordToNat {M1}) (wordToNat {M2}) '
        'else hwb_rich b). '
        '{ destruct (hw_pmerge_adjacent b ' + M1 + ' ' + M2 + ') eqn:Hadj. '
        '- apply step_rich_cascade; [ rewrite (step_{low}_morph_valid_table {args} b Hf Hb), '
        '(pt_room_one_of_lt b Hnext), Hadj; reflexivity '
        '| exact (step_{low}_morph_src_table {args} b Hf Hb) | exact (step_{low}_morph_dst_table {args} b Hf Hb) '
        '| exact (step_{low}_morph_coupling_desc_table {args} b Hf Hb) '
        '| exact (step_{low}_morph_identity_table {args} b Hf Hb) | exact (step_{low}_morph_next_id {args} b Hf Hb) '
        '| exact (step_{low}_coupling_desc_label_table {args} b Hf Hb) '
        '| exact (step_{low}_coupling_desc_label_len_table {args} b Hf Hb) ]. '
        '- apply step_rich_frame; '
        '[ rewrite (step_{low}_morph_valid_table {args} b Hf Hb), (pt_room_one_of_lt b Hnext), Hadj; reflexivity '
        '| exact (step_{low}_morph_src_table {args} b Hf Hb) | exact (step_{low}_morph_dst_table {args} b Hf Hb) '
        '| exact (step_{low}_morph_coupling_desc_table {args} b Hf Hb) '
        '| exact (step_{low}_morph_identity_table {args} b Hf Hb) | exact (step_{low}_morph_next_id {args} b Hf Hb) '
        '| exact (step_{low}_coupling_desc_label_table {args} b Hf Hb) '
        '| exact (step_{low}_coupling_desc_label_len_table {args} b Hf Hb) ]. } '
        'rewrite Hrich.'),
    pre='rewrite (pt_room_one_of_lt b Hnext). '
        'rewrite !hw_pmerge_adjacent_nat, ?wordToNat_trunc6_8.',
    post='change PTableSz with 64. '
         'destruct (snap_pmerge_adjacent _ _ _ _) eqn:Hadj; cbn [negb andb].',
    close=['exact Htrap', 'exact wordToNat_err_partition_overlap',
           'lazymatch goal with |- hwb_vector_nat _ = _ => '
           'unfold PTableIdxSz; rewrite <- (wordToNat_trunc6_8 A), <- (wordToNat_trunc6_8 Bw); rewrite ?hwb_vector_nat_at; '
           'refine (eq_trans (hwb_vector_nat_update _ _ _ _ _) _); '
           'let j := fresh "j" in extensionality j; '
           'rewrite hwb_vector_nat_update; cbv beta; rewrite hwb_vector_nat_update; cbv beta; '
           'rewrite (wordToNat_trunc6_small (hw_pt_next_id b)) by lia; '
           'rewrite ?hw_pmerge_base_nat, ?(wordToNat_wplus_bounded _ _ _ Hsum), ?wordToNat_word0_32; '
           'reflexivity end',
           'lazymatch goal with |- wordToNat (wplus (hw_pt_next_id _) _) = _ => '
           'rewrite wordToNat_wplus_7 by lia; lia end',
           'lazymatch goal with |- wordToNat (wplus (hw_partition_ops _) _) = _ => '
           'rewrite wordToNat_wplus_one_bounded by exact Hpo; lia end'])

P1 = '(split1 6 2 A)'
FRAME_ARGS = ' '.join(f'(step_{{low}}_{f} {{args}} b Hf Hb)' for f in [
    'morph_src_table', 'morph_dst_table', 'morph_coupling_desc_table', 'morph_identity_table',
    'morph_next_id', 'coupling_desc_label_table', 'coupling_desc_label_len_table'])

REFINE['PSPLIT'] = dict(
    instr='instr_psplit (wordToNat A) left right (wordToNat C)', vars=['left : list nat', 'right : list nat'],
    prem=COST_PREM + [('Hnext', 'wordToNat (hw_pt_next_id b) + 2 <= 64'),
                      ('Hpo', 'wordToNat (hw_partition_ops b) + 1 < pow2 WordSz'),
                      ('Hend', 'wordToNat (hw_ptBases b (split1 6 2 A)) + wordToNat (hw_ptTable b (split1 6 2 A)) < pow2 WordSz')],
    rich_tac=(
        f'rewrite (step_rich_cascade b {P1} {P1} '
        'ltac:(rewrite (step_{low}_morph_valid_table {args} b Hf Hb), (pt_room_two_of_le b Hnext); reflexivity) '
        + FRAME_ARGS + ').'),
    pre='rewrite (pt_room_two_of_le b Hnext). rewrite ?wordToNat_trunc6_8.',
    post='change PTableSz with 64.',
    close=['lazymatch goal with |- hwb_vector_nat _ = _ => '
           'change PTableSz with 64; unfold PTableIdxSz; rewrite <- (wordToNat_trunc6_8 A); '
           'rewrite ?hwb_vector_nat_at; '
           'refine (eq_trans (hwb_vector_nat_update _ _ _ _ _) _); '
           'let j := fresh "j" in extensionality j; '
           'rewrite hwb_vector_nat_update; cbv beta; rewrite hwb_vector_nat_update; cbv beta; '
           'rewrite (wordToNat_trunc6_small (hw_pt_next_id b)) by lia; '
           'rewrite (wordToNat_trunc6_small (wplus (hw_pt_next_id b) (natToWord PTableNextIdSz 1))) '
           'by (rewrite wordToNat_wplus_7; lia); '
           'rewrite wordToNat_wplus_7 by lia; '
           'rewrite ?wordToNat_wminus_le by (rewrite wordToNat_word_half; apply half_le); '
           'rewrite ?wordToNat_wplus_bounded by (rewrite wordToNat_word_half; pose proof (half_le (wordToNat (hw_ptTable b (split1 6 2 A)))); lia); '
           'rewrite ?wordToNat_word_half, ?wordToNat_word0_32, ?Nat.add_1_r; reflexivity end',
           'lazymatch goal with |- wordToNat (wplus (hw_pt_next_id _) _) = _ => '
           'rewrite wordToNat_wplus_7 by lia; lia end',
           'lazymatch goal with |- wordToNat (wplus (hw_partition_ops _) _) = _ => '
           'rewrite wordToNat_wplus_one_bounded by exact Hpo; lia end'])


def generate(only=None):
    t = HEADER
    count = 0
    for name, spec in REFINE.items():
        if only and name not in only:
            continue
        t += theorem(name, spec)
        count += 1
    return t, count


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--only', nargs='*')
    parser.add_argument('--out')
    args = parser.parse_args()
    generated, count = generate(args.only)
    target = Path(args.out) if args.out else TARGET
    if args.check:
        if target.read_text() != generated:
            raise SystemExit('PartitionRefine.v is stale; regenerate it')
    else:
        target.write_text(generated)
    print(f'PartitionRefine: {count} opcode refinements')
