#!/usr/bin/env python3
"""Generate ChshPhases.v: the CHSH_LASSERT FSM step at each concrete phase.

For every phase 1..23 and every register the FSM rule writes, the value after
[chsh_next] is stated with the phase multiplexers resolved: the one scratch
register of that phase receives the product of its two operands (as [m128],
[m256] or [m384] from ChshArith.v), every other scratch register keeps its
value, the phase advances, and at phase 23 the check result and the trap
commit are written. Operands and result widths are read from ThieleCPUCore.v.
"""
import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / 'coq/kami_hw/ChshPhases.v'
CPU = ROOT / 'coq/kami_hw/ThieleCPUCore.v'


def mux(text, name):
    i = text.index(f'LET {name} : Bit 384 <-')
    j = text.index('else $0;', i)
    return {int(k): v for k, v in re.findall(r'IF #phase_eq_(\d+)\s+then #(\w+)', text[i:j])}


def operand(v):
    base = v[:-len('_384')]
    if base in ('abs_C', 'abs_A', 'abs_B'):
        return f'(chsh_{base}_256 b)'
    return f'(hw_chsh_{base} b)'


def parse():
    text = CPU.read_text()
    d = text.index('Definition chsh_fsm_decoded')
    body = text[d:text.index(')%kami_action.', d)]
    opa, opb = mux(body, 'op_a_384'), mux(body, 'op_b_384')
    scratch = {}
    for reg, k, width in re.findall(r'Write "(chsh_\w+)"\s*<- IF #phase_eq_(\d+)\s+then #mult_(\d+)', body):
        scratch[reg] = (int(k), width)
    return opa, opb, scratch


def generate():
    opa, opb, scratch = parse()
    assert len(scratch) == 22, scratch
    t = '''(** ChshPhases.v: generated by scripts/generate_chsh_phases.py.
    The CHSH_LASSERT FSM rule at each concrete phase, with the phase
    multiplexers resolved. Each equation is checked by the kernel. *)
Require Import Kami.Kami Kami.Semantics.
From Coq Require Import String.
From KamiHW Require Import ThieleTypes ThieleCPUCore HWBoundary RuleNext ChshDecoded ChshArith ChshFsm.

(** Resolve the phase multiplexers with tactics before conversion: left to the
    kernel, the same check unfolds the wide word operations and takes minutes. *)
Ltac phase_mux :=
  cbn [evalExpr evalUniBool evalBinBitBool evalConstT isEq evalUniBit evalBinBit];
  repeat match goal with |- context [weq ?x ?y] =>
    let v := eval vm_compute in (if weq x y then true else false) in
    change (if weq x y then true else false) with v end;
  cbv beta iota.

Ltac phase_unfold :=
  unfold chsh_commit_trap, chsh_mult_128, chsh_mult_256, chsh_mult_384, chsh_mult_result_768,
    chsh_op_a_384, chsh_op_b_384, ''' + ', '.join(f'chsh_phase_eq_{k}' for k in range(1, 24)) + '''.

'''
    for k in range(1, 24):
        for j in range(1, 24):
            val = 'true' if k == j else 'false'
            t += (f'Lemma chsh_eq{k}_at{j} : forall b, hw_chsh_phase b = natToWord 5 {j} -> chsh_phase_eq_{k} b = {val}.\n'
                  f'Proof. intros b H. unfold chsh_phase_eq_{k}. cbn [evalExpr evalConstT isEq]. rewrite H. reflexivity. Qed.\n')
    t += '\n'
    count = 0
    for j in range(1, 24):
        rows = []
        for reg, (k, width) in scratch.items():
            if k == j:
                rows.append((reg, f'm{width} {operand(opa[k])} {operand(opb[k])}',
                             'phase_unfold. rewrite H. phase_mux. unfold m128, m256, m384. reflexivity.'))
            else:
                rows.append((reg, f'hw_{reg} b', f'rewrite (chsh_eq{k}_at{j} b H). kernel_refl.'))
        e23 = f'rewrite (chsh_eq23_at{j} b H).'
        if j == 23:
            rows += [('chsh_check_result', 'chsh_final_ok b', f'{e23} kernel_refl.'),
                     ('pc', 'if negb (chsh_final_ok b) then hw_trap_vector b else hw_pc b',
                      f'unfold chsh_commit_trap. {e23} kernel_refl.'),
                     ('err', 'if negb (chsh_final_ok b) then true else hw_err b',
                      f'unfold chsh_commit_trap. {e23} kernel_refl.'),
                     ('error_code', 'if negb (chsh_final_ok b) then ERR_LOGIC_VAL else hw_error_code b',
                      f'unfold chsh_commit_trap. {e23} kernel_refl.'),
                     ('chsh_phase', 'natToWord 5 0', f'{e23} kernel_refl.')]
        else:
            rows += [('chsh_check_result', 'hw_chsh_check_result b', f'{e23} kernel_refl.'),
                     ('pc', 'hw_pc b', f'unfold chsh_commit_trap. {e23} kernel_refl.'),
                     ('err', 'hw_err b', f'unfold chsh_commit_trap. {e23} kernel_refl.'),
                     ('error_code', 'hw_error_code b', f'unfold chsh_commit_trap. {e23} kernel_refl.'),
                     ('chsh_phase', f'natToWord 5 {j + 1}', f'{e23} rewrite H. kernel_refl.')]
        for reg, rhs, proof in rows:
            t += (f'Lemma chsh_phase{j}_{reg} : forall b, hw_chsh_phase b = natToWord 5 {j} ->\n'
                  f'  hw_{reg} (chsh_next b) = {rhs}.\n'
                  f'Proof. intros b H. rewrite chsh_next_{reg}. {proof} Qed.\n')
            count += 1
        t += '\n'
    return t, count


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--out')
    args = parser.parse_args()
    generated, count = generate()
    target = Path(args.out) if args.out else TARGET
    if args.check:
        if target.read_text() != generated:
            raise SystemExit('ChshPhases.v is stale; regenerate it')
    else:
        target.write_text(generated)
    print(f'ChshPhases: {count} phase equations')
