#!/usr/bin/env python3
"""Generate <File>.v: explicit next-state records for CPU FSM rules.

For each selected rule of ThieleCPUCore.thieleCore, every LET becomes a
definition [<prefix>_<name> b], literally [evalExpr] of the same Kami
expression with read variables replaced by boundary fields, and the rule's
next state becomes an explicit [HWB] record with one field per register [<prefix>_next b].
[<prefix>_next_correct] proves [rule_next (normalization_rule k) b] equals
that record for every boundary; the kernel checks the conversion once per
rule. Field equations follow by projection.

Usage: generate_fsm_next.py OUTFILE RULE:INDEX:PREFIX ...
"""
import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CPU = ROOT / 'coq/kami_hw/ThieleCPUCore.v'
HWB = ROOT / 'coq/kami_hw/HWBoundary.v'

READ = re.compile(r'^Read (\w+)\s*:\s*(.+?)\s*<-\s*"(\w+)"$')


def strip_comments(s):
    out, depth, i = [], 0, 0
    while i < len(s):
        if s.startswith('(*', i):
            depth += 1; i += 2
        elif s.startswith('*)', i) and depth:
            depth -= 1; i += 2
        else:
            if depth == 0:
                out.append(s[i])
            i += 1
    return ''.join(out)


def rule_body(name):
    text = CPU.read_text()
    i = text.index(f'with Rule "{name}" :=')
    nxt = [k for k in (text.find('with Rule "', i + 10), text.find('with Method "', i + 10)) if k > 0]
    body = strip_comments(text[i + len(f'with Rule "{name}" :='):min(nxt)]).strip()
    assert body.endswith('Retv'), name
    return [' '.join(s.split()) for s in body[:-len('Retv')].split(';') if s.strip()]


def hwb_fields():
    return re.findall(r'^\s*hw_(\w+) : (.+?);?$', HWB.read_text().split('Record HWB')[1].split('}.')[0], re.M)


def generate(specs):
    fields = hwb_fields()
    kinds = {f: k for f, k in fields}
    t = '''(** Generated by scripts/generate_fsm_next.py: explicit next-state records
    for CPU FSM rules. Each LET is [evalExpr] of the rule's own Kami
    expression over boundary fields; [*_next_correct] is checked by the
    kernel's conversion. *)
Require Import Kami.Kami Kami.Semantics.
From Coq Require Import String.
From KamiHW Require Import ThieleTypes ThieleCPUCore HWBoundary RuleNext RuleStep NormalizationSteps.

Ltac kernel_refl := match goal with |- ?x = _ => exact_no_check (eq_refl x) end.

'''
    for rule, index, prefix in specs:
        stmts = rule_body(rule)
        env, writes = {}, {}
        for s in stmts:
            m = READ.match(s)
            if m:
                env[m.group(1)] = (f'(hw_{m.group(3)} b)', m.group(2))
                continue
            if s.startswith('Assert'):
                continue
            m = re.match(r'^LET (\w+)\s*(?::\s*(.+?))?\s*<-\s*(.+)$', s)
            if m:
                name, kind, expr = m.group(1), m.group(2) or 'Bool', m.group(3)
                t += (f'Definition {prefix}_{name} (b : HWB) : type ({kind}) :=\n'
                      f'  evalExpr ({subst(expr, env)})%kami_expr.\n')
                env[name] = (f'({prefix}_{name} b)', kind)
                continue
            m = re.match(r'^Write "(\w+)"\s*<-\s*(.+)$', s)
            assert m, (rule, s)
            writes[m.group(1)] = m.group(2)
        t += f'\nDefinition {prefix}_next (b : HWB) : HWB :=\n  {{| '
        rows = []
        for f, kind in fields:
            if f in writes:
                rows.append(f'hw_{f} := evalExpr ({subst(writes[f], env)})%kami_expr')
            else:
                rows.append(f'hw_{f} := hw_{f} b')
        t += ';\n     '.join(rows) + ' |}.\n\n'
        t += (f'Lemma {prefix}_next_correct : forall b, rule_next (normalization_rule {index}) b = {prefix}_next b.\n'
              'Proof. intro b. kernel_refl. Qed.\n\n')
        for f in writes:
            assert f in kinds, (rule, f)
    return t


def subst(expr, env):
    def rep(m):
        term, kind = env[m.group(1)]
        return f'(Var type (SyntaxKind ({kind})) {term})'
    return re.sub(r'#(\w+)', rep, expr)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('out')
    parser.add_argument('specs', nargs='+')
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    specs = [tuple(s.split(':')) for s in args.specs]
    generated = generate(specs)
    target = Path(args.out)
    if args.check:
        if target.read_text() != generated:
            raise SystemExit(f'{target.name} is stale; regenerate it')
    else:
        target.write_text(generated)
    print(f'{target.name}: {len(specs)} rule next-state records')
