#!/usr/bin/env python3
"""Generate StepRefine.v: single-cycle retirement refinement per opcode.

For each single-cycle opcode the theorem states that, at a boundary whose
fetched word is the canonical encoding (all operand and cost bits symbolic),
with the Bianchi guard false, err and halted clear, and the listed admission
premises, the actual step rule's next boundary observes exactly
[kami_step (hwb_snapshot b) i] for the decoded abstract instruction [i].
"""
import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'scripts'))
from generate_step_fields import FIELDS, NAMES, BITS, inline  # noqa: E402

TARGET = ROOT / 'coq/kami_hw/StepRefine.v'

HEADER = r'''(** StepRefine.v: generated by scripts/generate_step_refine.py.
    Single-cycle retirement refinement of the actual step rule against
    [kami_step], one theorem per opcode at its canonical encoding. *)
Require Import Kami.Kami Kami.Semantics Kami.Lib.NatLib.
From Coq Require Import String NArith Arith Lia FunctionalExtensionality.
From KamiHW Require Import ThieleTypes HWBoundary RuleNext RuleStep BoundaryDecoded StepEval
  StepWordFacts StepFields StepRefineCommon PopcountSWAR ImplementationContract Abstraction.
Require Import Kernel.VMState Kernel.VMStep.
Import VMStep.VMStep.
Open Scope string_scope.

Ltac snap_projections :=
  cbn [snap_pc snap_mu snap_err snap_halted snap_regs snap_mem snap_partition_ops
    snap_mdl_ops snap_info_gain snap_error_code snap_mu_tensor snap_pt_sizes
    snap_pt_next_id snap_certified snap_wc_same_00 snap_wc_diff_00 snap_wc_same_01
    snap_wc_diff_01 snap_wc_same_10 snap_wc_diff_10 snap_wc_same_11 snap_wc_diff_11
    snap_module_tensors snap_rich_state snap_csr_cert_addr snap_csr_status snap_csr_err
    snap_csr_heap_base snap_logic_acc snap_mstatus hwb_snapshot].

Ltac syntactic := lazymatch goal with |- ?x = ?x => reflexivity end.

(** pc + 1 and mu + cost under no-wrap premises in context. *)
Ltac close_pc :=
  lazymatch goal with
  | H : wordToNat (hw_pc ?b) + 1 < pow2 WordSz
    |- wordToNat (wplus (hw_pc ?b) (natToWord _ 1)) = S (wordToNat (hw_pc ?b)) =>
      rewrite wordToNat_wplus_bounded; rewrite wordToNat_word1_32; [lia|exact H]
  end.

Ltac close_mu_cost :=
  lazymatch goal with
  | H : wordToNat (hw_mu ?b) + wordToNat ?c < pow2 WordSz
    |- wordToNat (wplus (hw_mu ?b) (zext ?c 24)) = wordToNat (hw_mu ?b) + wordToNat ?c =>
      rewrite wordToNat_wplus_bounded; rewrite wordToNat_zext8_32; [reflexivity|exact H]
  end.

(** mu + cost + 1 (cert-setter charge) under a no-wrap premise. *)
Ltac close_mu_cost_one :=
  lazymatch goal with
  | H : wordToNat (hw_mu ?b) + wordToNat ?c + 1 < pow2 WordSz
    |- wordToNat (wplus (wplus (hw_mu ?b) (zext ?c 24)) (natToWord _ 1)) = _ =>
      assert (H1 : wordToNat (wplus (hw_mu b) (zext c 24)) = wordToNat (hw_mu b) + wordToNat c)
        by (rewrite wordToNat_wplus_bounded; rewrite ?wordToNat_zext8_32; [reflexivity|lia]);
      rewrite wordToNat_wplus_one_bounded by (rewrite H1; exact H);
      rewrite H1; lia
  end.

(** mu + bits + cost + 1 (bit-priced charge) under a no-wrap premise. *)
Ltac close_mu_bits :=
  lazymatch goal with
  | H : wordToNat (hw_mu ?b) + wordToNat ?bw + wordToNat ?c + 1 < pow2 WordSz
    |- wordToNat (wplus (wplus (wplus (hw_mu ?b) (zext ?bw 24)) (zext ?c 24)) (natToWord _ 1)) = _ =>
      assert (H1 : wordToNat (wplus (hw_mu b) (zext bw 24)) = wordToNat (hw_mu b) + wordToNat bw)
        by (rewrite wordToNat_wplus_bounded; rewrite ?wordToNat_zext8_32; [reflexivity|lia]);
      assert (H2 : wordToNat (wplus (wplus (hw_mu b) (zext bw 24)) (zext c 24)) =
                   wordToNat (hw_mu b) + wordToNat bw + wordToNat c)
        by (rewrite wordToNat_wplus_bounded; rewrite ?H1, ?wordToNat_zext8_32; [reflexivity|lia]);
      rewrite wordToNat_wplus_one_bounded by (rewrite H2; exact H);
      rewrite H2; lia
  end.

(** Data-memory update at a truncated address: [pre] normalizes the address,
    [tac] proves the written value. *)
Ltac close_mem_update pre tac :=
  refine (eq_trans (hwb_vector_nat_update _ _ _ _ _) _);
  let j := fresh "j" in
  extensionality j;
  change RegCount with (2 ^ RegIdxSz); change MEM_SIZE with 128;
  rewrite ?hwb_vector_nat_at_mod;
  unfold MemAddrSz, RegIdxSz;
  rewrite wordToNat_trunc7; pre;
  lazymatch goal with
  | |- (if Nat.eqb ?i ?d then _ else _) = _ => destruct (Nat.eqb i d); [tac|reflexivity]
  end.

(** Register-file update: reduce to the written value, then [tac] proves it. *)
Ltac close_vector_update tac :=
  refine (eq_trans (hwb_vector_nat_update _ _ _ _ _) _);
  let j := fresh "j" in
  extensionality j;
  change RegCount with (2 ^ RegIdxSz);
  rewrite ?hwb_vector_nat_at_mod;
  repeat match goal with
  | |- context [wordToNat ?d mod 2 ^ RegIdxSz] =>
      rewrite (Nat.mod_small (wordToNat d) (2 ^ RegIdxSz)) by apply wordToNat_lt_pow2_small
  end;
  unfold RegIdxSz;
  lazymatch goal with
  | |- (if Nat.eqb ?i ?d then _ else _) = _ => destruct (Nat.eqb i d); [tac|reflexivity]
  end.

'''

# Per-opcode refinement specification:
#   instr: abstract instruction (inlined bit names allowed)
#   vars: extra universally quantified abstract operands (name : type)
#   prem: admission premises as (name, statement)
#   close: tactics tried on every non-syntactic field goal
COMMON_PREM = [('Hpc', 'wordToNat (hw_pc b) + 1 < pow2 WordSz')]
COST_PREM = [('Hmu', 'wordToNat (hw_mu b) + wordToNat C < pow2 WordSz')]

REFINE = {
    'ADD': dict(
        instr='instr_add (wordToNat AL) (wordToNat BH) (wordToNat BL) (wordToNat C)',
        prem=COST_PREM + [('Hv', 'wordToNat (hw_regs b BH) + wordToNat (hw_regs b BL) < pow2 WordSz')],
        close=['close_vector_update ltac:(rewrite wordToNat_wplus_bounded by exact Hv; '
               'rewrite word64_below_pow2_32 by exact Hv; reflexivity)']),
    'SUB': dict(
        instr='instr_sub (wordToNat AL) (wordToNat BH) (wordToNat BL) (wordToNat C)',
        prem=COST_PREM + [('Hv', 'wordToNat (hw_regs b BL) <= wordToNat (hw_regs b BH)')],
        close=['close_vector_update ltac:(rewrite wordToNat_wminus_le by exact Hv; '
               'rewrite word64_sub_small by (exact Hv || apply wordToNat_bound); '
               'rewrite word64_below_pow2_32 by apply word32_sub_lt_pow2_32; reflexivity)']),
    'AND': dict(
        instr='instr_and (wordToNat AL) (wordToNat BH) (wordToNat BL) (wordToNat C)',
        prem=COST_PREM,
        close=['close_vector_update ltac:(rewrite word64_and_word32, word64_word32; reflexivity)']),
    'OR': dict(
        instr='instr_or (wordToNat AL) (wordToNat BH) (wordToNat BL) (wordToNat C)',
        prem=COST_PREM,
        close=['close_vector_update ltac:(rewrite word64_or_word32, word64_word32; reflexivity)']),
    'XOR_ADD': dict(
        instr='instr_xor_add (wordToNat AL) (wordToNat BL) (wordToNat C)',
        prem=COST_PREM,
        close=['close_vector_update ltac:(rewrite word64_xor_word32, word64_word32; reflexivity)']),
    'MUL': dict(
        instr='instr_mul (wordToNat AL) (wordToNat BH) (wordToNat BL) (wordToNat C)',
        prem=COST_PREM + [('Hv', 'wordToNat (hw_regs b BH) * wordToNat (hw_regs b BL) < pow2 WordSz')],
        close=['close_vector_update ltac:(unfold word64_mul; '
               'rewrite wordToNat_wmult_bounded by exact Hv; '
               'rewrite word64_twice_small by exact Hv; reflexivity)']),
    'XFER': dict(
        instr='instr_xfer (wordToNat AL) (wordToNat BL) (wordToNat C)',
        prem=COST_PREM,
        close=['close_vector_update ltac:(rewrite word64_word32; reflexivity)']),
    'LOAD_IMM': dict(
        instr='instr_load_imm (wordToNat AL) (wordToNat Bw) (wordToNat C)',
        prem=COST_PREM,
        close=['close_vector_update ltac:(rewrite wordToNat_zext8_32; '
               'rewrite word64_below_pow2_32 by apply word8_lt_pow2_32; reflexivity)']),
    'SHL': dict(
        instr='instr_shl (wordToNat AL) (wordToNat BH) (wordToNat BL) (wordToNat C)',
        prem=COST_PREM + [('Hs', 'wordToNat (hw_regs b BL) < 32'),
                          ('Hv', 'wordToNat (hw_regs b BH) * pow2 (wordToNat (hw_regs b BL)) < pow2 WordSz')],
        close=['close_vector_update ltac:(rewrite word64_shl_word32 by (exact Hs || exact Hv); '
               'rewrite word64_word32; reflexivity)']),
    'SHR': dict(
        instr='instr_shr (wordToNat AL) (wordToNat BH) (wordToNat BL) (wordToNat C)',
        prem=COST_PREM + [('Hs', 'wordToNat (hw_regs b BL) < 64')],
        close=['close_vector_update ltac:(rewrite word64_shr_word32 by exact Hs; '
               'rewrite word64_word32; reflexivity)']),
    'LUI': dict(
        instr='instr_lui (wordToNat AL) (wordToNat Bw) (wordToNat C)',
        prem=COST_PREM,
        close=['close_vector_update ltac:(change (wordToNat (natToWord _ 8)) with 8; '
               'rewrite <- (wordToNat_zext8_32 Bw); '
               'rewrite word64_shl_word32 by (lia || apply lui_shift_bound); '
               'rewrite word64_below_pow2_32 by apply wordToNat_bound; reflexivity)']),
    'XOR_LOAD': dict(
        instr='instr_xor_load (wordToNat AL) (wordToNat Bw) (wordToNat C)',
        prem=COST_PREM,
        close=['close_vector_update ltac:(change MEM_SIZE with 128; '
               'rewrite <- wordToNat_trunc7_8; unfold MemAddrSz; rewrite hwb_vector_nat_at; '
               'rewrite word64_word32; reflexivity)']),
    'JUMP': dict(
        instr='instr_jump (wordToNat Bw + 256 * wordToNat A) (wordToNat C)',
        prem=COST_PREM,
        close=['lazymatch goal with |- wordToNat (evalZeroExtendTrunc _ (combine _ _)) = _ => '
               'rewrite wordToNat_zext16_ext, wordToNat_combine8; reflexivity end']),
    'JNEZ': dict(
        instr='instr_jnez (wordToNat AL) (wordToNat Bw) (wordToNat C)',
        prem=COST_PREM,
        close=['lazymatch goal with |- wordToNat (if weq ?x ?z then _ else _) = _ => '
               'change RegCount with (2 ^ RegIdxSz); rewrite hwb_vector_nat_at_mod; '
               'destruct (weq x z) as [E|E]; '
               '[rewrite E, wordToNat_word0_32; cbn [Nat.eqb]; close_pc '
               '|rewrite (word32_nonzero _ E), wordToNat_zext8_ext; reflexivity] end']),
    'MDLACC': dict(
        instr='instr_mdlacc (wordToNat A) (wordToNat C)',
        prem=COST_PREM + [('Hm', 'wordToNat (hw_mdl_ops b) + 1 < pow2 WordSz')],
        close=['lazymatch goal with |- wordToNat (wplus (hw_mdl_ops _) _) = _ => '
               'rewrite wordToNat_wplus_one_bounded by exact Hm; lia end']),
    'LJOIN': dict(
        instr='instr_ljoin (wordToNat A) (wordToNat Bw) (wordToNat C)',
        prem=[('Hmu', 'wordToNat (hw_mu b) + wordToNat C + 1 < pow2 WordSz')],
        close=['close_mu_cost_one']),
    'CERTIFY': dict(
        instr='instr_certify (wordToNat C)',
        prem=[('Hmu', 'wordToNat (hw_mu b) + wordToNat C + 1 < pow2 WordSz')],
        close=['close_mu_cost_one']),
    'READ_PORT': dict(
        instr='instr_read_port (wordToNat AL) chan 0 (wordToNat Bw) (wordToNat C)',
        vars=['chan : nat'],
        prem=[('Hmu', 'wordToNat (hw_mu b) + wordToNat Bw + wordToNat C + 1 < pow2 WordSz')],
        close=['close_mu_bits',
               'close_vector_update ltac:(rewrite wordToNat_word0_32, word64_zero; reflexivity)']),
    'EMIT': dict(
        instr='instr_emit (wordToNat A) payload (wordToNat C)',
        vars=['payload : string'],
        prem=[('Hp', 'payload_bit_length payload = wordToNat Bw'),
              ('Hmu', 'wordToNat (hw_mu b) + wordToNat Bw + wordToNat C + 1 < pow2 WordSz'),
              ('Hig', 'wordToNat (hw_info_gain b) + wordToNat Bw < pow2 WordSz')],
        close=['rewrite Hp; close_mu_bits',
               'lazymatch goal with |- wordToNat (wplus (hw_info_gain _) _) = _ => '
               'rewrite Hp; rewrite wordToNat_wplus_bounded; rewrite ?wordToNat_zext8_32; '
               '[reflexivity|exact Hig] end']),
    'REVEAL': dict(
        instr='instr_reveal (wordToNat AL) (wordToNat Bw) cert (wordToNat C)',
        vars=['cert : string'],
        prem=[('Hmu', 'wordToNat (hw_mu b) + wordToNat Bw + wordToNat C + 1 < pow2 WordSz'),
              ('Ht', 'wordToNat (hw_mu_tensor b AL) + wordToNat Bw < pow2 WordSz')],
        close=['close_mu_bits',
               'lazymatch goal with |- hwb_vector_nat (fun w => if weq w _ then wplus _ _ else _) = _ => '
               'unfold MuTensorIdxSz; etransitivity; '
               '[apply hwb_vector_nat_add_at; rewrite wordToNat_zext8_32; exact Ht|]; '
               'rewrite wordToNat_zext8_32; '
               'rewrite (Nat.mod_small (wordToNat AL) 16) by exact (wordToNat_bound AL); '
               'reflexivity end']),
    'XOR_SWAP': dict(
        instr='instr_xor_swap (wordToNat AL) (wordToNat BL) (wordToNat C)',
        prem=COST_PREM,
        close=['lazymatch goal with |- hwb_vector_nat (fun w => if weq w _ then _ else _) = _ => '
               'unfold RegIdxSz; etransitivity; [apply hwb_vector_nat_swap|]; '
               'let j := fresh "j" in extensionality j; change RegCount with 16; '
               'rewrite (Nat.mod_small (wordToNat AL) 16) by exact (wordToNat_bound AL); '
               'rewrite (Nat.mod_small (wordToNat BL) 16) by exact (wordToNat_bound BL); '
               'rewrite !hwb_vector_nat_at; reflexivity end']),
    'TENSOR_SET': dict(
        instr='instr_tensor_set (wordToNat AH) (wordToNat (bits2 a2 a3)) (wordToNat (bits2 a0 a1)) (wordToNat Bw) (wordToNat C)',
        prem=COST_PREM, post='rewrite tensor_indices_ok_bits2; snap_projections.',
        close=['lazymatch goal with |- (fun _ _ => if Nat.ltb _ 16 then _ else _) = _ => '
               'unfold ModTensorIdxSz, MuTensorIdxSz; etransitivity; [apply snap_tensor_set|]; '
               'rewrite tensor_flat_index, wordToNat_zext8_32; reflexivity end']),
    'TENSOR_GET': dict(
        instr='instr_tensor_get (wordToNat AL) (wordToNat BH) (wordToNat (bits2 b2 b3)) (wordToNat (bits2 b0 b1)) (wordToNat C)',
        prem=COST_PREM, post='rewrite tensor_indices_ok_bits2; snap_projections.',
        close=['close_vector_update ltac:(rewrite tensor_flat_index, word4_ltb_16, natToWord_wordToNat; '
               'unfold MuTensorIdxSz; rewrite hwb_vector_nat_at, word64_word32; reflexivity)']),
    'PDISCOVER': dict(
        instr='instr_pdiscover (wordToNat A) evidence (wordToNat C)',
        vars=['evidence : list VMAxiom'],
        fix={f'b{i}': 'false' for i in range(8)},
        prem=COST_PREM,
        pre='rewrite ?hw_nfi_ok_zero, ?wplus_zext_zero.',
        close=[]),
    'LOAD': dict(
        instr='instr_load (wordToNat AL) (wordToNat BL) (wordToNat C)',
        prem=COST_PREM + [('Hloc', 'wordToNat (split1 7 25 (hw_regs b BL)) < wordToNat (hw_ptTable b (hw_active_module b))')],
        pre='rewrite (region_ok_of_lt b _ Hloc).',
        close=['close_vector_update ltac:(change MEM_SIZE with 128; rewrite <- wordToNat_trunc7; '
               'unfold MemAddrSz; rewrite hwb_vector_nat_at, word64_word32; reflexivity)']),
    'STORE': dict(
        instr='instr_store (wordToNat AL) (wordToNat BL) (wordToNat C)',
        prem=COST_PREM + [('Hloc', 'wordToNat (split1 7 25 (hw_regs b AL)) < wordToNat (hw_ptTable b (hw_active_module b))')],
        pre='rewrite (region_ok_of_lt b _ Hloc).',
        close=['close_mem_update idtac ltac:(rewrite word64_word32; reflexivity)']),
    'HEAP_LOAD': dict(
        instr='instr_heap_load (wordToNat AL) (wordToNat BL) (wordToNat C)',
        prem=COST_PREM + [
            ('Hloc', 'wordToNat (split1 7 25 (wplus (hw_csr_heap_base b) (hw_regs b BL))) < wordToNat (hw_ptTable b (hw_active_module b))'),
            ('Hh', 'wordToNat (hw_csr_heap_base b) + wordToNat (hw_regs b BL) < pow2 WordSz')],
        pre='rewrite (region_ok_of_lt b _ Hloc).',
        close=['close_vector_update ltac:(change MEM_SIZE with 128; '
               'rewrite <- (wordToNat_wplus_bounded _ (hw_csr_heap_base b) (hw_regs b BL) Hh); '
               'rewrite <- wordToNat_trunc7; unfold MemAddrSz; rewrite hwb_vector_nat_at, word64_word32; '
               'reflexivity)']),
    'HEAP_STORE': dict(
        instr='instr_heap_store (wordToNat AL) (wordToNat BL) (wordToNat C)',
        prem=COST_PREM + [
            ('Hloc', 'wordToNat (split1 7 25 (wplus (hw_csr_heap_base b) (hw_regs b AL))) < wordToNat (hw_ptTable b (hw_active_module b))'),
            ('Hh', 'wordToNat (hw_csr_heap_base b) + wordToNat (hw_regs b AL) < pow2 WordSz')],
        pre='rewrite (region_ok_of_lt b _ Hloc).',
        close=['close_mem_update ltac:(rewrite (wordToNat_wplus_bounded _ (hw_csr_heap_base b) (hw_regs b AL) Hh)) '
               'ltac:(rewrite word64_word32; reflexivity)']),
    'CALL': dict(
        instr='instr_call (wordToNat Bw + 256 * wordToNat A) (wordToNat C)',
        prem=COST_PREM + [
            ('Hloc', 'wordToNat (split1 7 25 (hw_regs b hw_sp_idx)) < wordToNat (hw_ptTable b (hw_active_module b))'),
            ('Hsp', 'wordToNat (hw_regs b hw_sp_idx) + 1 < pow2 WordSz'), ('Hsp128', 'wordToNat (hw_regs b hw_sp_idx) < 128')],
        pre='rewrite (region_ok_of_lt b _ Hloc).',
        close=['lazymatch goal with |- wordToNat (evalZeroExtendTrunc _ (combine _ _)) = _ => '
               'rewrite wordToNat_zext16_ext, wordToNat_combine8; reflexivity end',
               'lazymatch goal with |- _ = (fun j => if Nat.eqb j kami_sp_reg then _ else _) => '
               'rewrite kami_sp_reg_15, hwb_vector_nat_sp; unfold word64_add; '
               'refine (eq_trans (hwb_vector_nat_update _ _ _ _ _) _); '
               'rewrite wordToNat_hw_sp_idx, wordToNat_wplus_one_bounded by exact Hsp; '
               'rewrite word64_below_pow2_32 by exact Hsp; '
               'let j := fresh "j" in extensionality j; rewrite Nat.add_1_r; reflexivity end',
               'lazymatch goal with |- _ = (fun j => if Nat.eqb j (hwb_vector_nat _ kami_sp_reg) then _ else _) => '
               'rewrite kami_sp_reg_15, hwb_vector_nat_sp; '
               'refine (eq_trans (hwb_vector_nat_update _ _ _ _ _) _); unfold MemAddrSz; '
               'rewrite wordToNat_trunc7_small by exact Hsp128; '
               'rewrite wordToNat_wplus_one_bounded by exact Hpc; reflexivity end']),
    'RET': dict(
        instr='instr_ret (wordToNat C)',
        prem=COST_PREM + [
            ('Hloc', 'wordToNat (split1 7 25 (wminus (hw_regs b hw_sp_idx) (natToWord WordSz 1))) < wordToNat (hw_ptTable b (hw_active_module b))'),
            ('Hsp1', '1 <= wordToNat (hw_regs b hw_sp_idx)'), ('Hsp128', 'wordToNat (hw_regs b hw_sp_idx) <= 128')],
        pre='rewrite (region_ok_of_lt b _ Hloc). '
            'assert (Esp : wordToNat (wminus (hw_regs b hw_sp_idx) (natToWord WordSz 1)) = wordToNat (hw_regs b hw_sp_idx) - 1) '
            'by (rewrite wordToNat_wminus_le; rewrite ?wordToNat_word1_32; lia). '
            'assert (Esub : word64_sub (wordToNat (hw_regs b hw_sp_idx)) 1 = wordToNat (hw_regs b hw_sp_idx) - 1) '
            'by (apply word64_sub_small; [lia|apply word32_lt_pow2_32]).',
        close=['lazymatch goal with |- wordToNat (hw_mem _ _) = _ => '
               'rewrite kami_sp_reg_15, hwb_vector_nat_sp, Esub, <- Esp; '
               'rewrite <- (wordToNat_trunc7_small (wminus (hw_regs b hw_sp_idx) (natToWord WordSz 1))) by lia; '
               'unfold MemAddrSz; rewrite hwb_vector_nat_at; reflexivity end',
               'lazymatch goal with |- _ = (fun j => if Nat.eqb j kami_sp_reg then _ else _) => '
               'rewrite kami_sp_reg_15, hwb_vector_nat_sp, Esub; '
               'refine (eq_trans (hwb_vector_nat_update _ _ _ _ _) _); '
               'rewrite wordToNat_hw_sp_idx, Esp; reflexivity end']),
    'PNEW': dict(
        instr='instr_pnew region (wordToNat C)', vars=['region : list nat'],
        prem=COST_PREM + [('Hreg', 'List.length (normalize_region region) = wordToNat Bw'),
                          ('Hnext', 'wordToNat (hw_pt_next_id b) < 64'),
                          ('Hpo', 'wordToNat (hw_partition_ops b) + 1 < pow2 WordSz')],
        pre='rewrite (pt_room_one_of_lt b Hnext).',
        close=['lazymatch goal with |- _ = (fun j => if Nat.eqb j (wordToNat (hw_pt_next_id _)) then _ else _) => '
               'rewrite Hreg; refine (eq_trans (hwb_vector_nat_update _ _ _ _ _) _); unfold PTableIdxSz; '
               'rewrite wordToNat_trunc6_small by exact Hnext; rewrite wordToNat_zext8_32; reflexivity end',
               'lazymatch goal with |- wordToNat (wplus (hw_pt_next_id _) _) = _ => '
               'rewrite wordToNat_wplus_7 by lia; lia end',
               'lazymatch goal with |- wordToNat (wplus (hw_partition_ops _) _) = _ => '
               'rewrite wordToNat_wplus_one_bounded by exact Hpo; lia end']),
    'PSPLIT': dict(
        instr='instr_psplit (wordToNat A) left right (wordToNat C)', vars=['left : list nat', 'right : list nat'],
        prem=COST_PREM + [('Hnext', 'wordToNat (hw_pt_next_id b) + 2 <= 64'),
                          ('Hpo', 'wordToNat (hw_partition_ops b) + 1 < pow2 WordSz')],
        pre='rewrite (pt_room_two_of_le b Hnext).',
        close=['lazymatch goal with |- hwb_vector_nat _ = _ => '
               'change PTableSz with 64; unfold PTableIdxSz; '
               'rewrite <- (wordToNat_trunc6_8 A); rewrite hwb_vector_nat_at; '
               'refine (eq_trans (hwb_vector_nat_update _ _ _ _ _) _); '
               'let j := fresh "j" in extensionality j; '
               'rewrite hwb_vector_nat_update; cbv beta; rewrite hwb_vector_nat_update; cbv beta; '
               'rewrite (wordToNat_trunc6_small (hw_pt_next_id b)) by lia; '
               'rewrite (wordToNat_trunc6_small (wplus (hw_pt_next_id b) (natToWord PTableNextIdSz 1))) '
               'by (rewrite wordToNat_wplus_7; lia); '
               'rewrite wordToNat_wplus_7 by lia; '
               'rewrite wordToNat_wminus_le by (rewrite wordToNat_word_half; apply half_le); '
               'rewrite wordToNat_word_half, wordToNat_word0_32, Nat.add_1_r; reflexivity end',
               'lazymatch goal with |- wordToNat (wplus (hw_pt_next_id _) _) = _ => '
               'rewrite wordToNat_wplus_7 by lia; lia end',
               'lazymatch goal with |- wordToNat (wplus (hw_partition_ops _) _) = _ => '
               'rewrite wordToNat_wplus_one_bounded by exact Hpo; lia end']),
    'PMERGE': dict(
        instr='instr_pmerge (wordToNat A) (wordToNat Bw) (wordToNat C)',
        prem=COST_PREM + [('Hnext', 'wordToNat (hw_pt_next_id b) < 64'),
                          ('Hpo', 'wordToNat (hw_partition_ops b) + 1 < pow2 WordSz'),
                          ('Hsum', 'wordToNat (hw_ptTable b (split1 6 2 A)) + wordToNat (hw_ptTable b (split1 6 2 Bw)) < pow2 WordSz')],
        pre='rewrite (pt_room_one_of_lt b Hnext).',
        close=['lazymatch goal with |- hwb_vector_nat _ = _ => '
               'change PTableSz with 64; unfold PTableIdxSz; '
               'rewrite <- (wordToNat_trunc6_8 A), <- (wordToNat_trunc6_8 Bw); rewrite !hwb_vector_nat_at; '
               'refine (eq_trans (hwb_vector_nat_update _ _ _ _ _) _); '
               'let j := fresh "j" in extensionality j; '
               'rewrite hwb_vector_nat_update; cbv beta; rewrite hwb_vector_nat_update; cbv beta; '
               'rewrite (wordToNat_trunc6_small (hw_pt_next_id b)) by lia; '
               'rewrite (wordToNat_wplus_bounded _ _ _ Hsum), wordToNat_word0_32; reflexivity end',
               'lazymatch goal with |- wordToNat (wplus (hw_pt_next_id _) _) = _ => '
               'rewrite wordToNat_wplus_7 by lia; lia end',
               'lazymatch goal with |- wordToNat (wplus (hw_partition_ops _) _) = _ => '
               'rewrite wordToNat_wplus_one_bounded by exact Hpo; lia end']),
    'CHSH_TRIAL': dict(
        instr='instr_chsh_trial (if a1 then 1 else 0) (if a0 then 1 else 0) (if b1 then 1 else 0) (if b0 then 1 else 0) (wordToNat C)',
        prem=COST_PREM + [(f'Hw{k}', f'wordToNat (hw_wc_{k} b) + 1 < pow2 WordSz') for k in
                          ['same_00', 'diff_00', 'same_01', 'diff_01', 'same_10', 'diff_10', 'same_11', 'diff_11']],
        post='destruct a0, a1, b0, b1; cbn [andb negb Bool.eqb Nat.eqb]; snap_projections.',
        close=['lazymatch goal with |- wordToNat (wplus ?x (natToWord _ 1)) = S (wordToNat ?x) => '
               'rewrite wordToNat_wplus_one_bounded by assumption; reflexivity end']),
    'XOR_RANK': dict(
        instr='instr_xor_rank (wordToNat AL) (wordToNat BL) (wordToNat C)',
        prem=COST_PREM,
        close=['close_vector_update ltac:(rewrite <- hw_popcount32_correct, word64_word32; reflexivity)']),
    'HALT': dict(instr='instr_halt (wordToNat C)', prem=COST_PREM, close=[]),
    'CHECKPOINT': dict(instr='instr_checkpoint label (wordToNat C)', vars=['label : string'],
                       prem=COST_PREM, close=[]),
    'WRITE_PORT': dict(instr='instr_write_port chan src (wordToNat C)',
                       vars=['chan : nat', 'src : nat'], prem=COST_PREM, close=[]),
}

PROJ_FIELDS = [f for f in FIELDS if f not in (
    'morph_src_table', 'morph_dst_table', 'morph_coupling_desc_table',
    'morph_identity_table', 'morph_valid_table', 'morph_next_id',
    'coupling_desc_label_table', 'coupling_desc_label_len_table', 'lassert_phase', 'chsh_phase', 'mc_phase')]


def theorem(name, spec):
    low = name.lower()
    fix = spec.get('fix', {})
    bits = BITS.split()
    args = ' '.join(fix.get(x, x) for x in bits)
    binders = ' '.join(x for x in bits if x not in fix)
    vars_ = ' '.join(f'({v})' for v in spec.get('vars', []))
    prem = COMMON_PREM + spec.get('prem', [])
    t = f'Theorem step_{low}_refines : forall {binders} (b : HWB) {vars_},\n'
    t += f'  step_fetched b = {low}_word {args} ->\n'
    t += '  hwb_bianchi b = false -> hw_err b = false -> hw_halted b = false ->\n'
    for _, stmt in prem:
        t += f'  {inline(stmt)} ->\n'
    t += f'  hwb_snapshot (step_next b) = kami_step (hwb_snapshot b) ({inline(spec["instr"])}).\n'
    names = ' '.join(n for n, _ in prem)
    varnames = ' '.join(v.split(':')[0].strip() for v in spec.get('vars', []))
    t += f'Proof.\n  intros {binders} b {varnames} Hf Hb Herr Hhalt {names}.\n'
    t += '  unfold hwb_snapshot at 1.\n'
    rich = ' '.join(f'(step_{low}_{f} {args} b Hf Hb)' for f in [
        'morph_valid_table', 'morph_src_table', 'morph_dst_table',
        'morph_coupling_desc_table', 'morph_identity_table', 'morph_next_id',
        'coupling_desc_label_table', 'coupling_desc_label_len_table'])
    t += f'  rewrite (step_rich_frame b {rich}).\n'
    t += '  rewrite ' + ', '.join(f'(step_{low}_{f} {args} b Hf Hb)' for f in PROJ_FIELDS) + '.\n'
    t += ('  rewrite step_keeps_csr_status, step_keeps_csr_heap_base, '
          'step_keeps_logic_acc, step_keeps_mstatus.\n')
    if 'pre' in spec:
        t += f'  {spec["pre"]}\n'
    t += '  unfold kami_step, kami_write_reg, kami_write_mem, kami_advance_default, kami_advance_info.\n'
    t += '  snap_projections. rewrite ?Herr, ?Hhalt.\n'
    if 'post' in spec:
        t += f'  {inline(spec["post"])}\n'
    t += '  all: apply kami_snapshot_ext; snap_projections.\n'
    closers = ['syntactic', 'close_pc', 'close_mu_cost'] + [inline(c) for c in spec.get('close', [])]
    t += '  all: first [ ' + ' | '.join(closers) + ' ].\n'
    t += 'Qed.\n\n'
    return t


def generate(only=None):
    t = HEADER
    count = 0
    for name, spec in REFINE.items():
        if only and name not in only:
            continue
        t += theorem(name, spec)
        count += 1
    return t, count


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--only', nargs='*')
    parser.add_argument('--out')
    args = parser.parse_args()
    generated, count = generate(args.only)
    target = Path(args.out) if args.out else TARGET
    if args.check:
        if target.read_text() != generated:
            raise SystemExit('StepRefine.v is stale; regenerate it')
    else:
        target.write_text(generated)
    print(f'StepRefine: {count} opcode refinements')
