#!/usr/bin/env python3
"""Generate ChshFsm.v: the CHSH_LASSERT FSM rule's next state as Gallina.

Every LET of [chsh_fsm_decoded] in ThieleCPUCore.v becomes a definition
[chsh_<name> b], literally [evalExpr] of the same Kami expression with the
rule's read variables replaced by boundary fields. Every write becomes a
field equation for [chsh_next], and every register the rule does not write
gets a frame equation. All equations hold by conversion, for every phase; the kernel checks
each conversion at Qed.
"""
import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / 'coq/kami_hw/ChshFsm.v'
CPU = ROOT / 'coq/kami_hw/ThieleCPUCore.v'
RULENEXT = ROOT / 'coq/kami_hw/RuleNext.v'

READ = re.compile(r'^\s*Read (\w+)\s*:\s*(.+?)\s*<-\s*"(\w+)";\s*$')


def strip_comments(s):
    out, depth, i = [], 0, 0
    while i < len(s):
        if s.startswith('(*', i):
            depth += 1; i += 2
        elif s.startswith('*)', i) and depth:
            depth -= 1; i += 2
        else:
            if depth == 0:
                out.append(s[i])
            i += 1
    return ''.join(out)


def parse():
    text = CPU.read_text()
    rule = text[text.index('with Rule "chsh_lassert_fsm" :='):]
    rule = rule[:rule.index('chsh_fsm_decoded ')]
    reads = [READ.match(l).groups() for l in rule.split('\n') if READ.match(l)]
    d = text.index('Definition chsh_fsm_decoded')
    body = text[text.index(':=\n', d) + 3:text.index(')%kami_action.', d)]
    body = strip_comments(body).strip()
    assert body.startswith('(')
    body = body[1:].strip()
    assert body.endswith('Retv')
    stmts = [s.strip() for s in body[:-len('Retv')].split(';') if s.strip()]
    lets, writes = [], []
    for s in stmts:
        s = ' '.join(s.split())
        m = re.match(r'^LET (\w+)\s*(?::\s*(.+?))?\s*<-\s*(.+)$', s)
        if m:
            lets.append((m.group(1), m.group(2) or 'Bool', m.group(3)))
            continue
        m = re.match(r'^Write "(\w+)"\s*<-\s*(.+)$', s)
        assert m, s
        writes.append((m.group(1), m.group(2)))
    return reads, lets, writes


def hw_fields():
    return re.findall(r'^\s*hw_(\w+) := write_value', RULENEXT.read_text(), re.M)


def generate():
    reads, lets, writes = parse()
    env = {}
    for name, kind, reg in reads:
        env[name] = (f'(hw_{reg} b)', kind)
    t = '''(** ChshFsm.v: generated by scripts/generate_chsh_fsm.py.
    The CHSH_LASSERT FSM rule's next state as Gallina: each LET of
    [chsh_fsm_decoded] is [evalExpr] of the same Kami expression over the
    boundary fields, each write is a field equation of [chsh_next], and each
    unwritten register is preserved. All equations hold by conversion. *)
Require Import Kami.Kami Kami.Semantics.
From Coq Require Import String.
From KamiHW Require Import ThieleTypes ThieleCPUCore HWBoundary RuleNext ChshDecoded.

(** The tactic unifier needs minutes for these conversions; the kernel
    checks each one in milliseconds when the proof term is checked at [Qed]. *)
Ltac kernel_refl := match goal with |- ?x = _ => exact_no_check (eq_refl x) end.

'''

    def subst(expr):
        def rep(m):
            v = m.group(1)
            term, kind = env[v]
            return f'(Var type (SyntaxKind ({kind})) {term})'
        return re.sub(r'#(\w+)', rep, expr)

    for name, kind, expr in lets:
        t += (f'Definition chsh_{name} (b : HWB) : type ({kind}) :=\n'
              f'  evalExpr ({subst(expr)})%kami_expr.\n')
        env[name] = (f'(chsh_{name} b)', kind)
    t += '\n'
    written = set()
    for reg, expr in writes:
        written.add(reg)
        t += (f'Lemma chsh_next_{reg} : forall b,\n'
              f'  hw_{reg} (chsh_next b) = evalExpr ({subst(expr)})%kami_expr.\n'
              'Proof. intro b. kernel_refl. Qed.\n')
    t += '\n'
    for f in hw_fields():
        if f in written:
            continue
        t += (f'Lemma chsh_keeps_{f} : forall b, hw_{f} (chsh_next b) = hw_{f} b.\n'
              'Proof. intro b. kernel_refl. Qed.\n')
    return t, len(lets), len(writes)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--out')
    args = parser.parse_args()
    generated, nl, nw = generate()
    target = Path(args.out) if args.out else TARGET
    if args.check:
        if target.read_text() != generated:
            raise SystemExit('ChshFsm.v is stale; regenerate it')
    else:
        target.write_text(generated)
    print(f'ChshFsm: {nl} LET definitions, {nw} write equations')
