#!/usr/bin/env python3
"""Generate StepFields.v: per-opcode field equations of the actual step rule.

For each single-cycle opcode, with the fetched word fixed to its canonical
ISA-v2 format-0 encoding (all operand and cost bits symbolic) and the Bianchi
guard false, every boundary field used by the refinement is stated as an
explicit bit-vector expression. State-dependent guards appear as named
Gallina predicates that mirror the hardware expressions. Each lemma is proved
by reducing the actual decoded action (tactic [hw_field]); nothing is assumed.
"""
import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / 'coq/kami_hw/StepFields.v'

HEADER = '''(** StepFields.v: generated by scripts/generate_step_fields.py.
    Field equations of [step_next] for every single-cycle opcode at its
    canonical format-0 encoding, with symbolic operand and cost bits. Each
    lemma is proved by reducing the actual decoded CPU action. *)
Require Import Kami.Kami Kami.Semantics.
From Coq Require Import String NArith Eqdep_dec Arith.PeanoNat.
From KamiHW Require Import ThieleTypes ThieleCPUCore HWBoundary RuleNext RuleStep
  BoundaryDecoded ActionObservation DispatchObservation StepEval.
Open Scope string_scope.

(** Hardware locality guard: the address lies in the active module's range,
    base <= addr < base + size, as the step rule's [check_bounds] computes it. *)
Definition hw_region_ok (b : HWB) (addr : word MemAddrSz) : bool :=
  evalExpr (check_bounds (Var type (SyntaxKind (Bit MemAddrSz)) addr)
    (Var type (SyntaxKind (Bit WordSz)) (hw_ptBases b (hw_active_module b)))
    (Var type (SyntaxKind (Bit WordSz)) (hw_ptTable b (hw_active_module b)))).

(** PNEW's range checks against the partition table, as in the step rule:
    [hw_pnew_conflict] (some module's range overlaps [a, a + len) without
    being it) and [hw_pnew_present] (some module owns exactly that range). *)
Definition hw_pnew_conflict (b : HWB) (a len : word WordSz) : bool :=
  evalExpr (pt_range_conflict
    (Var type (SyntaxKind (Vector (Bit WordSz) PTableIdxSz)) (hw_ptBases b))
    (Var type (SyntaxKind (Vector (Bit WordSz) PTableIdxSz)) (hw_ptTable b))
    (Var type (SyntaxKind (Bit PTableNextIdSz)) (hw_pt_next_id b))
    (Var type (SyntaxKind (Bit WordSz)) a) (Var type (SyntaxKind (Bit WordSz)) len)).
Definition hw_pnew_present (b : HWB) (a len : word WordSz) : bool :=
  evalExpr (pt_range_present
    (Var type (SyntaxKind (Vector (Bit WordSz) PTableIdxSz)) (hw_ptBases b))
    (Var type (SyntaxKind (Vector (Bit WordSz) PTableIdxSz)) (hw_ptTable b))
    (Var type (SyntaxKind (Bit PTableNextIdSz)) (hw_pt_next_id b))
    (Var type (SyntaxKind (Bit WordSz)) a) (Var type (SyntaxKind (Bit WordSz)) len)).

(** PNEW's memory check, as in the step rule: a nonempty range [a, a + len)
    must end inside data memory (128 words). *)
Definition hw_pnew_in_memory (a len : word WordSz) : bool :=
  evalExpr (!(((Var type (SyntaxKind (Bit WordSz)) len) != $0) &&
              ($$(natToWord WordSz 128) <
               ((Var type (SyntaxKind (Bit WordSz)) a) + (Var type (SyntaxKind (Bit WordSz)) len)))))%kami_expr.

(** PMERGE's adjacency check and the base of the joined range. *)
Definition hw_pmerge_adjacent (b : HWB) (m1 m2 : word PTableIdxSz) : bool :=
  evalExpr (((Var type (SyntaxKind (Bit WordSz)) (hw_ptTable b m1)) == $0) ||
            ((Var type (SyntaxKind (Bit WordSz)) (hw_ptTable b m2)) == $0) ||
            ((ext33 (Var type (SyntaxKind (Bit WordSz)) (hw_ptBases b m1)) +
              ext33 (Var type (SyntaxKind (Bit WordSz)) (hw_ptTable b m1))) ==
             ext33 (Var type (SyntaxKind (Bit WordSz)) (hw_ptBases b m2))) ||
            ((ext33 (Var type (SyntaxKind (Bit WordSz)) (hw_ptBases b m2)) +
              ext33 (Var type (SyntaxKind (Bit WordSz)) (hw_ptTable b m2))) ==
             ext33 (Var type (SyntaxKind (Bit WordSz)) (hw_ptBases b m1))))%kami_expr.
Definition hw_pmerge_base (b : HWB) (m1 m2 : word PTableIdxSz) : word WordSz :=
  evalExpr (IF ((Var type (SyntaxKind (Bit WordSz)) (hw_ptTable b m1)) == $0)
            then Var type (SyntaxKind (Bit WordSz)) (hw_ptBases b m2)
            else (IF ((Var type (SyntaxKind (Bit WordSz)) (hw_ptTable b m2)) == $0)
            then Var type (SyntaxKind (Bit WordSz)) (hw_ptBases b m1)
            else (IF ((ext33 (Var type (SyntaxKind (Bit WordSz)) (hw_ptBases b m1)) +
                       ext33 (Var type (SyntaxKind (Bit WordSz)) (hw_ptTable b m1))) ==
                      ext33 (Var type (SyntaxKind (Bit WordSz)) (hw_ptBases b m2)))
                  then Var type (SyntaxKind (Bit WordSz)) (hw_ptBases b m1)
                  else Var type (SyntaxKind (Bit WordSz)) (hw_ptBases b m2))))%kami_expr.

(** The morphism valid table after PSPLIT or PMERGE removes modules [m1]
    and [m2]: every entry naming either loses its valid bit. *)
Definition hw_morph_cascade (b : HWB) (m1 m2 : word PTableIdxSz) : word MorphTableIdxSz -> bool :=
  evalExpr (morph_cascade
    (Var type (SyntaxKind (Vector Bool MorphTableIdxSz)) (hw_morph_valid_table b))
    (Var type (SyntaxKind (Vector (Bit PTableIdxSz) MorphTableIdxSz)) (hw_morph_src_table b))
    (Var type (SyntaxKind (Vector (Bit PTableIdxSz) MorphTableIdxSz)) (hw_morph_dst_table b))
    (Var type (SyntaxKind (Bit PTableIdxSz)) m1) (Var type (SyntaxKind (Bit PTableIdxSz)) m2)
    MorphTableSz).

(** Partition-table capacity guards, as in the step rule. *)
Definition hw_pt_room_one (b : HWB) : bool :=
  if wlt_dec (hw_pt_next_id b) (natToWord PTableNextIdSz 64) then true else false.
Definition hw_pt_room_two (b : HWB) : bool :=
  if wlt_dec (natToWord PTableNextIdSz 64) (wplus (hw_pt_next_id b) (natToWord PTableNextIdSz 2))
  then false else true.

(** PDISCOVER declared-bound guard. *)
Definition hw_nfi_ok (cost opb : word 8) : bool :=
  if wlt_dec (zext cost 24) (zext opb 24) then false else true.

(** Stack pointer register index 15. *)
Definition hw_sp_idx : word RegIdxSz := bits4 true true true true.

(** The step rule's 32-bit tree popcount. *)
Definition hw_popcount32 (v : word WordSz) : word WordSz :=
  let m1 := WO~0~1~0~1~0~1~0~1~0~1~0~1~0~1~0~1~0~1~0~1~0~1~0~1~0~1~0~1~0~1~0~1 in
  let s1a := wand v m1 in
  let s1b := wand (wrshift v (wordToNat (WO~0~0~0~0~0~1))) m1 in
  let p2 := wplus s1a s1b in
  let m2 := WO~0~0~1~1~0~0~1~1~0~0~1~1~0~0~1~1~0~0~1~1~0~0~1~1~0~0~1~1~0~0~1~1 in
  let n1 := wand p2 m2 in
  let n2 := wand (wrshift p2 (wordToNat (WO~0~0~0~0~1~0))) m2 in
  let p4 := wplus n1 n2 in
  let m3 := WO~0~0~0~0~1~1~1~1~0~0~0~0~1~1~1~1~0~0~0~0~1~1~1~1~0~0~0~0~1~1~1~1 in
  let q1 := wand p4 m3 in
  let q2 := wand (wrshift p4 (wordToNat (WO~0~0~0~1~0~0))) m3 in
  let p8 := wplus q1 q2 in
  let m4 := WO~0~0~0~0~0~0~0~0~1~1~1~1~1~1~1~1~0~0~0~0~0~0~0~0~1~1~1~1~1~1~1~1 in
  let h1 := wand p8 m4 in
  let h2 := wand (wrshift p8 (wordToNat (WO~0~0~1~0~0~0))) m4 in
  let p16 := wplus h1 h2 in
  let m5 := WO~0~0~0~0~0~0~0~0~0~0~0~0~0~0~0~0~1~1~1~1~1~1~1~1~1~1~1~1~1~1~1~1 in
  let r1 := wand p16 m5 in
  let r2 := wand (wrshift p16 (wordToNat (WO~0~1~0~0~0~0))) m5 in
  wplus r1 r2.

'''

FIELDS = ['pc', 'mu', 'err', 'halted', 'regs', 'mem', 'error_code', 'cert_addr',
          'partition_ops', 'mdl_ops', 'info_gain', 'mu_tensor', 'module_tensors',
          'ptTable', 'ptBases', 'pt_next_id', 'certified',
          'wc_same_00', 'wc_diff_00', 'wc_same_01', 'wc_diff_01',
          'wc_same_10', 'wc_diff_10', 'wc_same_11', 'wc_diff_11',
          'morph_src_table', 'morph_dst_table', 'morph_coupling_desc_table',
          'morph_identity_table', 'morph_valid_table', 'morph_next_id',
          'coupling_desc_label_table', 'coupling_desc_label_len_table',
          'lassert_phase', 'chsh_phase', 'mc_phase']

PC1 = 'wplus (hw_pc b) (natToWord WordSz 1)'
MU = 'wplus (hw_mu b) (zext C 24)'
MU1 = 'wplus (wplus (hw_mu b) (zext C 24)) (natToWord WordSz 1)'
MUBITS = 'wplus (wplus (wplus (hw_mu b) (zext Bw 24)) (zext C 24)) (natToWord WordSz 1)'
SP = 'hw_regs b hw_sp_idx'


def default(field):
    return {
        'pc': PC1, 'mu': MU, 'err': 'false', 'halted': 'false',
        'lassert_phase': 'natToWord 3 0', 'chsh_phase': 'natToWord 5 0',
        'mc_phase': 'natToWord 4 0',
    }.get(field, f'hw_{field} b')


def upd(vec, idx, val):
    return f'(fun w => if weq w ({idx}) then {val} else {vec} w)'


def regs(val, idx='AL'):
    return upd('hw_regs b', idx, val)


def locality(guard, success):
    """Success fields when [guard] holds; the specified locality fault otherwise."""
    fault = {'pc': 'hw_trap_vector b', 'halted': 'true', 'err': 'true',
             'error_code': 'ERR_LOCALITY_VAL'}
    out = {}
    for f in set(success) | set(fault):
        s = success.get(f, default(f))
        x = fault.get(f, default(f))
        out[f] = s if s == x else f'if {guard} then {s} else {x}'
    return out


def partition(guard, success):
    """Success fields when [guard] (a capacity test) holds; the partition
    capacity fault otherwise: trap, err, the fault word, cost charged."""
    fault = {'pc': 'hw_trap_vector b', 'err': 'true',
             'error_code': 'ERR_PARTITION_VAL',
             'partition_ops': 'wplus (hw_partition_ops b) (natToWord WordSz 1)'}
    out = {}
    for f in set(success) | set(fault):
        s = success.get(f, default(f))
        x = fault.get(f, default(f))
        out[f] = s if s == x else f'if {guard} then {s} else {x}'
    return out


def overlap(guard, success):
    """Success fields when [guard] (a partition-overlap test) is false; the
    partition-overlap fault otherwise: trap, err, the fault word, cost charged."""
    fault = {'pc': 'hw_trap_vector b', 'err': 'true',
             'error_code': 'ERR_PARTITION_OVERLAP_VAL',
             'partition_ops': 'wplus (hw_partition_ops b) (natToWord WordSz 1)'}
    out = {}
    for f in set(success) | set(fault):
        s = success.get(f, default(f))
        x = fault.get(f, default(f))
        out[f] = s if s == x else f'if {guard} then {x} else {s}'
    return out


def nest(out):
    """Parenthesize every conditional field so it can sit inside another."""
    return {f: (f'({v})' if v.startswith('if ') else v) for f, v in out.items()}


def chsh_trial():
    same = '(Bool.eqb b0 b1)'
    buckets = {'00': '(andb (negb a1) (negb a0))', '01': '(andb (negb a1) a0)',
               '10': '(andb a1 (negb a0))', '11': '(andb a1 a0)'}
    out = {}
    for k, cond in buckets.items():
        out[f'wc_same_{k}'] = (f'if andb {cond} {same} then wplus (hw_wc_same_{k} b) '
                               f'(natToWord WordSz 1) else hw_wc_same_{k} b')
        out[f'wc_diff_{k}'] = (f'if andb {cond} (negb {same}) then wplus (hw_wc_diff_{k} b) '
                               f'(natToWord WordSz 1) else hw_wc_diff_{k} b')
    return out


def psplit():
    pid = 'split1 6 2 A'
    orig = f'hw_ptTable b ({pid})'
    base = f'hw_ptBases b ({pid})'
    left = f'wrshift ({orig}) (wordToNat (WO~0~0~0~0~1))'
    right = f'wminus ({orig}) ({left})'
    s1 = 'split1 6 1 (hw_pt_next_id b)'
    s2 = 'split1 6 1 (wplus (hw_pt_next_id b) (natToWord PTableNextIdSz 1))'
    t0 = upd('hw_ptTable b', pid, 'natToWord WordSz 0')
    t1 = upd(t0, s1, left)
    t2 = upd(t1, s2, right)
    u0 = upd('hw_ptBases b', pid, 'natToWord WordSz 0')
    u1 = upd(u0, s1, base)
    u2 = upd(u1, s2, f'wplus ({base}) ({left})')
    return partition('hw_pt_room_two b', {
        'ptTable': t2,
        'ptBases': u2,
        'pt_next_id': 'wplus (hw_pt_next_id b) (natToWord PTableNextIdSz 2)',
        'morph_valid_table': f'hw_morph_cascade b ({pid}) ({pid})',
        'partition_ops': 'wplus (hw_partition_ops b) (natToWord WordSz 1)'})


def pmerge():
    m1 = 'split1 6 2 A'
    m2 = 'split1 6 2 Bw'
    merged = f'wplus (hw_ptTable b ({m1})) (hw_ptTable b ({m2}))'
    slot = 'split1 6 1 (hw_pt_next_id b)'
    t0 = upd('hw_ptTable b', m1, 'natToWord WordSz 0')
    t1 = upd(t0, m2, 'natToWord WordSz 0')
    t2 = upd(t1, slot, merged)
    u0 = upd('hw_ptBases b', m1, 'natToWord WordSz 0')
    u1 = upd(u0, m2, 'natToWord WordSz 0')
    u2 = upd(u1, slot, f'hw_pmerge_base b ({m1}) ({m2})')
    inner = overlap(f'negb (hw_pmerge_adjacent b ({m1}) ({m2}))', {
        'ptTable': t2,
        'ptBases': u2,
        'pt_next_id': 'wplus (hw_pt_next_id b) (natToWord PTableNextIdSz 1)',
        'morph_valid_table': f'hw_morph_cascade b ({m1}) ({m2})',
        'partition_ops': 'wplus (hw_partition_ops b) (natToWord WordSz 1)'})
    return partition('hw_pt_room_one b', nest(inner))


def pnew():
    a, n = 'zext A 24', 'zext Bw 24'
    present = f'hw_pnew_present b ({a}) ({n})'
    slot = 'split1 6 1 (hw_pt_next_id b)'
    inner = overlap(f'hw_pnew_conflict b ({a}) ({n})', {
        'ptTable': f'if {present} then hw_ptTable b else {upd("hw_ptTable b", slot, n)}',
        'ptBases': f'if {present} then hw_ptBases b else {upd("hw_ptBases b", slot, a)}',
        'pt_next_id': (f'if {present} then hw_pt_next_id b else '
                       'wplus (hw_pt_next_id b) (natToWord PTableNextIdSz 1)'),
        'partition_ops': 'wplus (hw_partition_ops b) (natToWord WordSz 1)'})
    in_memory = partition(f'hw_pnew_in_memory ({a}) ({n})', nest(inner))
    return partition('hw_pt_room_one b', nest(in_memory))


def load_addr(base):
    return f'split1 7 25 ({base})'


OPS = {
    'LOAD_IMM': {'regs': regs('zext Bw 24')},
    'XFER': {'regs': regs('hw_regs b BL')},
    'ADD': {'regs': regs('wplus (hw_regs b BH) (hw_regs b BL)')},
    'SUB': {'regs': regs('wminus (hw_regs b BH) (hw_regs b BL)')},
    'AND': {'regs': regs('wand (hw_regs b BH) (hw_regs b BL)')},
    'OR': {'regs': regs('wor (hw_regs b BH) (hw_regs b BL)')},
    'MUL': {'regs': regs('wmult (hw_regs b BH) (hw_regs b BL)')},
    'SHL': {'regs': regs('wlshift (hw_regs b BH) (wordToNat (hw_regs b BL))')},
    'SHR': {'regs': regs('wrshift (hw_regs b BH) (wordToNat (hw_regs b BL))')},
    'LUI': {'regs': regs('wlshift (zext Bw 24) (wordToNat (natToWord WordSz 8))')},
    'XOR_LOAD': {'regs': regs('hw_mem b (split1 7 1 Bw)')},
    'XOR_ADD': {'regs': regs('wxor (hw_regs b AL) (hw_regs b BL)')},
    'XOR_SWAP': {'regs': upd(upd('hw_regs b', 'AL', 'hw_regs b BL'), 'BL', 'hw_regs b AL')},
    'XOR_RANK': {'regs': regs('hw_popcount32 (hw_regs b BL)')},
    'JUMP': {'pc': 'evalZeroExtendTrunc WordSz (combine Bw A)'},
    'JNEZ': {'pc': f'if weq (hw_regs b AL) (natToWord WordSz 0) then {PC1} '
                   'else evalZeroExtendTrunc WordSz Bw'},
    'HALT': {'halted': 'true'},
    'MDLACC': {'mdl_ops': 'wplus (hw_mdl_ops b) (natToWord WordSz 1)'},
    'LJOIN': {'mu': MU1},
    'CHECKPOINT': {},
    'WRITE_PORT': {},
    'READ_PORT': {'regs': regs('natToWord WordSz 0'), 'mu': MUBITS},
    'EMIT': {'info_gain': 'wplus (hw_info_gain b) (zext Bw 24)', 'mu': MUBITS},
    'REVEAL': {'mu': MUBITS,
               'mu_tensor': upd('hw_mu_tensor b', 'AL',
                                'wplus (hw_mu_tensor b AL) (zext Bw 24)')},
    'CERTIFY': {'mu': MU1, 'certified': 'true'},
    'TENSOR_SET': {'module_tensors': upd('hw_module_tensors b', 'AH',
                                         upd('hw_module_tensors b AH', 'AL', 'zext Bw 24'))},
    'TENSOR_GET': {'regs': regs('hw_module_tensors b BH BL')},
    'PDISCOVER': {f: (f'if hw_nfi_ok C Bw then {s} else {x}' if s != x else s)
                  for f, s, x in [
                      ('info_gain', 'wplus (hw_info_gain b) (zext Bw 24)', 'hw_info_gain b'),
                      ('pc', PC1, 'hw_trap_vector b'), ('halted', 'false', 'true'),
                      ('err', 'false', 'true'),
                      ('error_code', 'hw_error_code b', 'ERR_LOGIC_VAL'),
                      ('mu', MU, 'hw_mu b')]},
    'LOAD': locality(f'hw_region_ok b ({load_addr("hw_regs b BL")})',
                     {'regs': regs(f'hw_mem b ({load_addr("hw_regs b BL")})')}),
    'STORE': locality(f'hw_region_ok b ({load_addr("hw_regs b AL")})',
                      {'mem': upd('hw_mem b', load_addr('hw_regs b AL'), 'hw_regs b BL')}),
    'HEAP_LOAD': locality(
        f'hw_region_ok b ({load_addr("wplus (hw_csr_heap_base b) (hw_regs b BL)")})',
        {'regs': regs(f'hw_mem b ({load_addr("wplus (hw_csr_heap_base b) (hw_regs b BL)")})')}),
    'HEAP_STORE': locality(
        f'hw_region_ok b ({load_addr("wplus (hw_csr_heap_base b) (hw_regs b AL)")})',
        {'mem': upd('hw_mem b', load_addr('wplus (hw_csr_heap_base b) (hw_regs b AL)'),
                    'hw_regs b BL')}),
    'CALL': locality(f'hw_region_ok b ({load_addr(SP)})', {
        'pc': 'evalZeroExtendTrunc WordSz (combine Bw A)',
        'regs': regs(f'wplus ({SP}) (natToWord WordSz 1)', 'hw_sp_idx'),
        'mem': upd('hw_mem b', load_addr(SP), PC1)}),
    'RET': locality(
        f'hw_region_ok b ({load_addr(f"wminus ({SP}) (natToWord WordSz 1)")})', {
            'pc': f'hw_mem b ({load_addr(f"wminus ({SP}) (natToWord WordSz 1)")})',
            'regs': regs(f'wminus ({SP}) (natToWord WordSz 1)', 'hw_sp_idx')}),
    'PNEW': pnew(),
    'PSPLIT': psplit(),
    'PMERGE': pmerge(),
    'CHSH_TRIAL': chsh_trial(),
}

BITS = ('a0 a1 a2 a3 a4 a5 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 '
        'c0 c1 c2 c3 c4 c5 c6 c7')
NAMES = {
    'AL': '(bits4 a0 a1 a2 a3)', 'AH': '(bits4 a4 a5 a6 a7)',
    'BL': '(bits4 b0 b1 b2 b3)', 'BH': '(bits4 b4 b5 b6 b7)',
    'Bw': '(bits8 b0 b1 b2 b3 b4 b5 b6 b7)', 'A': '(bits8 a0 a1 a2 a3 a4 a5 a6 a7)',
    'C': '(bits8 c0 c1 c2 c3 c4 c5 c6 c7)',
}


def inline(expr):
    import re
    return re.sub(r'\b(AL|AH|BL|BH|Bw|A|C)\b', lambda m: NAMES[m.group(1)], expr)


def generate(only=None):
    t = HEADER
    count = 0
    for name, spec in OPS.items():
        if only and name not in only:
            continue
        low = name.lower()
        t += (f'Definition {low}_word ({BITS} : bool) : word InstrSz :=\n'
              f'  legacy_word OP_{name} {inline("A")} {inline("Bw")} {inline("C")}.\n')
        for f in FIELDS:
            rhs = inline(spec.get(f, default(f)))
            t += (f'Lemma step_{low}_{f} : forall {BITS} b,\n'
                  f'  step_fetched b = {low}_word {BITS} -> hwb_bianchi b = false ->\n'
                  f'  hw_{f} (step_next b) = {rhs}.\n'
                  'Proof. hw_field. Qed.\n')
            count += 1
        t += '\n'
    return t, count


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--only', nargs='*')
    parser.add_argument('--out')
    args = parser.parse_args()
    generated, count = generate(args.only)
    target = Path(args.out) if args.out else TARGET
    if args.check:
        if target.read_text() != generated:
            raise SystemExit('StepFields.v is stale; regenerate it')
    else:
        target.write_text(generated)
    print(f'StepFields: {count} field equations')
