#!/usr/bin/env python3
"""Generate or check the canonical RTL pipeline provenance manifest.

This is not a proof of PP.ml or BSC semantics. It is a tight provenance lock:
the checked RTL must be byte-identical to the generated synthesis RTL, and the
intermediate canonical extraction/printer/BSV/Verilog artifacts must be present,
non-empty, hashed, and wired through the declared canonical Coq entrypoints.
"""

from __future__ import annotations

import argparse
import difflib
import hashlib
import json
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUT = REPO_ROOT / "artifacts" / "rtl_pipeline_manifest.json"

PIPELINE_FILES = [
    "coq/kami_hw/CanonicalCPUProof.v",
    "coq/kami_hw/VerilogSemantics.v",
    "coq/kami_hw/KamiExtraction.v",
    "coq/kami_hw/ThieleCPUCore.v",
    "coq/kami_hw/ThieleCPUBusTop.v",
    "coq/kami_hw/ThieleTypes.v",
    "coq/kernel/hardware_bridge/VerilogRTLCorrespondence.v",
    "scripts/kami_extract.sh",
    "scripts/bsv_regfile_transform.py",
    "scripts/verilog_synth_transform.py",
    "vendor/kami/Kami/Ext/Ocaml/PP.ml",
    "vendor/kami/Kami/Ext/Ocaml/Main.ml",
    "build/kami_hw/Target.ml",
    "build/kami_hw/Target.mli",
    "build/kami_hw/PP.ml",
    "build/kami_hw/Main.ml",
    "build/kami_hw/thiele_hw.bsv",
    "build/kami_hw/thiele_hw_clean.bsv",
    "build/kami_hw/mkModule1.v",
    "build/kami_hw/mkModule1_synth.v",
    "thielecpu/hardware/rtl/RegFile.v",
    "thielecpu/hardware/rtl/thiele_cpu_kami.v",
]


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _rel_record(rel_path: str) -> dict[str, Any]:
    path = REPO_ROOT / rel_path
    if not path.exists():
        raise SystemExit(f"Required RTL pipeline file missing: {rel_path}")
    if not path.is_file():
        raise SystemExit(f"RTL pipeline path is not a file: {rel_path}")
    size = path.stat().st_size
    if size <= 0:
        raise SystemExit(f"RTL pipeline file is empty: {rel_path}")
    return {
        "path": rel_path,
        "sha256": _sha256(path),
        "size_bytes": size,
    }


def _text(rel_path: str) -> str:
    return (REPO_ROOT / rel_path).read_text(encoding="utf-8", errors="replace")


def _same_bytes(left: str, right: str) -> bool:
    return (REPO_ROOT / left).read_bytes() == (REPO_ROOT / right).read_bytes()


def _contains(rel_path: str, needle: str) -> bool:
    return needle in _text(rel_path)


def build_manifest() -> dict[str, Any]:
    invariants = {
        "canonical_cpu_module_declared": _contains(
            "coq/kami_hw/CanonicalCPUProof.v",
            "Definition canonical_cpu_module := thieleBusTopB.",
        ),
        "canonical_cpu_module_generated_in_coq": _contains(
            "coq/kami_hw/CanonicalCPUProof.v",
            "canonical_cpu_module = ModulesSToBModules thieleBusTopS",
        ),
        "targetB_declared_as_printer_entrypoint": _contains(
            "coq/kami_hw/CanonicalCPUProof.v",
            "Definition targetB (_ : nat) := canonical_cpu_module.",
        ),
        "kami_extraction_imports_canonical_source": _contains(
            "coq/kami_hw/KamiExtraction.v",
            "CanonicalCPUProof",
        ),
        "target_ml_exports_canonical_cpu_module": _contains(
            "build/kami_hw/Target.ml",
            "let canonical_cpu_module =",
        ),
        "target_ml_exports_targetB": _contains(
            "build/kami_hw/Target.ml",
            "let targetB _ =",
        ),
        "main_ml_drives_pp_through_targetB": _contains(
            "build/kami_hw/Main.ml",
            "match targetB iAddrSize with",
        ),
        "raw_verilog_is_bsc_generated": _contains(
            "build/kami_hw/mkModule1.v",
            "Generated by Bluespec Compiler",
        ),
        "raw_verilog_has_mkModule1_top": _contains(
            "build/kami_hw/mkModule1.v",
            "module mkModule1",
        ),
        "synth_verilog_has_mkModule1_top": _contains(
            "build/kami_hw/mkModule1_synth.v",
            "module mkModule1",
        ),
        "tracked_rtl_has_mkModule1_top": _contains(
            "thielecpu/hardware/rtl/thiele_cpu_kami.v",
            "module mkModule1",
        ),
        "tracked_rtl_matches_generated_synth_verilog": _same_bytes(
            "build/kami_hw/mkModule1_synth.v",
            "thielecpu/hardware/rtl/thiele_cpu_kami.v",
        ),
    }

    return {
        "schema_version": 1,
        "manifest_kind": "canonical_rtl_pipeline_provenance",
        "source_of_truth": {
            "coq_canonical_module": "coq/kami_hw/CanonicalCPUProof.v:canonical_cpu_module",
            "coq_generator_theorem": "coq/kami_hw/CanonicalCPUProof.v:canonical_cpu_module_from_source",
            "printer_entrypoint": "coq/kami_hw/CanonicalCPUProof.v:targetB",
        },
        "pipeline": [
            "Coq CanonicalCPUProof.v",
            "Coq extraction to build/kami_hw/Target.ml",
            "Kami PP.ml/Main.ml to Bluespec",
            "project BSV transform",
            "BSC to raw Verilog",
            "project Verilog synthesis transform",
            "tracked RTL thiele_cpu_kami.v",
        ],
        "files": [_rel_record(path) for path in PIPELINE_FILES],
        "invariants": invariants,
        "boundary_statement": {
            "closed_by_this_manifest": [
                "canonical source wiring",
                "intermediate artifact presence",
                "intermediate artifact hash pinning",
                "tracked RTL identity with generated synthesis RTL",
            ],
            "still_named_trust_boundary": (
                "Semantic preservation of PP.ml, project text transforms, BSC, "
                "and the generated Verilog backend remains outside Coq."
            ),
            "trusted_boundary": (
                "coq/kernel/hardware_bridge/VerilogRTLCorrespondence.v:bsc_kami_compilation_trusted"
            ),
        },
    }


def _write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default=str(DEFAULT_OUT), help="Manifest output path.")
    parser.add_argument("--check", action="store_true", help="Compare generated manifest with --out.")
    args = parser.parse_args()

    out = Path(args.out)
    if not out.is_absolute():
        out = (REPO_ROOT / out).resolve()

    payload = build_manifest()
    if not all(payload["invariants"].values()):
        failed = [name for name, ok in payload["invariants"].items() if not ok]
        raise SystemExit("RTL pipeline invariants failed:\n" + "\n".join(f"  {name}" for name in failed))

    if args.check:
        if not out.exists():
            raise SystemExit(f"RTL pipeline manifest missing: {out}")
        expected = json.dumps(payload, indent=2, sort_keys=True) + "\n"
        current = out.read_text(encoding="utf-8")
        if current != expected:
            diff = "\n".join(
                difflib.unified_diff(
                    current.splitlines(),
                    expected.splitlines(),
                    fromfile=str(out),
                    tofile="fresh rtl pipeline manifest",
                    lineterm="",
                )
            )
            raise SystemExit("RTL pipeline manifest is stale:\n" + diff)
        return 0

    _write_json(out, payload)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
