#!/usr/bin/env python3
"""Generate StepFieldsMorph.v: field equations of the actual step rule for the
single-cycle morph opcodes MORPH_ID, MORPH_DELETE, MORPH_ASSERT, MORPH_GET
and MORPH_TENSOR, which always faults.

Each opcode is covered at its legacy format-0 encoding and at the extended
encoding the assembler emits (format 3, or format 5 for MORPH_ASSERT, flags 4,
ext1 zero), with all operand, cost and ext0 bits symbolic. Morph-table,
module-presence and coupling-descriptor guards appear as named Gallina
predicates that mirror the hardware expressions; fault branch values are
stated too. Each lemma is proved by reducing the actual decoded action.
"""
import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'scripts'))
from generate_step_fields import FIELDS, NAMES, BITS, default, upd  # noqa: E402

TARGET = ROOT / 'coq/kami_hw/StepFieldsMorph.v'

# The projection list of [hw_field], taken from StepEval.v so both tactics agree.
CBN = next(l.strip() for l in (ROOT / 'coq/kami_hw/StepEval.v').read_text().splitlines()
           if l.strip().startswith('cbn [hwb_after hw_pc'))
EBITS = ' '.join(f'e{i}' for i in range(32))
MNAMES = dict(NAMES, E=f'(bits32 {EBITS})', SEL='(bits2 e0 e1)')

HEADER = '''(** StepFieldsMorph.v: generated by scripts/generate_step_fields_morph.py.
    Field equations of [step_next] for MORPH_ID, MORPH_DELETE, MORPH_ASSERT,
    MORPH_GET and MORPH_TENSOR at their legacy and extended encodings, with symbolic
    operand, cost and ext0 bits. Each lemma is proved by reducing the actual
    decoded CPU action. *)
Require Import Kami.Kami Kami.Semantics.
From Coq Require Import String NArith Eqdep_dec Arith.PeanoNat.
From KamiHW Require Import ThieleTypes ThieleCPUCore HWBoundary RuleNext RuleStep
  BoundaryDecoded ActionObservation DispatchObservation StepEval StepFields.
Open Scope string_scope.

Definition bits32 (''' + EBITS + ''' : bool) : word 32 :=
  ''' + ''.join(f'WS e{i} (' for i in range(32)) + 'WO' + ')' * 32 + '''.

Definition bits2 (x0 x1 : bool) : word 2 := WS x0 (WS x1 WO).

(** Version 2, format [fmt], flags 4 (subtype 0, descriptor kind 0, inline
    length 4), ext1 zero, extension word [e]; low lane as in [legacy_word]. *)
Definition rich_word (fmt : N) (op a b c : word 8) (e : word 32) : word InstrSz :=
  combine c (combine b (combine a (combine op (combine e
    (NToWord 64 (N.lor (N.shiftl 2 56) (N.lor (N.shiftl fmt 48) (N.shiftl 4 32)))))))).

(** Extended encodings leave comparisons between constants (the inline
    length against 8) folded, because [hw_lazy] keeps [wlt_dec] opaque for
    the symbolic guards. Decide each closed comparison, then continue as
    [hw_field]. *)
Ltac drop_closed_wlt :=
  repeat match goal with
  | |- context [wlt_dec ?x ?y] =>
      let v := eval vm_compute in (Nat.ltb (wordToNat x) (wordToNat y)) in
      lazymatch v with
      | true => let Hc := fresh "Hc" in
          destruct (wlt_dec x y) as [Hc|Hc];
          [clear Hc | exfalso; apply Hc; apply lt_wlt; apply Nat.ltb_lt; vm_compute; reflexivity]
      | false => let Hc := fresh "Hc" in
          destruct (wlt_dec x y) as [Hc|Hc];
          [exfalso; apply wlt_lt, Nat.ltb_lt in Hc; vm_compute in Hc; discriminate Hc | clear Hc]
      end
  end.

Ltac hw_field_rich :=
  intros;
  match goal with H : step_fetched _ = _ |- _ => rewrite (step_next_fetched _ _ H) end;
  ''' + CBN + '''
  unfold hwb_decoded;
  repeat match goal with H : hwb_bianchi _ = _ |- _ => rewrite H end;
  hw_lazy; clear_concrete_word_casts; hw_lazy; drop_closed_wlt; hw_lazy; hw_split_close.

(** Morph allocation room: [morph_next_id] below 16. *)
Definition hw_morph_room (b : HWB) : bool :=
  if wlt_dec (hw_morph_next_id b) (natToWord MorphTableNextIdSz 16) then true else false.

(** Module presence: nonzero partition-table size. *)
Definition hw_module_present (b : HWB) (m : word PTableIdxSz) : bool :=
  if weq (hw_ptTable b m) (natToWord WordSz 0) then false else true.

(** A morph slot is live when it is below [morph_next_id] and marked valid. *)
Definition hw_morph_live (b : HWB) (i : word MorphTableIdxSz) : bool :=
  if wlt_dec (zext i 1) (hw_morph_next_id b) then hw_morph_valid_table b i else false.

(** A coupling descriptor reference is acceptable to MORPH_GET when it is the
    empty descriptor 0, or below the next id and marked valid. *)
Definition hw_coupling_ref_ok (b : HWB) (d : word DescIdxSz) : bool :=
  if weq d (natToWord DescIdxSz 0) then true
  else if wlt_dec (zext d 1) (hw_coupling_desc_next_id b)
       then hw_coupling_desc_valid_table b d else false.

(** Coupling-descriptor allocation room: [coupling_desc_next_id] below 16. *)
Definition hw_desc_room (b : HWB) : bool :=
  if wlt_dec (hw_coupling_desc_next_id b) (natToWord DescTableNextIdSz 16) then true else false.

(** MORPH_GET readout for a selector. *)
Definition hw_morph_get_value (b : HWB) (i : word MorphTableIdxSz) (sel : word 2) : word WordSz :=
  if weq sel (natToWord 2 0) then zext (hw_morph_src_table b i) 26
  else if weq sel (natToWord 2 1) then zext (hw_morph_dst_table b i) 26
  else if weq sel (natToWord 2 2) then
    zext (if weq (hw_morph_coupling_desc_table b i) (natToWord DescIdxSz 0)
          then natToWord CouplingPairCountSz 0
          else hw_coupling_desc_count_table b (hw_morph_coupling_desc_table b i)) 27
  else if hw_morph_identity_table b i then natToWord WordSz 1 else natToWord WordSz 0.

'''

MU1 = 'wplus (wplus (hw_mu b) (zext C 24)) (natToWord WordSz 1)'
SLOT = 'split1 4 1 (hw_morph_next_id b)'


def guarded(chain, leaf):
    """chain: list of (guard, fault_fields); leaf: success fields.
    The result for each field nests the guards in order."""
    fields = set(leaf)
    for _, fault in chain:
        fields |= set(fault)
    out = {}
    for f in fields:
        def value(k):
            if k == len(chain):
                return leaf.get(f, default(f))
            g, fault = chain[k]
            s = value(k + 1)
            x = fault.get(f, default(f))
            return s if s == x else f'if {g} then {s} else {x}'
        out[f] = value(0)
    return out



NOT_FOUND = {'err': 'true', 'error_code': 'ERR_MORPH_NOT_FOUND'}
COUPLING = {'err': 'true', 'error_code': 'ERR_COUPLING_INVALID'}
OVERFLOW = {'pc': 'hw_trap_vector b', 'err': 'true', 'error_code': 'ERR_TABLE_OVERFLOW'}


def morph_id():
    mod = 'split1 6 2 Bw'
    return guarded(
        [('hw_morph_room b', OVERFLOW), (f'hw_module_present b ({mod})', COUPLING)],
        {'regs': upd('hw_regs b', 'AL', f'zext ({SLOT}) 28'),
         'morph_src_table': upd('hw_morph_src_table b', SLOT, mod),
         'morph_dst_table': upd('hw_morph_dst_table b', SLOT, mod),
         'morph_coupling_desc_table': upd('hw_morph_coupling_desc_table b', SLOT,
                                          'natToWord DescIdxSz 0'),
         'morph_identity_table': upd('hw_morph_identity_table b', SLOT, 'true'),
         'morph_valid_table': upd('hw_morph_valid_table b', SLOT, 'true'),
         'morph_next_id': 'wplus (hw_morph_next_id b) (natToWord MorphTableNextIdSz 1)'})


def morph_delete():
    return guarded([('hw_morph_live b AL', NOT_FOUND)],
                   {'morph_valid_table': upd('hw_morph_valid_table b', 'AL', 'false')})


def morph_assert(cert):
    spec = guarded([('hw_morph_live b AL', NOT_FOUND)], {'cert_addr': cert})
    spec['mu'] = MU1
    return spec


def morph_get_legacy():
    return guarded([('hw_morph_live b BL', NOT_FOUND)],
                   {'regs': upd('hw_regs b', 'AL', 'zext (hw_morph_src_table b BL) 26')})


def morph_get_ext():
    return guarded([('hw_morph_live b BL', NOT_FOUND),
                    ('hw_coupling_ref_ok b (hw_morph_coupling_desc_table b BL)', COUPLING)],
                   {'regs': upd('hw_regs b', 'AL', 'hw_morph_get_value b BL SEL')})


TYPE = {'err': 'true', 'error_code': 'ERR_COMPOSE_TYPE'}
DESC = 'split1 4 1 (hw_coupling_desc_next_id b)'
PAIR_NEXT = 'hw_coupling_pair_next_id b'


def alloc_rows(src, dst, desc, label, phase, length='natToWord 6 1'):
    return {'regs': upd('hw_regs b', 'AL', f'zext ({SLOT}) 28'),
            'morph_src_table': upd('hw_morph_src_table b', SLOT, src),
            'morph_dst_table': upd('hw_morph_dst_table b', SLOT, dst),
            'morph_coupling_desc_table': upd('hw_morph_coupling_desc_table b', SLOT, desc),
            'morph_identity_table': upd('hw_morph_identity_table b', SLOT, 'false'),
            'morph_valid_table': upd('hw_morph_valid_table b', SLOT, 'true'),
            'morph_next_id': 'wplus (hw_morph_next_id b) (natToWord MorphTableNextIdSz 1)',
            'coupling_desc_label_table': upd('hw_coupling_desc_label_table b', DESC, label),
            'coupling_desc_label_len_table': upd('hw_coupling_desc_label_len_table b', DESC, length),
            'mc_phase': phase}


def morph_ext():
    src, dst = 'split1 6 2 Bw', 'split1 6 26 E'
    rows = alloc_rows(src, dst, DESC, 'natToWord WordSz 0', 'natToWord 4 1')
    rows['mc_mem_base'] = 'zext (split1 7 19 (split2 6 26 E)) 25'
    base0 = {'mc_mem_base': 'natToWord WordSz 0'}
    spec = guarded(
        [('hw_morph_room b', dict(OVERFLOW, **base0)), ('hw_desc_room b', dict(OVERFLOW, **base0)),
         (f'hw_module_present b ({src})', dict(COUPLING, **base0)),
         (f'hw_module_present b ({dst})', dict(COUPLING, **base0))],
        rows)
    # The loading pointers are latched on every MORPH, whatever its outcome.
    spec['mc_write_base'] = PAIR_NEXT
    spec['mc_write_ptr'] = PAIR_NEXT
    return spec


def compose_ext():
    m1, m2 = 'BL', 'split1 4 28 E'
    d1, d2 = f'hw_morph_coupling_desc_table b {m1}', f'hw_morph_coupling_desc_table b ({m2})'
    id1, id2 = f'hw_morph_identity_table b {m1}', f'hw_morph_identity_table b ({m2})'

    def mask(d):
        return f'(if hw_coupling_desc_valid_table b ({d}) then hw_coupling_desc_label_table b ({d}) else natToWord WordSz 1)'

    def length(d):
        return f'(if hw_coupling_desc_valid_table b ({d}) then hw_coupling_desc_label_len_table b ({d}) else natToWord 6 1)'

    def count(d):
        return f'hw_coupling_desc_count_table b ({d})'
    rows = alloc_rows(f'hw_morph_src_table b {m1}', f'hw_morph_dst_table b ({m2})', DESC,
                      f'wplus {mask(d1)} (wlshift {mask(d2)} (wordToNat {length(d1)}))',
                      f'if {id1} then natToWord 4 4 else if {id2} then natToWord 4 4 else natToWord 4 7',
                      f'wplus {length(d1)} {length(d2)}')
    zero = 'natToWord CouplingPairCountSz 0'
    rows['mc_src1_count'] = f'if {id1} then {zero} else {count(d1)}'
    rows['mc_src2_count'] = f'if {id2} then {zero} else {count(d2)}'
    raw = {'mc_src1_count': count(d1), 'mc_src2_count': count(d2)}
    spec = guarded(
        [('hw_morph_room b', dict(OVERFLOW, **raw)),
         (f'hw_morph_live b {m1}', dict(NOT_FOUND, **raw)),
         (f'hw_morph_live b ({m2})', dict(NOT_FOUND, **raw)),
         (f'if weq (hw_morph_dst_table b {m1}) (hw_morph_src_table b ({m2})) then true else false', dict(TYPE, **raw)),
         ('hw_desc_room b', dict(raw))],
        rows)
    spec['mc_src1_base'] = f'hw_coupling_desc_base_table b ({d1})'
    spec['mc_src2_base'] = f'hw_coupling_desc_base_table b ({d2})'
    spec['mc_i'] = zero
    spec['mc_j'] = zero
    spec['mc_write_base'] = PAIR_NEXT
    spec['mc_write_ptr'] = PAIR_NEXT
    return spec


# name: (opcode, format N or None for legacy, spec)
OPS = {
    'MORPH_ID': ('OP_MORPH_ID', None, morph_id()),
    'MORPH_ID_EXT': ('OP_MORPH_ID', 3, morph_id()),
    'MORPH_DELETE': ('OP_MORPH_DELETE', None, morph_delete()),
    'MORPH_DELETE_EXT': ('OP_MORPH_DELETE', 3, morph_delete()),
    'MORPH_ASSERT': ('OP_MORPH_ASSERT', None, morph_assert('natToWord WordSz 0')),
    'MORPH_ASSERT_EXT': ('OP_MORPH_ASSERT', 5, morph_assert('E')),
    'MORPH_GET': ('OP_MORPH_GET', None, morph_get_legacy()),
    'MORPH_GET_EXT': ('OP_MORPH_GET', 3, morph_get_ext()),
    'MORPH_EXT': ('OP_MORPH', 3, morph_ext()),
    'COMPOSE_EXT': ('OP_COMPOSE', 3, compose_ext()),
    'MORPH_TENSOR': ('OP_MORPH_TENSOR', None, dict(NOT_FOUND)),
    'MORPH_TENSOR_EXT': ('OP_MORPH_TENSOR', 3, dict(NOT_FOUND)),
}


def inline(expr):
    import re
    return re.sub(r'\b(AL|AH|BL|BH|Bw|A|C|E|SEL)\b', lambda m: MNAMES[m.group(1)], expr)


def generate(only=None):
    t = HEADER
    count = 0
    for name, (op, fmt, spec) in OPS.items():
        if only and name not in only:
            continue
        low = name.lower()
        bits = BITS if fmt is None else f'{BITS} {EBITS}'
        if fmt is None:
            body = f'legacy_word {op} {inline("A")} {inline("Bw")} {inline("C")}'
        else:
            body = f'rich_word {fmt} {op} {inline("A")} {inline("Bw")} {inline("C")} {inline("E")}'
        t += f'Definition {low}_word ({bits} : bool) : word InstrSz :=\n  {body}.\n'
        for f in FIELDS + [k for k in spec if k not in FIELDS]:
            rhs = inline(spec.get(f, default(f)))
            t += (f'Lemma step_{low}_{f} : forall {bits} b,\n'
                  f'  step_fetched b = {low}_word {bits} -> hwb_bianchi b = false ->\n'
                  f'  hw_{f} (step_next b) = {rhs}.\n'
                  f'Proof. {"hw_field" if fmt is None else "hw_field_rich"}. Qed.\n')
            count += 1
        t += '\n'
    return t, count


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--only', nargs='*')
    parser.add_argument('--out')
    args = parser.parse_args()
    generated, count = generate(args.only)
    target = Path(args.out) if args.out else TARGET
    if args.check:
        if target.read_text() != generated:
            raise SystemExit('StepFieldsMorph.v is stale; regenerate it')
    else:
        target.write_text(generated)
    print(f'StepFieldsMorph: {count} field equations')
