#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import re
from collections import defaultdict, deque
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Set, Tuple


DECL_RE = re.compile(
    r"^\s*(?:Local\s+|Global\s+)?"
    r"(Lemma|Theorem|Corollary|Proposition|Fact|Remark|Definition|Fixpoint|Inductive|Record|CoFixpoint)\s+"
    r"([A-Za-z_][A-Za-z0-9_']*)\b"
)
END_RE = re.compile(r"^\s*(Qed\.|Defined\.|Admitted\.)\s*$")
TOKEN_RE = re.compile(r"\b[A-Za-z_][A-Za-z0-9_']*\b")
THEOREM_KINDS = {"Lemma", "Theorem", "Corollary", "Proposition", "Fact", "Remark"}

FOUNDATION_FILES: Tuple[str, ...] = (
    "coq/kernel/VMState.v",
    "coq/kernel/VMStep.v",
    "coq/kernel/MuCostModel.v",
    "coq/kernel/MuLedgerConservation.v",
    "coq/kernel/NoFreeInsight.v",
    "coq/kernel/MuInitiality.v",
)


def _is_autogenerated_coq_file(abs_path: Path) -> bool:
    """Detect generated Coq sources that should not be manually curated.

    These files can contain synthetic symbol manifests or generated model dumps.
    We exclude them from theorem-connectivity gating to avoid forcing manual edits
    to generated outputs.
    """

    try:
        head = "\n".join(abs_path.read_text(encoding="utf-8", errors="replace").splitlines()[:80])
    except Exception:
        return False
    return (
        "AUTO-GENERATED" in head
        or "Auto-generated formalization" in head
        or "Do not edit manually" in head
    )


@dataclass
class Decl:
    id: str
    name: str
    kind: str
    file: str
    line: int
    statement: str
    body: str


def _coq_files(root: Path) -> Iterable[Path]:
    return sorted(root.rglob("*.v"))


def _extract_decls(path: Path, coq_root: Path) -> List[Decl]:
    lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    rel = path.relative_to(coq_root).as_posix()
    out: List[Decl] = []
    i = 0
    while i < len(lines):
        match = DECL_RE.match(lines[i])
        if not match:
            i += 1
            continue

        kind, name = match.group(1), match.group(2)
        start = i + 1
        statement_lines: List[str] = [lines[i]]
        i += 1
        while i < len(lines):
            if re.search(r"\.\s*$", statement_lines[-1]):
                break
            statement_lines.append(lines[i])
            i += 1

        body_lines: List[str] = []
        if kind in THEOREM_KINDS:
            while i < len(lines):
                body_lines.append(lines[i])
                if END_RE.match(lines[i]):
                    i += 1
                    break
                i += 1
        else:
            # Non-theorem declarations are captured via their statement text.
            # Keep body empty to avoid accidental spillover into following decls.
            body_lines = []

        # Stable declaration identity to avoid name-collision ambiguity.
        # Format intentionally compact and deterministic for artifact diffs.
        decl_id = f"coq/{rel}:{start}:{kind.lower()}:{name}"

        out.append(
            Decl(
                id=decl_id,
                name=name,
                kind=kind,
                file=rel,
                line=start,
                statement="\n".join(statement_lines),
                body="\n".join(body_lines),
            )
        )
    return out


def _build_graph(
    decls: List[Decl],
) -> Tuple[Dict[str, Decl], Dict[str, List[str]], List[Tuple[str, str]], Dict[str, int]]:
    by_id: Dict[str, Decl] = {decl.id: decl for decl in decls}
    ids_by_name: Dict[str, List[str]] = defaultdict(list)
    for decl in decls:
        ids_by_name[decl.name].append(decl.id)

    edges: Set[Tuple[str, str]] = set()
    stats: Dict[str, int] = {
        "ambiguous_token_hits": 0,
        "self_token_hits_skipped": 0,
        "multi_target_token_edges": 0,
    }

    for decl in decls:
        token_source = f"{decl.statement}\n{decl.body}"
        tokens = set(TOKEN_RE.findall(token_source))
        for tok in tokens:
            candidate_ids = ids_by_name.get(tok)
            if not candidate_ids:
                continue
            if tok == decl.name:
                stats["self_token_hits_skipped"] += 1
            targets = [cid for cid in candidate_ids if cid != decl.id]
            if not targets:
                continue

            if len(targets) > 1:
                stats["ambiguous_token_hits"] += 1

                # Prefer prior declarations in same file to reduce false cross-file matches.
                same_file_prior = [
                    tid
                    for tid in targets
                    if by_id[tid].file == decl.file and by_id[tid].line < decl.line
                ]
                if same_file_prior:
                    targets = same_file_prior

            for target_id in targets:
                if len(targets) > 1:
                    stats["multi_target_token_edges"] += 1
                edges.add((decl.id, target_id))

    return by_id, dict(ids_by_name), sorted(edges), stats


def _rank(by_id: Dict[str, Decl], edges: List[Tuple[str, str]]) -> Dict[str, object]:
    indeg: Dict[str, int] = {k: 0 for k in by_id}
    outdeg: Dict[str, int] = {k: 0 for k in by_id}
    for src, dst in edges:
        outdeg[src] += 1
        indeg[dst] += 1

    roots = sorted([k for k, v in indeg.items() if v == 0])
    leaves = sorted([k for k, v in outdeg.items() if v == 0])
    isolated = sorted([k for k in by_id if indeg[k] == 0 and outdeg[k] == 0])
    top_out = sorted(outdeg.items(), key=lambda kv: kv[1], reverse=True)[:25]
    top_in = sorted(indeg.items(), key=lambda kv: kv[1], reverse=True)[:25]

    file_node_count: Dict[str, int] = defaultdict(int)
    for decl in by_id.values():
        file_node_count[decl.file] += 1
    top_files = sorted(file_node_count.items(), key=lambda kv: kv[1], reverse=True)[:25]

    weak_components = _weak_components(set(by_id.keys()), edges)
    scc_components = _scc_components(set(by_id.keys()), edges)

    return {
        "rootCount": len(roots),
        "leafCount": len(leaves),
        "isolatedCount": len(isolated),
        "roots": roots,
        "leaves": leaves,
        "isolated": isolated,
        "topOutDegree": [{"id": n, "out": d} for n, d in top_out],
        "topInDegree": [{"id": n, "in": d} for n, d in top_in],
        "topFilesByDecl": [{"file": f, "declCount": c} for f, c in top_files],
        "weakComponents": {
            "count": len(weak_components),
            "largest": [
                {
                    "size": len(component),
                    "sample": component[:8],
                }
                for component in weak_components[:20]
            ],
        },
        "stronglyConnectedCycles": {
            "count": len([component for component in scc_components if len(component) > 1]),
            "largest": [
                {
                    "size": len(component),
                    "sample": component[:8],
                }
                for component in [c for c in scc_components if len(c) > 1][:20]
            ],
        },
    }


def _weak_components(names: Set[str], edges: List[Tuple[str, str]]) -> List[List[str]]:
    adjacency: Dict[str, Set[str]] = {name: set() for name in names}
    for src, dst in edges:
        adjacency[src].add(dst)
        adjacency[dst].add(src)

    seen: Set[str] = set()
    components: List[List[str]] = []
    for name in sorted(names):
        if name in seen:
            continue
        queue = deque([name])
        seen.add(name)
        comp: List[str] = []
        while queue:
            node = queue.popleft()
            comp.append(node)
            for nxt in adjacency[node]:
                if nxt not in seen:
                    seen.add(nxt)
                    queue.append(nxt)
        components.append(sorted(comp))

    components.sort(key=lambda c: (-len(c), c[0]))
    return components


def _build_file_graph(by_id: Dict[str, Decl], edges: List[Tuple[str, str]]) -> Dict[str, Set[str]]:
    files = {f"coq/{d.file}" for d in by_id.values()}
    file_adj: Dict[str, Set[str]] = {f: set() for f in files}
    for src_id, dst_id in edges:
        src_file = f"coq/{by_id[src_id].file}"
        dst_file = f"coq/{by_id[dst_id].file}"
        if src_file != dst_file:
            file_adj[src_file].add(dst_file)
    return file_adj


def _reachable_foundations(file_adj: Dict[str, Set[str]], start_file: str, foundations: Set[str]) -> Set[str]:
    seen: Set[str] = set()
    stack: List[str] = [start_file]
    reached: Set[str] = set()
    while stack:
        node = stack.pop()
        if node in seen:
            continue
        seen.add(node)
        if node in foundations:
            reached.add(node)
        stack.extend(sorted(file_adj.get(node, set())))
    return reached


def _build_connectivity_audit(by_id: Dict[str, Decl], edges: List[Tuple[str, str]]) -> Dict[str, object]:
    file_adj = _build_file_graph(by_id, edges)
    foundations = set(FOUNDATION_FILES)
    theorem_bearing_files = {
        f"coq/{d.file}"
        for d in by_id.values()
        if d.kind in THEOREM_KINDS
    }
    theorem_files = sorted(theorem_bearing_files)
    per_file: List[Dict[str, object]] = []
    disconnected: List[str] = []
    excluded_autogenerated_files: List[str] = []

    generated_flags: Dict[str, bool] = {}
    for file_path in theorem_files:
        abs_path = Path(file_path)
        generated_flags[file_path] = _is_autogenerated_coq_file(abs_path)
        if generated_flags[file_path]:
            excluded_autogenerated_files.append(file_path)

    for file_path in theorem_files:
        if generated_flags.get(file_path, False):
            per_file.append(
                {
                    "file": file_path,
                    "connected_to_foundation": None,
                    "reached_foundation_files": [],
                    "out_edges": len(file_adj.get(file_path, set())),
                    "excluded_reason": "autogenerated",
                }
            )
            continue
        reached = sorted(_reachable_foundations(file_adj, file_path, foundations))
        connected = bool(reached) or file_path in foundations
        if not connected:
            disconnected.append(file_path)
        per_file.append(
            {
                "file": file_path,
                "connected_to_foundation": connected,
                "reached_foundation_files": reached,
                "out_edges": len(file_adj.get(file_path, set())),
            }
        )

    edge_count = sum(len(v) for v in file_adj.values())
    return {
        "foundation_files": sorted(foundations),
        "file_node_count": len(theorem_files),
        "file_edge_count": edge_count,
        "disconnected_file_count": len(disconnected),
        "disconnected_files": disconnected,
        "excluded_autogenerated_file_count": len(excluded_autogenerated_files),
        "excluded_autogenerated_files": excluded_autogenerated_files,
        "per_file": per_file,
    }


def _mermaid_file_graph(file_adj: Dict[str, Set[str]], limit_nodes: int = 180) -> str:
    nodes = sorted(file_adj.keys())
    # Keep a readable graph size while still representing entire codebase in JSON.
    selected = set(nodes[:limit_nodes])
    lines = ["flowchart TD"]
    for idx, file_path in enumerate(sorted(selected), start=1):
        node = f"F{idx}"
        label = file_path.replace('"', "")
        lines.append(f"  {node}[\"{label}\"]")

    index = {f: f"F{i+1}" for i, f in enumerate(sorted(selected))}
    for src in sorted(selected):
        for dst in sorted(file_adj.get(src, set())):
            if dst not in selected:
                continue
            lines.append(f"  {index[src]} --> {index[dst]}")
    return "\n".join(lines)


def _render_foundation_report(repo_root: Path, conn: Dict[str, object]) -> str:
    disconnected = conn.get("disconnected_files", [])
    foundations = conn.get("foundation_files", [])
    excluded_generated = conn.get("excluded_autogenerated_files", [])
    lines = [
        "# Coq Foundation Reachability Audit",
        "",
        "This report is generated from theorem-body symbol dependencies (not import graph only).",
        "",
        "## Foundation Files",
        "",
    ]
    for f in foundations:
        lines.append(f"- `{f}`")
    lines.extend(
        [
            "",
            "## Summary",
            "",
            f"- File nodes analyzed: **{conn.get('file_node_count', 0)}**",
            f"- File edges inferred from theorem dependencies: **{conn.get('file_edge_count', 0)}**",
            f"- Excluded autogenerated theorem files: **{conn.get('excluded_autogenerated_file_count', 0)}**",
            f"- Disconnected theorem files: **{conn.get('disconnected_file_count', 0)}**",
            "",
            "## Excluded Autogenerated Theorem Files",
            "",
        ]
    )
    if excluded_generated:
        for f in excluded_generated:
            lines.append(f"- `{f}`")
    else:
        lines.append("(none)")

    lines.extend(
        [
            "",
            "## Disconnected Files",
            "",
        ]
    )
    if disconnected:
        for f in disconnected:
            lines.append(f"- `{f}`")
    else:
        lines.append("(none)")

    lines.extend(
        [
            "",
            "## Diagram",
            "",
            "```mermaid",
            (repo_root / "artifacts" / "proof_dependency_file_graph.mmd").read_text(encoding="utf-8", errors="replace"),
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def _scc_components(names: Set[str], edges: List[Tuple[str, str]]) -> List[List[str]]:
    adjacency: Dict[str, List[str]] = {name: [] for name in names}
    for src, dst in edges:
        adjacency[src].append(dst)

    index = 0
    stack: List[str] = []
    on_stack: Set[str] = set()
    indices: Dict[str, int] = {}
    lowlink: Dict[str, int] = {}
    components: List[List[str]] = []

    def strongconnect(node: str) -> None:
        nonlocal index
        indices[node] = index
        lowlink[node] = index
        index += 1
        stack.append(node)
        on_stack.add(node)

        for nxt in adjacency[node]:
            if nxt not in indices:
                strongconnect(nxt)
                lowlink[node] = min(lowlink[node], lowlink[nxt])
            elif nxt in on_stack:
                lowlink[node] = min(lowlink[node], indices[nxt])

        if lowlink[node] == indices[node]:
            comp: List[str] = []
            while True:
                w = stack.pop()
                on_stack.remove(w)
                comp.append(w)
                if w == node:
                    break
            components.append(sorted(comp))

    for name in sorted(names):
        if name not in indices:
            strongconnect(name)

    components.sort(key=lambda c: (-len(c), c[0]))
    return components


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate theorem dependency DAG for Coq files")
    parser.add_argument("--coq-root", default="coq", help="Path to Coq root directory")
    parser.add_argument("--out", default="artifacts/proof_dependency_dag.json", help="Output JSON path")
    parser.add_argument(
        "--connectivity-out",
        default="artifacts/proof_dependency_connectivity.json",
        help="Output JSON path for file-level foundation reachability audit",
    )
    parser.add_argument(
        "--file-graph-mermaid",
        default="artifacts/proof_dependency_file_graph.mmd",
        help="Output mermaid file for file-level dependency graph",
    )
    parser.add_argument(
        "--foundation-report",
        default="artifacts/PROOF_FOUNDATION_AUDIT.md",
        help="Output markdown report for foundation reachability",
    )
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parents[1]
    coq_root = (repo_root / args.coq_root).resolve()
    out_path = (repo_root / args.out).resolve()
    conn_out_path = (repo_root / args.connectivity_out).resolve()
    file_graph_path = (repo_root / args.file_graph_mermaid).resolve()
    foundation_report_path = (repo_root / args.foundation_report).resolve()

    decls: List[Decl] = []
    for file_path in _coq_files(coq_root):
        decls.extend(_extract_decls(file_path, coq_root))

    by_id, ids_by_name, edges, build_stats = _build_graph(decls)
    rank = _rank(by_id, edges)
    file_adj = _build_file_graph(by_id, edges)
    conn = _build_connectivity_audit(by_id, edges)

    payload = {
        "meta": {
            "coqRoot": str(coq_root.relative_to(repo_root)),
            "nodeCount": len(by_id),
            "edgeCount": len(edges),
            "note": "Edges are symbol-reference dependencies inferred from theorem statements and proof bodies.",
            "buildStats": build_stats,
        },
        "nodes": [
            {
                "id": decl.id,
                "name": decl.name,
                "kind": decl.kind,
                "file": f"coq/{decl.file}",
                "line": decl.line,
            }
            for decl in sorted(by_id.values(), key=lambda d: (d.file, d.line, d.name))
        ],
        # Keep legacy `from`/`to` fields for compatibility with existing consumers.
        "edges": [
            {
                "from": by_id[src].name,
                "to": by_id[dst].name,
                "fromId": src,
                "toId": dst,
                "fromFile": f"coq/{by_id[src].file}",
                "toFile": f"coq/{by_id[dst].file}",
            }
            for src, dst in edges
        ],
        "nameIndex": {k: v for k, v in sorted(ids_by_name.items())},
        "rank": rank,
    }

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")

    conn_out_path.parent.mkdir(parents=True, exist_ok=True)
    conn_out_path.write_text(json.dumps(conn, indent=2), encoding="utf-8")

    file_graph_path.parent.mkdir(parents=True, exist_ok=True)
    file_graph_path.write_text(_mermaid_file_graph(file_adj), encoding="utf-8")

    foundation_report_path.parent.mkdir(parents=True, exist_ok=True)
    foundation_report_path.write_text(_render_foundation_report(repo_root, conn), encoding="utf-8")

    print(f"Wrote {out_path.relative_to(repo_root)}")
    print(f"Wrote {conn_out_path.relative_to(repo_root)}")
    print(f"Wrote {file_graph_path.relative_to(repo_root)}")
    print(f"Wrote {foundation_report_path.relative_to(repo_root)}")
    print(f"Nodes: {payload['meta']['nodeCount']}, Edges: {payload['meta']['edgeCount']}")
    print(
        "Disconnected theorem files from foundation chain: "
        f"{conn.get('disconnected_file_count', 0)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
