#!/usr/bin/env python3
"""Generate LassertStepFields.v: field equations of the actual step rule at the
canonical LASSERT encodings, with the kind bit op_a[5] fixed to 1 (SAT witness
check, which starts the FSM) and to 0 (immediate trap), and every other
operand and cost bit symbolic. Besides the refinement fields, the LASSERT FSM
registers are stated. Each lemma is proved by reducing the actual decoded
action.
"""
import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'scripts'))
from generate_step_fields import FIELDS, default, inline  # noqa: E402

TARGET = ROOT / 'coq/kami_hw/LassertStepFields.v'

BITS = 'a0 a1 a2 a3 a4 a6 a7 b0 b1 b2 b3 b4 b5 b6 b7 c0 c1 c2 c3 c4 c5 c6 c7'
FSM = ['lassert_kind', 'lassert_fbase', 'lassert_cbase', 'lassert_cptr', 'lassert_fptr', 'lassert_flen',
       'lassert_clen', 'lassert_nvars', 'lassert_clause_sat', 'lassert_counter_clause_sat',
       'lassert_counter_seen_fail']
Z32 = 'natToWord WordSz 0'
HEADER_ADDR = 'split1 7 25 (hw_regs b AL)'


def rows(kind):
    a5 = 'true' if kind else 'false'
    A = f'(bits8 a0 a1 a2 a3 a4 {a5} a6 a7)'
    if kind:
        spec = {'pc': 'hw_pc b', 'mu': 'hw_mu b', 'lassert_phase': 'natToWord 3 1',
                'lassert_kind': 'true', 'lassert_fbase': 'hw_regs b AL', 'lassert_cbase': 'hw_regs b BL',
                'lassert_cptr': 'zext C 24'}
    else:
        spec = {'pc': 'hw_trap_vector b', 'err': 'true', 'error_code': 'ERR_LOGIC_VAL',
                'mu': (f'wplus (wplus (wplus (hw_mu b) (wlshift (hw_mem b ({HEADER_ADDR})) '
                       f'(wordToNat (WO~0~0~0~0~1~1)))) (zext C 24)) (natToWord WordSz 1)'),
                'lassert_kind': 'false', 'lassert_fbase': Z32, 'lassert_cbase': Z32, 'lassert_cptr': Z32}
    out = []
    for f in FIELDS + FSM:
        if f in spec:
            rhs = spec[f]
        elif f in ('lassert_fptr', 'lassert_flen', 'lassert_clen', 'lassert_nvars'):
            rhs = Z32
        elif f in ('lassert_clause_sat', 'lassert_counter_clause_sat', 'lassert_counter_seen_fail'):
            rhs = 'false'
        else:
            rhs = default(f)
        out.append((f, rhs))
    return A, out


def generate():
    t = '''(** LassertStepFields.v: generated by scripts/generate_lassert_step_fields.py.
    Field equations of [step_next] at the canonical LASSERT encodings, with the
    kind bit fixed to SAT (the FSM starts) and to UNSAT (immediate trap). *)
Require Import Kami.Kami Kami.Semantics.
From Coq Require Import String NArith Eqdep_dec Arith.PeanoNat.
From KamiHW Require Import ThieleTypes ThieleCPUCore HWBoundary RuleNext RuleStep
  BoundaryDecoded ActionObservation DispatchObservation StepEval StepFields.
Open Scope string_scope.

'''
    count = 0
    for kind, name in [(True, 'lassert_sat'), (False, 'lassert_unsat')]:
        A, rs = rows(kind)
        t += (f'Definition {name}_word ({BITS} : bool) : word InstrSz :=\n'
              f'  legacy_word OP_LASSERT {A} (bits8 b0 b1 b2 b3 b4 b5 b6 b7) (bits8 c0 c1 c2 c3 c4 c5 c6 c7).\n')
        for f, rhs in rs:
            t += (f'Lemma step_{name}_{f} : forall {BITS} b,\n'
                  f'  step_fetched b = {name}_word {BITS} -> hwb_bianchi b = false ->\n'
                  f'  hw_{f} (step_next b) = {inline(rhs)}.\n'
                  'Proof. hw_field. Qed.\n')
            count += 1
        t += '\n'
    return t, count


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--out')
    args = parser.parse_args()
    generated, count = generate()
    target = Path(args.out) if args.out else TARGET
    if args.check:
        if target.read_text() != generated:
            raise SystemExit('LassertStepFields.v is stale; regenerate it')
    else:
        target.write_text(generated)
    print(f'LassertStepFields: {count} field equations')
