#!/usr/bin/env python3
"""Generate StepRefineMorph.v: single-cycle retirement refinement for
MORPH_ID, MORPH_DELETE, MORPH_ASSERT and MORPH_GET, legacy and extended.

Each theorem states that, at a boundary whose fetched word is the canonical
encoding (all operand, cost and ext0 bits symbolic), with the Bianchi guard
false, err and halted clear and the listed admission premises, the actual
step rule's next boundary observes exactly [kami_step (hwb_snapshot b) i].
Success and morph-runtime fault branches are both covered; table-overflow
rich faults are excluded by an explicit room premise for MORPH_ID.
"""
import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'scripts'))
from generate_step_fields import FIELDS, BITS  # noqa: E402
from generate_step_fields_morph import EBITS, inline  # noqa: E402

TARGET = ROOT / 'coq/kami_hw/StepRefineMorph.v'

HEADER = r'''(** StepRefineMorph.v: generated by scripts/generate_step_refine_morph.py.
    Single-cycle retirement refinement of the actual step rule against
    [kami_step] for the morph-table opcodes MORPH_ID, MORPH_DELETE,
    MORPH_ASSERT, MORPH_GET and MORPH_TENSOR, at legacy and extended
    encodings. *)
Require Import Kami.Kami Kami.Semantics Kami.Lib.NatLib.
From Coq Require Import String NArith Arith Lia FunctionalExtensionality.
From KamiHW Require Import ThieleTypes HWBoundary RuleNext RuleStep BoundaryDecoded StepEval
  StepWordFacts StepFields StepRefineCommon StepRefine StepFieldsMorph
  ImplementationContract Abstraction MorphTensorGap.
Require Import Kernel.VMState Kernel.VMStep.
Import VMStep.VMStep.
Open Scope string_scope.

(** * Diagnostic codes *)

Lemma wordToNat_err_morph_not_found : wordToNat ERR_MORPH_NOT_FOUND = KAMI_ERR_MORPH_NOT_FOUND.
Proof.
  unfold KAMI_ERR_MORPH_NOT_FOUND. destruct kami_err_morph_not_found_witness as [n E].
  cbn [proj1_sig]. subst n. rewrite <- N_to_nat_wordToN. f_equal; vm_compute; reflexivity.
Qed.

Lemma wordToNat_err_coupling_invalid : wordToNat ERR_COUPLING_INVALID = KAMI_ERR_COUPLING_INVALID.
Proof.
  unfold KAMI_ERR_COUPLING_INVALID. destruct kami_err_coupling_invalid_witness as [n E].
  cbn [proj1_sig]. subst n. rewrite <- N_to_nat_wordToN. f_equal; vm_compute; reflexivity.
Qed.

(** * Table projections *)

Lemma hwb_valid_at : forall n (v : type (Vector Bool n)) (i : word n),
  hwb_valid v (wordToNat i) = v i.
Proof.
  intros n v i. unfold hwb_valid.
  rewrite (proj2 (Nat.ltb_lt _ _) (wordToNat_lt_pow2_small n i)).
  rewrite natToWord_wordToNat. reflexivity.
Qed.

Lemma hwb_valid_update : forall n (v : type (Vector Bool n)) (d : word n) (x : bool),
  hwb_valid (n := n) (fun i => if weq i d then x else v i) =
  fun j => if Nat.eqb j (wordToNat d) then x else hwb_valid v j.
Proof.
  intros n v d x. extensionality j. unfold hwb_valid.
  destruct (Nat.ltb j (2 ^ n)) eqn:Hj.
  - apply Nat.ltb_lt in Hj.
    destruct (weq (natToWord n j) d) as [E|N].
    + subst d. rewrite wordToNat_natToWord_idempotent' by exact Hj.
      rewrite Nat.eqb_refl. reflexivity.
    + destruct (Nat.eqb j (wordToNat d)) eqn:Ejd; [|reflexivity].
      apply Nat.eqb_eq in Ejd. subst j. rewrite natToWord_wordToNat in N. contradiction.
  - apply Nat.ltb_ge in Hj.
    destruct (Nat.eqb j (wordToNat d)) eqn:Ejd; [|reflexivity].
    apply Nat.eqb_eq in Ejd. subst j. pose proof (wordToNat_lt_pow2_small n d). lia.
Qed.

Lemma rich_morph_table_at : forall b (i : word MorphTableIdxSz),
  rich_morph_table (hwb_rich b) (wordToNat i) =
  if hw_morph_valid_table b i then
    Some {| morph_entry_source := wordToNat (hw_morph_src_table b i);
            morph_entry_target := wordToNat (hw_morph_dst_table b i);
            morph_entry_coupling_desc := wordToNat (hw_morph_coupling_desc_table b i);
            morph_entry_is_identity := hw_morph_identity_table b i |}
  else None.
Proof.
  intros b i. unfold hwb_rich. cbn [rich_morph_table].
  rewrite hwb_valid_at, !hwb_vector_nat_at, hwb_valid_at. reflexivity.
Qed.

Lemma rich_coupling_desc_table_at : forall b (d : word CouplingDescIdxSz),
  rich_coupling_desc_table (hwb_rich b) (wordToNat d) =
  if hw_coupling_desc_valid_table b d then
    Some {| coupling_desc_base := wordToNat (hw_coupling_desc_base_table b d);
            coupling_desc_count := wordToNat (hw_coupling_desc_count_table b d);
            coupling_desc_label := atom_label (wordToNat (hw_coupling_desc_label_len_table b d)) (wordToNat (hw_coupling_desc_label_table b d)) |}
  else None.
Proof.
  intros b d. unfold hwb_rich. cbn [rich_coupling_desc_table].
  rewrite hwb_valid_at, !hwb_vector_nat_at. reflexivity.
Qed.

(** * Admission invariants of the morph and coupling tables *)

(** Every valid morph slot lies below [morph_next_id]. *)
Definition hwb_morph_valid_below_next (b : HWB) : Prop :=
  forall i, hw_morph_valid_table b i = true -> wordToNat i < wordToNat (hw_morph_next_id b).

(** Every valid morph slot refers to descriptor 0 or to a valid descriptor
    below [coupling_desc_next_id]. *)
Definition hwb_morph_coupling_refs_ok (b : HWB) : Prop :=
  forall i, hw_morph_valid_table b i = true ->
  hw_coupling_ref_ok b (hw_morph_coupling_desc_table b i) = true.

(** Coupling descriptor 0 is the reserved empty descriptor and is never valid. *)
Definition hwb_coupling_desc_zero_invalid (b : HWB) : Prop :=
  hw_coupling_desc_valid_table b (natToWord CouplingDescIdxSz 0) = false.

Lemma morph_live_valid : forall b i, hwb_morph_valid_below_next b ->
  hw_morph_live b i = hw_morph_valid_table b i.
Proof.
  intros b i H. unfold hw_morph_live.
  destruct (wlt_dec _ _) as [L|L]; [reflexivity|].
  destruct (hw_morph_valid_table b i) eqn:Hv; [|reflexivity].
  exfalso. apply L. apply lt_wlt. rewrite wordToNat_zext. exact (H i Hv).
Qed.

Lemma morph_room_of_lt : forall b, wordToNat (hw_morph_next_id b) < 16 -> hw_morph_room b = true.
Proof.
  intros b H. unfold hw_morph_room.
  destruct (wlt_dec _ _) as [_|L]; [reflexivity|].
  exfalso. apply L. apply lt_wlt. exact H.
Qed.

Lemma module_present_eqb : forall b m,
  hw_module_present b m = negb (Nat.eqb (wordToNat (hw_ptTable b m)) 0).
Proof.
  intros b m. unfold hw_module_present.
  destruct (weq _ _) as [E|N].
  - rewrite E. reflexivity.
  - destruct (Nat.eqb_spec (wordToNat (hw_ptTable b m)) 0) as [Z|Z]; [|reflexivity].
    exfalso. apply N. apply wordToNat_inj. rewrite Z. symmetry. apply wordToNat_word0_32.
Qed.

Lemma wordToNat_trunc4_5_small : forall w : word MorphTableNextIdSz,
  wordToNat w < 16 -> wordToNat (split1 4 1 w) = wordToNat w.
Proof.
  intros w H. rewrite (wordToNat_split1 4 1 w). apply Nat.mod_small. exact H.
Qed.

Lemma word64_ptidx : forall w : word PTableIdxSz, word64 (wordToNat w) = wordToNat w.
Proof.
  intro w. apply word64_below_pow2_32.
  eapply Nat.lt_le_trans; [apply wordToNat_bound|]. apply Nat.pow_le_mono_r; unfold PTableIdxSz; lia.
Qed.

Lemma lt16_pow2_32 : forall n, n < 16 -> n < pow2 32.
Proof.
  intros n H. eapply Nat.lt_le_trans; [exact H|].
  change 16 with (2 ^ 4). apply Nat.pow_le_mono_r; lia.
Qed.

Lemma wordToNat_zext6_32 : forall w : word PTableIdxSz, @wordToNat WordSz (zext w 26) = wordToNat w.
Proof. intro w. exact (wordToNat_zext w 26). Qed.

Lemma wordToNat_zext4_32 : forall w : word 4, @wordToNat WordSz (zext w 28) = wordToNat w.
Proof. intro w. exact (wordToNat_zext w 28). Qed.

(** * Rich state after the step rule *)

Ltac rich_keeps :=
  rewrite step_keeps_coupling_desc_valid_table, step_keeps_coupling_desc_base_table,
    step_keeps_coupling_desc_count_table, step_keeps_coupling_desc_next_id,
    step_keeps_coupling_pair_valid_table, step_keeps_coupling_pair_src_table,
    step_keeps_coupling_pair_dst_table, step_keeps_coupling_pair_next_id,
    step_keeps_formula_desc_valid_table, step_keeps_formula_desc_base_table,
    step_keeps_formula_desc_count_table, step_keeps_formula_desc_next_id,
    step_keeps_cert_desc_valid_table, step_keeps_cert_desc_base_table,
    step_keeps_cert_desc_count_table, step_keeps_cert_desc_next_id,
    step_keeps_desc_meta_valid_table, step_keeps_desc_meta_subtype_table,
    step_keeps_desc_meta_kind_table, step_keeps_desc_meta_inline_len_table,
    step_keeps_desc_meta_aux_table, step_keeps_desc_meta_next_id.

Lemma step_rich_delete : forall b (i : word MorphTableIdxSz),
  hw_morph_valid_table (step_next b) = (fun w => if weq w i then false else hw_morph_valid_table b w) ->
  hw_morph_src_table (step_next b) = hw_morph_src_table b ->
  hw_morph_dst_table (step_next b) = hw_morph_dst_table b ->
  hw_morph_coupling_desc_table (step_next b) = hw_morph_coupling_desc_table b ->
  hw_morph_identity_table (step_next b) = hw_morph_identity_table b ->
  hw_morph_next_id (step_next b) = hw_morph_next_id b ->
  hw_coupling_desc_label_table (step_next b) = hw_coupling_desc_label_table b ->
  hw_coupling_desc_label_len_table (step_next b) = hw_coupling_desc_label_len_table b ->
  hwb_rich (step_next b) = rich_state_delete_morph (hwb_rich b) (wordToNat i).
Proof.
  intros b i H1 H2 H3 H4 H5 H6 H7 H8. unfold hwb_rich at 1.
  rewrite H1, H2, H3, H4, H5, H6, H7, H8. rich_keeps.
  unfold rich_state_delete_morph, hwb_rich. cbn [rich_morph_table rich_next_morph_id
    rich_coupling_desc_table rich_next_coupling_desc_id rich_coupling_pair_table
    rich_next_coupling_pair_id rich_formula_desc_table rich_next_formula_desc_id
    rich_cert_desc_table rich_next_cert_desc_id rich_desc_meta_table
    rich_next_desc_meta_id rich_lassert_state].
  rewrite hwb_valid_update. f_equal.
  extensionality j. destruct (Nat.eqb j (wordToNat i)); reflexivity.
Qed.

Lemma step_rich_alloc : forall b (s : word MorphTableIdxSz) (src dst : word PTableIdxSz)
    (cd : word DescIdxSz) (idf : bool) srcn dstn cdn,
  wordToNat (hw_morph_next_id b) < 16 ->
  wordToNat s = wordToNat (hw_morph_next_id b) ->
  wordToNat src = srcn -> wordToNat dst = dstn -> wordToNat cd = cdn ->
  hw_morph_valid_table (step_next b) = (fun w => if weq w s then true else hw_morph_valid_table b w) ->
  hw_morph_src_table (step_next b) = (fun w => if weq w s then src else hw_morph_src_table b w) ->
  hw_morph_dst_table (step_next b) = (fun w => if weq w s then dst else hw_morph_dst_table b w) ->
  hw_morph_coupling_desc_table (step_next b) =
    (fun w => if weq w s then cd else hw_morph_coupling_desc_table b w) ->
  hw_morph_identity_table (step_next b) = (fun w => if weq w s then idf else hw_morph_identity_table b w) ->
  hw_morph_next_id (step_next b) = wplus (hw_morph_next_id b) (natToWord MorphTableNextIdSz 1) ->
  hw_coupling_desc_label_table (step_next b) = hw_coupling_desc_label_table b ->
  hw_coupling_desc_label_len_table (step_next b) = hw_coupling_desc_label_len_table b ->
  rich_state_add_morph (hwb_rich b) srcn dstn cdn idf =
    (hwb_rich (step_next b), wordToNat (hw_morph_next_id b)).
Proof.
  intros b s src dst cd idf srcn dstn cdn Hroom Hs Hsrc Hdst Hcd H1 H2 H3 H4 H5 H6 H7 H8.
  subst srcn dstn cdn. unfold hwb_rich at 2.
  rewrite H1, H2, H3, H4, H5, H6, H7, H8. rich_keeps.
  unfold rich_state_add_morph, hwb_rich. cbn [rich_morph_table rich_next_morph_id
    rich_coupling_desc_table rich_next_coupling_desc_id rich_coupling_pair_table
    rich_next_coupling_pair_id rich_formula_desc_table rich_next_formula_desc_id
    rich_cert_desc_table rich_next_cert_desc_id rich_desc_meta_table
    rich_next_desc_meta_id rich_lassert_state].
  rewrite !hwb_valid_update, !hwb_vector_nat_update, Hs.
  rewrite (wordToNat_wplus_one_bounded MorphTableNextIdSz) by (cbn; lia).
  f_equal. f_equal; [|lia].
  extensionality j. destruct (Nat.eqb j (wordToNat (hw_morph_next_id b))); reflexivity.
Qed.

(** * MORPH_GET readout *)

Lemma rich_coupling_desc_table_at4 : forall b (d : word DescIdxSz),
  rich_coupling_desc_table (hwb_rich b) (wordToNat d) =
  if hw_coupling_desc_valid_table b d then
    Some {| coupling_desc_base := wordToNat (hw_coupling_desc_base_table b d);
            coupling_desc_count := wordToNat (hw_coupling_desc_count_table b d);
            coupling_desc_label := atom_label (wordToNat (hw_coupling_desc_label_len_table b d)) (wordToNat (hw_coupling_desc_label_table b d)) |}
  else None.
Proof. intros b d. exact (rich_coupling_desc_table_at b d). Qed.


Lemma get_value_sel0 : forall b i, hw_morph_get_value b i (bits2 false false) = zext (hw_morph_src_table b i) 26.
Proof. reflexivity. Qed.
Lemma get_value_sel1 : forall b i, hw_morph_get_value b i (bits2 true false) = zext (hw_morph_dst_table b i) 26.
Proof. reflexivity. Qed.
Lemma get_value_sel2 : forall b i, hw_morph_get_value b i (bits2 false true) =
  zext (if weq (hw_morph_coupling_desc_table b i) (natToWord DescIdxSz 0)
        then natToWord CouplingPairCountSz 0
        else hw_coupling_desc_count_table b (hw_morph_coupling_desc_table b i)) 27.
Proof. reflexivity. Qed.
Lemma get_value_sel3 : forall b i, hw_morph_get_value b i (bits2 true true) =
  if hw_morph_identity_table b i then natToWord WordSz 1 else natToWord WordSz 0.
Proof. reflexivity. Qed.

Lemma morph_get_value_nat : forall b (i : word MorphTableIdxSz) e0 e1,
  hwb_coupling_desc_zero_invalid b ->
  hw_coupling_ref_ok b (hw_morph_coupling_desc_table b i) = true ->
  wordToNat (hw_morph_get_value b i (bits2 e0 e1)) =
  word64 (match wordToNat (bits2 e0 e1) with
          | 0 => wordToNat (hw_morph_src_table b i)
          | 1 => wordToNat (hw_morph_dst_table b i)
          | 2 => match rich_coupling_desc_table (hwb_rich b)
                         (wordToNat (hw_morph_coupling_desc_table b i)) with
                 | Some desc => coupling_desc_count desc
                 | None => 0
                 end
          | 3 => if hw_morph_identity_table b i then 1 else 0
          | _ => 0
          end).
Proof.
  intros b i e0 e1 Hz Href.
  destruct e0, e1.
  - rewrite get_value_sel3. change (wordToNat (bits2 true true)) with 3. cbv beta iota.
    destruct (hw_morph_identity_table b i); vm_compute; reflexivity.
  - rewrite get_value_sel1. change (wordToNat (bits2 true false)) with 1. cbv beta iota.
    etransitivity; [apply wordToNat_zext6_32|]. symmetry. apply word64_ptidx.
  - rewrite get_value_sel2. change (wordToNat (bits2 false true)) with 2. cbv beta iota.
    rewrite rich_coupling_desc_table_at4.
    unfold hw_coupling_ref_ok in Href. unfold hwb_coupling_desc_zero_invalid in Hz.
    etransitivity; [exact (wordToNat_zext _ 27)|].
    destruct (weq (hw_morph_coupling_desc_table b i) (natToWord DescIdxSz 0)) as [E|E].
    + rewrite E. change (natToWord CouplingDescIdxSz 0) with (natToWord DescIdxSz 0) in Hz.
      rewrite Hz. vm_compute. reflexivity.
    + destruct (wlt_dec _ _) as [_|_]; [|discriminate Href].
      rewrite Href. cbn [coupling_desc_count].
      symmetry. apply word64_below_pow2_32.
      eapply Nat.lt_le_trans; [apply wordToNat_bound|]. apply Nat.pow_le_mono_r; unfold CouplingPairCountSz; lia.
  - rewrite get_value_sel0. change (wordToNat (bits2 false false)) with 0. cbv beta iota.
    etransitivity; [apply wordToNat_zext6_32|]. symmetry. apply word64_ptidx.
Qed.

'''

COMMON_PREM = [('Hpc', 'wordToNat (hw_pc b) + 1 < pow2 WordSz')]
COST_PREM = [('Hmu', 'wordToNat (hw_mu b) + wordToNat C < pow2 WordSz')]
COST1_PREM = [('Hmu', 'wordToNat (hw_mu b) + wordToNat C + 1 < pow2 WordSz')]
INV = [('Hinv', 'hwb_morph_valid_below_next b')]

FAULT_CLOSE = ['exact wordToNat_err_morph_not_found', 'exact wordToNat_err_coupling_invalid',
               # equal up to the implicit width (MorphTableIdxSz against 4)
               'lazymatch goal with |- rich_state_delete_morph _ _ = rich_state_delete_morph _ _ => reflexivity end']
FRAME = ('rewrite (step_rich_frame b F_morph_valid_table F_morph_src_table F_morph_dst_table '
         'F_morph_coupling_desc_table F_morph_identity_table F_morph_next_id F_coupling_desc_label_table F_coupling_desc_label_len_table)')
DELETE_RICH = ('rewrite (step_rich_delete b AL F_morph_valid_table F_morph_src_table F_morph_dst_table '
               'F_morph_coupling_desc_table F_morph_identity_table F_morph_next_id F_coupling_desc_label_table F_coupling_desc_label_len_table)')
LOOKUP = ('rewrite ?rich_morph_table_at, ?G; cbv beta iota delta [negb]; '
          'cbn [morph_entry_source morph_entry_target morph_entry_coupling_desc morph_entry_is_identity].')


def delete_like(instr, prem, lookup='AL', extra_close=()):
    return dict(
        instr=instr, prem=prem + INV,
        cases=f'rewrite (morph_live_valid b _ Hinv) in *. '
              f'destruct (hw_morph_valid_table b {lookup}) eqn:G; cbv beta iota delta [negb] in F_*.',
        close=FAULT_CLOSE + list(extra_close))


REFINE = {
    'MORPH_DELETE': dict(delete_like('instr_morph_delete (wordToNat AL) (wordToNat C)', COST_PREM),
                         rich=f'first [ {DELETE_RICH} | {FRAME} ]',
                         unfold='kami_advance_rich_noret, kami_advance_err_code'),
    'MORPH_ASSERT': dict(delete_like('instr_morph_assert (wordToNat AL) property cert (wordToNat C)',
                                     COST1_PREM + [('Hprop', 'ascii_checksum property = 0')],
                                     extra_close=['close_mu_cost_one',
                                                  'rewrite Hprop, wordToNat_word0_32; reflexivity']),
                         vars=['property : string', 'cert : string'], rich=FRAME,
                         unfold='kami_advance_cert_addr, kami_advance_err_code'),
    'MORPH_GET': dict(delete_like('instr_morph_get (wordToNat AL) (wordToNat BL) 0 (wordToNat C)', COST_PREM,
                                  lookup='BL',
                                  extra_close=['close_vector_update ltac:(etransitivity; [apply wordToNat_zext6_32|]; symmetry; apply word64_ptidx)']),
                      rich=FRAME, unfold='kami_advance_reg, kami_write_reg, kami_advance_err_code'),
    'MORPH_ID': dict(
        instr='instr_morph_id (wordToNat AL) (wordToNat (split1 6 2 Bw)) (wordToNat C)',
        prem=COST_PREM + [('Hroom', 'wordToNat (hw_morph_next_id b) < 16')],
        cases='rewrite (morph_room_of_lt b Hroom) in *. cbv beta iota delta [negb] in F_*. '
              'rewrite module_present_eqb in *. '
              'destruct (Nat.eqb (wordToNat (hw_ptTable b (split1 6 2 Bw))) 0) eqn:G; '
              'cbv beta iota delta [negb] in F_*.',
        rich=f'try {FRAME}',
        # [rewrite] with the allocation lemma overflows the stack on this goal,
        # so the allocation is abstracted with [pattern] and [eq_rect_r].
        kami='rewrite ?(hwb_vector_nat_at 6), ?G; cbv beta iota delta [negb]; '
             'try (pose proof (step_rich_alloc b (split1 4 1 (hw_morph_next_id b)) (split1 6 2 Bw) (split1 6 2 Bw) '
             '(natToWord DescIdxSz 0) true (wordToNat (split1 6 2 Bw)) (wordToNat (split1 6 2 Bw)) 0 Hroom (wordToNat_trunc4_5_small _ Hroom) eq_refl eq_refl eq_refl '
             'F_morph_valid_table F_morph_src_table F_morph_dst_table F_morph_coupling_desc_table '
             'F_morph_identity_table F_morph_next_id F_coupling_desc_label_table F_coupling_desc_label_len_table) as Halloc; '
             'match type of Halloc with ?l = _ => pattern l end; refine (eq_rect_r _ _ Halloc); clear Halloc); cbv beta iota delta [negb].',
        unfold='kami_advance_rich_morph, kami_advance_err_code',
        close=FAULT_CLOSE + [
            'close_vector_update ltac:(etransitivity; [apply wordToNat_zext4_32|]; rewrite (wordToNat_trunc4_5_small _ Hroom); '
            'rewrite word64_below_pow2_32 by exact (lt16_pow2_32 _ Hroom); reflexivity)']),
}

REFINE['MORPH_DELETE_EXT'] = dict(REFINE['MORPH_DELETE'], fmt=3)
REFINE['MORPH_ID_EXT'] = dict(REFINE['MORPH_ID'], fmt=3)
REFINE['MORPH_ASSERT_EXT'] = dict(
    delete_like('instr_morph_assert (wordToNat AL) property cert (wordToNat C)',
                COST1_PREM + [('Hprop', 'ascii_checksum property = wordToNat E')],
                extra_close=['close_mu_cost_one', 'rewrite Hprop; reflexivity']),
    vars=['property : string', 'cert : string'], rich=FRAME,
    unfold='kami_advance_cert_addr, kami_advance_err_code', fmt=5)
REFINE['MORPH_GET_EXT'] = dict(
    instr='instr_morph_get (wordToNat AL) (wordToNat BL) (wordToNat SEL) (wordToNat C)',
    prem=COST_PREM + INV + [('Hrefs', 'hwb_morph_coupling_refs_ok b'),
                            ('Hz', 'hwb_coupling_desc_zero_invalid b')],
    cases='rewrite (morph_live_valid b _ Hinv) in *. '
          'destruct (hw_morph_valid_table b BL) eqn:G; '
          'try rewrite (Hrefs _ G) in *; cbv beta iota delta [negb] in F_*.',
    rich=FRAME, unfold='kami_advance_reg, kami_write_reg, kami_advance_err_code', fmt=3,
    close=FAULT_CLOSE + ['close_vector_update ltac:(apply morph_get_value_nat; [exact Hz|exact (Hrefs _ G)])'])

REFINE['MORPH_TENSOR'] = dict(
    instr='instr_morph_tensor (wordToNat AL) f g (wordToNat C)', vars=['f : nat', 'g : nat'],
    prem=COST_PREM, cases='idtac.', rich=FRAME, unfold='kami_advance_err_code',
    kami='rewrite snap_graph_tensor_none; cbv beta iota.', close=FAULT_CLOSE)
REFINE['MORPH_TENSOR_EXT'] = dict(REFINE['MORPH_TENSOR'], fmt=3)

PROJ_FIELDS = [f for f in FIELDS if f not in (
    'morph_src_table', 'morph_dst_table', 'morph_coupling_desc_table',
    'morph_identity_table', 'morph_valid_table', 'morph_next_id',
    'coupling_desc_label_table', 'coupling_desc_label_len_table', 'lassert_phase', 'chsh_phase', 'mc_phase')]


def theorem(name, spec):
    low = name.lower()
    fmt = spec.get('fmt')
    bits = BITS if fmt is None else f'{BITS} {EBITS}'
    vars_ = ' '.join(f'({v})' for v in spec.get('vars', []))
    prem = COMMON_PREM + spec.get('prem', [])
    t = f'Theorem step_{low}_refines : forall {bits} (b : HWB) {vars_},\n'
    t += f'  step_fetched b = {low}_word {bits} ->\n'
    t += '  hwb_bianchi b = false -> hw_err b = false -> hw_halted b = false ->\n'
    for _, stmt in prem:
        t += f'  {inline(stmt)} ->\n'
    t += f'  hwb_snapshot (step_next b) = kami_step (hwb_snapshot b) ({inline(spec["instr"])}).\n'
    names = ' '.join(n for n, _ in prem)
    varnames = ' '.join(v.split(':')[0].strip() for v in spec.get('vars', []))
    t += f'Proof.\n  intros {bits} b {varnames} Hf Hb Herr Hhalt {names}.\n'
    for f in FIELDS:
        t += f'  pose proof (step_{low}_{f} {bits} b Hf Hb) as F_{f}.\n'
    allf = ', '.join(f'F_{f}' for f in FIELDS)
    t += '  ' + inline(spec["cases"]).replace('F_*', allf) + '\n'
    t += '  all: unfold hwb_snapshot at 1.\n'
    t += f'  all: {inline(spec["rich"])}.\n'
    t += '  all: rewrite ' + ', '.join(f'F_{f}' for f in PROJ_FIELDS) + '.\n'
    t += ('  all: rewrite step_keeps_csr_status, step_keeps_csr_heap_base, '
          'step_keeps_logic_acc, step_keeps_mstatus.\n')
    t += f'  all: unfold kami_step, {spec["unfold"]}.\n'
    t += '  all: snap_projections; rewrite ?Herr, ?Hhalt.\n'
    t += f'  all: {inline(spec.get("kami", LOOKUP))}\n'
    t += '  all: apply kami_snapshot_ext; snap_projections.\n'
    closers = ['syntactic', 'close_pc', 'close_mu_cost'] + [inline(c) for c in spec.get('close', [])]
    t += '  all: first [ ' + ' | '.join(closers) + ' ].\n'
    t += 'Qed.\n\n'
    return t


def generate(only=None):
    t = HEADER
    count = 0
    for name, spec in REFINE.items():
        if only and name not in only:
            continue
        t += theorem(name, spec)
        count += 1
    return t, count


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--only', nargs='*')
    parser.add_argument('--out')
    args = parser.parse_args()
    generated, count = generate(args.only)
    target = Path(args.out) if args.out else TARGET
    if args.check:
        if target.read_text() != generated:
            raise SystemExit('StepRefineMorph.v is stale; regenerate it')
    else:
        target.write_text(generated)
    print(f'StepRefineMorph: {count} opcode refinements')
