#!/usr/bin/env python3
"""Generate DispatchLets.v: the step rule's decoded action as Gallina.

Every LET of [dispatch_decoded] in ThieleCPUCore.v becomes a definition
[dd_<name> b w], literally [evalExpr] of the same Kami expression with the
action's parameters replaced by the boundary fields that [hwb_decoded]
passes and the fetched word [w]. Every write becomes a field equation for
[step_next] at [w := step_fetched b]. All equations hold by conversion; the
kernel checks each one at Qed.
"""
import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / 'coq/kami_hw/DispatchLets.v'
CPU = ROOT / 'coq/kami_hw/ThieleCPUCore.v'
DECODED = ROOT / 'coq/kami_hw/BoundaryDecoded.v'

PARAM = re.compile(r'^\s*\((\w+)\s*:\s*ty\s*\((.+)\)\)\s*$')


def strip_comments(s):
    out, depth, i = [], 0, 0
    while i < len(s):
        if s.startswith('(*', i):
            depth += 1; i += 2
        elif s.startswith('*)', i) and depth:
            depth -= 1; i += 2
        else:
            if depth == 0:
                out.append(s[i])
            i += 1
    return ''.join(out)


def parse():
    text = CPU.read_text()
    d = text.index('Definition dispatch_decoded')
    head = text[d:text.index(': ActionT ty Void :=', d)]
    params = [PARAM.match(l).groups() for l in head.split('\n') if PARAM.match(l)]
    body = text[text.index(':=\n', d) + 3:text.index(')%kami_action.', d)]
    body = strip_comments(body).strip()
    assert body.startswith('(')
    body = body[1:].strip()
    assert body.endswith('Retv')
    stmts = [s.strip() for s in body[:-len('Retv')].split(';') if s.strip()]
    lets, writes = [], []
    for s in stmts:
        s = ' '.join(s.split())
        m = re.match(r'^LET (\w+)\s*(?::\s*(.+?))?\s*<-\s*(.+)$', s)
        if m:
            lets.append((m.group(1), m.group(2) or 'Bool', m.group(3)))
            continue
        m = re.match(r'^Write "(\w+)"\s*<-\s*(.+)$', s)
        assert m, s
        writes.append((m.group(1), m.group(2)))
    return params, lets, writes


def decoded_args():
    text = DECODED.read_text()
    d = text.index('Definition hwb_decoded')
    body = text[text.index('dispatch_decoded', d) + len('dispatch_decoded'):
                text.index('.\n', d)]
    args = []
    for line in body.split('\n'):
        line = line.strip()
        if not line:
            continue
        if line == 'instruction':
            args.append('w')
        else:
            assert line.startswith('(') and line.endswith(')'), line
            args.append(line)
    return args


def generate():
    params, lets, writes = parse()
    args = decoded_args()
    assert len(params) == len(args), (len(params), len(args))
    env = {}
    for (name, kind), arg in zip(params, args):
        env[name] = (arg, kind)
    t = '''(** DispatchLets.v: generated by scripts/generate_dispatch_lets.py.
    The step rule's decoded action as Gallina: each LET of [dispatch_decoded]
    is [evalExpr] of the same Kami expression over the boundary fields and the
    fetched word [w], and each write is a field equation of [step_next]. All
    equations hold by conversion. *)
Require Import Kami.Kami Kami.Semantics.
From Coq Require Import String.
From KamiHW Require Import ThieleTypes ThieleCPUCore HWBoundary RuleNext
  BoundaryDecoded RuleStep.

(** The kernel checks each conversion when the proof term is checked at
    [Qed]; the tactic unifier is far slower on these terms. *)
Ltac kernel_refl := match goal with |- ?x = _ => exact_no_check (eq_refl x) end.

'''

    def subst(expr):
        def rep(m):
            v = m.group(1)
            term, kind = env[v]
            return f'(Var type (SyntaxKind ({kind})) {term})'
        return re.sub(r'#(\w+)', rep, expr)

    for name, kind, expr in lets:
        t += (f'Definition dd_{name} (b : HWB) (w : word InstrSz) : type ({kind}) :=\n'
              f'  evalExpr ({subst(expr)})%kami_expr.\n')
        env[name] = (f'(dd_{name} b w)', kind)
    t += '\n'
    for reg, expr in writes:
        m = re.match(r'^#(\w+)$', expr)
        if m and m.group(1) in env and env[m.group(1)][0].startswith('(dd_'):
            rhs = env[m.group(1)][0][1:-1]
        else:
            rhs = f'evalExpr ({subst(expr)})%kami_expr'
        rhs = rhs.replace(' b w)', ' b (step_fetched b))')
        rhs = re.sub(r' b w$', ' b (step_fetched b)', rhs)
        rhs = rhs.replace(' w)', ' (step_fetched b))')
        t += (f'Lemma step_next_{reg} : forall b,\n'
              f'  hw_{reg} (step_next b) = {rhs}.\n'
              'Proof. intro b. kernel_refl. Qed.\n')
    return t, len(lets), len(writes)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--out')
    args = parser.parse_args()
    generated, nl, nw = generate()
    target = Path(args.out) if args.out else TARGET
    if args.check:
        if target.read_text() != generated:
            raise SystemExit('DispatchLets.v is stale; regenerate it')
    else:
        target.write_text(generated)
    print(f'DispatchLets: {nl} LET definitions, {nw} write equations')
