#!/usr/bin/env python3
"""Generate an FSM-rule decoding file for rules of ThieleCPUCore.thieleCore.

For each rule (given as RULE:INDEX:PREFIX) whose reads and assertions all
precede its other statements, the generated file defines
  <prefix>_decoded : the rule's statements after its reads, as a pure action
                     over the read values (checked equal to the rule by
                     conversion in <prefix>_rule_action);
  <prefix>_observer : at a typed boundary the rule's observations are those of
                     the decoded action applied to the boundary fields;
  <prefix>_next     : the explicit next-state record, with every LET as
                     [evalExpr] of the rule's own expression, proved equal to
                     [rule_next (normalization_rule INDEX) b];
  <prefix>_enabled  : when the rule's assertions hold, it evaluates and its
                     update produces [<prefix>_next b].

Usage: generate_fsm_decoded.py OUTFILE RULE:INDEX:PREFIX ...
"""
import argparse
import re
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'scripts'))
from generate_fsm_next import rule_body, hwb_fields, subst  # noqa: E402

READ = re.compile(r'^Read (\w+)\s*:\s*(.+?)\s*<-\s*"(\w+)"$')


def raw_rule_text(name):
    text = (ROOT / 'coq/kami_hw/ThieleCPUCore.v').read_text()
    i = text.index(f'with Rule "{name}" :=') + len(f'with Rule "{name}" :=')
    nxt = [k for k in (text.find('with Rule "', i), text.find('with Method "', i)) if k > 0]
    return text[i:min(nxt)].rstrip()


def split_rule(name):
    stmts = rule_body(name)
    prefix, rest = [], []
    for s in stmts:
        if not rest and (READ.match(s) or s.startswith('Assert')):
            prefix.append(s)
        else:
            rest.append(s)
    return prefix, rest


def generate(specs):
    fields = hwb_fields()
    t = '''(** Generated by scripts/generate_fsm_decoded.py. Each listed CPU FSM rule is
    its register reads and assertions followed by a pure decoded action; at a
    typed boundary its next state is an explicit record whose fields are
    [evalExpr] of the rule's own expressions. *)
Require Import Kami.Kami Kami.Semantics.
From Coq Require Import String List Bool.
From KamiHW Require Import ThieleTypes ThieleCPUCore HWBoundary HWBoundaryReads ActionEvaluator
  ActionObservation ReadFreeObservation NormalizationSteps CoreRules CoreExecution CoreTyping
  RuleNext RuleStep RuleEnabled.
Import ListNotations.
Open Scope string_scope.

Ltac kernel_refl := match goal with |- ?x = _ => exact_no_check (eq_refl x) end.

'''
    for rule, index, p in specs:
        pre, rest = split_rule(rule)
        reads = [READ.match(s).groups() for s in pre if READ.match(s)]
        late = [READ.match(s).groups() for s in rest if READ.match(s)]
        asserts = [s for s in pre if s.startswith('Assert')]
        names = [n for n, _, _ in reads]
        params = ' '.join(f'({n} : type ({k}))' for n, k, _ in reads)
        body = ';\n    '.join(rest) + ';\n    Retv'
        call = f'{p}_decoded ' + ' '.join(names)
        fetch = ';\n    '.join(pre) + ';\n    ' + call
        regs = list(dict.fromkeys(r for _, _, r in reads))
        alts = '\n  '.join(f'| rewrite hwb_read_{r}' for r in regs)
        args = ' '.join(f'(hw_{r} b)' for _, _, r in reads)
        late_names = [n for n, _, _ in late]
        late_params = ' '.join(f'({n} : type ({k}))' for n, k, _ in late)
        late_args = ' '.join(f'(hw_{r} b)' for _, _, r in late)
        rf_body = ';\n    '.join(s for s in rest if not READ.match(s)) + ';\n    Retv'
        alts_all = '\n  '.join(f'| rewrite hwb_read_{r}' for r in dict.fromkeys(r for _, _, r in reads + late))
        t += f'''(** * Rule {rule} *)

Definition {p}_decoded {params} : ActionT type Void :=
  ({body})%kami_action.

Definition {p}_fetch_action : ActionT type Void :=
  ({fetch})%kami_action.

'''
        t += f'''Lemma {p}_rule_action : attrType (normalization_rule {index}) type = {p}_fetch_action.
Proof. reflexivity. Qed.

'''
        if not late:
            t += f'''Lemma {p}_decoded_read_free : forall {' '.join(names)},
  read_free_action ({p}_decoded {' '.join(names)}).
Proof. intros. unfold {p}_decoded. repeat (cbn [read_free_action]; intro). exact I. Qed.

Lemma {p}_decoded_total : forall {' '.join(names)},
  total_from nil ({p}_decoded {' '.join(names)}).
Proof. intros. unfold {p}_decoded. repeat (cbn [total_from existsb String.eqb Ascii.eqb Bool.eqb]; intro). exact I. Qed.

Definition hwb_{p}_decoded (b : HWB) : ActionT type Void := {p}_decoded {args}.

Local Opaque {p}_decoded.
Theorem {p}_observer : forall b key,
  observe_action_write (hwb_regs b) key (attrType (normalization_rule {index}) type) =
  observe_action_write (M.empty _) key (hwb_{p}_decoded b).
Proof.
  intros b key. rewrite {p}_rule_action. unfold {p}_fetch_action, hwb_{p}_decoded.
  repeat first [progress cbn [observe_action_write]
  {alts}].
  apply observe_read_free_action. apply {p}_decoded_read_free.
Qed.
Local Transparent {p}_decoded.

'''
        else:
            t += f'''Definition {p}_decoded_rf {params} {late_params} : ActionT type Void :=
  ({rf_body})%kami_action.

Lemma {p}_decoded_rf_read_free : forall {' '.join(names)} {' '.join(late_names)},
  read_free_action ({p}_decoded_rf {' '.join(names)} {' '.join(late_names)}).
Proof. intros. unfold {p}_decoded_rf. repeat (cbn [read_free_action]; intro). exact I. Qed.

Definition hwb_{p}_decoded (b : HWB) : ActionT type Void := {p}_decoded_rf {args} {late_args}.

Theorem {p}_observer : forall b key,
  observe_action_write (hwb_regs b) key (attrType (normalization_rule {index}) type) =
  observe_action_write (M.empty _) key (hwb_{p}_decoded b).
Proof.
  intros b key. rewrite {p}_rule_action. unfold {p}_fetch_action, hwb_{p}_decoded, {p}_decoded, {p}_decoded_rf.
  repeat first [progress cbn [observe_action_write]
  {alts_all}].
  first [ (apply observe_read_free_action; repeat (cbn [read_free_action]; intro); exact I) | reflexivity ].
Qed.

'''
        env = {n: (f'(hw_{r} b)', k) for n, k, r in reads + late}
        writes = {}
        for s in rest:
            if READ.match(s):
                continue
            m = re.match(r'^LET (\w+)\s*(?::\s*(.+?))?\s*<-\s*(.+)$', s)
            if m:
                name, kind, expr = m.group(1), m.group(2) or 'Bool', m.group(3)
                t += (f'Definition {p}_{name} (b : HWB) : type ({kind}) :=\n'
                      f'  evalExpr ({subst(expr, env)})%kami_expr.\n')
                env[name] = (f'({p}_{name} b)', kind)
                continue
            m = re.match(r'^Write "(\w+)"\s*<-\s*(.+)$', s)
            assert m, (rule, s)
            writes[m.group(1)] = m.group(2)
        rows = [f'hw_{f} := evalExpr ({subst(writes[f], env)})%kami_expr' if f in writes
                else f'hw_{f} := hw_{f} b' for f, _ in fields]
        t += f'\nDefinition {p}_next (b : HWB) : HWB :=\n  {{| ' + ';\n     '.join(rows) + ' |}.\n\n'
        t += f'''Lemma {p}_after_next : forall b,
  hwb_after b (fun key => observe_action_write (M.empty _) key (hwb_{p}_decoded b)) = {p}_next b.
Proof. intro b. kernel_refl. Qed.

Lemma {p}_rule_next : forall b, rule_next (normalization_rule {index}) b = {p}_next b.
Proof.
  intro b. transitivity (hwb_after b (fun key => observe_action_write (M.empty _) key (hwb_{p}_decoded b))).
  - unfold rule_next. apply hwb_after_ext. intro key. apply {p}_observer.
  - apply {p}_after_next.
Qed.

'''
        dec_unfold = f', {p}_decoded' if late else ''
        total_tac = ('(repeat (cbn [total_from existsb String.eqb Ascii.eqb Bool.eqb]; intro); exact I)'
                     if late else f'apply {p}_decoded_total')
        guards = ' /\\ '.join(f'evalExpr ({subst(a[len("Assert"):].strip(), env)})%kami_expr = true' for a in asserts) or 'True'
        t += f'''Theorem {p}_enabled : forall b,
  {guards} ->
  exists u, eval_cpu_rule (hwb_regs b) (normalization_rule {index}) = Some u /\\
    M.union u (hwb_regs b) = hwb_regs ({p}_next b).
Proof.
  intros b Hg.
  assert (He : exists u, eval_cpu_rule (hwb_regs b) (normalization_rule {index}) = Some u).
  {{ unfold eval_cpu_rule. rewrite {p}_rule_action. unfold {p}_fetch_action{dec_unfold}.
    repeat first [progress cbn [eval_linear_action]
    {alts_all}].
    repeat match goal with H : _ /\\ _ |- _ => destruct H end.
    repeat match goal with H : evalExpr ?e = true |- context [if evalExpr ?e then _ else _] => rewrite H end.
    first [ (match goal with |- context [eval_linear_action ?o ?a] =>
               assert (T : total_from nil a) by {total_tac};
               destruct (total_from_eval _ a nil o T) as [u [ret [E' _]]]; rewrite E'
             end; eexists; reflexivity)
          | (eexists; reflexivity) ]. }}
  destruct He as [u Hu]. exists u. split; [exact Hu|].
  rewrite <- {p}_rule_next. apply rule_next_correct; [|exact Hu].
  rewrite cpu_rules_listed. apply in_map. cbn [In]. auto 13.
Qed.

'''
    return t


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('out')
    parser.add_argument('specs', nargs='+')
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    specs = [tuple(s.split(':')) for s in args.specs]
    generated = generate(specs)
    target = Path(args.out)
    if args.check:
        if target.read_text() != generated:
            raise SystemExit(f'{target.name} is stale; regenerate it')
    else:
        target.write_text(generated)
    print(f'{target.name}: {len(specs)} decoded FSM rules')
