#!/usr/bin/env python3
"""Generate ChshPhases.v: the CHSH_LASSERT FSM step at each concrete phase.

For every phase 1..29 and every register the FSM rule writes, the value after
[chsh_next] is stated with the phase multiplexers resolved. In phases 1..20
the one scratch register of that phase receives the product of its two
operands (as [m128] or [m256] from ChshArith.v). In phases 21..24 chsh_C_sq
and in 25..28 chsh_A_times_B accumulate the four partial products of their
operand halves. Every other scratch register keeps its value, the phase
advances, and at phase 29 the check result and the trap commit are written.
Operands and result widths are read from ThieleCPUCore.v.
"""
import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / 'coq/kami_hw/ChshPhases.v'
CPU = ROOT / 'coq/kami_hw/ThieleCPUCore.v'


LAST = 29
ACCUMULATORS = {'chsh_C_sq': 21, 'chsh_A_times_B': 25}


def mux(text, name):
    i = text.index(f'LET {name} : Bit 128 <-')
    j = text.index('else $0;', i)
    return {int(k): v for k, v in re.findall(r'IF #phase_eq_(\d+)\s+then #(\w+)', text[i:j])}


def operand(v):
    """Gallina term of mux entry v at boundary b."""
    for half, cut in (('_lo', 'split1'), ('_hi', 'split2')):
        if v.endswith(half) and v[:-len(half)] in ('abs_C', 'abs_A', 'abs_B'):
            return f'({cut} 128 128 (chsh_{v[:-len(half)]}_256 b))'
    if v.endswith('_128'):
        return f'(hw_chsh_{v[:-len("_128")]} b)'
    assert v.startswith('chsh_') and v.endswith('_v'), v
    return f'(hw_{v[:-len("_v")]} b)'


def accumulate(k, prev, a, b):
    """The value an accumulator holds after its (k+1)-th phase."""
    if k == 0:
        return f'evalZeroExtendTrunc 384 (m256 {a} {b})'
    if k in (1, 2):
        return f'wplus {prev} (combine (natToWord 128 0) (m256 {a} {b}))'
    return f'wplus {prev} (combine (natToWord 256 0) (split1 128 128 (m256 {a} {b})))'


def parse():
    text = CPU.read_text()
    d = text.index('Definition chsh_fsm_decoded')
    body = text[d:text.index(')%kami_action.', d)]
    opa, opb = mux(body, 'op_a_128'), mux(body, 'op_b_128')
    scratch = {}
    for reg, k, width in re.findall(r'Write "(chsh_\w+)"\s*<- IF #phase_eq_(\d+)\s+then #mult_(\d+)', body):
        scratch[reg] = (int(k), width)
    return opa, opb, scratch


def generate():
    opa, opb, scratch = parse()
    assert len(scratch) == 20, scratch
    t = '''(** ChshPhases.v: generated by scripts/generate_chsh_phases.py.
    The CHSH_LASSERT FSM rule at each concrete phase, with the phase
    multiplexers resolved. Each equation is checked by the kernel. *)
Require Import Kami.Kami Kami.Semantics.
From Coq Require Import String.
From KamiHW Require Import ThieleTypes ThieleCPUCore HWBoundary RuleNext ChshDecoded ChshArith ChshFsm.

(** Resolve the phase multiplexers with tactics before conversion: left to the
    kernel, the same check unfolds the wide word operations and takes minutes. *)
Ltac phase_mux :=
  cbn [evalExpr evalUniBool evalBinBitBool evalConstT isEq evalUniBit evalBinBit];
  repeat match goal with |- context [weq ?x ?y] =>
    let v := eval vm_compute in (if weq x y then true else false) in
    change (if weq x y then true else false) with v end;
  cbv beta iota.

Ltac phase_unfold :=
  unfold chsh_commit_trap, chsh_part_0, chsh_part_128, chsh_part_256, chsh_mult_128, chsh_mult_256,
    chsh_op_a_128, chsh_op_b_128, ''' + ', '.join(f'chsh_phase_eq_{k}' for k in range(1, LAST + 1)) + '''.

'''
    for k in range(1, LAST + 1):
        for j in range(1, LAST + 1):
            val = 'true' if k == j else 'false'
            t += (f'Lemma chsh_eq{k}_at{j} : forall b, hw_chsh_phase b = natToWord 5 {j} -> chsh_phase_eq_{k} b = {val}.\n'
                  f'Proof. intros b H. unfold chsh_phase_eq_{k}. cbn [evalExpr evalConstT isEq]. rewrite H. reflexivity. Qed.\n')
    t += '\n'
    count = 0
    for j in range(1, LAST + 1):
        rows = []
        for reg, (k, width) in scratch.items():
            if k == j:
                rows.append((reg, f'm{width} {operand(opa[k])} {operand(opb[k])}',
                             'phase_unfold. rewrite H. phase_mux. unfold m128, m256. reflexivity.'))
            else:
                rows.append((reg, f'hw_{reg} b', f'rewrite (chsh_eq{k}_at{j} b H). kernel_refl.'))
        for reg, s in ACCUMULATORS.items():
            if s <= j < s + 4:
                rhs = accumulate(j - s, f'(hw_{reg} b)', operand(opa[j]), operand(opb[j]))
                rows.append((reg, rhs, 'phase_unfold. rewrite H. phase_mux. unfold m256. reflexivity.'))
            else:
                eqs = ' '.join(f'rewrite (chsh_eq{k}_at{j} b H).' for k in range(s, s + 4))
                rows.append((reg, f'hw_{reg} b', f'{eqs} kernel_refl.'))
        e_last = f'rewrite (chsh_eq{LAST}_at{j} b H).'
        if j == LAST:
            rows += [('chsh_check_result', 'chsh_final_ok b', f'{e_last} kernel_refl.'),
                     ('pc', 'if negb (chsh_final_ok b) then hw_trap_vector b else hw_pc b',
                      f'unfold chsh_commit_trap. {e_last} kernel_refl.'),
                     ('err', 'if negb (chsh_final_ok b) then true else hw_err b',
                      f'unfold chsh_commit_trap. {e_last} kernel_refl.'),
                     ('error_code', 'if negb (chsh_final_ok b) then ERR_LOGIC_VAL else hw_error_code b',
                      f'unfold chsh_commit_trap. {e_last} kernel_refl.'),
                     ('chsh_phase', 'natToWord 5 0', f'{e_last} kernel_refl.')]
        else:
            rows += [('chsh_check_result', 'hw_chsh_check_result b', f'{e_last} kernel_refl.'),
                     ('pc', 'hw_pc b', f'unfold chsh_commit_trap. {e_last} kernel_refl.'),
                     ('err', 'hw_err b', f'unfold chsh_commit_trap. {e_last} kernel_refl.'),
                     ('error_code', 'hw_error_code b', f'unfold chsh_commit_trap. {e_last} kernel_refl.'),
                     ('chsh_phase', f'natToWord 5 {j + 1}', f'{e_last} rewrite H. kernel_refl.')]
        for reg, rhs, proof in rows:
            t += (f'Lemma chsh_phase{j}_{reg} : forall b, hw_chsh_phase b = natToWord 5 {j} ->\n'
                  f'  hw_{reg} (chsh_next b) = {rhs}.\n'
                  f'Proof. intros b H. rewrite chsh_next_{reg}. {proof} Qed.\n')
            count += 1
        t += '\n'
    return t, count


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--out')
    args = parser.parse_args()
    generated, count = generate()
    target = Path(args.out) if args.out else TARGET
    if args.check:
        if target.read_text() != generated:
            raise SystemExit('ChshPhases.v is stale; regenerate it')
    else:
        target.write_text(generated)
    print(f'ChshPhases: {count} phase equations')
