#!/usr/bin/env python3
"""Strip non-synthesizable constructs from Verilog for FPGA synthesis."""

import re
import sys
from pathlib import Path

def make_synthesizable(input_path: Path, output_path: Path):
    """Remove non-synthesizable constructs from Verilog file."""
    
    with open(input_path, 'r') as f:
        lines = f.readlines()
    
    output_lines = []
    skip_next = False
    
    for i, line in enumerate(lines):
        # Skip $display statements and their continuation lines
        if '$display' in line:
            # Check if the line ends with a semicolon
            if ';' not in line:
                skip_next = True
            continue
        
        if skip_next:
            if ');' in line or ';' in line:
                skip_next = False
            continue
        
        # Skip other simulation-only constructs
        if any(construct in line for construct in ['$readmemh', '$write', '$finish', 
                                                     '$dumpfile', '$dumpvars', '$monitor']):
            continue
        
        # Fix dynamic loop bounds - replace with maximum value
        if 'for (i = 0; i < next_module_id; i = i + 1)' in line:
            # Replace with NUM_MODULES (64) and add guard
            line = line.replace('i < next_module_id', 'i < NUM_MODULES')
            output_lines.append(line)
            # Add comment explaining the change
            output_lines.append('                // SYNTH: Using max bound; check validity inside loop\n')
            continue
        
        output_lines.append(line)
    
    # Add synthesis header
    header = """// ============================================================================
// SYNTHESIZABLE VERSION
// ============================================================================
// This file is auto-generated from thiele_cpu.v with non-synthesizable
// constructs removed for FPGA/ASIC synthesis.
//
// Differences from simulation version:
// - All $display statements removed
// - Dynamic loop bounds replaced with static maximums
// - Simulation-only constructs removed
//
// Generated by: scripts/make_synthesizable.py
// ============================================================================

"""
    
    # Insert header after license block
    final_lines = []
    license_end = 0
    for i, line in enumerate(output_lines):
        if 'timescale' in line:
            license_end = i
            break
    
    final_lines = output_lines[:license_end] + [header] + output_lines[license_end:]
    
    with open(output_path, 'w') as f:
        f.writelines(final_lines)
    
    print(f"✓ Created synthesizable version: {output_path}")
    print(f"  Removed ~{len(lines) - len(final_lines)} non-synthesizable lines")

if __name__ == '__main__':
    repo_root = Path(__file__).resolve().parents[1]
    hw_dir = repo_root / 'thielecpu' / 'hardware'
    
    input_file = hw_dir / 'thiele_cpu.v'
    output_file = hw_dir / 'thiele_cpu_synth.v'
    
    make_synthesizable(input_file, output_file)
