(*** Autogenerated by scripts/translate_receipts_to_coq.py.
      Do not edit by hand.  Regenerate via scripts/prove_it_all.sh. ***)

        Require Import List.
        Require Import Nat.
        Require Import Sandbox.VerifiedGraphSolver.

        Import ListNotations.
        Import VerifiedGraphSolver.

        Definition receipt_claims : list (nat * colour) := [ (0, Red); (1, Green) ].
        Definition receipt_propagation : list nat := [ 2; 3; 4; 5; 6; 7; 8 ].

        Definition replay_claims (σ : thiele_state) : thiele_state :=
          fold_left (fun st '(node, colour) => claim st node colour) receipt_claims σ.

        Definition replay_propagation (σ : thiele_state) : thiele_state :=
          fold_left propagate_node receipt_propagation σ.

        Definition receipt_run : thiele_state :=
          replay_propagation (replay_claims thiele_empty).

        Definition receipt_solution : list (nat * colour) := [ (0, Red); (1, Green); (2, Blue); (3, Red); (4, Green); (5, Blue); (6, Red); (7, Green); (8, Blue) ].

        Definition receipt_expected : thiele_state :=
          {|
  state_partial := canonical_partial;
  state_mu := 23;
  state_arith := 0
|}.

        Lemma receipt_run_matches_expected : receipt_run = receipt_expected.
        Proof.
          unfold receipt_run, receipt_expected, replay_propagation, replay_claims.
          vm_compute.
          reflexivity.
        Qed.

        Lemma thiele_run_matches_expected : thiele_run = receipt_expected.
        Proof.
          unfold receipt_expected, thiele_run.
          vm_compute.
          reflexivity.
        Qed.

        Theorem python_receipt_sound : receipt_run = thiele_run.
        Proof.
          transitivity receipt_expected; [apply receipt_run_matches_expected |].
          symmetry; apply thiele_run_matches_expected.
        Qed.

        (* Recorded metrics from the receipts: *)
        Definition receipt_mu_cost : nat := 23.
        Definition receipt_targeted_checks : nat := 0.
        Definition receipt_solver_queries : nat := 21.
