#!/bin/bash
# Release script for self-hosting Thiele kernel
# Creates a tagged release with all verification artifacts

set -euo pipefail

echo "=== Thiele Kernel Release Script ==="
echo ""

# Configuration
VERSION=${1:-"v1.0"}
RELEASE_DIR="release_${VERSION}"

# Step 1: Clean workspace
echo "1. Cleaning workspace..."
rm -rf "$RELEASE_DIR" dist/
rm -f thiele_min.py hello.txt

# Step 2: Run all checks
echo "2. Running verification checks..."
python3 verifier/replay.py bootstrap_receipts

# Verify hash
ACTUAL_HASH=$(sha256sum thiele_min.py | awk '{print $1}')
EXPECTED_HASH=$(cat tests/expected_kernel_sha256.txt)

if [ "$ACTUAL_HASH" != "$EXPECTED_HASH" ]; then
    echo "✗ ERROR: Hash mismatch!"
    echo "  Expected: $EXPECTED_HASH"
    echo "  Actual: $ACTUAL_HASH"
    exit 1
fi
echo "✓ Kernel hash verified"

# Verify self-check
python3 thiele_min.py --verify bootstrap_receipts/050_kernel_emit.json
echo "✓ Kernel self-verification passed"

# Run integrity proof
python3 tools/prove_integrity.py
echo "✓ Integrity proof passed"

# Check LoC budget
LOC=$(python3 -c "
with open('verifier/replay.py', 'r') as f:
    lines = f.readlines()
print(sum(1 for line in lines if line.strip() and not line.strip().startswith('#')))
")

if [ "$LOC" -gt 220 ]; then
    echo "✗ ERROR: Verifier exceeds LoC budget ($LOC > 220)"
    exit 1
fi
echo "✓ LoC budget OK ($LOC / 220)"

# Step 3: Create proof pack
echo ""
echo "3. Creating proof pack..."
python3 tools/make_proofpack.py
echo "✓ Proof pack created"

# Step 4: Create release directory
echo ""
echo "4. Packaging release..."
mkdir -p "$RELEASE_DIR"

# Copy essential files
cp -r bootstrap_receipts "$RELEASE_DIR/"
cp -r verifier "$RELEASE_DIR/"
cp -r docs "$RELEASE_DIR/"
cp -r attestations "$RELEASE_DIR/"
cp -r checksums "$RELEASE_DIR/"
cp -r tests/expected_kernel_sha256.txt "$RELEASE_DIR/"
cp README.md "$RELEASE_DIR/"
cp LICENSE "$RELEASE_DIR/"
cp SELF_HOSTING_KERNEL.md "$RELEASE_DIR/"

# Copy proof pack
cp dist/proofpack.tar.* "$RELEASE_DIR/"

# Step 5: Generate RELEASE_NOTES.md
echo ""
echo "5. Generating release notes..."

cat > "$RELEASE_DIR/RELEASE_NOTES.md" << EOF
# Thiele Self-Hosting Kernel Release $VERSION

**Release Date:** $(date -u +"%Y-%m-%d %H:%M:%S UTC")

## Quick Start

\`\`\`bash
# One-line verification
python3 verifier/replay.py bootstrap_receipts && sha256sum thiele_min.py
\`\`\`

## Hashes

- **Kernel SHA256:** \`$EXPECTED_HASH\`
- **Global Digest:** \`$(python3 verifier/replay.py --print-digest bootstrap_receipts)\`
- **Verifier LoC:** $LOC (budget: 220)

## What's Included

- \`bootstrap_receipts/\` - Cryptographic receipts (7 steps)
- \`verifier/replay.py\` - Receipt verifier ($LOC LoC TCB)
- \`verifier/replay_sh.sh\` - Shell-based verifier (POSIX)
- \`docs/\` - Complete documentation
- \`attestations/\` - SBOM, reproducibility guide, TCB metrics
- \`proofpack.tar.*\` - Self-contained proof bundle

## Verification

### Full Verification

\`\`\`bash
python3 verifier/replay.py bootstrap_receipts && \\
python3 thiele_min.py --verify bootstrap_receipts/050_kernel_emit.json && \\
sha256sum thiele_min.py
\`\`\`

### Expected Output

\`\`\`
Materialized: thiele_min.py (8348 bytes, sha256=$EXPECTED_HASH)
Receipt verification complete. All invariants satisfied.
Receipt verification OK
Global digest: $(python3 verifier/replay.py --print-digest bootstrap_receipts)
$EXPECTED_HASH  thiele_min.py
\`\`\`

## Security Properties

- **Minimal TCB:** Only $LOC lines of verifier code
- **Cryptographic integrity:** Hash chains + global digest
- **Deterministic:** Same receipts → identical kernel on any platform
- **Self-verifying:** Kernel can verify its own construction
- **No dependencies:** Pure Python stdlib

## Documentation

- **Architecture:** See SELF_HOSTING_KERNEL.md
- **Receipt Schema:** docs/receipt_schema.md
- **Reproducibility:** attestations/REPRODUCIBILITY.md
- **SBOM:** attestations/SBOM.md

## Checksums

\`\`\`
$(cat checksums/receipts_sha256.txt)
\`\`\`

## License

Apache-2.0

---

Generated by \`tools/release.sh\` on $(date -u +"%Y-%m-%d")
EOF

echo "✓ Release notes generated"

# Step 6: Create tarball
echo ""
echo "6. Creating release tarball..."
tar -czf "${RELEASE_DIR}.tar.gz" "$RELEASE_DIR"
TARBALL_HASH=$(sha256sum "${RELEASE_DIR}.tar.gz" | awk '{print $1}')

echo "✓ Release tarball created: ${RELEASE_DIR}.tar.gz"
echo "  SHA256: $TARBALL_HASH"

# Step 7: Summary
echo ""
echo "=== Release $VERSION Complete ==="
echo ""
echo "Artifacts:"
echo "  • ${RELEASE_DIR}.tar.gz ($TARBALL_HASH)"
echo "  • ${RELEASE_DIR}/proofpack.tar.*"
echo ""
echo "To create GitHub release:"
echo "  git tag $VERSION"
echo "  git push origin $VERSION"
echo "  gh release create $VERSION ${RELEASE_DIR}.tar.gz \\"
echo "    --title 'Self-Hosting Kernel $VERSION' \\"
echo "    --notes-file ${RELEASE_DIR}/RELEASE_NOTES.md"
echo ""
echo "To test release:"
echo "  tar -xzf ${RELEASE_DIR}.tar.gz"
echo "  cd ${RELEASE_DIR}"
echo "  python3 verifier/replay.py bootstrap_receipts"
