(** * Local Morphism Support Semantics for PSPLIT Subsystems

    WHY THIS FILE EXISTS:
    EntanglementEntropy.v currently states area-law bounds from an explicit
    locality hypothesis. This file introduces a split-morphism support
    semantics and a nearest-neighbor predicate that exposes that locality
    condition at morphism level.

    BRIDGE THEOREM:
    local_morphism_support_bound
      is_nearest_neighbor P
      + support reachable by P
      -> boundary_local_support on (split_left P, split_right P).
*)

From Coq Require Import List Bool Arith.PeanoNat Lia.
Import ListNotations.

From Kernel Require Import VMState.
From Kernel Require Import VMStep.
From Kernel Require Import MuCostModel.
From Kernel Require Import SimulationProof.

(** Joint support of a bipartite state in finite coordinates (a,b). *)
Definition joint_support := list (nat * nat).

(** Boundary edges on a 1D cell lattice: an edge crosses the split when
    consecutive cells belong to opposite regions. *)
Definition cut_edge_1d (left right : list nat) (x : nat) : bool :=
  orb (andb (nat_list_mem x left) (nat_list_mem (S x) right))
      (andb (nat_list_mem x right) (nat_list_mem (S x) left)).

(** Boundary size of the split interface (1D discretization). *)
Definition boundary_size_1d (left right : list nat) : nat :=
  List.length (filter (cut_edge_1d left right)
    (normalize_region (left ++ right))).

(** Partial trace over the right subsystem at support level:
    project support onto left coordinates. *)
Definition partial_trace_right_support (support : joint_support) : list nat :=
  nodup Nat.eq_dec (map fst support).

(** Reduced support on subsystem A after tracing out B. *)
Definition reduced_state_support (support : joint_support) : list nat :=
  partial_trace_right_support support.

(** Locality condition used by area-law proofs. *)
Definition boundary_local_support
  (left right : list nat)
  (support : joint_support) : Prop :=
  List.length (reduced_state_support support) <=
  Nat.pow 2 (boundary_size_1d left right).

(** Split morphism semantics: explicit split regions + reachable joint supports. *)
Record SplitMorphism := {
  split_left : list nat;
  split_right : list nat;
  coupling_pairs : list (nat * nat);
  morphism_support_semantics : list joint_support;

  (** Every declared coupling connects left to right. *)
  coupling_pairs_wf :
    forall a b,
      In (a, b) coupling_pairs ->
      In a split_left /\ In b split_right;

  (** Reachable reduced-support modes are generated by declared couplings. *)
  support_generated_by_couplings :
    forall support,
      In support morphism_support_semantics ->
      forall a,
        In a (reduced_state_support support) ->
        exists b, In (a, b) coupling_pairs
}.

Definition coupled (P : SplitMorphism) (a b : nat) : Prop :=
  In (a, b) (coupling_pairs P).

(** Nearest-neighbor locality at morphism level:
    couplings only occur across cut-adjacent boundary cells. *)
Definition is_nearest_neighbor (P : SplitMorphism) : Prop :=
  forall a,
    In a (split_left P) ->
    forall b,
      In b (split_right P) ->
      coupled P a b ->
      cut_edge_1d (split_left P) (split_right P) a = true.

Lemma nodup_nat_NoDup :
  forall xs,
    NoDup (nodup Nat.eq_dec xs).
Proof.
  induction xs as [|x xs IH]; simpl.
  - constructor.
  - destruct (in_dec Nat.eq_dec x xs) as [Hin | Hnotin].
    + exact IH.
    + constructor.
      * intro Hcontra.
        apply nodup_In in Hcontra.
        contradiction.
      * exact IH.
Qed.

Lemma reduced_support_nodup :
  forall support,
    NoDup (reduced_state_support support).
Proof.
  intro support.
  unfold reduced_state_support, partial_trace_right_support.
  apply nodup_nat_NoDup.
Qed.

Lemma in_normalize_union_of_left :
  forall left right a,
    In a left ->
    In a (normalize_region (left ++ right)).
Proof.
  intros left right a Hin.
  unfold normalize_region.
  apply nodup_In.
  apply in_or_app. left. exact Hin.
Qed.

Lemma reduced_support_in_boundary_carrier :
  forall (P : SplitMorphism) (support : joint_support) (a : nat),
    is_nearest_neighbor P ->
    In support (morphism_support_semantics P) ->
    In a (reduced_state_support support) ->
    In a
      (filter (cut_edge_1d (split_left P) (split_right P))
        (normalize_region (split_left P ++ split_right P))).
Proof.
  intros P support a Hnn Hin_sem Hin_red.
  destruct (support_generated_by_couplings P support Hin_sem a Hin_red) as [b Hpair].
  pose proof (coupling_pairs_wf P a b Hpair) as [Hin_left Hin_right].
  assert (Hcut : cut_edge_1d (split_left P) (split_right P) a = true).
  { apply (Hnn a Hin_left b Hin_right). exact Hpair. }
  apply filter_In.
  split.
  - apply in_normalize_union_of_left. exact Hin_left.
  - exact Hcut.
Qed.

Lemma reduced_support_length_le_boundary_size :
  forall (P : SplitMorphism) (support : joint_support),
    is_nearest_neighbor P ->
    In support (morphism_support_semantics P) ->
    List.length (reduced_state_support support) <=
    boundary_size_1d (split_left P) (split_right P).
Proof.
  intros P support Hnn Hin_sem.
  unfold boundary_size_1d.
  apply NoDup_incl_length.
  - apply reduced_support_nodup.
  - intros a Ha.
    eapply reduced_support_in_boundary_carrier; eauto.
Qed.

Lemma pow2_ge_1 : forall n, 1 <= Nat.pow 2 n.
Proof.
  induction n as [|n IH].
  - simpl. lia.
  - simpl. lia.
Qed.

Lemma nat_le_pow2_self : forall n, n <= Nat.pow 2 n.
Proof.
  induction n as [|n IH].
  - simpl. lia.
  - change (S n <= Nat.pow 2 (S n)).
    simpl.
    assert (Hpow1 : 1 <= Nat.pow 2 n).
    { apply pow2_ge_1. }
    assert (Hsn : S n <= S (Nat.pow 2 n)).
    { lia. }
    assert (Hstep : S (Nat.pow 2 n) <= 2 * Nat.pow 2 n).
    { lia. }
    lia.
Qed.

(** ------------------------------------------------------------------------
    PSPLIT-to-SplitMorphism bridge (execution-level connection)
    ------------------------------------------------------------------------ *)

Definition cartesian_pairs (xs ys : list nat) : list (nat * nat) :=
  flat_map (fun x => map (fun y => (x, y)) ys) xs.

Lemma in_map_fst_exists_pair :
  forall (pairs : list (nat * nat)) a,
    In a (map fst pairs) ->
    exists b, In (a, b) pairs.
Proof.
  induction pairs as [|[x y] rest IH]; intros a Hin; simpl in *.
  - contradiction.
  - destruct Hin as [Heq | Hin_rest].
    + subst a. exists y. left. reflexivity.
    + apply IH in Hin_rest.
      destruct Hin_rest as [b Hb].
      exists b. right. exact Hb.
Qed.

Lemma in_cartesian_pairs_wf :
  forall xs ys a b,
    In (a, b) (cartesian_pairs xs ys) ->
    In a xs /\ In b ys.
Proof.
  intros xs ys a b Hin.
  unfold cartesian_pairs in Hin.
  apply in_flat_map in Hin.
  destruct Hin as [x [Hx Hmap]].
  apply in_map_iff in Hmap.
  destruct Hmap as [y [Heq Hy]].
  inversion Heq; subst.
  split; assumption.
Qed.

Definition psplit_support_morphism (left right : list nat) : SplitMorphism.
Proof.
  refine
    {| split_left := normalize_region left;
       split_right := normalize_region right;
       coupling_pairs := cartesian_pairs (normalize_region left) (normalize_region right);
       morphism_support_semantics :=
         [cartesian_pairs (normalize_region left) (normalize_region right)] |}.
  - intros a b Hin.
    apply in_cartesian_pairs_wf in Hin.
    exact Hin.
  - intros support Hin_sem a Hin_red.
    simpl in Hin_sem.
    destruct Hin_sem as [Hsupport | Hnil].
    + subst support.
      unfold reduced_state_support, partial_trace_right_support in Hin_red.
      apply nodup_In in Hin_red.
      apply in_map_fst_exists_pair in Hin_red.
      exact Hin_red.
    + contradiction.
Defined.

Theorem vm_step_psplit_constructs_support_morphism :
  forall s s' module left right cost,
    vm_step s (instr_psplit module left right cost) s' ->
    exists P : SplitMorphism,
      split_left P = normalize_region left /\
      split_right P = normalize_region right /\
      In (cartesian_pairs (normalize_region left) (normalize_region right))
         (morphism_support_semantics P) /\
      (forall support,
        In support (morphism_support_semantics P) ->
        forall a,
          In a (reduced_state_support support) ->
          exists b, coupled P a b).
Proof.
  intros s s' module left right cost Hstep.
  inversion Hstep; subst.
  - exists (psplit_support_morphism left right).
    split.
    + reflexivity.
    + split.
      * reflexivity.
      * split.
        -- simpl. left. reflexivity.
        -- intros support Hin_sem a Hin_red.
           simpl in Hin_sem.
           destruct Hin_sem as [Hsupport | Hnil].
           ++ subst support.
              unfold reduced_state_support, partial_trace_right_support in Hin_red.
              apply nodup_In in Hin_red.
              apply in_map_fst_exists_pair in Hin_red.
              destruct Hin_red as [b Hb].
              exists b. unfold coupled. exact Hb.
           ++ contradiction.
  - exists (psplit_support_morphism left right).
    split.
    + reflexivity.
    + split.
      * reflexivity.
      * split.
        -- simpl. left. reflexivity.
        -- intros support Hin_sem a Hin_red.
           simpl in Hin_sem.
           destruct Hin_sem as [Hsupport | Hnil].
           ++ subst support.
              unfold reduced_state_support, partial_trace_right_support in Hin_red.
              apply nodup_In in Hin_red.
              apply in_map_fst_exists_pair in Hin_red.
              destruct Hin_red as [b Hb].
              exists b. unfold coupled. exact Hb.
           ++ contradiction.
Qed.

(** Reachable support model induced by concrete vm_apply on PSPLIT. *)
Definition vm_apply_psplit_reachable_supports
  (s : VMState)
  (module : ModuleID)
  (left right : list nat)
  (cost : nat) : list joint_support :=
  match graph_psplit s.(vm_graph) module left right with
  | Some _ => [cartesian_pairs (normalize_region left) (normalize_region right)]
  | None => []
  end.

(** Conservativity (successful PSPLIT case): every support in the cartesian
    split semantics is reachable in the vm_apply-induced support model. *)
Theorem psplit_cartesian_semantics_conservative_vm_apply :
  forall s s' module left right cost,
    vm_step s (instr_psplit module left right cost) s' ->
    graph_psplit s.(vm_graph) module left right <> None ->
    forall support,
      In support
        (morphism_support_semantics (psplit_support_morphism left right)) ->
      In support (vm_apply_psplit_reachable_supports s module left right cost).
Proof.
  intros s s' module left right cost _ Hsucc support Hin.
  unfold vm_apply_psplit_reachable_supports.
  destruct (graph_psplit s.(vm_graph) module left right) as [[[g' l] r]|] eqn:Hsplit.
  - simpl in *. exact Hin.
  - exfalso. apply Hsucc. reflexivity.
Qed.

(** vm_apply agreement for successful PSPLIT vm_step transitions. *)
Theorem psplit_vm_apply_reaches_step_state :
  forall s s' module left right cost,
    vm_step s (instr_psplit module left right cost) s' ->
    graph_psplit s.(vm_graph) module left right <> None ->
    vm_apply s (instr_psplit module left right cost) = s'.
Proof.
  intros s s' module left right cost Hstep _.
  apply vm_step_vm_apply. exact Hstep.
Qed.

Theorem local_morphism_support_bound :
  forall (P : SplitMorphism) (support : joint_support),
    is_nearest_neighbor P ->
    In support (morphism_support_semantics P) ->
    boundary_local_support (split_left P) (split_right P) support.
Proof.
  intros P support Hnn Hin.
  unfold boundary_local_support.
  eapply Nat.le_trans.
  - apply reduced_support_length_le_boundary_size; eauto.
  - apply nat_le_pow2_self.
Qed.
